//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class KBABTestHitInfo, NSDictionary;

@interface KBABTestDetailInfo : NSObject
{
    KBABTestHitInfo *_hitInfo;
    NSDictionary *_params;
}

+ (id)instanceFromDict:(id)arg1;
+ (id)instanceFromRep:(id)arg1;
- (void).cxx_destruct;
@property(retain, nonatomic) NSDictionary *params; // @synthesize params=_params;
@property(retain, nonatomic) KBABTestHitInfo *hitInfo; // @synthesize hitInfo=_hitInfo;
- (id)description;
- (id)toDict;

@end

