//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface KBABTestUtil : NSObject
{
}

+ (long long)keyboardType;
+ (id)clientVersion;
+ (id)deviceInfo;

@end

