//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface KBABTestHitInfo : NSObject
{
    unsigned int _exptId;
    unsigned int _groupId;
    unsigned int _hitType;
    unsigned int _launchLayerId;
    unsigned long long _bucketSrc;
}

@property(nonatomic) unsigned long long bucketSrc; // @synthesize bucketSrc=_bucketSrc;
@property(nonatomic) unsigned int launchLayerId; // @synthesize launchLayerId=_launchLayerId;
@property(nonatomic) unsigned int hitType; // @synthesize hitType=_hitType;
@property(nonatomic) unsigned int groupId; // @synthesize groupId=_groupId;
@property(nonatomic) unsigned int exptId; // @synthesize exptId=_exptId;

@end

