//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "WBPreferencesFileObserving-Protocol.h"

@class NSArray, NSDictionary, NSMutableArray, NSString;
@protocol WBBusinessRequestProtocol;

@interface KBABTestMgr : NSObject <WBPreferencesFileObserving>
{
    NSArray *_engineInfos;
    NSArray *_validClientInfos;
    NSArray *_invalidClientInfos;
    NSArray *_voiceABHitedInfos;
    id <WBBusinessRequestProtocol> _requestHandler;
    double _lastFetchedTimeInterval;
    NSDictionary *_flat_engineInfos;
    NSDictionary *_flat_validClientInfos;
    NSMutableArray *_validateBlocks;
}

+ (id)sharedInstance;
- (void).cxx_destruct;
@property(retain) NSMutableArray *validateBlocks; // @synthesize validateBlocks=_validateBlocks;
@property(retain) NSDictionary *flat_validClientInfos; // @synthesize flat_validClientInfos=_flat_validClientInfos;
@property(retain) NSDictionary *flat_engineInfos; // @synthesize flat_engineInfos=_flat_engineInfos;
@property(nonatomic) double lastFetchedTimeInterval; // @synthesize lastFetchedTimeInterval=_lastFetchedTimeInterval;
@property(nonatomic) __weak id <WBBusinessRequestProtocol> requestHandler; // @synthesize requestHandler=_requestHandler;
@property(retain) NSArray *voiceABHitedInfos; // @synthesize voiceABHitedInfos=_voiceABHitedInfos;
@property(retain) NSArray *invalidClientInfos; // @synthesize invalidClientInfos=_invalidClientInfos;
@property(retain) NSArray *validClientInfos; // @synthesize validClientInfos=_validClientInfos;
@property(retain) NSArray *engineInfos; // @synthesize engineInfos=_engineInfos;
- (id)clientInfoForReport;
- (id)infoForKey:(id)arg1;
- (_Bool)boolValueForKey:(id)arg1 defaultValue:(_Bool)arg2;
- (id)toolbarSuggestedInfo;
- (id)voiceinputLanguageModel;
- (id)stickerInfo;
- (void)updateIMEInfos;
- (void)updateFlatEngineInfos:(id)arg1 flatValidClientInfos:(id)arg2 shouldNotify:(_Bool)arg3;
- (void)readInfos:(_Bool)arg1;
- (void)saveInfos;
- (id)diffsetFromOldDictionary:(id)arg1 toNewictionary:(id)arg2;
- (void)addClientInfoValidatorWithBlock:(CDUnknownBlockType)arg1;
- (_Bool)validateClientInfo:(id)arg1;
- (void)fetchAbTestData;
- (void)preferencesDidReloadFromFile:(Class)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

