//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIView.h>

#import "UIGestureRecognizerDelegate-Protocol.h"

@class NSString, UIButton, UIControl, UIGestureRecognizer, UILabel, UITextView;

@interface KBAlertView : UIView <UIGestureRecognizerDelegate>
{
    _Bool _needCancelButton;
    _Bool _needActionButton;
    CDUnknownBlockType _didDismissBlock;
    CDUnknownBlockType _didActionBlock;
    NSString *_title;
    NSString *_subTitle;
    NSString *_cancelBtnTitle;
    NSString *_actionBtnTitle;
    UIControl *_maskView;
    UIView *_contentView;
    UITextView *_textView;
    UIButton *_cancelButton;
    UIButton *_actionButton;
    UILabel *_titleLabel;
    UILabel *_subTitleLabel;
    UIView *_separatorView;
    UIButton *_doCopyButton;
    UIGestureRecognizer *_tapGesture;
    struct CGSize _contentViewSize;
}

- (void).cxx_destruct;
@property(nonatomic) struct CGSize contentViewSize; // @synthesize contentViewSize=_contentViewSize;
@property(retain, nonatomic) UIGestureRecognizer *tapGesture; // @synthesize tapGesture=_tapGesture;
@property(retain, nonatomic) UIButton *doCopyButton; // @synthesize doCopyButton=_doCopyButton;
@property(retain, nonatomic) UIView *separatorView; // @synthesize separatorView=_separatorView;
@property(retain, nonatomic) UILabel *subTitleLabel; // @synthesize subTitleLabel=_subTitleLabel;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(retain, nonatomic) UIButton *actionButton; // @synthesize actionButton=_actionButton;
@property(retain, nonatomic) UIButton *cancelButton; // @synthesize cancelButton=_cancelButton;
@property(retain, nonatomic) UITextView *textView; // @synthesize textView=_textView;
@property(retain, nonatomic) UIView *contentView; // @synthesize contentView=_contentView;
@property(retain, nonatomic) UIControl *maskView; // @synthesize maskView=_maskView;
@property(copy, nonatomic) NSString *actionBtnTitle; // @synthesize actionBtnTitle=_actionBtnTitle;
@property(copy, nonatomic) NSString *cancelBtnTitle; // @synthesize cancelBtnTitle=_cancelBtnTitle;
@property(copy, nonatomic) NSString *subTitle; // @synthesize subTitle=_subTitle;
@property(copy, nonatomic) NSString *title; // @synthesize title=_title;
@property(nonatomic) _Bool needActionButton; // @synthesize needActionButton=_needActionButton;
@property(nonatomic) _Bool needCancelButton; // @synthesize needCancelButton=_needCancelButton;
@property(copy, nonatomic) CDUnknownBlockType didActionBlock; // @synthesize didActionBlock=_didActionBlock;
@property(copy, nonatomic) CDUnknownBlockType didDismissBlock; // @synthesize didDismissBlock=_didDismissBlock;
- (_Bool)gestureRecognizer:(id)arg1 shouldRecognizeSimultaneouslyWithGestureRecognizer:(id)arg2;
- (void)handleCopy:(id)arg1;
- (void)handleAction:(id)arg1;
- (void)handleDismiss:(id)arg1;
- (void)showString;
- (void)layoutSubviews;
- (void)initSubviews;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

