//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface KBDeviceUtil : NSObject
{
}

+ (long long)performance;
+ (id)buildBranch;
+ (long long)currentMemory;
+ (long long)processIdentifier;
+ (id)processName;
+ (_Bool)isExtensionTarget;
+ (id)deviceType;
+ (id)deviceMachine;
+ (id)deviceName;
+ (id)osVersion;
+ (id)osName;
+ (id)marketVersion;
+ (id)appVersion;
+ (id)pluginBundleId;
+ (id)bundleId;
+ (double)getiOSVersion;
+ (_Bool)isiPhone;
+ (_Bool)isiOS14plus;
+ (id)idfaUUID;
+ (void)load;

@end

