//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "WBPreferences.h"

@interface KBFeatureFileSync : WBPreferences
{
}

+ (_Bool)reloadFromDiskAutomatically;
+ (id)folderPath;
+ (id)defaultConfig;
+ (id)defaultValuesMapper;

@end

