//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMutableArray;
@protocol WBBusinessRequestProtocol;

@interface KBFeatureMgr : NSObject
{
    NSMutableArray *_updaterBlocks;
    id <WBBusinessRequestProtocol> _requestHandler;
    double _lastFetchedTimeInterval;
}

+ (id)sharedInstance;
- (void).cxx_destruct;
@property(nonatomic) double lastFetchedTimeInterval; // @synthesize lastFetchedTimeInterval=_lastFetchedTimeInterval;
@property(nonatomic) __weak id <WBBusinessRequestProtocol> requestHandler; // @synthesize requestHandler=_requestHandler;
- (void)addFeaturePreferenceDidReloadFromFileObserver:(id)arg1;
- (void)addFeatureDidChangeObserver:(id)arg1 selector:(SEL)arg2;
- (_Bool)boolValueForKey:(id)arg1 defaultValueBlock:(CDUnknownBlockType)arg2;
- (_Bool)boolValueForKey:(id)arg1;
- (id)dictValueForKey:(id)arg1;
- (void)dictValueForKey:(id)arg1 variablePtr:(id *)arg2 defaultValueBlock:(CDUnknownBlockType)arg3;
- (long long)integerValueForKey:(id)arg1 defaultValueBlock:(CDUnknownBlockType)arg2;
- (long long)integerValueForKey:(id)arg1 integerVariablePtr:(long long *)arg2 defaultValueBlock:(CDUnknownBlockType)arg3;
- (_Bool)boolValueForKey:(id)arg1 boolVariablePtr:(_Bool *)arg2 defaultValueBlock:(CDUnknownBlockType)arg3;
- (void)valueForKey:(id)arg1 variablePtr:(id *)arg2 featureAssignedBlock:(CDUnknownBlockType)arg3 defaultValueBlock:(CDUnknownBlockType)arg4;
- (id)stringValueForKey:(id)arg1;
- (void)clearAllFeature;
- (void)setTestValue:(id)arg1 forKey:(id)arg2;
- (void)saveFeatures:(id)arg1 syncKey:(unsigned long long)arg2;
- (void)fetchFeatures;
- (_Bool)isKeyBoard;
- (id)init;

@end

