//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface KBFontUtil : NSObject
{
}

+ (void)unRegisterDinFont;
+ (void)registerDinFont;
+ (void)unregisterFontWithFileName:(id)arg1;
+ (void)registerFontWithFileName:(id)arg1;

@end

