//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMutableArray;

@interface KBHandWriteStroke : NSObject
{
    NSMutableArray *_points;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSMutableArray *points; // @synthesize points=_points;
- (double)endTime;
- (double)beginTime;
- (id)init;

@end

