//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface KBHandWritePoint : NSObject
{
    double _t;
    double _x;
    double _y;
}

+ (id)fromX:(double)arg1 y:(double)arg2 baseTime:(double)arg3;
@property(nonatomic) double y; // @synthesize y=_y;
@property(nonatomic) double x; // @synthesize x=_x;
@property(nonatomic) double t; // @synthesize t=_t;
- (id)description;

@end

