//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSAttributedString, NSString, WBMinimalCandidate;
@protocol KBIMECandidateAttachedDataProtocol;

@interface KBIMECandidateWord : NSObject
{
    _Bool _isFromCloud;
    _Bool _isLocalCloud;
    _Bool _isLocalPastboard;
    _Bool _isAssociating;
    _Bool _isHotWord;
    _Bool _isUserDictWord;
    _Bool _isPrior;
    _Bool _isCloudComplete;
    _Bool _isCalculateResult;
    _Bool _isPronounce;
    _Bool _isEmoji;
    _Bool _isNormalEmoji;
    _Bool _isComposeEmoji;
    _Bool _isWechatEmoji;
    _Bool _isYanEmoji;
    _Bool _isLate;
    _Bool _showPlusIcon;
    unsigned int _pendintInputVersion;
    int _yanWordType;
    int _hwStrokeNum;
    int _type;
    int _calculate_format;
    int _input_scene;
    int _pending_len;
    unsigned int _source;
    unsigned int _process_time;
    unsigned int _asso_info_time;
    unsigned int _asso_info_count;
    unsigned int _asso_info_clk_time;
    unsigned int _asso_info_clk_count;
    unsigned int _asso_info_expose_time;
    unsigned int _asso_info_expose_count;
    int _mostLikelyType;
    unsigned int _IDLen;
    unsigned int _originKind;
    long long _reportCandidateLength;
    NSString *_word;
    NSString *_emitText;
    NSString *_hotwordComment;
    NSString *_yanwordComment;
    NSString *_yanwordModelInfo;
    NSAttributedString *_attributedText;
    NSString *_requestId;
    NSString *_requestIdForNoContent;
    unsigned long long _flag;
    unsigned long long _render_flag;
    long long _ime_flag;
    NSObject<KBIMECandidateAttachedDataProtocol> *_attachedData;
    id _attachedData2;
    unsigned long long _cloudServiceVersion;
    char *_ID;
    long long _repeatedCout;
    long long _preferedCandidateIndex;
}

+ (_Bool)mergeCloudMostLikelyCandidateByEngine;
+ (_Bool)mergeCloudCandidateByEngine;
+ (id)candidateWordWithIMECandidate:(struct _wxime_candidate)arg1 type:(int)arg2 pendintInputVersion:(unsigned int)arg3 requestId:(id)arg4 requestIdForNoContent:(id)arg5 flag:(unsigned long long *)arg6 processTime:(unsigned int)arg7;
+ (struct _wxime_candidate_icon_info *)iconInfoWithWXIMECandidate:(struct _wxime_candidate *)arg1;
- (void).cxx_destruct;
@property(nonatomic) unsigned int originKind; // @synthesize originKind=_originKind;
@property(nonatomic) long long preferedCandidateIndex; // @synthesize preferedCandidateIndex=_preferedCandidateIndex;
@property(nonatomic) long long repeatedCout; // @synthesize repeatedCout=_repeatedCout;
@property(nonatomic) _Bool showPlusIcon; // @synthesize showPlusIcon=_showPlusIcon;
@property(nonatomic) _Bool isLate; // @synthesize isLate=_isLate;
@property(nonatomic) unsigned int IDLen; // @synthesize IDLen=_IDLen;
@property(nonatomic) char *ID; // @synthesize ID=_ID;
@property(nonatomic) _Bool isYanEmoji; // @synthesize isYanEmoji=_isYanEmoji;
@property(nonatomic) _Bool isWechatEmoji; // @synthesize isWechatEmoji=_isWechatEmoji;
@property(nonatomic) _Bool isComposeEmoji; // @synthesize isComposeEmoji=_isComposeEmoji;
@property(nonatomic) _Bool isNormalEmoji; // @synthesize isNormalEmoji=_isNormalEmoji;
@property(nonatomic) _Bool isEmoji; // @synthesize isEmoji=_isEmoji;
@property(nonatomic) _Bool isPronounce; // @synthesize isPronounce=_isPronounce;
@property(nonatomic) _Bool isCalculateResult; // @synthesize isCalculateResult=_isCalculateResult;
@property(nonatomic) _Bool isCloudComplete; // @synthesize isCloudComplete=_isCloudComplete;
@property(nonatomic) unsigned long long cloudServiceVersion; // @synthesize cloudServiceVersion=_cloudServiceVersion;
@property(nonatomic) _Bool isPrior; // @synthesize isPrior=_isPrior;
@property(nonatomic) _Bool isUserDictWord; // @synthesize isUserDictWord=_isUserDictWord;
@property(nonatomic) _Bool isHotWord; // @synthesize isHotWord=_isHotWord;
@property(nonatomic) _Bool isAssociating; // @synthesize isAssociating=_isAssociating;
@property(nonatomic) _Bool isLocalPastboard; // @synthesize isLocalPastboard=_isLocalPastboard;
@property(nonatomic) _Bool isLocalCloud; // @synthesize isLocalCloud=_isLocalCloud;
@property(nonatomic) _Bool isFromCloud; // @synthesize isFromCloud=_isFromCloud;
@property(readonly, nonatomic) id attachedData2; // @synthesize attachedData2=_attachedData2;
@property(retain, nonatomic) NSObject<KBIMECandidateAttachedDataProtocol> *attachedData; // @synthesize attachedData=_attachedData;
@property(nonatomic) int mostLikelyType; // @synthesize mostLikelyType=_mostLikelyType;
@property(nonatomic) unsigned int asso_info_expose_count; // @synthesize asso_info_expose_count=_asso_info_expose_count;
@property(nonatomic) unsigned int asso_info_expose_time; // @synthesize asso_info_expose_time=_asso_info_expose_time;
@property(nonatomic) unsigned int asso_info_clk_count; // @synthesize asso_info_clk_count=_asso_info_clk_count;
@property(nonatomic) unsigned int asso_info_clk_time; // @synthesize asso_info_clk_time=_asso_info_clk_time;
@property(nonatomic) unsigned int asso_info_count; // @synthesize asso_info_count=_asso_info_count;
@property(nonatomic) unsigned int asso_info_time; // @synthesize asso_info_time=_asso_info_time;
@property(readonly, nonatomic) unsigned int process_time; // @synthesize process_time=_process_time;
@property(nonatomic) unsigned int source; // @synthesize source=_source;
@property(readonly, nonatomic) int pending_len; // @synthesize pending_len=_pending_len;
@property(readonly, nonatomic) int input_scene; // @synthesize input_scene=_input_scene;
@property(nonatomic) int calculate_format; // @synthesize calculate_format=_calculate_format;
@property(readonly, nonatomic) long long ime_flag; // @synthesize ime_flag=_ime_flag;
@property(nonatomic) int type; // @synthesize type=_type;
@property(readonly, nonatomic) unsigned long long render_flag; // @synthesize render_flag=_render_flag;
@property(readonly, nonatomic) unsigned long long flag; // @synthesize flag=_flag;
@property(copy, nonatomic) NSString *requestIdForNoContent; // @synthesize requestIdForNoContent=_requestIdForNoContent;
@property(copy, nonatomic) NSString *requestId; // @synthesize requestId=_requestId;
@property(copy, nonatomic) NSAttributedString *attributedText; // @synthesize attributedText=_attributedText;
@property(copy, nonatomic) NSString *yanwordModelInfo; // @synthesize yanwordModelInfo=_yanwordModelInfo;
@property(copy, nonatomic) NSString *yanwordComment; // @synthesize yanwordComment=_yanwordComment;
@property(copy, nonatomic) NSString *hotwordComment; // @synthesize hotwordComment=_hotwordComment;
@property(copy, nonatomic) NSString *emitText; // @synthesize emitText=_emitText;
@property(copy, nonatomic) NSString *word; // @synthesize word=_word;
@property(nonatomic) long long reportCandidateLength; // @synthesize reportCandidateLength=_reportCandidateLength;
@property(nonatomic) int hwStrokeNum; // @synthesize hwStrokeNum=_hwStrokeNum;
@property(nonatomic) int yanWordType; // @synthesize yanWordType=_yanWordType;
@property(nonatomic) unsigned int pendintInputVersion; // @synthesize pendintInputVersion=_pendintInputVersion;
@property(readonly, nonatomic) WBMinimalCandidate *minimalCopy;
- (void)dealloc;
- (id)description;
@property(readonly, nonatomic) NSString *displayAssociatingInfo;
- (void)appendSeparator;
- (_Bool)needRepeat;
- (void)updateRequestID:(id)arg1 requestIdForNoContent:(id)arg2;
- (void)updateUIWith:(id)arg1 attachedData:(id)arg2;
- (id)uniqWord;
- (id)initWithAskAIModel:(id)arg1;
- (id)initWithVoiceInputSimilarResult:(id)arg1 attachData:(id)arg2;
- (id)initWithPasteboardText:(id)arg1 isImage:(_Bool)arg2 isSubText:(_Bool)arg3 renderFlag:(unsigned long long)arg4 refPasteboard:(id)arg5;
- (id)initWithBigBoomText:(id)arg1;
- (id)initForPasteboardHistory;
- (id)initForTranslateWhileTyping;
- (id)initInnerHWCandidate;
- (id)initWithRewriteRec:(id)arg1 attachedData:(id)arg2 attachedData2:(id)arg3 reqId:(id)arg4 reqIdForNoContent:(id)arg5;
- (id)initWithEmojiRec:(id)arg1 query:(id)arg2 hideDesc:(_Bool)arg3 attachedData:(id)arg4 reqId:(id)arg5 reqIdForNoContent:(id)arg6 stickerInfo:(id)arg7;
- (id)initWithBookVideoRec:(id)arg1 attachedData:(id)arg2 attachedData2:(id)arg3 reqId:(id)arg4 reqIdForNoContent:(id)arg5;
- (id)initWithRecommendWord:(id)arg1 comment:(id)arg2 iconInfo:(struct _wxime_candidate_icon_info *)arg3;
- (id)initWithResDisplay:(id)arg1 resModel:(id)arg2 reqId:(id)arg3 reqIdForNoContent:(id)arg4;
- (id)initWithWord:(id)arg1 iconInfo:(struct _wxime_candidate_icon_info *)arg2;
- (id)initWithDynamicEmojiWord:(id)arg1 iconInfo:(struct _wxime_candidate_icon_info *)arg2;
- (id)initWithString:(id)arg1 cornerMark:(unsigned long long)arg2;
- (id)initWithString:(id)arg1;
- (double)itemWidth;
- (_Bool)asyncCompute;
- (id)textLayoutForArrangeView:(id)arg1 attributes:(id)arg2 limitedWidth:(double)arg3;
- (double)widthForArrangeView:(id)arg1 attributes:(id)arg2 horizontalEdges:(double)arg3 limitedWidth:(double)arg4;
- (id)textLayoutForArrangeView:(id)arg1;

@end

