//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "KBIMECandidateAttachedDataProtocol-Protocol.h"

@class NSString, UIImage, UILabel;

@interface KBIMECandidateSymbolAttachment : NSObject <KBIMECandidateAttachedDataProtocol>
{
    UIImage *_cornerImage;
    UILabel *_renderLabel;
}

- (void).cxx_destruct;
- (void)setPreferedCandidateIndex:(long long)arg1;
- (long long)preferedCandidateIndex;
- (id)cornerImage;
- (id)tintColor;
- (id)iconImage;
- (id)initWithSymbol:(id)arg1 cornerMark:(unsigned long long)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

