//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "KBIMECandidateAttachedDataProtocol-Protocol.h"

@class NSString;

@interface KBIMECandidateRecommendAttachment : NSObject <KBIMECandidateAttachedDataProtocol>
{
    NSString *_pendingInput;
    NSString *_requestId;
    NSString *_requestIdForNoContent;
    NSString *_dispayWord;
    NSString *_searchWord;
    long long _iconId;
}

+ (id)instanceWithWord:(id)arg1 comment:(id)arg2 iconId:(long long)arg3;
- (void).cxx_destruct;
@property(nonatomic) long long iconId; // @synthesize iconId=_iconId;
@property(copy, nonatomic) NSString *searchWord; // @synthesize searchWord=_searchWord;
@property(copy, nonatomic) NSString *dispayWord; // @synthesize dispayWord=_dispayWord;
@property(copy, nonatomic) NSString *requestIdForNoContent; // @synthesize requestIdForNoContent=_requestIdForNoContent;
@property(copy, nonatomic) NSString *requestId; // @synthesize requestId=_requestId;
@property(copy, nonatomic) NSString *pendingInput; // @synthesize pendingInput=_pendingInput;
- (void)setPreferedCandidateIndex:(long long)arg1;
- (long long)preferedCandidateIndex;
- (id)cornerImage;
- (id)tintColor;
- (id)iconImage;
- (_Bool)isTextExpansion;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

