//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "KBIMECandidateAttachedDataProtocol-Protocol.h"

@class NSString, UIColor, UIImage;

@interface KBIMECandidateBaseAttachment : NSObject <KBIMECandidateAttachedDataProtocol>
{
    UIImage *_image;
    UIColor *_tintColor;
}

- (void).cxx_destruct;
- (void)setPreferedCandidateIndex:(long long)arg1;
- (long long)preferedCandidateIndex;
- (id)cornerImage;
- (id)tintColor;
- (id)iconImage;
- (id)initWithImage:(id)arg1 tintColor:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

