//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "WBSymbolListItemProtocol-Protocol.h"

@class NSString;

@interface KBIMESyllable : NSObject <WBSymbolListItemProtocol>
{
    NSString *_syllable;
    char *_syllableId;
    unsigned long long _syllableIdLen;
}

- (void).cxx_destruct;
@property(nonatomic) unsigned long long syllableIdLen; // @synthesize syllableIdLen=_syllableIdLen;
@property(nonatomic) char *syllableId; // @synthesize syllableId=_syllableId;
@property(copy, nonatomic) NSString *syllable; // @synthesize syllable=_syllable;
- (void)dealloc;
@property(readonly, copy) NSString *description;
- (_Bool)supportsSelectedStyle;
- (id)text;
- (double)itemWidth;
- (_Bool)asyncCompute;
- (_Bool)supportsSelectedStyle;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

