//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "KBIMECandidateAttachedDataProtocol-Protocol.h"

@class NSDictionary, NSString, UIImage;

@interface KBIMECandidateCommonAttachment : NSObject <KBIMECandidateAttachedDataProtocol>
{
    UIImage *_iconImage;
    NSDictionary *_userInfo;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSDictionary *userInfo; // @synthesize userInfo=_userInfo;
@property(retain, nonatomic) UIImage *iconImage; // @synthesize iconImage=_iconImage;
- (void)setPreferedCandidateIndex:(long long)arg1;
- (long long)preferedCandidateIndex;
- (id)cornerImage;
- (id)tintColor;
- (id)initWithIconImage:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

