//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "KBIMECandidateAttachedDataProtocol-Protocol.h"

@class NSString, UIColor, UIImage;

@interface KBIMECandidateDynamicEmojiAttachment : NSObject <KBIMECandidateAttachedDataProtocol>
{
    UIImage *_iconImage;
    UIColor *_tintColor;
    _Bool _eyeCatching;
    NSString *_pendingInput;
    NSString *_requestId;
    NSString *_requestIdForNoContent;
    NSString *_word;
    long long _sentiment;
}

+ (id)instanceWithWord:(id)arg1 sentiment:(long long)arg2;
- (void).cxx_destruct;
@property(nonatomic) _Bool eyeCatching; // @synthesize eyeCatching=_eyeCatching;
@property(nonatomic) long long sentiment; // @synthesize sentiment=_sentiment;
@property(copy, nonatomic) NSString *word; // @synthesize word=_word;
@property(copy, nonatomic) NSString *requestIdForNoContent; // @synthesize requestIdForNoContent=_requestIdForNoContent;
@property(copy, nonatomic) NSString *requestId; // @synthesize requestId=_requestId;
@property(copy, nonatomic) NSString *pendingInput; // @synthesize pendingInput=_pendingInput;
- (void)setPreferedCandidateIndex:(long long)arg1;
- (long long)preferedCandidateIndex;
- (id)cornerImage;
- (id)tintColor;
- (id)iconImage;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

