//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface KBLoggerUtil : NSObject
{
}

+ (void)diagnosedLogWithFormat:(id)arg1;
+ (void)flush;
+ (void)reportError:(id)arg1;
+ (void)updateLogLevel:(unsigned long long)arg1;
+ (_Bool)shouldLog:(unsigned long long)arg1;
+ (void)logWithLevel:(unsigned long long)arg1 _module:(const char *)arg2 file:(const char *)arg3 line:(int)arg4 func:(const char *)arg5 message:(id)arg6;
+ (void)logWithLevel:(unsigned long long)arg1 _module:(const char *)arg2 file:(const char *)arg3 line:(int)arg4 func:(const char *)arg5 format:(id)arg6;
+ (void)initKBLogger;

@end

