//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Foundation/NSOperation.h>

@class Command;

@interface KBRCOperation : NSOperation
{
    _Bool _executing;
    _Bool _finished;
    Command *_cmd;
    unsigned long long _type;
    CDUnknownBlockType _finishCmdBlock;
    CDUnknownBlockType _reqFinishCommendsCompletion;
}

+ (_Bool)isBigSizeCommand:(id)arg1;
+ (id)argValueForCmd:(id)arg1 key:(id)arg2;
+ (id)checkShouldCreateInstance:(id)arg1;
- (void).cxx_destruct;
@property(copy, nonatomic) CDUnknownBlockType reqFinishCommendsCompletion; // @synthesize reqFinishCommendsCompletion=_reqFinishCommendsCompletion;
@property(copy, nonatomic) CDUnknownBlockType finishCmdBlock; // @synthesize finishCmdBlock=_finishCmdBlock;
@property(nonatomic) unsigned long long type; // @synthesize type=_type;
@property(retain) Command *cmd; // @synthesize cmd=_cmd;
- (void)finishCmd;
- (_Bool)isAsynchronous;
@property(nonatomic, getter=isFinished) _Bool finished; // @synthesize finished=_finished;
@property(nonatomic, getter=isExecuting) _Bool executing; // @synthesize executing=_executing;
- (void)done;
- (void)start;

@end

