//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "KBRCOperation.h"

@class NSString;

@interface KBRCOperation_3 : KBRCOperation
{
    NSString *_cmdString;
}

+ (id)checkShouldCreateInstance:(id)arg1;
- (void).cxx_destruct;
- (void)resetDebugSwitchDefault;
- (void)start;
- (id)initWithCMD:(id)arg1;

@end

