//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "KBRCOperation.h"

@interface KBRCOperation_1 : KBRCOperation
{
}

+ (id)checkShouldCreateInstance:(id)arg1;
- (void)removeUploadPath:(id)arg1;
- (void)uploadZippedLogs:(id)arg1;
- (int)requestBusinessWithSuccess:(CDUnknownBlockType)arg1 onFailure:(CDUnknownBlockType)arg2;
- (void)start;
- (id)internalLogFolderPath;

@end

