//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "KBRCOperation.h"

@class NSString;

@interface KBRCOperation_7 : KBRCOperation
{
    NSString *_showCmd;
}

+ (id)checkShouldCreateInstance:(id)arg1;
- (void).cxx_destruct;
- (void)start;
- (id)initWithShowCmd:(id)arg1;

@end

