//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray, NSOperationQueue;
@protocol OS_dispatch_queue;

@interface KBRCMgr : NSObject
{
    NSObject<OS_dispatch_queue> *_commendHandleDispatchQueue;
    NSOperationQueue *_commendHandleQueue;
    NSArray *_processingCommends;
}

+ (id)sharedInstance;
- (void).cxx_destruct;
@property(retain, nonatomic) NSArray *processingCommends; // @synthesize processingCommends=_processingCommends;
@property(retain, nonatomic) NSOperationQueue *commendHandleQueue; // @synthesize commendHandleQueue=_commendHandleQueue;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *commendHandleDispatchQueue; // @synthesize commendHandleDispatchQueue=_commendHandleDispatchQueue;
- (int)finishCommends:(id)arg1 complection:(CDUnknownBlockType)arg2;
- (void)addNonCommendOperation:(id)arg1;
- (void)processingCommends:(id)arg1;
- (void)fetchCommends;
- (id)businessMgr;
- (id)init;

@end

