//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "KBRCOperation.h"

@interface KBRCOperation_6 : KBRCOperation
{
}

+ (id)checkShouldCreateInstance:(id)arg1;
- (void)start;

@end

