//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface KBTextAroundCursorInfo : NSObject
{
    int _prev_change_reason;
    int _current_change_reason;
}

@property(nonatomic) int current_change_reason; // @synthesize current_change_reason=_current_change_reason;
@property(nonatomic) int prev_change_reason; // @synthesize prev_change_reason=_prev_change_reason;

@end

