//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface KBUtility : NSObject
{
}

+ (_Bool)isiPad;
+ (_Bool)hasNotch;
+ (id)libraryCachePath;
+ (id)evadFolderPath;
+ (id)internalLogFolderPath_deprecated;
+ (id)internalLogFolderPath;
+ (int)currentIMEDataVersion;

@end

