//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "WBSettingsViewController.h"

@class NSArray, UIScrollView;

@interface WBAbilityManagerViewController : WBSettingsViewController
{
    UIScrollView *_scrollView;
    NSArray *_itemViews;
}

+ (id)actionContextForKey:(int)arg1;
+ (void)logConfirmDecision:(int)arg1 isConfirm:(_Bool)arg2;
+ (void)logChangeSetting:(int)arg1 isTurnOn:(_Bool)arg2;
- (void).cxx_destruct;
@property(retain, nonatomic) NSArray *itemViews; // @synthesize itemViews=_itemViews;
@property(retain, nonatomic) UIScrollView *scrollView; // @synthesize scrollView=_scrollView;
- (void)viewDidLayoutSubviews;
- (void)setupNavigationItems;
- (void)setupItems;
- (void)reloadItems;
- (void)handleChangeForSwitch:(id)arg1 bit:(int)arg2 doneBlock:(CDUnknownBlockType)arg3;
- (id)itemViewWidhTitle:(id)arg1 subtitle:(id)arg2 image:(id)arg3 bit:(int)arg4;
- (void)plusStateDidChange;
- (void)viewDidLoad;

@end

