//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "WBThreeViewController.h"

@class CAShapeLayer, NSMutableArray, UIButton, UIImageView, UILabel;

@interface WBAboutViewController : WBThreeViewController
{
    NSMutableArray *_captainzhuLayoutBlocks;
    long long _initialSelectedPlatform;
    UIButton *_agreementButton;
    UIButton *_secretButton;
    UILabel *_versionLabel;
    CAShapeLayer *_sepBtnLayer;
    UIImageView *_aboutImageView;
    long long _upgradeState;
    long long _selectedIndex;
}

- (void).cxx_destruct;
@property(nonatomic) long long selectedIndex; // @synthesize selectedIndex=_selectedIndex;
@property(nonatomic) long long upgradeState; // @synthesize upgradeState=_upgradeState;
@property(retain, nonatomic) UIImageView *aboutImageView; // @synthesize aboutImageView=_aboutImageView;
@property(retain, nonatomic) CAShapeLayer *sepBtnLayer; // @synthesize sepBtnLayer=_sepBtnLayer;
@property(retain, nonatomic) UILabel *versionLabel; // @synthesize versionLabel=_versionLabel;
@property(retain, nonatomic) UIButton *secretButton; // @synthesize secretButton=_secretButton;
@property(retain, nonatomic) UIButton *agreementButton; // @synthesize agreementButton=_agreementButton;
@property(nonatomic) long long initialSelectedPlatform; // @synthesize initialSelectedPlatform=_initialSelectedPlatform;
- (void)onTap:(id)arg1;
- (void)jumpSecret;
- (void)jumpRecord;
- (void)jumpAgreement;
- (void)joinTestFlight;
- (void)openTestFlight;
- (void)handleTapUpdateButton;
- (_Bool)hasInstalledTestFlight;
- (void)markUnread;
- (void)appDidEnterBackground:(id)arg1;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)willShowTabWithIndex:(long long)arg1;
- (void)decideInitialSelectedIndex;
- (long long)wrapperViewHeight;
- (_Bool)showActionButton:(id)arg1;
- (void)refreshUIForUpgradeState;
- (void)refreshUIForNoUpgradeState;
- (void)refreshUpgradeUI;
- (id)currentPlatformDict;
- (void)readConfig;
- (void)viewDidAppear:(_Bool)arg1;
- (void)handleDidSyncAboutFeatureNotification:(id)arg1;
- (void)addObservers;
- (void)viewDidLoad;
- (id)title;
- (id)init;
- (void)didMoveToParentViewController:(id)arg1;
- (void)viewDidLayoutSubviews;

@end

