//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString, UIView;

@interface WBAlertControllerAction : NSObject
{
    NSString *_title;
    unsigned long long _style;
    CDUnknownBlockType _handler;
    UIView *_button;
}

+ (id)actionWithTitle:(id)arg1 style:(unsigned long long)arg2 handler:(CDUnknownBlockType)arg3;
+ (id)actionWithTitle:(id)arg1 style:(unsigned long long)arg2 buttonBlock:(CDUnknownBlockType)arg3 handler:(CDUnknownBlockType)arg4;
- (void).cxx_destruct;
@property(retain, nonatomic) UIView *button; // @synthesize button=_button;
@property(copy, nonatomic) CDUnknownBlockType handler; // @synthesize handler=_handler;
@property(nonatomic) unsigned long long style; // @synthesize style=_style;
@property(copy, nonatomic) NSString *title; // @synthesize title=_title;

@end

