//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIViewController.h>

@class NSMutableArray, NSString, UILabel, UIView, WBTapView, YYAnimatedImageView;

@interface WBAlertController : UIViewController
{
    _Bool _shown;
    UIView *_alertView;
    WBTapView *_tapView;
    UILabel *_titleLabel;
    UILabel *_subtitleLabel;
    YYAnimatedImageView *_image;
    _Bool _disableTapBackgroundToDismiss;
    unsigned long long _contentType;
    NSString *_contentTitle;
    NSString *_contentSubtitle;
    NSString *_lightModeImageName;
    NSString *_darkModeImageName;
    CDUnknownBlockType _onCancelBlock;
    NSMutableArray *_actions;
}

+ (void)presetWithParentViewController:(id)arg1 onCancelBlock:(CDUnknownBlockType)arg2 onConfirmBlock:(CDUnknownBlockType)arg3;
- (void).cxx_destruct;
@property(retain, nonatomic) NSMutableArray *actions; // @synthesize actions=_actions;
@property(nonatomic) _Bool disableTapBackgroundToDismiss; // @synthesize disableTapBackgroundToDismiss=_disableTapBackgroundToDismiss;
@property(copy, nonatomic) CDUnknownBlockType onCancelBlock; // @synthesize onCancelBlock=_onCancelBlock;
@property(copy, nonatomic) NSString *darkModeImageName; // @synthesize darkModeImageName=_darkModeImageName;
@property(copy, nonatomic) NSString *lightModeImageName; // @synthesize lightModeImageName=_lightModeImageName;
@property(copy, nonatomic) NSString *contentSubtitle; // @synthesize contentSubtitle=_contentSubtitle;
@property(copy, nonatomic) NSString *contentTitle; // @synthesize contentTitle=_contentTitle;
@property(nonatomic) unsigned long long contentType; // @synthesize contentType=_contentType;
- (void)show;
- (void)dismissWithAnimation:(_Bool)arg1;
- (void)cancel;
- (void)addAction:(id)arg1;
- (void)viewDidLayoutSubviews;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewDidLoad;
- (id)init;

@end

