//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "WBCodingObject.h"

@class NSArray, NSDictionary, NSString;

@interface WBAppSettingsObject : WBCodingObject
{
    char *_appArguments;
    char *_ignoreUpgradeAppVersion;
    char *_appOperations;
    char *_customPinyinSymbols;
    char *_customNumberSymbols;
    char *_lastLongAppVersion;
    char *_aboutFeature;
    char *_pluginInfoSync;
    char *_secKeyboardsOrder;
    unsigned char _doublePinyinSolution;
    unsigned char _wubiPlan;
    unsigned char _voiceInputLanguage;
    unsigned char _voiceInputPunctuation;
    unsigned char _plusConfirmType;
    unsigned char _keyboadVolume;
    unsigned char _hapticLevel;
    unsigned char _candidateFontSizeLevel;
    unsigned char _operationsSyncKey;
    unsigned char _firstInstallTime_deprecated;
    unsigned char _shouldShowRatingEntrance;
    unsigned char _showRatingEntranceRemainTimes;
    unsigned char _upgradeUniqId;
    unsigned char _hasTriggeredSavePhotoAuthorization;
    char *_bits;
    char *_bitVersions;
    unsigned long long _feedbackSeq;
    unsigned long long _feedbackUnreadCount;
    unsigned long long _voiceinputIconFixTimeAfterUse;
    unsigned long long _textViewActiveTime;
    double _firstInstallTime;
    unsigned long long _pasteboardStorageTime;
}

+ (void)setDefaultValueForBoolItemBlock:(CDUnknownBlockType)arg1;
+ (CDUnknownBlockType)defaultValueForBoolItemBlock;
+ (id)diffBits:(char *)arg1 otherBits:(char *)arg2;
+ (id)defaultValuesMapper;
+ (unsigned long long)properties:(const struct WBCodingProperty **)arg1;
@property(nonatomic) unsigned long long pasteboardStorageTime; // @synthesize pasteboardStorageTime=_pasteboardStorageTime;
@property(nonatomic) unsigned char hasTriggeredSavePhotoAuthorization; // @synthesize hasTriggeredSavePhotoAuthorization=_hasTriggeredSavePhotoAuthorization;
@property(nonatomic) double firstInstallTime; // @synthesize firstInstallTime=_firstInstallTime;
@property(nonatomic) unsigned long long textViewActiveTime; // @synthesize textViewActiveTime=_textViewActiveTime;
@property(nonatomic) unsigned char upgradeUniqId; // @synthesize upgradeUniqId=_upgradeUniqId;
@property(nonatomic) unsigned char showRatingEntranceRemainTimes; // @synthesize showRatingEntranceRemainTimes=_showRatingEntranceRemainTimes;
@property(nonatomic) unsigned char shouldShowRatingEntrance; // @synthesize shouldShowRatingEntrance=_shouldShowRatingEntrance;
@property(nonatomic) unsigned char firstInstallTime_deprecated; // @synthesize firstInstallTime_deprecated=_firstInstallTime_deprecated;
@property(nonatomic) unsigned char operationsSyncKey; // @synthesize operationsSyncKey=_operationsSyncKey;
@property(nonatomic) unsigned char candidateFontSizeLevel; // @synthesize candidateFontSizeLevel=_candidateFontSizeLevel;
@property(nonatomic) unsigned char hapticLevel; // @synthesize hapticLevel=_hapticLevel;
@property(nonatomic) unsigned char keyboadVolume; // @synthesize keyboadVolume=_keyboadVolume;
@property(nonatomic) unsigned char plusConfirmType; // @synthesize plusConfirmType=_plusConfirmType;
@property(nonatomic) unsigned long long voiceinputIconFixTimeAfterUse; // @synthesize voiceinputIconFixTimeAfterUse=_voiceinputIconFixTimeAfterUse;
@property(nonatomic) unsigned long long feedbackUnreadCount; // @synthesize feedbackUnreadCount=_feedbackUnreadCount;
@property(nonatomic) unsigned long long feedbackSeq; // @synthesize feedbackSeq=_feedbackSeq;
@property(nonatomic) unsigned char voiceInputPunctuation; // @synthesize voiceInputPunctuation=_voiceInputPunctuation;
@property(nonatomic) unsigned char voiceInputLanguage; // @synthesize voiceInputLanguage=_voiceInputLanguage;
@property(nonatomic) unsigned char wubiPlan; // @synthesize wubiPlan=_wubiPlan;
@property(nonatomic) unsigned char doublePinyinSolution; // @synthesize doublePinyinSolution=_doublePinyinSolution;
@property(nonatomic) char *bitVersions; // @synthesize bitVersions=_bitVersions;
@property(nonatomic) char *bits; // @synthesize bits=_bits;
@property(copy, nonatomic) NSArray *customNumberSymbols;
@property(copy, nonatomic) NSArray *customPinyinSymbols;
@property(copy, nonatomic) NSString *lastLongAppVersion;
@property(copy, nonatomic) NSString *pluginInfoSync;
@property(copy, nonatomic) NSArray *secKeyboardsOrder;
@property(copy, nonatomic) NSString *aboutFeature;
@property(copy, nonatomic) NSString *ignoreUpgradeAppVersion;
@property(retain, nonatomic) NSDictionary *appOperations;
@property(retain, nonatomic) NSDictionary *appArguments;
- (char *)copyBits;
- (void)setBool:(_Bool)arg1 forKey:(int)arg2;
- (_Bool)boolForKey:(int)arg1;
- (id)description;
- (_Bool)writeToFile:(id)arg1 atomically:(_Bool)arg2;
- (void)checkBitsVerionUpdate;
- (id)initWithContentsOfFile:(id)arg1 dataUpdated:(_Bool *)arg2;

@end

