//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString, WBAppSettingsObject;

@interface WBAppSettingsMgr : NSObject
{
    struct _opaque_pthread_rwlock_t _lock;
    _Bool _transaction;
    char *_tempBits;
    NSString *_curUserName;
    WBAppSettingsObject *_settings;
    NSString *_filePath;
}

+ (void)addObserver:(id)arg1 selector:(SEL)arg2;
+ (id)allocWithZone:(struct _NSZone *)arg1;
+ (id)sharedInstance;
- (void).cxx_destruct;
@property(copy, nonatomic) NSString *filePath; // @synthesize filePath=_filePath;
@property(retain, nonatomic) WBAppSettingsObject *settings; // @synthesize settings=_settings;
@property(copy, nonatomic) NSString *curUserName; // @synthesize curUserName=_curUserName;
- (void)notifyAppSettingsUserInfo:(id)arg1;
- (_Bool)saveAndShouldNotify:(_Bool)arg1;
- (_Bool)save;
- (_Bool)setTransaction:(_Bool)arg1;
- (void)addObserver:(id)arg1 selector:(SEL)arg2;
- (_Bool)boolForKey:(int)arg1;
- (void)setBool:(_Bool)arg1 forKey:(int)arg2;
- (void)applySettings;
- (void)reloadWithUserInfo:(id)arg1;
- (id)init;

@end

