//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface WBAppRecoverManager : NSObject
{
}

+ (id)manager;
- (void)clean;
- (id)lastedOpened;
- (void)markLastOpened:(id)arg1 extraInfo:(id)arg2;

@end

