//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Foundation/NSData.h>

@interface WBAppAliveCheckUtil : NSData
{
}

+ (id)debugInfo;
+ (_Bool)aliveCheckerEnable;
+ (_Bool)killLogicEnabled;
+ (double)delayCheckProtectTime;
+ (double)delayCheckTime;

@end

