//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface WBAppAskAIHeper : NSObject
{
}

+ (void)clearAllCache;
+ (void)clearKVCache;
+ (void)hideAllToast;
+ (void)showToast:(id)arg1 message:(id)arg2;
+ (void)fetchHtmlData:(_Bool)arg1 complection:(CDUnknownBlockType)arg2;

@end

