//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "WBKeyViewHostingProtocol-Protocol.h"

@class KBIMESession, NSArray, NSDictionary, NSMutableArray, NSString, UIView, WBAskAIAuxiliary, WBClipboardMsg, WBHotArea, WBPendingInput, WBRecommendResult, WBToolBarAuxiliary;
@protocol WBControlCenterProtocol, WBKeyViewTouchEventMonitorProtocol;

@interface WBAppKeyboardHosting : NSObject <WBKeyViewHostingProtocol>
{
}

+ (id)allocWithZone:(struct _NSZone *)arg1;
+ (void)initialize;
+ (id)sharedHosting;
- (void)notifySelector:(SEL)arg1 withObject:(id)arg2;
- (void)notifySelector:(SEL)arg1;
- (void)removeEventObserver:(id)arg1 selector:(SEL)arg2;
- (void)addEventObserver:(id)arg1 selector:(SEL)arg2;
@property(readonly, nonatomic) _Bool shouldPerformLongPressLaunch;
@property(readonly, nonatomic) _Bool voiceInputDataTransferActive;
- (long long)subTitlePositionForItem:(id)arg1;
- (_Bool)shouldShowUpTitleForKeyView:(id)arg1;
- (id)uninstallKeyTagSetWithOptions:(unsigned long long)arg1 panelType:(long long)arg2;
@property(readonly, nonatomic) long long returnKeyType;
@property(readonly, nonatomic) long long returnActionType;
- (void)refreshFontSize;
- (id)candidateTextAttributesWithSource:(long long)arg1;
@property(readonly, nonatomic) struct WBKeyboardRectInfo rectInfo;
- (id)methodSignatureForSelector:(SEL)arg1;
- (void)forwardInvocation:(id)arg1;

// Remaining properties
@property(nonatomic) double accessoryHeight;
@property(retain, nonatomic) UIView *accessoryView;
@property(readonly, nonatomic) NSArray *allAbInfo;
@property(readonly, nonatomic) _Bool allowsBeginHandwriting;
@property(readonly, nonatomic) WBAskAIAuxiliary *askAIAuxiliary;
@property(readonly, nonatomic) long long bottomPanelType;
@property(nonatomic) double boundingHeight;
@property(readonly, nonatomic) unsigned char candidateFontSizeLevel;
@property(readonly, nonatomic) NSArray *candidateWord;
@property(readonly, nonatomic) _Bool characterPreviewEnabled;
@property(readonly, nonatomic) NSArray *cloudCandidateWords;
@property(readonly, nonatomic) id <WBControlCenterProtocol> controlCenter;
@property(readonly, nonatomic) NSString *currentEstimatedPendingInputText;
@property(readonly, nonatomic) long long currentPanelType;
@property(readonly, nonatomic) WBPendingInput *currentPendingInput;
@property(retain, nonatomic) NSDictionary *customizedLogoButtonInfo;
@property(nonatomic) double debugAccessoryHeight;
@property(retain, nonatomic) UIView *debugAccessoryView;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly, nonatomic) NSString *documentContextAfterCursor;
@property(readonly, nonatomic) NSString *documentContextBeforeCursor;
@property(readonly, nonatomic) NSString *documentContextBeforeCursorAndSelected;
@property(readonly, nonatomic) NSString *documentContextBeforeInputEstimated;
@property(readonly, nonatomic) NSString *documentContextSelected;
@property(readonly, nonatomic) double documentModifyTime;
@property(readonly, nonatomic) _Bool duringTextViewTap;
@property(readonly, nonatomic) _Bool enablePinyinInWubiKeyboard;
@property(readonly, nonatomic) long long firstScreenFullVisibleLastCellIndex;
@property(readonly, nonatomic) unsigned long long flags;
@property(readonly, nonatomic) NSString *fullDocumentContext;
@property(readonly, nonatomic) struct _NSRange fullVisibleIndexRange;
@property(readonly, nonatomic) _Bool hasAccessView;
@property(readonly, nonatomic) _Bool hasAssociatedCandidate;
@property(readonly, nonatomic) _Bool hasDocumentText;
@property(readonly, nonatomic) _Bool hasInputTypeCandidate;
@property(readonly, nonatomic) _Bool hasOverlayLogoContent;
@property(readonly, nonatomic) _Bool hasPendingInput;
@property(readonly, nonatomic) _Bool hasRectInfo;
@property(readonly) unsigned long long hash;
@property(readonly, nonatomic) NSArray *hitAbInfo;
@property(readonly, nonatomic) NSString *hostBundleID;
@property(readonly, nonatomic) WBHotArea *hotArea;
@property(readonly, nonatomic) _Bool inVoiceInputTransfering;
@property(nonatomic) unsigned long long innerHandwritingState;
@property(readonly, nonatomic) _Bool isCustomSymbolEnv;
@property(readonly, nonatomic) _Bool isEmptyBeforeInputAtLine;
@property(readonly, nonatomic) _Bool isFocusingEmbeddedInputView;
@property(readonly, nonatomic) _Bool isHotwordEditViewShowing;
@property(readonly, nonatomic) _Bool isInHandwriteOrInnerHWPanel;
@property(readonly, nonatomic) _Bool isParticipleForT26PinYinEnabled;
@property(readonly, nonatomic) _Bool isShowingCustomStickerView;
@property(readonly, nonatomic) _Bool isTranslationInputShowing;
@property(readonly, nonatomic) _Bool isVoiceInputControlBarVisible;
@property(readonly, nonatomic) long long keyboardType;
@property(readonly, nonatomic) NSString *lastSentKeyword;
@property(readonly, nonatomic) NSString *lastSentStickerKeyword;
@property(readonly, nonatomic) _Bool needsSemicolonKey;
@property(readonly, nonatomic) _Bool needsSyllables;
@property(readonly, nonatomic) NSString *orginalFullDocumentContext;
@property(readonly, nonatomic) NSString *originalEmitAndSentKeyword;
@property(copy, nonatomic) CDUnknownBlockType overrideHeightBlock;
@property(nonatomic) struct CGSize overridePanelContainerSize;
@property(readonly, nonatomic) WBClipboardMsg *pasteboardForCandidates;
@property(readonly, nonatomic) _Bool prefersRecommendedSymbolCandidate;
@property(readonly, nonatomic) long long primaryPanelType;
@property(readonly, nonatomic) NSDictionary *processedAppArguments;
@property(readonly, nonatomic) WBRecommendResult *recommendData;
@property(readonly, nonatomic) _Bool responsibleForNewline;
@property(readonly, nonatomic) UIView *rootView;
@property(readonly, nonatomic) NSArray *secKeyboards;
@property(readonly, nonatomic) NSString *sendId;
@property(readonly, nonatomic) NSString *sendIdForNoContent;
@property(readonly, nonatomic) KBIMESession *session;
@property(readonly, nonatomic) unsigned long long sessionId;
@property(readonly, nonatomic) _Bool showingRectSettingView;
@property(readonly, nonatomic) _Bool showingT9AtPendingInput;
@property(nonatomic) _Bool splitReversed;
@property(readonly) Class superclass;
@property(readonly, nonatomic) NSArray *syllableItems;
@property(readonly, nonatomic) WBToolBarAuxiliary *toolBarAuxiliary;
@property(readonly, nonatomic) NSMutableArray *topBarCandidateWords;
@property(readonly, nonatomic) unsigned long long topBarState;
@property(nonatomic) __weak id <WBKeyViewTouchEventMonitorProtocol> touchEventMonitor;
@property(readonly, nonatomic) unsigned long long touchKeyCount;
@property(readonly, nonatomic) unsigned long long touchPlayState;
@property(readonly, nonatomic) _Bool traditionalEnabled;
@property(nonatomic) long long translationLanguage;
@property(readonly, nonatomic) _Bool usingDebugNet;
@property(readonly, nonatomic) long long willSwitchingPaneType;

@end

