//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface WBAppUIHelper : NSObject
{
}

+ (id)topViewController;
+ (void)openAppSettings;
+ (void)showPasteboardGuideWithScene:(unsigned long long)arg1;
+ (void)showOpenFullAccessGuideWithTitle:(id)arg1 actionBlock:(CDUnknownBlockType)arg2 cancelBlock:(CDUnknownBlockType)arg3;
+ (void)showClearUserDictConfirmWithNavigationController:(id)arg1;
+ (id)currentRootNaivgationController;
+ (void)popToHomeVC:(id)arg1 animated:(_Bool)arg2 completionBlock:(CDUnknownBlockType)arg3;
+ (void)dismissPresentedViewController:(id)arg1;
+ (void)dismissAllPresentedVCWithAnimation:(_Bool)arg1 completeBlock:(CDUnknownBlockType)arg2;
+ (id)backTitle;
+ (void)impactFeedbackLight;
+ (void)impactFeedback;
+ (id)attributesWithFont:(id)arg1 textColor:(id)arg2 lineHeight:(double)arg3 lineBreakMode:(long long)arg4 textAlignment:(long long)arg5;

@end

