//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIView.h>

@class QMUILabel, WBCandidateView, WBCommonPanelView;

@interface WBAppKeyboardView : UIView
{
    QMUILabel *_pendingInputLabel;
    WBCandidateView *_candidateView;
    WBCommonPanelView *_panelView;
    struct UIEdgeInsets _extraInset;
}

- (void).cxx_destruct;
@property(nonatomic) struct UIEdgeInsets extraInset; // @synthesize extraInset=_extraInset;
@property(retain, nonatomic) WBCommonPanelView *panelView; // @synthesize panelView=_panelView;
@property(retain, nonatomic) WBCandidateView *candidateView; // @synthesize candidateView=_candidateView;
@property(retain, nonatomic) QMUILabel *pendingInputLabel; // @synthesize pendingInputLabel=_pendingInputLabel;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;
- (void)layoutSubviews;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)demoCandidateWords;

@end

