//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "BuglyDelegate-Protocol.h"

@class NSString;

@interface WBAppBugly : NSObject <BuglyDelegate>
{
    _Bool _standaloneEnable;
    _Bool _inited;
}

+ (id)sdkVersion;
+ (id)sharedInstance;
@property(nonatomic) _Bool inited; // @synthesize inited=_inited;
@property(nonatomic) _Bool standaloneEnable; // @synthesize standaloneEnable=_standaloneEnable;
- (void)onAppSettingsChanged;
- (id)attachmentForException:(id)arg1;
- (id)buglyAppKey;
- (id)buglyAppId;
- (void)setupBugly;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

