//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIControl.h>

@class NSMutableArray, UIView;

@interface WBAppButton : UIControl
{
    UIView *_highlightMask;
    NSMutableArray *_captainzhuLayoutBlocks;
    CDUnknownBlockType _captainzhuLayoutFitBlock;
}

+ (id)content:(id)arg1 background:(id)arg2 width:(double)arg3 height:(double)arg4 cornerRadius:(double)arg5 target:(id)arg6 action:(SEL)arg7 superview:(id)arg8;
- (void).cxx_destruct;
- (void)setHighlighted:(_Bool)arg1;
- (id)initWithContent:(id)arg1;
- (void)willMoveToSuperview:(id)arg1;
- (void)sizeToFit;
- (void)layoutSubviews;

@end

