//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "PBCoding-Protocol.h"

@class NSString;

@interface WBAppPBSettings : NSObject <PBCoding>
{
    unsigned long long doublePinyinSolution;
    unsigned long long wubiPlan;
    unsigned long long voiceInputLanguage;
    unsigned long long voiceInputPunctuation;
    unsigned long long feedbackSeq;
    unsigned long long feedbackUnreadCount;
    unsigned long long voiceinputIconFixTimeAfterUse;
    unsigned long long plusConfirmType;
}

+ (void)initialize;
+ (void)PBArrayAdd_plusConfirmType;
+ (void)PBArrayAdd_voiceinputIconFixTimeAfterUse;
+ (void)PBArrayAdd_feedbackUnreadCount;
+ (void)PBArrayAdd_feedbackSeq;
+ (void)PBArrayAdd_voiceInputPunctuation;
+ (void)PBArrayAdd_voiceInputLanguage;
+ (void)PBArrayAdd_wubiPlan;
+ (void)PBArrayAdd_doublePinyinSolution;
@property(nonatomic) unsigned long long plusConfirmType; // @synthesize plusConfirmType;
@property(nonatomic) unsigned long long voiceinputIconFixTimeAfterUse; // @synthesize voiceinputIconFixTimeAfterUse;
@property(nonatomic) unsigned long long feedbackUnreadCount; // @synthesize feedbackUnreadCount;
@property(nonatomic) unsigned long long feedbackSeq; // @synthesize feedbackSeq;
@property(nonatomic) unsigned long long voiceInputPunctuation; // @synthesize voiceInputPunctuation;
@property(nonatomic) unsigned long long voiceInputLanguage; // @synthesize voiceInputLanguage;
@property(nonatomic) unsigned long long wubiPlan; // @synthesize wubiPlan;
@property(nonatomic) unsigned long long doublePinyinSolution; // @synthesize doublePinyinSolution;
@property(readonly, copy) NSString *description;
- (id)getPBPropertyTable;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

