//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIScrollView.h>

#import "UIScrollViewDelegate-Protocol.h"

@class CALayer, NSArray, NSMapTable, NSMutableArray, NSMutableDictionary, NSMutableSet, NSNumber, NSObject, NSString, WBArrangeSentinel, WBGridBoderFillLayer;
@protocol OS_dispatch_queue, WBArrangeCellUpdateDelegate, WBArrangeComputeDelegate;

@interface WBArrangeView : UIScrollView <UIScrollViewDelegate>
{
    NSArray *_computedItemLayouts;
    NSMutableArray *_itemLayouts;
    NSMutableDictionary *_visibleIndexsMapCells;
    NSMapTable *_cacheCellIndexs;
    double _lastComputeBoundsWidth;
    double _lastComputeBoundsHeight;
    NSMutableArray *_reuseCellPool;
    NSMutableArray *_reuseLayoutPool;
    WBArrangeSentinel *_sentinel;
    _Bool _contentOffsetLock;
    _Bool _needsReComputeRect;
    CALayer *_visiblePartRectDebugLayer;
    NSObject<OS_dispatch_queue> *_poolQueue;
    _Bool _delegateResposeToDidSetArrangeItem;
    _Bool _delegateResposeToDidShowFullArrangeItem;
    _Bool _delegateResposeToAnimationForInsertedCell;
    _Bool _delegateResposeToWillResetContentOffset;
    _Bool _delegateResposeToDidScroll;
    _Bool _delegateResposeToDidUpdateLayout;
    _Bool _delegateResposeToDidCreateCell;
    _Bool _delegateResposeToShouldNewLineForCell;
    NSNumber *_customAnimatedIndex;
    unsigned long long _selectedIndex;
    _Bool _needsCallbackOnFirstTime;
    double _remainWidthOfLastRow;
    unsigned long long _lastRequestComputeToken;
    NSMutableArray *_actionsAfterDidUpdateComputedItemLayouts;
    WBGridBoderFillLayer *_gridFillView;
    NSMutableSet *_forceUpdateCells;
    NSMutableArray *_tempComputeRectCallbackBlocks;
    _Bool _needsCallWillResetContentOffsetDelegateForNextChanges;
    unsigned long long _firstScreenFullVisibleLastCellIndex;
    unsigned long long _fullVisibleBeginCellIndex;
    unsigned long long _fullVisibleEndCellIndex;
    _Bool _averageWidthPerRow;
    _Bool _variableHeightMode;
    _Bool _multipleFreeMode;
    _Bool _hasMoreItem;
    _Bool _fillGirdBoderAutomatically;
    _Bool _canSelectCell;
    _Bool _adjustsContentOffsetAfterSizeChange;
    Class _cellClass;
    NSArray *_items;
    id <WBArrangeCellUpdateDelegate> _eventDelegate;
    id <WBArrangeComputeDelegate> _computeDelegate;
    long long _direction;
    long long _arrangeType;
    double _lineHeight;
    CDUnknownBlockType _lineHeightBlock;
    double _multipleWidth;
    CDUnknownBlockType _multipleWidthBlock;
    double _rowCount;
    double _verticalSpacing;
    double _horizontalSpacing;
    CDUnknownBlockType _verticalSpacingBlock;
    CDUnknownBlockType _horizontalSpacingBlock;
    CDUnknownBlockType _visiblePartRectBlock;
    CDUnknownBlockType _contentInsetBlock;
    CDUnknownBlockType _hitTestBlock;
    double _firstCellHorizontalSpacingExt;
    struct CGSize _fullSize;
    struct CGRect _visiblePartRect;
}

- (void).cxx_destruct;
@property(nonatomic) double firstCellHorizontalSpacingExt; // @synthesize firstCellHorizontalSpacingExt=_firstCellHorizontalSpacingExt;
@property(nonatomic) _Bool adjustsContentOffsetAfterSizeChange; // @synthesize adjustsContentOffsetAfterSizeChange=_adjustsContentOffsetAfterSizeChange;
@property(nonatomic) _Bool canSelectCell; // @synthesize canSelectCell=_canSelectCell;
@property(nonatomic) _Bool fillGirdBoderAutomatically; // @synthesize fillGirdBoderAutomatically=_fillGirdBoderAutomatically;
@property(readonly, nonatomic) NSArray *itemLayouts; // @synthesize itemLayouts=_itemLayouts;
@property(readonly, nonatomic) unsigned long long selectedIndex; // @synthesize selectedIndex=_selectedIndex;
@property(copy, nonatomic) CDUnknownBlockType hitTestBlock; // @synthesize hitTestBlock=_hitTestBlock;
@property(readonly, nonatomic) unsigned long long firstScreenFullVisibleLastCellIndex; // @synthesize firstScreenFullVisibleLastCellIndex=_firstScreenFullVisibleLastCellIndex;
@property(copy, nonatomic) CDUnknownBlockType contentInsetBlock; // @synthesize contentInsetBlock=_contentInsetBlock;
@property(copy, nonatomic) CDUnknownBlockType visiblePartRectBlock; // @synthesize visiblePartRectBlock=_visiblePartRectBlock;
@property(nonatomic) struct CGRect visiblePartRect; // @synthesize visiblePartRect=_visiblePartRect;
@property(nonatomic) struct CGSize fullSize; // @synthesize fullSize=_fullSize;
@property(copy, nonatomic) CDUnknownBlockType horizontalSpacingBlock; // @synthesize horizontalSpacingBlock=_horizontalSpacingBlock;
@property(copy, nonatomic) CDUnknownBlockType verticalSpacingBlock; // @synthesize verticalSpacingBlock=_verticalSpacingBlock;
@property(nonatomic) double horizontalSpacing; // @synthesize horizontalSpacing=_horizontalSpacing;
@property(nonatomic) double verticalSpacing; // @synthesize verticalSpacing=_verticalSpacing;
@property(nonatomic) double rowCount; // @synthesize rowCount=_rowCount;
@property(nonatomic) _Bool hasMoreItem; // @synthesize hasMoreItem=_hasMoreItem;
@property(copy, nonatomic) CDUnknownBlockType multipleWidthBlock; // @synthesize multipleWidthBlock=_multipleWidthBlock;
@property(nonatomic) _Bool multipleFreeMode; // @synthesize multipleFreeMode=_multipleFreeMode;
@property(nonatomic) double multipleWidth; // @synthesize multipleWidth=_multipleWidth;
@property(copy, nonatomic) CDUnknownBlockType lineHeightBlock; // @synthesize lineHeightBlock=_lineHeightBlock;
@property(nonatomic) _Bool variableHeightMode; // @synthesize variableHeightMode=_variableHeightMode;
@property(nonatomic) double lineHeight; // @synthesize lineHeight=_lineHeight;
@property(nonatomic) long long arrangeType; // @synthesize arrangeType=_arrangeType;
@property(nonatomic) long long direction; // @synthesize direction=_direction;
@property(nonatomic) __weak id <WBArrangeComputeDelegate> computeDelegate; // @synthesize computeDelegate=_computeDelegate;
@property(nonatomic) __weak id <WBArrangeCellUpdateDelegate> eventDelegate; // @synthesize eventDelegate=_eventDelegate;
@property(readonly, nonatomic) NSArray *items; // @synthesize items=_items;
@property(nonatomic) _Bool averageWidthPerRow; // @synthesize averageWidthPerRow=_averageWidthPerRow;
@property(readonly, nonatomic) Class cellClass; // @synthesize cellClass=_cellClass;
- (void)didMoveToSuperview;
- (void)reloadData;
- (void)scrollToTop;
- (void)scrollToTopAnimated:(_Bool)arg1;
- (void)scrollToTopForce:(_Bool)arg1 animated:(_Bool)arg2;
- (_Bool)canScroll;
- (struct CGPoint)contentOffsetForItemAtIndex:(unsigned long long)arg1 adjuestBlock:(CDUnknownBlockType)arg2;
- (id)visibleCellAtIndex:(unsigned long long)arg1;
@property(readonly, nonatomic) struct _NSRange fullVisibleIndexRange;
@property(readonly, nonatomic) NSArray *visibleCells;
@property(readonly, nonatomic) NSArray *firstScreenItems;
@property(readonly, nonatomic) NSArray *firstScreenLayouts;
- (void)getFirstScreenLayoutsPtr:(id *)arg1 itemsPtr:(id *)arg2;
- (void)cell:(id)arg1 touchesEnded:(id)arg2 withEvent:(id)arg3;
- (void)cell:(id)arg1 touchesBegan:(id)arg2 withEvent:(id)arg3;
- (void)updateVisibleCellFrame;
- (void)cleanAllCacheIndex;
- (void)layoutSubviews;
- (_Bool)touchesShouldCancelInContentView:(id)arg1;
- (void)detectLoadMoreWithContentOffset:(struct CGPoint)arg1;
- (void)updateVisibleCell;
- (id)hitTest:(struct CGPoint)arg1 withEvent:(id)arg2;
- (void)updateVisiblePartRect;
- (void)updateCell:(id)arg1 forItem:(id)arg2 atIndex:(unsigned long long)arg3 layout:(id)arg4;
- (void)scrollViewDidScroll:(id)arg1;
- (void)_computeRect:(CDUnknownBlockType)arg1;
- (void)computeRect:(CDUnknownBlockType)arg1;
- (void)syncItemLayouts;
- (void)computeRect;
- (void)_computeRectForItems:(id)arg1 fromIndex:(long long)arg2 indeterminacyItemLayouts:(id)arg3 forceSync:(_Bool)arg4 callbackBlock:(CDUnknownBlockType)arg5;
- (void)adjustItemWidthToFillRowWithLayoutsForFreeMode:(id)arg1 remainWidth:(double)arg2 fullWidth:(double)arg3;
- (void)adjustItemWidthToFillRowWithLayouts:(id)arg1 remainWidth:(double)arg2;
- (void)setDelegate:(id)arg1;
- (void)setContentSize:(struct CGSize)arg1;
- (void)setBounds:(struct CGRect)arg1;
- (void)setFrame:(struct CGRect)arg1;
- (unsigned long long)_edgesApplyingSafeAreaInsetsToContentInset;
- (void)setContentOffset:(struct CGPoint)arg1;
- (void)setContentInset:(struct UIEdgeInsets)arg1;
- (void)setContentOffset:(struct CGPoint)arg1 animated:(_Bool)arg2;
- (void)performWithoutChangeContentOffset:(CDUnknownBlockType)arg1;
- (void)setSelectedIndex:(unsigned long long)arg1 forCell:(id)arg2;
- (void)setSelectedIndex:(unsigned long long)arg1;
- (void)replaceRange:(struct _NSRange)arg1 withItems:(id)arg2 animated:(_Bool)arg3;
- (void)updateComputedItemLayouts:(id)arg1;
- (void)insertItem:(id)arg1 atIndex:(unsigned long long)arg2 animated:(_Bool)arg3;
- (void)doActionsAfterDidUpdateComputedItemLayouts;
- (void)performAfterDidUpdateComputedItemLayouts:(CDUnknownBlockType)arg1;
- (void)appendItems:(id)arg1 callbackBlock:(CDUnknownBlockType)arg2;
- (void)execTempComputeRectCallbackBlocksWithTimes:(long long)arg1 reason:(unsigned long long)arg2 finished:(_Bool)arg3;
- (void)addTempComputeRectCallbackBlock:(CDUnknownBlockType)arg1;
- (void)setItems:(id)arg1 callbackBlock:(CDUnknownBlockType)arg2;
- (void)resetContentOffsetIfNeeded;
- (void)setItems:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1 cellClass:(Class)arg2;
- (id)initWithCellClass:(Class)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

