//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface WBArrangeSentinel : NSObject
{
    _Atomic int _value;
}

@property(readonly) _Atomic int value; // @synthesize value=_value;
- (_Atomic int)increase;

@end

