//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class WBArrangeView;

@protocol WBArrangeComputeDelegate <NSObject>

@optional
- (_Bool)arrangeView:(WBArrangeView *)arg1 shouldAsyncComputeForItem:(id)arg2;
- (_Bool)arrangeView:(WBArrangeView *)arg1 shouldNewLineForCell:(id)arg2 atIndex:(unsigned long long)arg3;
- (double)arrangeView:(WBArrangeView *)arg1 heightForItem:(id)arg2 atIndex:(unsigned long long)arg3;
- (double)arrangeView:(WBArrangeView *)arg1 widthForItem:(id)arg2;
@end

