//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSArray, UIView, WBArrangeItemLayout, WBArrangeView;
@protocol WBArrangeCellProtocol;

@protocol WBArrangeCellUpdateDelegate <NSObject>

@optional
- (void)arrangeView:(WBArrangeView *)arg1 didFullShowArrangeItem:(id)arg2 forCell:(id)arg3 atIndex:(unsigned long long)arg4;
- (void)arrangeView:(WBArrangeView *)arg1 didUpdateLayout:(NSArray *)arg2;
- (void)arrangeView:(WBArrangeView *)arg1 didScroll:(struct CGPoint)arg2;
- (void)arrangeViewWillResetContentOffset:(WBArrangeView *)arg1 targetContentOffset:(inout struct CGPoint *)arg2 layout:(WBArrangeItemLayout *)arg3;
- (void)arrangeView:(WBArrangeView *)arg1 animationForInsertedCell:(id)arg2 atIndex:(unsigned long long)arg3 targetRect:(struct CGRect)arg4 layoutBlock:(void (^)(void))arg5;
- (void)arrangeView:(WBArrangeView *)arg1 didSetArrangeItem:(id)arg2 forCell:(id)arg3 atIndex:(unsigned long long)arg4;
- (void)arrangeViewContentSizeChanged:(WBArrangeView *)arg1;
- (void)arrangeViewRequireMoreItem:(WBArrangeView *)arg1;
- (UIView<WBArrangeCellProtocol> *)arrangeView:(WBArrangeView *)arg1 requireCreateCellAtIndex:(long long)arg2;
- (void)arrangeView:(WBArrangeView *)arg1 didSelectCell:(UIView<WBArrangeCellProtocol> *)arg2 atIndex:(unsigned long long)arg3;
- (unsigned long long)arrangeView:(WBArrangeView *)arg1 willSelectCell:(UIView<WBArrangeCellProtocol> *)arg2 atIIndex:(unsigned long long)arg3;
- (void)arrangeView:(WBArrangeView *)arg1 touchBeginAtCell:(UIView<WBArrangeCellProtocol> *)arg2 atIIndex:(unsigned long long)arg3;
- (void)arrangeView:(WBArrangeView *)arg1 didCreateCell:(UIView<WBArrangeCellProtocol> *)arg2 atIIndex:(unsigned long long)arg3;
@end

