//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface WBArrangeItemLayout : NSObject
{
    double _originalWidth;
    double _noMultiplierPtrWidth;
    unsigned long long _multiplier;
    struct CGRect _frame;
    unsigned long long _row;
    unsigned long long _indexOfRow;
    unsigned long long _index;
    id _item;
}

- (void).cxx_destruct;
@property(readonly, nonatomic) unsigned long long index; // @synthesize index=_index;
@property(readonly, nonatomic) unsigned long long indexOfRow; // @synthesize indexOfRow=_indexOfRow;
@property(readonly, nonatomic) unsigned long long row; // @synthesize row=_row;
@property(readonly, nonatomic) struct CGRect frame; // @synthesize frame=_frame;
@property(readonly, nonatomic) double originalWidth; // @synthesize originalWidth=_originalWidth;
- (id)description;
@property(readonly, nonatomic) id item;
- (void)resetForReues;

@end

