//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIView.h>

#import "WBArrangeCellProtocol-Protocol.h"

@class NSString, WBArrangeView;

@interface WBArrangeCell : UIView <WBArrangeCellProtocol>
{
    _Bool _lasted;
    _Bool _isFirstScreen;
    _Bool _fullShown;
    _Bool _fullShownCallbacked;
    _Bool _enabled;
    _Bool _selected;
    _Bool _highlighted;
    WBArrangeView *_arrangeView;
    id _arrangeItem;
    unsigned long long _index;
}

- (void).cxx_destruct;
@property(nonatomic, getter=isHighlighted) _Bool highlighted; // @synthesize highlighted=_highlighted;
@property(nonatomic, getter=isSelected) _Bool selected; // @synthesize selected=_selected;
@property(nonatomic, getter=isEnabled) _Bool enabled; // @synthesize enabled=_enabled;
@property(nonatomic) _Bool fullShownCallbacked; // @synthesize fullShownCallbacked=_fullShownCallbacked;
@property(nonatomic) _Bool fullShown; // @synthesize fullShown=_fullShown;
@property(nonatomic) _Bool isFirstScreen; // @synthesize isFirstScreen=_isFirstScreen;
@property(nonatomic) unsigned long long index; // @synthesize index=_index;
@property(nonatomic) _Bool lasted; // @synthesize lasted=_lasted;
@property(retain, nonatomic) id arrangeItem; // @synthesize arrangeItem=_arrangeItem;
@property(nonatomic) __weak WBArrangeView *arrangeView; // @synthesize arrangeView=_arrangeView;
- (void)cleanUpFullShownStatus;
- (void)cleanUp;
- (void)sendClickTouch:(id)arg1;
- (void)setArrangeItem:(id)arg1 atIndex:(unsigned long long)arg2 layout:(id)arg3;
- (void)touchesCancelled:(id)arg1 withEvent:(id)arg2;
- (void)touchesEnded:(id)arg1 withEvent:(id)arg2;
- (void)touchesBegan:(id)arg1 withEvent:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

