//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class WBArrangeItemLayout, WBArrangeView;

@protocol WBArrangeCellProtocol <NSObject>
@property(nonatomic) __weak WBArrangeView *arrangeView;
@property(nonatomic) _Bool fullShownCallbacked;
@property(nonatomic) _Bool fullShown;
@property(nonatomic) _Bool isFirstScreen;
@property(nonatomic) _Bool lasted;
@property(nonatomic) unsigned long long index;
@property(retain, nonatomic) id arrangeItem;
- (void)setArrangeItem:(id)arg1 atIndex:(unsigned long long)arg2 layout:(WBArrangeItemLayout *)arg3;

@optional
- (void)cleanUpFullShownStatus;
- (void)cleanUp;
@end

