//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "WBButton.h"

@class UIView;

@interface WBAskAIToast : WBButton
{
    CDUnknownBlockType _layoutBlock;
    UIView *_parentView;
    unsigned long long _animationStyle;
}

+ (unsigned long long)animationStyle;
+ (void)setAnimationStyle:(unsigned long long)arg1;
+ (void)showNormalWithText:(id)arg1;
+ (void)showSuccessWithText:(id)arg1;
+ (void)showErrorWithText:(id)arg1;
+ (void)hideLoading;
+ (void)showLoadingWithText:(id)arg1;
+ (id)makeToast;
+ (id)toastWithType:(unsigned long long)arg1;
+ (void)hideMoreContentTips;
+ (void)showMoreContentTips;
+ (id)appearance;
+ (void)disconnectFromParentView:(id)arg1;
+ (void)connectToParentView:(id)arg1;
+ (void)hideAllToastView;
+ (id)allToastView;
- (void).cxx_destruct;
@property(nonatomic) unsigned long long animationStyle; // @synthesize animationStyle=_animationStyle;
@property(nonatomic) __weak UIView *parentView; // @synthesize parentView=_parentView;
@property(copy, nonatomic) CDUnknownBlockType layoutBlock; // @synthesize layoutBlock=_layoutBlock;
- (void)showTipsButtonTitle:(id)arg1 type:(unsigned long long)arg2 edgeInset:(double)arg3 rotationAnimation:(_Bool)arg4 hideAfterDelay:(double)arg5;
- (void)showWithAnimated:(_Bool)arg1;
- (void)hideTipsButton;
- (void)didMoveToSuperview;
- (id)initWithFrame:(struct CGRect)arg1;

@end

