//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "WBWebView.h"

@interface WBAskAIWebView : WBWebView
{
    CDUnknownBlockType _compositingLayerDidSetContents;
}

+ (void)initialize;
+ (id)wbScrollIndicatorColor;
- (void).cxx_destruct;
@property(copy, nonatomic) CDUnknownBlockType compositingLayerDidSetContents; // @synthesize compositingLayerDidSetContents=_compositingLayerDidSetContents;
- (void)sendShareImage;
- (void)saveShareImage;
- (void)initPluginContent:(id)arg1;
- (void)onPageExpose:(_Bool)arg1 source:(id)arg2;
- (void)scrollWebViewContenViaJs:(_Bool)arg1;
- (void)abortAskAI;
- (void)askAI:(id)arg1 displayQuery:(id)arg2 cookie:(id)arg3 forceNewChat:(_Bool)arg4 isAutoSendQuery:(_Bool)arg5;
- (void)getContentHeight:(CDUnknownBlockType)arg1;
- (void)takeSnapshotWithCompletion:(CDUnknownBlockType)arg1;
- (void)evaluateJavaScriptAndTakeSnapshot:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (id)initWithFrame:(struct CGRect)arg1 configuration:(id)arg2;
- (id)description;
- (id)wbTintColor;

@end

