//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "WBViewController.h"

#import "QMUITextViewDelegate-Protocol.h"
#import "WKNavigationDelegate-Protocol.h"
#import "WKUIDelegate-Protocol.h"

@class NSDictionary, NSString, UIButton, UIImageView, UILabel, UIView, WBAskAITextView, WBAskAIWebView;

@interface WBAskAIViewController : WBViewController <QMUITextViewDelegate, WKNavigationDelegate, WKUIDelegate>
{
    _Bool _webviewBroken;
    _Bool _keyboardActive;
    _Bool _updateWithFrameChange;
    _Bool _inKeyboardAnimation;
    _Bool _viewAppeared;
    _Bool _firstPageReadyActionHandled;
    NSDictionary *_initialParams;
    UIView *_bottomView;
    UIImageView *_titleImageView;
    UILabel *_titleDescLabel;
    UIView *_titleContainerView;
    long long _buttonStatus;
    WBAskAITextView *_askTextView;
    UIButton *_askBtn;
    WBAskAIWebView *_webView;
    double _keyboardHeight;
    double _webviewContentHeight;
    double _navigationHeight;
    long long _status;
    UIButton *_retryBtn;
    UILabel *_emptyLabel;
    UIView *_emptyContainerView;
}

+ (void)preload;
+ (void)initialize;
+ (id)sharedInstance;
+ (id)sharedInstanceWithParams:(id)arg1;
- (void).cxx_destruct;
@property(retain, nonatomic) UIView *emptyContainerView; // @synthesize emptyContainerView=_emptyContainerView;
@property(retain, nonatomic) UILabel *emptyLabel; // @synthesize emptyLabel=_emptyLabel;
@property(retain, nonatomic) UIButton *retryBtn; // @synthesize retryBtn=_retryBtn;
@property(nonatomic) long long status; // @synthesize status=_status;
@property(nonatomic) _Bool firstPageReadyActionHandled; // @synthesize firstPageReadyActionHandled=_firstPageReadyActionHandled;
@property(nonatomic) _Bool viewAppeared; // @synthesize viewAppeared=_viewAppeared;
@property(nonatomic) _Bool inKeyboardAnimation; // @synthesize inKeyboardAnimation=_inKeyboardAnimation;
@property(nonatomic) _Bool updateWithFrameChange; // @synthesize updateWithFrameChange=_updateWithFrameChange;
@property(nonatomic) _Bool keyboardActive; // @synthesize keyboardActive=_keyboardActive;
@property(nonatomic) _Bool webviewBroken; // @synthesize webviewBroken=_webviewBroken;
@property(nonatomic) double navigationHeight; // @synthesize navigationHeight=_navigationHeight;
@property(nonatomic) double webviewContentHeight; // @synthesize webviewContentHeight=_webviewContentHeight;
@property(nonatomic) double keyboardHeight; // @synthesize keyboardHeight=_keyboardHeight;
@property(retain, nonatomic) WBAskAIWebView *webView; // @synthesize webView=_webView;
@property(retain, nonatomic) UIButton *askBtn; // @synthesize askBtn=_askBtn;
@property(retain, nonatomic) WBAskAITextView *askTextView; // @synthesize askTextView=_askTextView;
@property(nonatomic) long long buttonStatus; // @synthesize buttonStatus=_buttonStatus;
@property(retain, nonatomic) UIView *titleContainerView; // @synthesize titleContainerView=_titleContainerView;
@property(retain, nonatomic) UILabel *titleDescLabel; // @synthesize titleDescLabel=_titleDescLabel;
@property(retain, nonatomic) UIImageView *titleImageView; // @synthesize titleImageView=_titleImageView;
@property(retain, nonatomic) UIView *bottomView; // @synthesize bottomView=_bottomView;
@property(retain, nonatomic) NSDictionary *initialParams; // @synthesize initialParams=_initialParams;
- (void)webViewWebContentProcessDidTerminate:(id)arg1;
- (void)webViewDidClose:(id)arg1;
- (id)webView:(id)arg1 createWebViewWithConfiguration:(id)arg2 forNavigationAction:(id)arg3 windowFeatures:(id)arg4;
- (void)webView:(id)arg1 runJavaScriptTextInputPanelWithPrompt:(id)arg2 defaultText:(id)arg3 initiatedByFrame:(id)arg4 completionHandler:(CDUnknownBlockType)arg5;
- (void)webView:(id)arg1 runJavaScriptConfirmPanelWithMessage:(id)arg2 initiatedByFrame:(id)arg3 completionHandler:(CDUnknownBlockType)arg4;
- (void)webView:(id)arg1 runJavaScriptAlertPanelWithMessage:(id)arg2 initiatedByFrame:(id)arg3 completionHandler:(CDUnknownBlockType)arg4;
- (void)webView:(id)arg1 didReceiveAuthenticationChallenge:(id)arg2 completionHandler:(CDUnknownBlockType)arg3;
- (void)webView:(id)arg1 didFailNavigation:(id)arg2 withError:(id)arg3;
- (void)webView:(id)arg1 didFinishNavigation:(id)arg2;
- (void)webView:(id)arg1 didCommitNavigation:(id)arg2;
- (void)webView:(id)arg1 didFailProvisionalNavigation:(id)arg2 withError:(id)arg3;
- (void)webView:(id)arg1 didReceiveServerRedirectForProvisionalNavigation:(id)arg2;
- (void)webView:(id)arg1 didStartProvisionalNavigation:(id)arg2;
- (void)webView:(id)arg1 decidePolicyForNavigationAction:(id)arg2 decisionHandler:(CDUnknownBlockType)arg3;
- (void)handleJSAPIName:(id)arg1 params:(id)arg2 callbackId:(id)arg3;
- (void)onPageExpose:(_Bool)arg1 source:(id)arg2;
- (void)scrollWebViewContenViaJs:(_Bool)arg1;
- (void)abortAskAI;
- (void)initPluginContent:(id)arg1;
- (void)askAI:(id)arg1 displayQuery:(id)arg2 cookie:(id)arg3 forceNewChat:(_Bool)arg4 isAutoSendQuery:(_Bool)arg5;
- (void)getContentHeight:(CDUnknownBlockType)arg1;
@property(readonly, nonatomic) _Bool webViewPageReady;
- (void)handleReportPageReady;
- (void)reloadWebView;
- (void)onBusinessInited:(id)arg1;
- (void)keyboardWillHide:(id)arg1;
- (void)didEnterBackground:(id)arg1;
- (void)applicationDidBecomeActive:(id)arg1;
- (void)keyboardWillShow:(id)arg1;
- (void)handleTitleAction:(id)arg1;
- (void)handleReBtnAction:(id)arg1;
- (void)updateButtonEnable;
- (_Bool)isOnlyWhitespaceOrNewline:(id)arg1;
- (_Bool)textView:(id)arg1 shouldChangeTextInRange:(struct _NSRange)arg2 replacementText:(id)arg3;
- (void)textView:(id)arg1 newHeightAfterTextChanged:(double)arg2;
- (void)textViewDidChange:(id)arg1;
- (void)fetchData;
- (void)handleActionAfterPageReady;
- (id)baseTextAttribute;
- (void)scrollWebViewToBottom;
- (void)updateWebViewFrameWithOffset;
- (void)updateWebViewFrameWithoutOffset;
- (void)updateFrame;
- (void)viewDidLayoutSubviews;
- (void)resetReusableData;
- (void)initData;
- (void)initUI;
@property(readonly, copy) NSString *description;
- (void)dealloc;
- (_Bool)shouldPopViewControllerByBackButtonOrPopGesture:(_Bool)arg1;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)updateParams:(id)arg1;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

