//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "QMUITextView.h"

@interface WBAskAITextView : QMUITextView
{
    CDUnknownBlockType _actionBeforeBecomeFirstResponder;
}

- (void).cxx_destruct;
@property(copy, nonatomic) CDUnknownBlockType actionBeforeBecomeFirstResponder; // @synthesize actionBeforeBecomeFirstResponder=_actionBeforeBecomeFirstResponder;
- (void)becomeFirstResponder_O;
- (_Bool)becomeFirstResponder;

@end

