//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "WBViewController.h"

@class NSDictionary, UIScrollView, UIView, WBAuthAndPrivacyItemView;

@interface WBAuthAndPrivacyViewController : WBViewController
{
    UIScrollView *_containerView;
    UIView *_bgView;
    WBAuthAndPrivacyItemView *_kbView;
    WBAuthAndPrivacyItemView *_fullAccessView;
    WBAuthAndPrivacyItemView *_microPhoneView;
    WBAuthAndPrivacyItemView *_userDictView;
    WBAuthAndPrivacyItemView *_photoPrivacyView;
    NSDictionary *_featureDicts;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSDictionary *featureDicts; // @synthesize featureDicts=_featureDicts;
@property(retain, nonatomic) WBAuthAndPrivacyItemView *photoPrivacyView; // @synthesize photoPrivacyView=_photoPrivacyView;
@property(retain, nonatomic) WBAuthAndPrivacyItemView *userDictView; // @synthesize userDictView=_userDictView;
@property(retain, nonatomic) WBAuthAndPrivacyItemView *microPhoneView; // @synthesize microPhoneView=_microPhoneView;
@property(retain, nonatomic) WBAuthAndPrivacyItemView *fullAccessView; // @synthesize fullAccessView=_fullAccessView;
@property(retain, nonatomic) WBAuthAndPrivacyItemView *kbView; // @synthesize kbView=_kbView;
@property(retain, nonatomic) UIView *bgView; // @synthesize bgView=_bgView;
@property(retain, nonatomic) UIScrollView *containerView; // @synthesize containerView=_containerView;
- (void)showClearPasteboardConfirm;
- (void)showClearUserDictConfirm;
- (void)gotoSystemSetting;
- (void)refreshStatus;
- (id)modelForNetwork;
- (id)modelForMicroPhoneNotOpened;
- (id)modelForPhotoPrivacy;
- (id)modelForUserDict;
- (id)modelForMicroPhoneOpened;
- (id)modelForFullAccessNone;
- (id)modelForFullAccessNotOpened;
- (id)modelForFullAccessOpened;
- (id)modelForKeyboardInActive;
- (id)modelForKeyboardActived;
- (id)modelForKeyboardInUsing;
- (id)featureDescForKey:(id)arg1 descKey:(id)arg2;
- (_Bool)showPhotoPrivacy;
- (_Bool)showUserDict;
- (_Bool)showMicroPhoneView;
- (_Bool)showFullAccessView;
- (_Bool)showKBView;
- (void)onAppDidBecomeActive:(id)arg1;
- (void)pluginInfoDidChange;
- (void)inputModeStateDidChange;
- (void)reOrderAllItems;
- (void)initUI;
- (void)addObservers;
- (id)title;
- (void)viewDidLayoutSubviews;
- (void)dealloc;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewDidLoad;

@end

