//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIView.h>

@class SFSafariViewController, UILabel, WBAlertController;

@interface WBAuthButton : UIView
{
    UILabel *_label;
    SFSafariViewController *_safariViewController;
    int _port;
    int _webServerCallback;
    unsigned long long _initialChangeCount;
    WBAlertController *_viewController;
    CDUnknownBlockType _copyFinishBlock;
}

- (void).cxx_destruct;
@property(copy, nonatomic) CDUnknownBlockType copyFinishBlock; // @synthesize copyFinishBlock=_copyFinishBlock;
@property(nonatomic) __weak WBAlertController *viewController; // @synthesize viewController=_viewController;
- (void)runLoop;
- (void)layoutSubviews;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;
- (void)setupSafariViewControllerIfNeeded;
- (void)setupWebServer;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;

@end

