//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIView.h>

@class UILabel, YYLabel;

@interface WBAuthAndPrivacyItemView : UIView
{
    UILabel *_titleLabel;
    UILabel *_indicatorLabel;
    YYLabel *_detailLabel;
    UIView *_separatorView;
    CDUnknownBlockType _clickBlock;
    struct _NSRange _highlightRange;
}

- (void).cxx_destruct;
@property(copy, nonatomic) CDUnknownBlockType clickBlock; // @synthesize clickBlock=_clickBlock;
@property(nonatomic) struct _NSRange highlightRange; // @synthesize highlightRange=_highlightRange;
@property(retain, nonatomic) UIView *separatorView; // @synthesize separatorView=_separatorView;
@property(retain, nonatomic) YYLabel *detailLabel; // @synthesize detailLabel=_detailLabel;
@property(retain, nonatomic) UILabel *indicatorLabel; // @synthesize indicatorLabel=_indicatorLabel;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
- (void)layoutSubviews;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;
- (void)initUI;
- (void)render:(id)arg1 indicator:(id)arg2 indicatorOn:(_Bool)arg3 detail:(id)arg4 highlightRange:(struct _NSRange)arg5 clickBlock:(CDUnknownBlockType)arg6;
- (void)enableSeparator:(_Bool)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

