//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface WBAuthAndPrivacyItemModel : NSObject
{
    _Bool _enabled;
    NSString *_title;
    NSString *_hint;
    NSString *_desc;
    NSString *_clickable;
}

- (void).cxx_destruct;
@property(nonatomic) _Bool enabled; // @synthesize enabled=_enabled;
@property(copy, nonatomic) NSString *clickable; // @synthesize clickable=_clickable;
@property(copy, nonatomic) NSString *desc; // @synthesize desc=_desc;
@property(copy, nonatomic) NSString *hint; // @synthesize hint=_hint;
@property(copy, nonatomic) NSString *title; // @synthesize title=_title;
- (struct _NSRange)highlightRange;
- (id)displayDetail;

@end

