//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "GPBMessage.h"

@class NSMutableArray;

@interface WBBookVideoSearchResultItemSubWindow : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(nonatomic) _Bool hasIcon; // @dynamic hasIcon;
@property(nonatomic) int icon; // @dynamic icon;
@property(retain, nonatomic) NSMutableArray *textListArray; // @dynamic textListArray;
@property(readonly, nonatomic) unsigned long long textListArray_Count; // @dynamic textListArray_Count;

@end

