//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "GPBMessage.h"

@class NSString;

@interface WBBookVideoSearchResultItemSubWindowText : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(nonatomic) unsigned long long color; // @dynamic color;
@property(nonatomic) unsigned long long colorDark; // @dynamic colorDark;
@property(nonatomic) int fontSize; // @dynamic fontSize;
@property(nonatomic) _Bool hasColor; // @dynamic hasColor;
@property(nonatomic) _Bool hasColorDark; // @dynamic hasColorDark;
@property(nonatomic) _Bool hasFontSize; // @dynamic hasFontSize;
@property(nonatomic) _Bool hasText; // @dynamic hasText;
@property(copy, nonatomic) NSString *text; // @dynamic text;

@end

