//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "GPBMessage.h"

@class GPBStringInt64Dictionary, NSMutableArray, NSString;

@interface WBBookVideoSearchReq : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(nonatomic) long long aBtestOpt; // @dynamic aBtestOpt;
@property(retain, nonatomic) GPBStringInt64Dictionary *aBtestOpts; // @dynamic aBtestOpts;
@property(readonly, nonatomic) unsigned long long aBtestOpts_Count; // @dynamic aBtestOpts_Count;
@property(copy, nonatomic) NSString *appver; // @dynamic appver;
@property(nonatomic) long long clientTimestamp; // @dynamic clientTimestamp;
@property(copy, nonatomic) NSString *content; // @dynamic content;
@property(copy, nonatomic) NSString *context; // @dynamic context;
@property(nonatomic) int cursorIndex; // @dynamic cursorIndex;
@property(copy, nonatomic) NSString *extraInfo; // @dynamic extraInfo;
@property(nonatomic) unsigned long long featureFlag; // @dynamic featureFlag;
@property(nonatomic) _Bool hasABtestOpt; // @dynamic hasABtestOpt;
@property(nonatomic) _Bool hasAppver; // @dynamic hasAppver;
@property(nonatomic) _Bool hasClientTimestamp; // @dynamic hasClientTimestamp;
@property(nonatomic) _Bool hasContent; // @dynamic hasContent;
@property(nonatomic) _Bool hasContext; // @dynamic hasContext;
@property(nonatomic) _Bool hasCursorIndex; // @dynamic hasCursorIndex;
@property(nonatomic) _Bool hasExtraInfo; // @dynamic hasExtraInfo;
@property(nonatomic) _Bool hasFeatureFlag; // @dynamic hasFeatureFlag;
@property(nonatomic) _Bool hasInterval; // @dynamic hasInterval;
@property(nonatomic) _Bool hasKeyboardType; // @dynamic hasKeyboardType;
@property(nonatomic) _Bool hasNoDefault; // @dynamic hasNoDefault;
@property(nonatomic) _Bool hasPf; // @dynamic hasPf;
@property(nonatomic) _Bool hasScene; // @dynamic hasScene;
@property(nonatomic) _Bool hasSelectedContent; // @dynamic hasSelectedContent;
@property(nonatomic) _Bool hasSessionId; // @dynamic hasSessionId;
@property(nonatomic) _Bool hasSuggestType; // @dynamic hasSuggestType;
@property(nonatomic) _Bool hasTraceId; // @dynamic hasTraceId;
@property(nonatomic) long long interval; // @dynamic interval;
@property(nonatomic) int keyboardType; // @dynamic keyboardType;
@property(nonatomic) _Bool noDefault; // @dynamic noDefault;
@property(copy, nonatomic) NSString *pf; // @dynamic pf;
@property(nonatomic) int scene; // @dynamic scene;
@property(copy, nonatomic) NSString *selectedContent; // @dynamic selectedContent;
@property(copy, nonatomic) NSString *sessionId; // @dynamic sessionId;
@property(retain, nonatomic) NSMutableArray *statusArray; // @dynamic statusArray;
@property(readonly, nonatomic) unsigned long long statusArray_Count; // @dynamic statusArray_Count;
@property(nonatomic) int suggestType; // @dynamic suggestType;
@property(copy, nonatomic) NSString *traceId; // @dynamic traceId;

@end

