//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <QuartzCore/CAShapeLayer.h>

@class UIView;

@interface WBBorderLayer : CAShapeLayer
{
    UIView *__qmuibd_targetBorderView;
}

- (void).cxx_destruct;
@property(nonatomic) __weak UIView *_qmuibd_targetBorderView; // @synthesize _qmuibd_targetBorderView=__qmuibd_targetBorderView;
- (void)layoutSublayers;

@end

