//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "GPBMessage.h"

@class WBBookVideoSearchResultItemSubWindow;

@interface WBBookVideoSearchResultItem : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(nonatomic) _Bool hasSubWindow; // @dynamic hasSubWindow;
@property(retain, nonatomic) WBBookVideoSearchResultItemSubWindow *subWindow; // @dynamic subWindow;

@end

