//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "GPBMessage.h"

@class NSMutableArray, NSString, WBBookVideoSearchResultItemDetail;

@interface WBBookVideoSearchRsp : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(copy, nonatomic) NSString *abParams; // @dynamic abParams;
@property(retain, nonatomic) WBBookVideoSearchResultItemDetail *detail; // @dynamic detail;
@property(nonatomic) _Bool hasAbParams; // @dynamic hasAbParams;
@property(nonatomic) _Bool hasDetail; // @dynamic hasDetail;
@property(nonatomic) _Bool hasScene; // @dynamic hasScene;
@property(nonatomic) _Bool hasVersion; // @dynamic hasVersion;
@property(retain, nonatomic) NSMutableArray *itemsArray; // @dynamic itemsArray;
@property(readonly, nonatomic) unsigned long long itemsArray_Count; // @dynamic itemsArray_Count;
@property(nonatomic) int scene; // @dynamic scene;
@property(nonatomic) int version; // @dynamic version;

@end

