//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "GPBMessage.h"

@class NSString;

@interface WBBookVideoSearchResultItemDetail : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(nonatomic) _Bool hasJson; // @dynamic hasJson;
@property(copy, nonatomic) NSString *json; // @dynamic json;

@end

