//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface WBBundleLoaderStat : NSObject
{
    NSString *_bundleName;
    NSString *_bundleMD5;
    long long _loadCount;
    long long _succCount;
    long long _failCount;
}

- (void).cxx_destruct;
@property(nonatomic) long long failCount; // @synthesize failCount=_failCount;
@property(nonatomic) long long succCount; // @synthesize succCount=_succCount;
@property(nonatomic) long long loadCount; // @synthesize loadCount=_loadCount;
@property(retain, nonatomic) NSString *bundleMD5; // @synthesize bundleMD5=_bundleMD5;
@property(retain, nonatomic) NSString *bundleName; // @synthesize bundleName=_bundleName;
- (id)initWithBundleName:(id)arg1 bundleMD5:(id)arg2;

@end

