//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIButton.h>

@class CALayer, UIColor, UIView;

@interface WBButton : UIButton
{
    UIView *_unreadDotView;
    _Bool _adjustsTitleTintColorAutomatically;
    _Bool _adjustsImageTintColorAutomatically;
    _Bool _adjustsButtonWhenHighlighted;
    _Bool _adjustsButtonWhenDisabled;
    _Bool _isRounded;
    _Bool _showUnreadDot;
    _Bool _hasTapTarget;
    _Bool _longPressGestureRecognizerAdded;
    UIColor *_tintColorAdjustsTitleAndImage;
    UIColor *_highlightedBackgroundColor;
    UIColor *_highlightedBorderColor;
    unsigned long long _imagePosition;
    double _spacingBetweenImageAndTitle;
    double _cornerRadius;
    CDUnknownBlockType _tapBlock;
    double _minimumPressDuration;
    CDUnknownBlockType _longPressBlock;
    id _extraInfo;
    CDUnknownBlockType _sizeThatFitsBlock;
    CDUnknownBlockType _adjustedSizeThatFitsBlock;
    CALayer *_highlightedBackgroundLayer;
    UIColor *_originBorderColor;
}

- (void).cxx_destruct;
@property(nonatomic) _Bool longPressGestureRecognizerAdded; // @synthesize longPressGestureRecognizerAdded=_longPressGestureRecognizerAdded;
@property(nonatomic) _Bool hasTapTarget; // @synthesize hasTapTarget=_hasTapTarget;
@property(retain, nonatomic) UIColor *originBorderColor; // @synthesize originBorderColor=_originBorderColor;
@property(retain, nonatomic) CALayer *highlightedBackgroundLayer; // @synthesize highlightedBackgroundLayer=_highlightedBackgroundLayer;
@property(nonatomic) _Bool showUnreadDot; // @synthesize showUnreadDot=_showUnreadDot;
@property(nonatomic) _Bool isRounded; // @synthesize isRounded=_isRounded;
@property(copy, nonatomic) CDUnknownBlockType adjustedSizeThatFitsBlock; // @synthesize adjustedSizeThatFitsBlock=_adjustedSizeThatFitsBlock;
@property(copy, nonatomic) CDUnknownBlockType sizeThatFitsBlock; // @synthesize sizeThatFitsBlock=_sizeThatFitsBlock;
@property(retain, nonatomic) id extraInfo; // @synthesize extraInfo=_extraInfo;
@property(copy, nonatomic) CDUnknownBlockType longPressBlock; // @synthesize longPressBlock=_longPressBlock;
@property(nonatomic) double minimumPressDuration; // @synthesize minimumPressDuration=_minimumPressDuration;
@property(copy, nonatomic) CDUnknownBlockType tapBlock; // @synthesize tapBlock=_tapBlock;
@property(nonatomic) double cornerRadius; // @synthesize cornerRadius=_cornerRadius;
@property(nonatomic) double spacingBetweenImageAndTitle; // @synthesize spacingBetweenImageAndTitle=_spacingBetweenImageAndTitle;
@property(nonatomic) unsigned long long imagePosition; // @synthesize imagePosition=_imagePosition;
@property(retain, nonatomic) UIColor *highlightedBorderColor; // @synthesize highlightedBorderColor=_highlightedBorderColor;
@property(retain, nonatomic) UIColor *highlightedBackgroundColor; // @synthesize highlightedBackgroundColor=_highlightedBackgroundColor;
@property(nonatomic) _Bool adjustsButtonWhenDisabled; // @synthesize adjustsButtonWhenDisabled=_adjustsButtonWhenDisabled;
@property(nonatomic) _Bool adjustsButtonWhenHighlighted; // @synthesize adjustsButtonWhenHighlighted=_adjustsButtonWhenHighlighted;
@property(retain, nonatomic) UIColor *tintColorAdjustsTitleAndImage; // @synthesize tintColorAdjustsTitleAndImage=_tintColorAdjustsTitleAndImage;
@property(nonatomic) _Bool adjustsImageTintColorAutomatically; // @synthesize adjustsImageTintColorAutomatically=_adjustsImageTintColorAutomatically;
@property(nonatomic) _Bool adjustsTitleTintColorAutomatically; // @synthesize adjustsTitleTintColorAutomatically=_adjustsTitleTintColorAutomatically;
- (void)setBounds:(struct CGRect)arg1;
- (void)setFrame:(struct CGRect)arg1;
- (void)setTitle:(id)arg1 selectedTitle:(id)arg2;
- (void)setImage:(id)arg1 selectedImage:(id)arg2;
- (id)styledCopy;
- (void)applyStyleFromButton:(id)arg1;
- (id)initWithImage:(id)arg1;
- (id)initWithTitle:(id)arg1 image:(id)arg2;
- (void)handleLongPressGesture:(id)arg1;
- (void)handleTouchUpInside:(in id)arg1;
- (void)tintColorDidChange;
- (void)setImage:(id)arg1 forState:(unsigned long long)arg2;
- (void)updateImageRenderingModeIfNeeded;
- (void)updateTitleColorIfNeeded;
- (void)adjustsButtonHighlighted;
- (void)setEnabled:(_Bool)arg1;
- (void)setHighlighted:(_Bool)arg1;
- (id)layoutForImagePositionRight:(_Bool)arg1 contentSize:(struct CGSize)arg2 imageTotalSize:(struct CGSize)arg3 spacingBetweenImageAndTitle:(double)arg4 isImageViewShowing:(_Bool)arg5 imageFrame:(struct CGRect)arg6 contentEdgeInsets:(struct UIEdgeInsets)arg7 titleFrame:(struct CGRect)arg8 titleTotalSize:(struct CGSize)arg9;
- (id)layoutForImagePositionLeft:(_Bool)arg1 contentSize:(struct CGSize)arg2 imageTotalSize:(struct CGSize)arg3 spacingBetweenImageAndTitle:(double)arg4 isImageViewShowing:(_Bool)arg5 imageFrame:(struct CGRect)arg6 contentEdgeInsets:(struct UIEdgeInsets)arg7 titleFrame:(struct CGRect)arg8 titleTotalSize:(struct CGSize)arg9;
- (void)layoutForImagePositionLeftOrRight:(_Bool)arg1 contentSize:(struct CGSize)arg2 imageTotalSize:(struct CGSize)arg3 spacingBetweenImageAndTitle:(double)arg4 isImageViewShowing:(_Bool)arg5 imageFrame:(struct CGRect)arg6 contentEdgeInsets:(struct UIEdgeInsets)arg7;
- (id)layoutForImagePositionBottom:(_Bool)arg1 contentSize:(struct CGSize)arg2 imageTotalSize:(struct CGSize)arg3 spacingBetweenImageAndTitle:(double)arg4 isImageViewShowing:(_Bool)arg5 imageFrame:(struct CGRect)arg6 contentEdgeInsets:(struct UIEdgeInsets)arg7 titleFrame:(struct CGRect)arg8 titleTotalSize:(struct CGSize)arg9;
- (id)layoutForImagePositionTop:(_Bool)arg1 contentSize:(struct CGSize)arg2 imageTotalSize:(struct CGSize)arg3 spacingBetweenImageAndTitle:(double)arg4 isImageViewShowing:(_Bool)arg5 imageFrame:(struct CGRect)arg6 contentEdgeInsets:(struct UIEdgeInsets)arg7 titleFrame:(struct CGRect)arg8 titleTotalSize:(struct CGSize)arg9;
- (void)layoutForImagePositionTopOrBottom:(_Bool)arg1 contentSize:(struct CGSize)arg2 imageTotalSize:(struct CGSize)arg3 spacingBetweenImageAndTitle:(double)arg4 isImageViewShowing:(_Bool)arg5 imageFrame:(struct CGRect)arg6 imageLimitSize:(struct CGSize)arg7 contentEdgeInsets:(struct UIEdgeInsets)arg8;
- (void)layoutSubviews;
- (struct CGSize)intrinsicContentSize;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;
- (id)_qmui_imageView;
- (void)didInitialize;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

