//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMutableDictionary;

@interface WBBundleLoaderWatchDog : NSObject
{
    NSMutableDictionary *_info;
}

+ (id)sharedInstance;
- (void).cxx_destruct;
@property(retain, nonatomic) NSMutableDictionary *info; // @synthesize info=_info;
- (_Bool)canLoadBundle:(id)arg1;
- (void)didFailLoadCurrentBundleForError:(id)arg1;
- (void)didFailLoadBundle:(id)arg1;
- (void)didSuccessLoadBundle:(id)arg1;
- (void)startLoadBundle:(id)arg1;
- (id)statForBundle:(id)arg1 bundleMD5:(id)arg2;
- (id)init;

@end

