//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "MMService.h"

#import "MMServiceProtocol-Protocol.h"
#import "WBBusinessRequestProtocol-Protocol.h"

@class NSMutableArray, NSString;

@interface WBBusinessMgr : MMService <MMServiceProtocol, WBBusinessRequestProtocol>
{
    _Bool _useDebug;
    _Bool _standaloneEnable;
    NSMutableArray *_reportCacheForNoUin;
    unsigned long long _uin;
    NSString *_deviceCode;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSString *deviceCode; // @synthesize deviceCode=_deviceCode;
@property(nonatomic) unsigned long long uin; // @synthesize uin=_uin;
- (void)fetchServerTimestamp;
- (void)notifyConnectStatusDidChange:(_Bool)arg1;
- (void)flushReportToDB;
- (_Bool)isBusinessNotifyConnected;
- (void)stopAutoReportLogs;
- (void)startAutoReportLogs;
- (void)stopReceiveNotify;
- (void)startReceiveNotify;
- (void)handShakeIfNeeded;
- (void)reportInstantID:(id)arg1 base64Content:(id)arg2;
- (void)reportInstantID:(id)arg1 content:(id)arg2;
- (void)doReportID:(id)arg1 base64Content:(id)arg2;
- (void)reportID:(id)arg1 base64Content:(id)arg2;
- (void)reportID:(id)arg1 content:(id)arg2;
- (int)requestBusinessWithCmd:(unsigned int)arg1 subCmd:(unsigned int)arg2 data:(id)arg3 userInfo:(id)arg4 timeout:(double)arg5 onSuccess:(CDUnknownBlockType)arg6 onFailure:(CDUnknownBlockType)arg7;
- (int)requestBusinessWithCmd:(unsigned int)arg1 subCmd:(unsigned int)arg2 pb:(id)arg3 userInfo:(id)arg4 timeout:(double)arg5 onSuccess:(CDUnknownBlockType)arg6 onFailure:(CDUnknownBlockType)arg7;
- (void)dealloc;
- (void)onSettingsChanged;
- (void)updateBuglyUserId:(unsigned long long)arg1;
- (void)reportCacheDataForNoUin;
- (void)updateCurrentUin:(id)arg1 needSave:(_Bool)arg2 resetBusinessUin:(_Bool)arg3;
- (void)initBusiness:(id)arg1 oldUin:(id)arg2 deviceCode:(id)arg3 needGetUin:(_Bool)arg4;
- (void)doInitLogic;
- (void)updateDeviceCode:(id)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

