//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class GPBMessage, NSData;

@protocol WBBusinessRequestProtocol <NSObject>
- (int)requestBusinessWithCmd:(unsigned int)arg1 subCmd:(unsigned int)arg2 data:(NSData *)arg3 userInfo:(id)arg4 timeout:(double)arg5 onSuccess:(void (^)(NSData *, id, int))arg6 onFailure:(void (^)(int, id, int))arg7;
- (int)requestBusinessWithCmd:(unsigned int)arg1 subCmd:(unsigned int)arg2 pb:(GPBMessage *)arg3 userInfo:(id)arg4 timeout:(double)arg5 onSuccess:(void (^)(NSData *, id, int))arg6 onFailure:(void (^)(int, id, int))arg7;
@end

