//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "WBTextItemCell.h"

@class CALayer, CAShapeLayer, UIImageView, UILabel, WBTextLayout;

@interface WBCandidateCell : WBTextItemCell
{
    _Bool _hasHasOverrideFrameForCornerIconView;
    _Bool _hasHasOverrideFrameForTextLabel;
    _Bool _needsSeparatorLayer;
    CAShapeLayer *_wavyUnderlineLayer;
    CALayer *_separatorLayer;
    _Bool _expandTouchAreaInHorizontalLaout;
    UIImageView *_cornerIconView;
    UILabel *_repeatedLabel;
    WBTextLayout *_layout;
    struct CGSize _cornerIconSize;
}

- (void).cxx_destruct;
@property(nonatomic) _Bool expandTouchAreaInHorizontalLaout; // @synthesize expandTouchAreaInHorizontalLaout=_expandTouchAreaInHorizontalLaout;
@property(readonly, nonatomic) struct CGSize cornerIconSize; // @synthesize cornerIconSize=_cornerIconSize;
@property(retain, nonatomic) WBTextLayout *layout; // @synthesize layout=_layout;
@property(retain, nonatomic) UILabel *repeatedLabel; // @synthesize repeatedLabel=_repeatedLabel;
@property(retain, nonatomic) UIImageView *cornerIconView; // @synthesize cornerIconView=_cornerIconView;
- (void)initRepeatedLabelIfNeeded;
- (void)initCornerIconViewIfNeeded;
- (void)logExposureWithCandidateWord:(id)arg1 atIndex:(unsigned long long)arg2;
- (void)renderCandidateWord:(id)arg1 focusedStyle:(_Bool)arg2 atIndex:(unsigned long long)arg3;
- (id)cornerIconImageForItem:(id)arg1;
- (struct CGRect)frameForCornerIconView;
- (struct CGRect)frameForTextLabel;
- (void)setNeedsSeparatorLayer:(_Bool)arg1;
- (void)layoutSubviews;
- (void)updateWavyUnderlineLayer;
- (void)initWavyUnderlineLayerIfNeeded;
- (struct CGPoint)offsetForCandidateWord:(id)arg1;
- (_Bool)pointInside:(struct CGPoint)arg1 withEvent:(id)arg2;
- (id)initWithFrame:(struct CGRect)arg1;

@end

