//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "WBBaseView.h"

#import "UIGestureRecognizerDelegate-Protocol.h"
#import "WBArrangeCellUpdateDelegate-Protocol.h"
#import "WBArrangeComputeDelegate-Protocol.h"

@class CALayer, NSArray, NSDictionary, NSMutableArray, NSString, UIImageView, UILongPressGestureRecognizer, WBArrangeView, WBButton, YYLabel;
@protocol WBCandidateViewDelegate;

@interface WBCandidateView : WBBaseView <WBArrangeCellUpdateDelegate, WBArrangeComputeDelegate, UIGestureRecognizerDelegate>
{
    YYLabel *_label;
    WBArrangeView *_arrangeView;
    UIImageView *lineImage;
    CALayer *_edgeSeparator;
    UIImageView *_edgeSeparatorMaskImageView;
    NSDictionary *_textAttributes;
    struct UIEdgeInsets _arrangeViewInset;
    UILongPressGestureRecognizer *_longPressGesture;
    double _minCellWidth;
    unsigned long long _focusedIndex;
    NSMutableArray *_stashCandidates;
    _Bool _isLandscape;
    _Bool _hidesContent;
    _Bool _hidesRightButton;
    _Bool _canExpand;
    _Bool _canSplit;
    _Bool _canAskAI;
    _Bool _active;
    _Bool _expanded;
    id <WBCandidateViewDelegate> _delegate;
    WBButton *_expandButton;
    WBButton *_closeButton;
    WBButton *_splittingButton;
    WBButton *_askAIButton;
}

- (void).cxx_destruct;
@property(retain, nonatomic) WBButton *askAIButton; // @synthesize askAIButton=_askAIButton;
@property(retain, nonatomic) WBButton *splittingButton; // @synthesize splittingButton=_splittingButton;
@property(nonatomic) _Bool expanded; // @synthesize expanded=_expanded;
@property(nonatomic) _Bool active; // @synthesize active=_active;
@property(nonatomic) _Bool canAskAI; // @synthesize canAskAI=_canAskAI;
@property(nonatomic) _Bool canSplit; // @synthesize canSplit=_canSplit;
@property(nonatomic) _Bool canExpand; // @synthesize canExpand=_canExpand;
@property(nonatomic) _Bool hidesRightButton; // @synthesize hidesRightButton=_hidesRightButton;
@property(nonatomic) _Bool hidesContent; // @synthesize hidesContent=_hidesContent;
@property(retain, nonatomic) WBButton *closeButton; // @synthesize closeButton=_closeButton;
@property(retain, nonatomic) WBButton *expandButton; // @synthesize expandButton=_expandButton;
@property(nonatomic) __weak id <WBCandidateViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void)handleLongPressGesture:(id)arg1;
- (_Bool)gestureRecognizerShouldBegin:(id)arg1;
- (double)arrangeView:(id)arg1 widthForItem:(id)arg2;
- (_Bool)arrangeView:(id)arg1 shouldAsyncComputeForItem:(id)arg2;
- (void)arrangeViewContentSizeChanged:(id)arg1;
- (unsigned long long)indexForBookVideoCandidates:(id)arg1 percent:(double)arg2 indexOffset:(long long)arg3 checkMatch:(_Bool)arg4;
- (unsigned long long)indexForInnerHWCandidate;
- (void)arrangeView:(id)arg1 didScroll:(struct CGPoint)arg2;
- (void)arrangeViewWillResetContentOffset:(id)arg1 targetContentOffset:(inout struct CGPoint *)arg2 layout:(id)arg3;
- (void)arrangeView:(id)arg1 animationForInsertedCell:(id)arg2 atIndex:(unsigned long long)arg3 targetRect:(struct CGRect)arg4 layoutBlock:(CDUnknownBlockType)arg5;
- (void)arrangeView:(id)arg1 touchBeginAtCell:(id)arg2 atIIndex:(unsigned long long)arg3;
- (void)arrangeView:(id)arg1 didSelectCell:(id)arg2 atIndex:(unsigned long long)arg3;
- (void)arrangeViewRequireMoreItem:(id)arg1;
- (void)arrangeView:(id)arg1 didFullShowArrangeItem:(id)arg2 forCell:(id)arg3 atIndex:(unsigned long long)arg4;
- (void)arrangeView:(id)arg1 didSetArrangeItem:(id)arg2 forCell:(id)arg3 atIndex:(unsigned long long)arg4;
- (void)arrangeView:(id)arg1 didCreateCell:(id)arg2 atIIndex:(unsigned long long)arg3;
- (void)updatViewsVisible;
@property(readonly, nonatomic) NSArray *firstScreenWords;
@property(readonly, nonatomic) struct _NSRange fullVisibleIndexRange;
@property(readonly, nonatomic) unsigned long long firstScreenFullVisibleLastCellIndex;
@property(readonly, nonatomic) NSArray *candidateWords;
- (void)replaceRange:(struct _NSRange)arg1 withCandidateWords:(id)arg2 animated:(_Bool)arg3;
- (void)insertCandidateWord:(id)arg1 atIndex:(unsigned long long)arg2 animated:(_Bool)arg3;
- (void)appendCandidateWords:(id)arg1;
- (void)setCandidateWords:(id)arg1 focusedIndex:(unsigned long long)arg2 completion:(CDUnknownBlockType)arg3;
- (void)setCandidateWords:(id)arg1;
- (void)layoutSubviews;
- (void)updateArrangeViewContentInset;
- (void)currentPanelTypeDidChange;
- (void)didAttachHosting;
- (void)presentationTypeDidChange;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

