//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "GPBMessage.h"

@class ChatItem, NSString;

@interface WBChatMessage : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(nonatomic) _Bool hasImageName; // @dynamic hasImageName;
@property(nonatomic) _Bool hasItem; // @dynamic hasItem;
@property(nonatomic) _Bool hasState; // @dynamic hasState;
@property(copy, nonatomic) NSString *imageName; // @dynamic imageName;
@property(retain, nonatomic) ChatItem *item; // @dynamic item;
@property(nonatomic) int state; // @dynamic state;

@end

