//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIViewController.h>

@class NSMutableArray, NSString, UIView;

@interface WBClearViewController : UIViewController
{
    _Bool _shown;
    UIView *_alertView;
    NSString *_title;
    NSString *_desc;
    NSString *_actionTitle;
    NSMutableArray *_captainzhuLayoutBlocks;
    CDUnknownBlockType _callback;
}

+ (void)showWith:(id)arg1 title:(id)arg2 desc:(id)arg3 actionTitle:(id)arg4 callback:(CDUnknownBlockType)arg5;
- (void).cxx_destruct;
@property(copy, nonatomic) CDUnknownBlockType callback; // @synthesize callback=_callback;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)show;
- (void)confirm;
- (void)dismiss;
- (void)viewDidLoad;
- (void)didMoveToParentViewController:(id)arg1;
- (void)viewDidLayoutSubviews;

@end

