//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSData, NSString;

@interface WBClipboardMsg : NSObject
{
    _Bool _isDisposed;
    _Bool _didFetchCOS;
    _Bool _isLocal;
    _Bool _isLargeContent;
    _Bool _local_unRead;
    _Bool _local_isExpanedTipsShown;
    _Bool _needsAttentionAnimation;
    _Bool _prefersDisplayStayStyle;
    _Bool _isReported;
    long long _msgVersion;
    long long _type;
    NSString *_text;
    NSData *_imageData;
    NSString *_dataFilePath;
    long long _dataVersion;
    NSString *_url;
    NSString *_decryptionMD5;
    NSData *_dataSecretKey;
    double _expireAt;
    double _expiration;
    double _clientCreateTime;
    unsigned long long _fromUin;
    unsigned long long _stayReason;
    unsigned long long _stayType;
    unsigned long long _imageType;
    long long _state;
    long long _binaryDataSize;
    double _uploadBeginTimestamp;
    double _uploadEndTimestamp;
    double _sendBeginTimestamp;
    double _receiveSystemTimestamp;
    double _receiveServerTimestamp;
    double _showTimestamp;
    double _downloadBeginTimestamp;
    double _downloadEndTimestamp;
    struct CGSize _imageSize;
}

+ (id)imageSupportedExt;
+ (long long)imageLimitedSize;
- (void).cxx_destruct;
@property(nonatomic) double downloadEndTimestamp; // @synthesize downloadEndTimestamp=_downloadEndTimestamp;
@property(nonatomic) double downloadBeginTimestamp; // @synthesize downloadBeginTimestamp=_downloadBeginTimestamp;
@property(nonatomic) double showTimestamp; // @synthesize showTimestamp=_showTimestamp;
@property(nonatomic) double receiveServerTimestamp; // @synthesize receiveServerTimestamp=_receiveServerTimestamp;
@property(nonatomic) double receiveSystemTimestamp; // @synthesize receiveSystemTimestamp=_receiveSystemTimestamp;
@property(nonatomic) double sendBeginTimestamp; // @synthesize sendBeginTimestamp=_sendBeginTimestamp;
@property(nonatomic) double uploadEndTimestamp; // @synthesize uploadEndTimestamp=_uploadEndTimestamp;
@property(nonatomic) double uploadBeginTimestamp; // @synthesize uploadBeginTimestamp=_uploadBeginTimestamp;
@property(nonatomic) long long binaryDataSize; // @synthesize binaryDataSize=_binaryDataSize;
@property(nonatomic) long long state; // @synthesize state=_state;
@property(nonatomic) _Bool isReported; // @synthesize isReported=_isReported;
@property(nonatomic) unsigned long long imageType; // @synthesize imageType=_imageType;
@property(nonatomic) unsigned long long stayType; // @synthesize stayType=_stayType;
@property(nonatomic) unsigned long long stayReason; // @synthesize stayReason=_stayReason;
@property(nonatomic) _Bool prefersDisplayStayStyle; // @synthesize prefersDisplayStayStyle=_prefersDisplayStayStyle;
@property(nonatomic) _Bool needsAttentionAnimation; // @synthesize needsAttentionAnimation=_needsAttentionAnimation;
@property(nonatomic) struct CGSize imageSize; // @synthesize imageSize=_imageSize;
@property(nonatomic) _Bool local_isExpanedTipsShown; // @synthesize local_isExpanedTipsShown=_local_isExpanedTipsShown;
@property(nonatomic) _Bool local_unRead; // @synthesize local_unRead=_local_unRead;
@property(nonatomic) _Bool isLargeContent; // @synthesize isLargeContent=_isLargeContent;
@property(nonatomic) _Bool isLocal; // @synthesize isLocal=_isLocal;
@property(nonatomic) _Bool didFetchCOS; // @synthesize didFetchCOS=_didFetchCOS;
@property(nonatomic) unsigned long long fromUin; // @synthesize fromUin=_fromUin;
@property(nonatomic) double clientCreateTime; // @synthesize clientCreateTime=_clientCreateTime;
@property(nonatomic) double expiration; // @synthesize expiration=_expiration;
@property(nonatomic) double expireAt; // @synthesize expireAt=_expireAt;
@property(retain, nonatomic) NSData *dataSecretKey; // @synthesize dataSecretKey=_dataSecretKey;
@property(copy, nonatomic) NSString *decryptionMD5; // @synthesize decryptionMD5=_decryptionMD5;
@property(copy, nonatomic) NSString *url; // @synthesize url=_url;
@property(nonatomic) long long dataVersion; // @synthesize dataVersion=_dataVersion;
@property(copy, nonatomic) NSString *dataFilePath; // @synthesize dataFilePath=_dataFilePath;
@property(retain, nonatomic) NSData *imageData; // @synthesize imageData=_imageData;
@property(copy, nonatomic) NSString *text; // @synthesize text=_text;
@property(nonatomic) long long type; // @synthesize type=_type;
@property(nonatomic) long long msgVersion; // @synthesize msgVersion=_msgVersion;
- (id)description;
- (id)descriptionForShow;
- (id)candidateText;
- (id)fileExtension;
- (void)calcImageProperties;
- (_Bool)isEqualToMsgText:(id)arg1;
- (void)reportOnce;
- (void)dispose;
- (_Bool)canShowAsCandidate;
- (_Bool)isImageType;
- (_Bool)isTextType;
- (id)extraInfoForSend;
- (void)dealloc;
- (id)initWithClipboardMsgPB:(id)arg1;

@end

