//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "MMService.h"

#import "MMServiceProtocol-Protocol.h"
#import "QCloudSignatureProvider-Protocol.h"

@class NSMutableDictionary, NSString;

@interface WBCOSMgr : MMService <QCloudSignatureProvider, MMServiceProtocol>
{
    NSMutableDictionary *_tokens;
}

+ (void)setFetchDisableBeaconBlock:(CDUnknownBlockType)arg1;
- (void).cxx_destruct;
- (void)signatureWithFields:(id)arg1 request:(id)arg2 urlRequest:(id)arg3 compelete:(CDUnknownBlockType)arg4;
- (void)removeToken:(id)arg1;
- (void)addToken:(id)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

