//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface WBColor : NSObject
{
}

+ (id)whiteInBrand;
+ (id)color16;
+ (id)color15;
+ (id)brand;
+ (id)color13;
+ (id)color12;
+ (id)color11;
+ (id)color10;
+ (id)color09;
+ (id)color08;
+ (id)color07;
+ (id)color06;
+ (id)color05;
+ (id)color04;
+ (id)color03;
+ (id)color02;
+ (id)color01;
+ (id)color00;
+ (id)highlight;
+ (id)mainAppHomeColor;
+ (_Bool)isDarkTheme;
+ (void)load;

@end

