//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface WBCommonBusinessManager : NSObject
{
}

+ (void)reportAppSettings;
+ (void)removeRNAssetsCache;
+ (void)removeTempDirContent;
+ (void)cleanStorage;
+ (void)checkStorageSize;
+ (void)checkMainAppSize;
+ (void)compareLatestVersion;
+ (void)setAboutEntranceHasNewVersionNotice:(_Bool)arg1;
+ (_Bool)aboutEntranceHasNewVersionNotice;
+ (void)setAboutHasNotice:(_Bool)arg1 platform:(long long)arg2;
+ (_Bool)aboutHasNoticeWithPlatform:(long long)arg1;
+ (_Bool)hasInstalledTestFlight:(id)arg1;
+ (id)findInfoWithPlatform:(long long)arg1 inInfos:(id)arg2;
+ (void)processUpgradeFeature;
+ (id)updateToolbarDesc;
+ (id)latestVersionInfo;

@end

