//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "WBTransitionView.h"

#import "WBKeyViewDelegate-Protocol.h"
#import "WBPanelLayoutDelegate-Protocol.h"
#import "WBPanelProxy-Protocol.h"

@class NSSet, NSString, UITouch, WBDeleteWordManager, WBKeyView, WBPanelLayout, WBSwipeEdgeDetector;
@protocol WBKeyViewHostingProtocol, WBPanelNavigatorProtocol;

@interface WBCommonPanelView : WBTransitionView <WBPanelLayoutDelegate, WBPanelProxy, WBKeyViewDelegate>
{
    _Bool _needsKeyboadViewLaout;
    WBKeyView *_currentTouchView;
    WBKeyView *_waitingDoubleTouchView;
    WBKeyView *_willRecognizeLongPressView;
    WBKeyView *_recognizingLongPressView;
    WBKeyView *_recognizingSwipeView;
    WBKeyView *_recognizingSwipeUpView;
    WBKeyView *_recognizingSwipeDownView;
    UITouch *_lastSwipeTouch;
    struct CGPoint _swipeLastPoint;
    id <WBKeyViewHostingProtocol> _hosting;
    long long _horSwipeGestureRespType;
    unsigned long long _supportsMoveCursorDirection;
    WBDeleteWordManager *_deleteManager;
    WBSwipeEdgeDetector *_edgeDetector;
    long long _panelType;
    long long _launchingVoiceInputTipsState;
    int _characterPreviewEnabled;
    unsigned long long _adjustingTextPositionCount;
    double _lastLetterKeyUpTime;
    NSSet *_excludedSymbolSet;
    _Bool _showing;
    _Bool _root;
    _Bool _splitEnabled;
    _Bool _separateEnabled;
    _Bool _moveCursorStyle;
    id <WBPanelNavigatorProtocol> _navigator;
    WBPanelLayout *_layout;
    unsigned long long _dynamicallyKeyOptions;
    CDUnknownBlockType _keyViewsLayoutDidUpdateBlock;
}

- (void).cxx_destruct;
@property(nonatomic) _Bool moveCursorStyle; // @synthesize moveCursorStyle=_moveCursorStyle;
@property(nonatomic) _Bool separateEnabled; // @synthesize separateEnabled=_separateEnabled;
@property(nonatomic) _Bool splitEnabled; // @synthesize splitEnabled=_splitEnabled;
@property(copy, nonatomic) CDUnknownBlockType keyViewsLayoutDidUpdateBlock; // @synthesize keyViewsLayoutDidUpdateBlock=_keyViewsLayoutDidUpdateBlock;
@property(readonly, nonatomic) unsigned long long dynamicallyKeyOptions; // @synthesize dynamicallyKeyOptions=_dynamicallyKeyOptions;
@property(readonly, nonatomic) _Bool root; // @synthesize root=_root;
@property(readonly, nonatomic) _Bool showing; // @synthesize showing=_showing;
@property(readonly, nonatomic) WBPanelLayout *layout; // @synthesize layout=_layout;
@property(nonatomic) __weak id <WBPanelNavigatorProtocol> navigator; // @synthesize navigator=_navigator;
- (void)showBlinkAnimationForKeyFunc:(long long)arg1;
- (void)sendClickTouch:(id)arg1;
@property(readonly, nonatomic) _Bool isUppercase;
@property(readonly, nonatomic) unsigned long long letterTextShiftRule;
- (void)willHidePanel;
- (void)willShowPanel;
@property(readonly, nonatomic) long long panelType;
@property(readonly, nonatomic) _Bool isWubiPanel;
@property(readonly, nonatomic) _Bool isShuangPinPanel;
@property(readonly, nonatomic) _Bool canResponseSyllables;
- (id)uninstallKeyTagSet;
- (id)placeholderTagSet;
- (void)layoutDidUpdate:(id)arg1;
- (void)subviewsDidCreate:(id)arg1;
- (void)separatedMidWidthChanged;
- (long long)optionsForLayout:(id)arg1;
- (struct CGRect)rectForLayout:(id)arg1;
- (struct CGPoint)layout:(id)arg1 locationForTouch:(id)arg2;
- (void)setNeedsLayout:(id)arg1;
- (void)layout:(id)arg1 addKeyView:(id)arg2;
- (void)prepareSwitchWithPreviousPanelType:(long long)arg1 nearestPanelType:(long long)arg2;
- (id)excludedSymbolsForTopBar;
- (void)mainInputSettingDidChange;
- (void)needsEmoticonKeyDidChange;
- (void)returnActionTypeDidChange;
- (void)handleInputKeyTouchEnd:(id)arg1 hasProcessedInput:(_Bool)arg2;
- (void)handleShiftKeyViewEvent:(id)arg1 options:(unsigned long long)arg2;
- (void)keyViewsLayoutDidUpdate:(id)arg1;
- (void)keyViewsDidLoad:(id)arg1;
- (void)didAttachHosting;
- (void)processSwipeEnded:(id)arg1 touch:(id)arg2;
- (void)processSwipeMoved:(id)arg1 touch:(id)arg2;
- (void)processSwipeBegan:(id)arg1 touch:(id)arg2;
- (void)recognizeSwipeTouch:(id)arg1 keyView:(id)arg2;
- (_Bool)canRecognizeSwipeTouch:(id)arg1 keyView:(id)arg2;
- (long long)tryRecognizeSwipeTouch:(id)arg1 keyView:(id)arg2 supportsMoveCursorDirection:(unsigned long long *)arg3 force:(_Bool)arg4;
- (void)processSwipeDownEnded:(id)arg1;
- (void)processSwipeUpEnded:(id)arg1;
- (void)processSwipeDownMoved:(id)arg1 touch:(id)arg2;
- (void)processSwipeUpMoved:(id)arg1 touch:(id)arg2;
- (void)processSwipeDownBegan:(id)arg1 touch:(id)arg2;
- (void)processSwipeUpBegan:(id)arg1 touch:(id)arg2 isOpenUpTips:(_Bool)arg3;
- (void)recognizeSwipeUpTouch:(id)arg1 keyView:(id)arg2;
- (_Bool)canRecognizeSwipeUpTouch:(id)arg1 keyView:(id)arg2 isOpenUpTips:(_Bool *)arg3;
- (_Bool)canRecognizeSwipeDownTouch:(id)arg1 keyView:(id)arg2;
- (_Bool)isSupportLongPressListKeyView:(id)arg1;
- (_Bool)isSupportUpSwipeForKeyView:(id)arg1;
- (void)processLongPressEnded:(id)arg1 keyView:(id)arg2;
- (void)processLongPressFailed:(id)arg1 keyView:(id)arg2;
- (void)processLongPressMoved:(id)arg1 keyView:(id)arg2;
- (void)processLongPressBegan:(id)arg1 keyView:(id)arg2;
- (void)keyViewLongPressBegin:(id)arg1;
- (void)recognizeLongPressWithTouch:(id)arg1 keyView:(id)arg2;
- (void)processLongPressTouchEnd:(id)arg1 keyView:(id)arg2;
- (void)handleLongPressFailed:(id)arg1 keyView:(id)arg2;
- (void)processTouchMoveWithTouch:(id)arg1 keyView:(id)arg2;
- (void)keyViewTouchEnd:(id)arg1 interrupterKeyView:(id)arg2;
- (void)processTouchEnd:(id)arg1 keyView:(id)arg2 interrupterKeyView:(id)arg3;
- (void)processTouchEnd:(id)arg1 keyView:(id)arg2;
- (void)transferTouchForKeyView:(id)arg1 source:(long long)arg2;
- (void)processTouchCancel:(id)arg1 keyView:(id)arg2;
- (void)setTouchCancelForkeyView:(id)arg1 source:(long long)arg2;
- (void)processTouchBegan:(id)arg1 keyView:(id)arg2;
- (void)createSubviewsIfNecessary;
- (void)touchesCancelled:(id)arg1 withEvent:(id)arg2;
- (void)_beginSwipeGestureFormKeyView:(id)arg1 touch:(id)arg2 force:(_Bool)arg3;
- (void)forceBeginHorSwipeGestureFormKeyView:(id)arg1 touch:(id)arg2;
- (void)touchesEnded:(id)arg1 withEvent:(id)arg2;
- (void)touchesMoved:(id)arg1 withEvent:(id)arg2;
- (void)touchesBegan:(id)arg1 withEvent:(id)arg2;
- (void)layoutSubviews;
- (void)updateKeyViews;
- (id)hitTest:(struct CGPoint)arg1 withEvent:(id)arg2;
- (id)initWithLayout:(id)arg1 isRoot:(_Bool)arg2;
- (id)initWithPanelType:(long long)arg1 isRoot:(_Bool)arg2;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly, nonatomic) double firstUpFloatingKeyWidth;
@property(readonly) unsigned long long hash;
@property(readonly, nonatomic) unsigned long long shiftState;
@property(readonly) Class superclass;

@end

