//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSDictionary, NSMutableDictionary;

@interface WBCodingObject : NSObject
{
    unsigned long long _size;
    const struct WBCodingProperty *_properties;
    NSDictionary *_defaultValuesMapper;
    NSMutableDictionary *_buffers;
}

+ (id)defaultValuesMapper;
+ (unsigned long long)properties:(const struct WBCodingProperty **)arg1;
- (void).cxx_destruct;
- (unsigned long long)lendthForCArrayKey:(id)arg1;
- (void)check;
- (void)decodeWithData:(id)arg1 dataUpdated:(_Bool *)arg2;
- (void)setBuffer:(id)arg1 forKey:(id)arg2 ivar:(struct objc_ivar *)arg3;
- (id)bufferForIvarName:(id)arg1;
- (void)setBuffer:(id)arg1 forIvarName:(id)arg2;
- (id)defaultValueForKey:(id)arg1;
- (id)description;
- (id)encodeData;
- (_Bool)writeToFile:(id)arg1 atomically:(_Bool)arg2;
- (void)checkDataType;
- (id)initWithContentsOfFile:(id)arg1 dataUpdated:(_Bool *)arg2;
- (id)initWithContentsOfFile:(id)arg1;

@end

