//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSDictionary, NSMutableDictionary, UIColor, WBINIParser, WBKeyViewItem;

@interface WBConfigManager : NSObject
{
    NSMutableDictionary *_tempStyleCache;
    NSMutableDictionary *_styleCache;
    WBKeyViewItem *_normalKeyItem;
    WBKeyViewItem *_grayKeyItem;
    WBKeyViewItem *_greenKeyItem;
    UIColor *_candidateFocusedTextColor;
    NSDictionary *_styleInfo;
    WBINIParser *_iniParser;
}

+ (id)allocWithZone:(struct _NSZone *)arg1;
+ (id)manager;
+ (void)load;
- (void).cxx_destruct;
@property(retain, nonatomic) WBINIParser *iniParser; // @synthesize iniParser=_iniParser;
@property(retain, nonatomic) NSDictionary *styleInfo; // @synthesize styleInfo=_styleInfo;
@property(retain, nonatomic) UIColor *candidateFocusedTextColor; // @synthesize candidateFocusedTextColor=_candidateFocusedTextColor;
@property(retain, nonatomic) WBKeyViewItem *greenKeyItem; // @synthesize greenKeyItem=_greenKeyItem;
@property(retain, nonatomic) WBKeyViewItem *grayKeyItem; // @synthesize grayKeyItem=_grayKeyItem;
@property(retain, nonatomic) WBKeyViewItem *normalKeyItem; // @synthesize normalKeyItem=_normalKeyItem;
- (id)layoutForPanelViewType:(long long)arg1 iniFileName:(id)arg2;
- (void)reloadFeatureConfig;
- (id)keyItemConfigByINISection:(id)arg1 styleInjecter:(CDUnknownBlockType)arg2 panelConfigBlock:(CDUnknownBlockType)arg3 keyConfigBlock:(CDUnknownBlockType)arg4;
- (id)styleForName:(id)arg1;
- (void)preload;

@end

