//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "WBViewController.h"

@class UITextField;

@interface WBCustomInputTestViewController : WBViewController
{
    UITextField *_textField;
}

- (void).cxx_destruct;
@property(retain, nonatomic) UITextField *textField; // @synthesize textField=_textField;
- (void)onClickButton:(id)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (id)barColor;

@end

