//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UITableViewCell.h>

#import "UITextFieldDelegate-Protocol.h"

@class NSString, WBCustomSymbolsData, WBFocusLastTextField;

@interface WBCustomSymbolsTableViewCell : UITableViewCell <UITextFieldDelegate>
{
    _Bool _isInDeleteMode;
    WBCustomSymbolsData *_symbolData;
    WBFocusLastTextField *_symbolTextField;
    CDUnknownBlockType _textFieldDidEndEditing;
    struct UIEdgeInsets _padding;
}

- (void).cxx_destruct;
@property(nonatomic) _Bool isInDeleteMode; // @synthesize isInDeleteMode=_isInDeleteMode;
@property(nonatomic) struct UIEdgeInsets padding; // @synthesize padding=_padding;
@property(copy, nonatomic) CDUnknownBlockType textFieldDidEndEditing; // @synthesize textFieldDidEndEditing=_textFieldDidEndEditing;
@property(retain, nonatomic) WBFocusLastTextField *symbolTextField; // @synthesize symbolTextField=_symbolTextField;
@property(readonly, nonatomic) WBCustomSymbolsData *symbolData; // @synthesize symbolData=_symbolData;
- (void)textFieldDidEndEditing:(id)arg1;
- (_Bool)textField:(id)arg1 shouldChangeCharactersInRange:(struct _NSRange)arg2 replacementString:(id)arg3;
- (void)layoutSubviews;
- (id)deleteControl;
- (void)_updateReorderControlVisibilityWithTextLength:(long long)arg1;
- (void)updateReorderControlVisibility;
- (void)renderWithSymbolData:(id)arg1 isInDeleteMode:(_Bool)arg2 padding:(struct UIEdgeInsets)arg3;
- (void)initSubviews;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

