//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UITableView.h>

@interface WBCustomSymbolsTableView : UITableView
{
    struct UIEdgeInsets _wbLayoutMargins;
}

@property(nonatomic) struct UIEdgeInsets wbLayoutMargins; // @synthesize wbLayoutMargins=_wbLayoutMargins;
- (struct UIEdgeInsets)wbOriginLayoutMargins;
- (struct UIEdgeInsets)layoutMargins;

@end

