//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "WBViewController.h"

#import "QMUIKeyboardManagerDelegate-Protocol.h"
#import "UITableViewDataSource-Protocol.h"
#import "UITableViewDelegate-Protocol.h"

@class NSMutableArray, NSString, QMUIKeyboardManager, WBCustomSymbolsDataSectionHeaderView, WBCustomSymbolsSegment, WBCustomSymbolsTableView, WBUIKeyboardManager;

@interface WBCustomSymbolsViewController : WBViewController <UITableViewDataSource, UITableViewDelegate, QMUIKeyboardManagerDelegate>
{
    _Bool _isAddButtonClicked;
    WBCustomSymbolsTableView *_tableView;
    NSMutableArray *_pinyinSymbols;
    NSMutableArray *_numberSymbols;
    NSMutableArray *_dataSource;
    QMUIKeyboardManager *_keyboardManager;
    double _keyboardHeight;
    WBCustomSymbolsSegment *_segment;
    long long _initialSelectedIndex;
    WBUIKeyboardManager *_uikeyboardManager;
    WBCustomSymbolsDataSectionHeaderView *_sectionHeaderView;
}

- (void).cxx_destruct;
@property(nonatomic) _Bool isAddButtonClicked; // @synthesize isAddButtonClicked=_isAddButtonClicked;
@property(retain, nonatomic) WBCustomSymbolsDataSectionHeaderView *sectionHeaderView; // @synthesize sectionHeaderView=_sectionHeaderView;
@property(retain, nonatomic) WBUIKeyboardManager *uikeyboardManager; // @synthesize uikeyboardManager=_uikeyboardManager;
@property(nonatomic) long long initialSelectedIndex; // @synthesize initialSelectedIndex=_initialSelectedIndex;
@property(retain, nonatomic) WBCustomSymbolsSegment *segment; // @synthesize segment=_segment;
@property(nonatomic) double keyboardHeight; // @synthesize keyboardHeight=_keyboardHeight;
@property(retain, nonatomic) QMUIKeyboardManager *keyboardManager; // @synthesize keyboardManager=_keyboardManager;
@property(retain, nonatomic) NSMutableArray *dataSource; // @synthesize dataSource=_dataSource;
@property(retain, nonatomic) NSMutableArray *numberSymbols; // @synthesize numberSymbols=_numberSymbols;
@property(retain, nonatomic) NSMutableArray *pinyinSymbols; // @synthesize pinyinSymbols=_pinyinSymbols;
@property(retain, nonatomic) WBCustomSymbolsTableView *tableView; // @synthesize tableView=_tableView;
- (void)keyboardDidHideWithUserInfo:(id)arg1;
- (void)keyboardWillHideWithUserInfo:(id)arg1;
- (void)keyboardWillShowWithUserInfo:(id)arg1;
- (void)layoutContentViewForKeyboardEvent;
- (void)viewDidLayoutSubviews;
- (void)scrollViewWillBeginDragging:(id)arg1;
- (void)tableView:(id)arg1 commitEditingStyle:(long long)arg2 forRowAtIndexPath:(id)arg3;
- (void)tableView:(id)arg1 moveRowAtIndexPath:(id)arg2 toIndexPath:(id)arg3;
- (id)tableView:(id)arg1 targetIndexPathForMoveFromRowAtIndexPath:(id)arg2 toProposedIndexPath:(id)arg3;
- (_Bool)tableView:(id)arg1 canMoveRowAtIndexPath:(id)arg2;
- (_Bool)tableView:(id)arg1 shouldIndentWhileEditingRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 editingStyleForRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 willDisplayCell:(id)arg2 forRowAtIndexPath:(id)arg3;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 viewForHeaderInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (void)commitWithIndex:(long long)arg1;
- (void)commit;
- (void)collectAndRemoveInvalidDataWithIndex:(long long)arg1;
- (void)deleteCellWithIndexPaths:(id)arg1;
- (void)insertCell;
- (_Bool)showAdditionCellWitCount:(long long)arg1;
- (_Bool)showAdditionCell;
- (void)handleTapAddSymbolButton;
- (id)focusedCell;
- (void)resignAll;
- (void)handleEdit:(id)arg1;
- (void)setIsInDeleteMode:(_Bool)arg1;
- (_Bool)isInDeleteMode;
- (void)segmentSelectedIndexDidChangeWithOldValue:(long long)arg1;
- (void)updateSectionHeaderViewTitle;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)setupNavigationItems;
- (void)initSubviews;
- (id)generateSymbolDataWithSymbols:(id)arg1;
- (void)appDidEnterBackground:(id)arg1;
- (void)addObservers;
- (void)viewDidLoad;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

