//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface WBCustomSymbolsData : NSObject
{
    NSString *_symbol;
    long long _editTime;
}

- (void).cxx_destruct;
@property(nonatomic) long long editTime; // @synthesize editTime=_editTime;
@property(retain, nonatomic) NSString *symbol; // @synthesize symbol=_symbol;
- (id)description;
- (id)initWithSymbol:(id)arg1;

@end

