//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIView.h>

@class QMUIButton, UIControl, UIImageView, UILabel;

@interface WBCustomSymbolsSegment : UIView
{
    long long _selectedIndex;
    QMUIButton *_leftButton;
    QMUIButton *_rightButton;
    UIView *_selectedBackgrounView;
    UIControl *_leftControl;
    UIImageView *_leftImageView;
    UIView *_leftImageViewWrapperView;
    UILabel *_leftLabel;
    UIControl *_rightControl;
    UIImageView *_rightImageView;
    UIView *_rightImageViewWrapperView;
    UILabel *_rightLabel;
    UIView *_backgroundView;
    struct UIEdgeInsets _margin;
}

- (void).cxx_destruct;
@property(retain, nonatomic) UIView *backgroundView; // @synthesize backgroundView=_backgroundView;
@property(retain, nonatomic) UILabel *rightLabel; // @synthesize rightLabel=_rightLabel;
@property(retain, nonatomic) UIView *rightImageViewWrapperView; // @synthesize rightImageViewWrapperView=_rightImageViewWrapperView;
@property(retain, nonatomic) UIImageView *rightImageView; // @synthesize rightImageView=_rightImageView;
@property(retain, nonatomic) UIControl *rightControl; // @synthesize rightControl=_rightControl;
@property(retain, nonatomic) UILabel *leftLabel; // @synthesize leftLabel=_leftLabel;
@property(retain, nonatomic) UIView *leftImageViewWrapperView; // @synthesize leftImageViewWrapperView=_leftImageViewWrapperView;
@property(retain, nonatomic) UIImageView *leftImageView; // @synthesize leftImageView=_leftImageView;
@property(retain, nonatomic) UIControl *leftControl; // @synthesize leftControl=_leftControl;
@property(retain, nonatomic) UIView *selectedBackgrounView; // @synthesize selectedBackgrounView=_selectedBackgrounView;
@property(retain, nonatomic) QMUIButton *rightButton; // @synthesize rightButton=_rightButton;
@property(retain, nonatomic) QMUIButton *leftButton; // @synthesize leftButton=_leftButton;
@property(nonatomic) struct UIEdgeInsets margin; // @synthesize margin=_margin;
@property(nonatomic) long long selectedIndex; // @synthesize selectedIndex=_selectedIndex;
- (void)layoutSubviews;
- (struct CGSize)calcImageSizeWithContainerSize:(struct CGSize)arg1;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;
- (void)handleTouchRightControl:(id)arg1;
- (void)handleTouchLeftControl:(id)arg1;
- (void)initSubviews;
- (id)initWithFrame:(struct CGRect)arg1;

@end

