//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIView.h>

@class QMUILabel, UIButton;

@interface WBCustomSymbolsDataSectionHeaderView : UIView
{
    _Bool _isInEditMode;
    CDUnknownBlockType _didTapEditButton;
    QMUILabel *_label;
    UIButton *_editButton;
}

- (void).cxx_destruct;
@property(retain, nonatomic) UIButton *editButton; // @synthesize editButton=_editButton;
@property(retain, nonatomic) QMUILabel *label; // @synthesize label=_label;
@property(copy, nonatomic) CDUnknownBlockType didTapEditButton; // @synthesize didTapEditButton=_didTapEditButton;
@property(nonatomic) _Bool isInEditMode; // @synthesize isInEditMode=_isInEditMode;
- (void)layoutSubviews;
- (void)setLabelText:(id)arg1;
- (void)handleTapEditButton:(id)arg1;
- (void)initSubviews;
- (id)init;

@end

