//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface WBDataUpgrader : NSObject
{
}

+ (void)updateLastAppVersion;
+ (id)lastAppVersion;
+ (id)allocWithZone:(struct _NSZone *)arg1;
+ (id)sharedInstance;
- (void)handleAppDowngrade;
- (void)handleAppUpgrade;
- (void)handleNewInstallation;
- (unsigned long long)checkInstallType;
- (void)processAppInstallation;
- (_Bool)moveItemAtPath:(id)arg1 toPath:(id)arg2 overwrite:(_Bool)arg3 error:(id *)arg4;
- (_Bool)removeItemAtPath:(id)arg1 error:(id *)arg2;
- (_Bool)createDirectoryAtPath:(id)arg1 error:(id *)arg2;
- (id)directoryAtPath:(id)arg1;
- (_Bool)isExistsAtPath:(id)arg1;
- (void)removeOldLogs;
- (void)transferAppSettings;
- (void)upgrade;

@end

