//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface WBDataStore : NSObject
{
}

+ (id)fullPathForFileName:(id)arg1 path:(id)arg2;
+ (void)cleanUpOldVersionFiles;
+ (void)initialize;
+ (void)deleteFilesWithPrefix:(id)arg1 path:(id)arg2;
+ (id)listFiles;
+ (_Bool)fileExistsWithFileName:(id)arg1;
+ (id)readStringWithFileName:(id)arg1;
+ (void)saveString:(id)arg1 fileName:(id)arg2;
+ (id)readDataWithFileName:(id)arg1;
+ (void)saveData:(id)arg1 fileName:(id)arg2;
+ (id)listFilesInPath:(id)arg1;
+ (_Bool)fileExistsWithFileName:(id)arg1 path:(id)arg2;
+ (id)readGroupStringWithFileName:(id)arg1 path:(id)arg2;
+ (id)readStringWithFileName:(id)arg1 path:(id)arg2;
+ (void)saveString:(id)arg1 fileName:(id)arg2 path:(id)arg3;
+ (id)readDataWithFileName:(id)arg1 path:(id)arg2;
+ (void)clearGroupData:(id)arg1 limit:(long long)arg2;
+ (void)clearGroupData:(id)arg1 fileName:(id)arg2;
+ (void)saveGroupData:(id)arg1 fileName:(id)arg2 path:(id)arg3;
+ (void)clearData:(id)arg1 fileName:(id)arg2;
+ (void)saveData:(id)arg1 fileName:(id)arg2 path:(id)arg3;

@end

