//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIViewController.h>

@class NSDictionary, NSString, UIView;

@interface WBDebugRNViewController : UIViewController
{
    NSString *_moduleName;
    NSDictionary *_initialProps;
    UIView *_rootView;
}

- (void).cxx_destruct;
@property(retain, nonatomic) UIView *rootView; // @synthesize rootView=_rootView;
@property(retain, nonatomic) NSDictionary *initialProps; // @synthesize initialProps=_initialProps;
@property(retain, nonatomic) NSString *moduleName; // @synthesize moduleName=_moduleName;
- (void)viewDidLayoutSubviews;
- (void)viewDidLoad;

@end

