//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "QMUIModalPresentationViewController.h"

@interface WBDebugTipsViewController : QMUIModalPresentationViewController
{
}

- (void)renderDebugInfo:(id)arg1;
- (id)rnInfo;
- (id)generateDebugInfo;
- (void)viewDidLoad;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

@end

