//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "WBSettingsViewController.h"

@class NSURL, WBSettingsElement;

@interface WBDebugViewController : WBSettingsViewController
{
    _Bool _commonDictUpdateToastEnabled;
    _Bool _newHotDictUpdateToastEnabled;
    NSURL *_recordFileUrl;
    WBSettingsElement *_debugDictLocationElement;
}

- (void).cxx_destruct;
@property(retain, nonatomic) WBSettingsElement *debugDictLocationElement; // @synthesize debugDictLocationElement=_debugDictLocationElement;
@property(retain, nonatomic) NSURL *recordFileUrl; // @synthesize recordFileUrl=_recordFileUrl;
- (void)handleShowAboutFeature;
- (void)onNewHotDictsUpdateRepeated;
- (void)onNewHotDictsUpdateFailure;
- (void)onNewHotDictsUpdateSuccess;
- (void)onCommonDictsUpdateRepeated;
- (void)onCommonDictsUpdateFailure;
- (void)onCommonDictsUpdateSuccess;
- (void)reported;
- (void)dealloc;
- (void)viewWillAppear:(_Bool)arg1;
- (void)clearRNFeedbackData;
- (void)debugRNVC;
- (void)debugRN;
- (void)customUIN;
- (void)customRNServerIP;
- (void)resetPluginNotFoundGuide;
- (void)addLocalNotice;
- (void)patchTest;
- (void)setupGroups;
- (void)exportPDFImage;
- (void)viewDidLoad;
- (id)title;

@end

