//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class WBKeyView;

@interface WBDeleteWordManager : NSObject
{
    WBKeyView *_detectingSwipeKeyView;
    unsigned long long _currentStyle;
    CDUnknownBlockType _deleteActionBlock;
    WBKeyView *_keyView;
    double _swipeLastDistance;
}

- (void).cxx_destruct;
@property(nonatomic) double swipeLastDistance; // @synthesize swipeLastDistance=_swipeLastDistance;
@property(nonatomic) __weak WBKeyView *keyView; // @synthesize keyView=_keyView;
@property(copy, nonatomic) CDUnknownBlockType deleteActionBlock; // @synthesize deleteActionBlock=_deleteActionBlock;
@property(nonatomic) unsigned long long currentStyle; // @synthesize currentStyle=_currentStyle;
@property(nonatomic) __weak WBKeyView *detectingSwipeKeyView; // @synthesize detectingSwipeKeyView=_detectingSwipeKeyView;
- (void)detectorTrigger:(unsigned long long)arg1;
- (void)performAction:(unsigned long long)arg1 distance:(double)arg2 edge:(unsigned long long)arg3;
- (void)performAction:(unsigned long long)arg1 distance:(double)arg2;
- (_Bool)checkDetectSwipeDelete:(id)arg1;
- (_Bool)enableSwipeDelete;
- (void)cleanSwipe;
- (void)cleanLongPress;
- (void)singleTouch:(id)arg1 keyView:(id)arg2;
- (void)swipe:(id)arg1 keyView:(id)arg2 state:(unsigned long long)arg3 distance:(double)arg4;
- (void)longPress:(id)arg1 keyView:(id)arg2 state:(unsigned long long)arg3;

@end

