//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface WBDelayAction : NSObject
{
    NSString *_identifier;
    CDUnknownBlockType _actionsBlock;
}

+ (void)performAction:(id)arg1;
+ (void)cancelPerformWithIdentifier:(id)arg1;
+ (void)performWithDelay:(double)arg1 identifier:(id)arg2 actions:(CDUnknownBlockType)arg3 cancelPreceding:(_Bool)arg4;
+ (void)performWithDelay:(double)arg1 identifier:(id)arg2 actions:(CDUnknownBlockType)arg3;
+ (id)actionWithIdentifier:(id)arg1 actions:(CDUnknownBlockType)arg2;
+ (id)actionWithIdentifier:(id)arg1;
- (void).cxx_destruct;
@property(copy, nonatomic) CDUnknownBlockType actionsBlock; // @synthesize actionsBlock=_actionsBlock;
@property(copy, nonatomic) NSString *identifier; // @synthesize identifier=_identifier;
- (_Bool)isEqual:(id)arg1;

@end

