//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface WBDeviceHelper : NSObject
{
}

+ (id)buildBranch;
+ (long long)currentMemory;
+ (long long)processIdentifier;
+ (id)processName;
+ (id)appGroupName;
+ (_Bool)isExtensionTarget;
+ (id)deviceName;
+ (id)osVersion;
+ (id)osName;
+ (id)appVersion;
+ (id)marketVersion;
+ (id)appMainBundle;
+ (id)deviceId;
+ (id)bundleId;

@end

