//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class WBClipboardMsg, WBDSGroupInfo;
@protocol OS_dispatch_queue, WBBusinessRequestProtocol;

@interface WBDeviceSyncManager : NSObject
{
    id <WBBusinessRequestProtocol> _requestHandler;
    WBDSGroupInfo *_groupInfo;
    WBClipboardMsg *_clipboardMsg;
    NSObject<OS_dispatch_queue> *_queue;
}

+ (id)decryptImageData:(id)arg1 key:(id)arg2 expectedMD5:(id)arg3;
+ (id)descForEventType:(long long)arg1;
+ (id)sharedInstance;
- (void).cxx_destruct;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *queue; // @synthesize queue=_queue;
@property(retain) WBClipboardMsg *clipboardMsg; // @synthesize clipboardMsg=_clipboardMsg;
@property(retain) WBDSGroupInfo *groupInfo; // @synthesize groupInfo=_groupInfo;
@property(nonatomic) __weak id <WBBusinessRequestProtocol> requestHandler; // @synthesize requestHandler=_requestHandler;
- (void)reportMsg:(id)arg1;
- (void)fetchDataFromCOS:(id)arg1 useFile:(_Bool)arg2 limitedSize:(long long)arg3 onSuccess:(CDUnknownBlockType)arg4 onFailures:(CDUnknownBlockType)arg5;
- (void)uploadDataToCOSWithBody:(id)arg1 fileExtension:(id)arg2 onSuccess:(CDUnknownBlockType)arg3 onFailures:(CDUnknownBlockType)arg4;
- (void)showDebugTipsIfNeeded:(id)arg1;
- (struct _wxime_group_sync_info)wximeGroupInfo;
- (void)updateIMEGroupInfo;
@property unsigned long long hotWordversion;
- (_Bool)isHotwordEnabled;
- (_Bool)isClipboardEnabled;
- (_Bool)needNotify;
- (_Bool)hasUsedInPast;
- (_Bool)currentHasBoundDevice;
- (_Bool)updateClipboardMsg:(id)arg1;
- (void)renewExpireTime:(id)arg1;
- (id)_createLocalClipboardMsgWithCreateTime:(double)arg1;
- (id)_createLocalClipboardWithImage:(id)arg1 imageData:(id)arg2 dataFilePath:(id)arg3 createTime:(double)arg4;
- (id)_createLocalClipboardWithText:(id)arg1 createTime:(double)arg2;
- (id)createLocalUnreadClipboardWithContent:(id)arg1 createTime:(double)arg2;
- (id)createLocalClipboardWithContent:(id)arg1 createTime:(double)arg2;
- (_Bool)isClipboardMsgJustArrived:(id)arg1;
- (_Bool)isClipboardMsgExpired:(id)arg1;
- (void)fetchFullImage:(id)arg1 succBlock:(CDUnknownBlockType)arg2 failBlock:(CDUnknownBlockType)arg3;
- (void)fetchFullClipboardMsg:(id)arg1 succBlock:(CDUnknownBlockType)arg2 failBlock:(CDUnknownBlockType)arg3;
- (void)uploadClipboardToCOSIfNeeded:(id)arg1 succBlock:(CDUnknownBlockType)arg2 failBlock:(CDUnknownBlockType)arg3;
- (void)_handleNotifyOnQueueWithEventType:(long long)arg1 data:(id)arg2;
- (void)handleNotifyWithEventType:(long long)arg1 dataBuf:(const char *)arg2 dataLen:(long long)arg3;
- (void)readGroupInfo;
- (void)updateGroupInfoRNDict:(id)arg1;
- (void)_saveGroupInfoWithRsp:(id)arg1 updated:(_Bool *)arg2;
- (void)sendClipboardMsg:(id)arg1 completeBlock:(CDUnknownBlockType)arg2;
- (void)_requestWithBeforeBlock:(CDUnknownBlockType)arg1 succBlock:(CDUnknownBlockType)arg2 failBlock:(CDUnknownBlockType)arg3;
- (void)_handleFetchItemsSuccWithFilter:(int)arg1 rsp:(id)arg2 completeBlock:(CDUnknownBlockType)arg3;
- (void)fetchItemsWithFilter:(int)arg1 succBlock:(CDUnknownBlockType)arg2 failBlock:(CDUnknownBlockType)arg3;
- (void)_handleFetchGroupInfoSuccWithRsp:(id)arg1 updated:(_Bool *)arg2;
- (void)fetchGroupInfoWithSuccBlock:(CDUnknownBlockType)arg1 failBlock:(CDUnknownBlockType)arg2;
- (void)_startSyncOnQueueWithCompleteBlock:(CDUnknownBlockType)arg1;
- (void)startSyncWithCompleteBlock:(CDUnknownBlockType)arg1;
- (void)handleBusinessNotifyConnectStatusDidChange:(id)arg1;
- (void)addObservers;
- (id)init;

@end

