//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "MMService.h"

#import "MMServiceProtocol-Protocol.h"
#import "WBDictUpdateTaskDelegate-Protocol.h"

@class NSArray, NSDictionary, NSMutableDictionary, NSObject, NSOperationQueue, NSRecursiveLock, NSString;
@protocol OS_dispatch_queue;

@interface WBDictUpdater : MMService <WBDictUpdateTaskDelegate, MMServiceProtocol>
{
    NSObject<OS_dispatch_queue> *_downloadDispatchQueue;
    NSArray *_forceUpdateDicts;
    NSDictionary *_dictsBeforeUpdate;
    NSMutableDictionary *_pendingDelete;
    NSMutableDictionary *_pendingUpdate;
    NSMutableDictionary *_failedDicts;
    _Bool _currentDownloadUsingWlan;
    _Bool _cancelled;
    _Bool _currentUpdateCallbacked;
    _Bool _needUpdateWlanDLData;
    unsigned long long _status;
    double _nextUpdateTime;
    long long _currentDownloadDictSize;
    long long _currentDictSizeDownloaded;
    unsigned long long _currentDownloadSource;
    CDUnknownBlockType _downloadSuccessExtraAction;
    CDUnknownBlockType _downloadFailedExtraAction;
    NSOperationQueue *_downloadQueue;
    unsigned long long _backgroundTask;
    long long _taskCount;
    NSArray *_currentDictToDownload;
    NSArray *_downloadingTasks;
    NSMutableDictionary *_resumeDataInfo;
    NSRecursiveLock *_lockForResumeData;
}

+ (id)failureNotification;
+ (id)repeatedNotification;
+ (id)successNotification;
+ (id)fetchDictSizeSuccessNotification;
+ (void)removeRepeatedObserver:(id)arg1 selector:(SEL)arg2;
+ (void)removeFailureObserver:(id)arg1 selector:(SEL)arg2;
+ (void)removeSuccessObserver:(id)arg1 selector:(SEL)arg2;
+ (void)addRepeatedObserver:(id)arg1 selector:(SEL)arg2;
+ (void)addFailureObserver:(id)arg1 selector:(SEL)arg2;
+ (void)addSuccessObserver:(id)arg1 selector:(SEL)arg2;
+ (void)addfetchDictSizeSuccessObserver:(id)arg1 selector:(SEL)arg2;
+ (_Bool)isNewHot;
+ (id)parseResp:(id)arg1 toDictItems:(id *)arg2 abinfos:(id *)arg3 interval:(unsigned int *)arg4 content:(id *)arg5;
+ (unsigned int)subCmdForQuickDict;
+ (unsigned int)subCmd;
+ (id)newRequestWithExpectedDeviceType:(int)arg1 option:(unsigned long long)arg2 engineVersion:(id)arg3 cellDictVersion:(int)arg4 stokeDictVersion:(int)arg5 wubiDictVersion:(int)arg6 largeDictVersion:(int)arg7 e2eModeVersion:(int)arg8 baseVersion:(int)arg9 secondVersion:(int)arg10 nnlmVersion:(int)arg11 jianpinVersion:(int)arg12 handwriteVersion:(int)arg13 newYearCardVersion:(int)arg14 extraInfo:(id)arg15 clientDicts:(id)arg16;
+ (double)userStorageLeftInGb;
+ (id)logPrefix;
- (void).cxx_destruct;
@property(retain, nonatomic) NSRecursiveLock *lockForResumeData; // @synthesize lockForResumeData=_lockForResumeData;
@property(retain, nonatomic) NSMutableDictionary *resumeDataInfo; // @synthesize resumeDataInfo=_resumeDataInfo;
@property(retain, nonatomic) NSArray *downloadingTasks; // @synthesize downloadingTasks=_downloadingTasks;
@property(retain, nonatomic) NSArray *currentDictToDownload; // @synthesize currentDictToDownload=_currentDictToDownload;
@property(nonatomic) long long taskCount; // @synthesize taskCount=_taskCount;
@property(nonatomic) unsigned long long backgroundTask; // @synthesize backgroundTask=_backgroundTask;
@property(nonatomic) _Bool needUpdateWlanDLData; // @synthesize needUpdateWlanDLData=_needUpdateWlanDLData;
@property(nonatomic) _Bool currentUpdateCallbacked; // @synthesize currentUpdateCallbacked=_currentUpdateCallbacked;
@property(nonatomic) _Bool cancelled; // @synthesize cancelled=_cancelled;
@property(retain, nonatomic) NSOperationQueue *downloadQueue; // @synthesize downloadQueue=_downloadQueue;
@property(copy, nonatomic) CDUnknownBlockType downloadFailedExtraAction; // @synthesize downloadFailedExtraAction=_downloadFailedExtraAction;
@property(copy, nonatomic) CDUnknownBlockType downloadSuccessExtraAction; // @synthesize downloadSuccessExtraAction=_downloadSuccessExtraAction;
@property(nonatomic) unsigned long long currentDownloadSource; // @synthesize currentDownloadSource=_currentDownloadSource;
@property(nonatomic) long long currentDictSizeDownloaded; // @synthesize currentDictSizeDownloaded=_currentDictSizeDownloaded;
@property(nonatomic) long long currentDownloadDictSize; // @synthesize currentDownloadDictSize=_currentDownloadDictSize;
@property(nonatomic) _Bool currentDownloadUsingWlan; // @synthesize currentDownloadUsingWlan=_currentDownloadUsingWlan;
@property(nonatomic) double nextUpdateTime; // @synthesize nextUpdateTime=_nextUpdateTime;
@property(nonatomic) unsigned long long status; // @synthesize status=_status;
- (void)onFailure:(id)arg1 downloadURL:(id)arg2 because:(id)arg3 fromError:(id)arg4;
- (void)onFailure:(id)arg1 because:(id)arg2;
- (void)onSuccess:(id)arg1;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (id)popResumeDataForURL:(id)arg1;
- (void)setResumeData:(id)arg1 forURL:(id)arg2;
- (void)cleanResumeDataIfNeed;
- (void)setupResumeDataInfo;
- (void)onUpdateFinished;
- (void)onGetDictInfo;
- (void)onNoUpdate;
- (void)onUpdateRepeated;
- (void)onOperationQueueFinished;
- (void)checkOperationQueueFinished;
- (void)onUpdateFailed:(id)arg1 errorCode:(unsigned long long)arg2;
- (void)failed:(id)arg1 bytesWritten:(long long)arg2 because:(id)arg3 errorCode:(unsigned long long)arg4;
- (void)updated:(id)arg1 bytesWritten:(long long)arg2;
- (void)downloadDicts:(unsigned long long)arg1 startBackGroundTask:(_Bool)arg2 successBlock:(CDUnknownBlockType)arg3 failedBlock:(CDUnknownBlockType)arg4;
- (void)endBackgroundTask;
- (void)startBackgroundTask;
- (void)downloadDicts:(id)arg1 source:(unsigned long long)arg2 startBackGroundTask:(_Bool)arg3 successBlock:(CDUnknownBlockType)arg4 failedBlock:(CDUnknownBlockType)arg5;
- (void)handleRespWithDictItems:(id)arg1 abinfos:(id)arg2 interval:(unsigned int)arg3 content:(id)arg4 autoDownload:(_Bool)arg5 source:(unsigned long long)arg6 startBackGroundTask:(_Bool)arg7;
- (unsigned long long)downloadOption;
- (void)cancel:(_Bool)arg1;
- (void)cancel;
@property(readonly, nonatomic) double process;
- (void)update:(_Bool)arg1 startBackGroundTask:(_Bool)arg2 source:(unsigned long long)arg3 extraInfo:(id)arg4 successBlock:(CDUnknownBlockType)arg5 failedBlock:(CDUnknownBlockType)arg6;
- (void)update:(_Bool)arg1 startBackGroundTask:(_Bool)arg2 source:(unsigned long long)arg3 successBlock:(CDUnknownBlockType)arg4 failedBlock:(CDUnknownBlockType)arg5;
- (void)update:(_Bool)arg1 startBackGroundTask:(_Bool)arg2 source:(unsigned long long)arg3 option:(unsigned long long)arg4 extraInfo:(id)arg5 successBlock:(CDUnknownBlockType)arg6 failedBlock:(CDUnknownBlockType)arg7;
- (void)resetData;
- (void)cancelDownloadQueue;
- (void)destoryDownloadQueue;
- (void)createDownloadQueue;
- (_Bool)isDownloadingDict;
- (id)createDownloadUnderlyingQueue;
- (void)syncUpdatedData:(id)arg1;
@property(readonly, nonatomic) _Bool backgroundTaskEnable;
- (void)syncAbTestInfo:(id)arg1;
- (id)checkCanUpdate:(id)arg1 dictSizeToDLMapByType:(id)arg2 forceUpdateDicts:(id)arg3 needUpdateWlanDLData:(_Bool *)arg4 networkStatus:(long long)arg5;
- (void)syncWlanDLUsage:(long long)arg1;
- (void)syncUpdateTime;
- (id)forceUpdateDicts;
- (id)sourceDicts:(unsigned long long)arg1;
- (_Bool)canUpdate;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

