//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray, NSString;

@interface WBDict : NSObject
{
    _Bool _inIMEData;
    _Bool _isNewHot;
    _Bool _canUpdate;
    unsigned int _version;
    unsigned int _type;
    unsigned int _timestamp;
    int _dictType;
    int _specialDictKind;
    int _specialDictSize;
    NSString *_name;
    NSString *_md5;
    NSString *_uniqueId;
    unsigned long long _experiment;
    NSArray *_bundles;
    unsigned long long _returnKeys;
    NSArray *_tags;
    NSArray *_weights;
    NSString *_engineVersion;
    NSString *_cellDictVersion;
    NSString *_wubiDictVersion;
    NSString *_stokeDictVersion;
    NSString *_largeDictVersion;
    NSString *_e2eModeVersion;
    NSString *_baseDictVersion;
    NSString *_secondDictVersion;
    NSString *_nnlmDictVersion;
    NSString *_jianpinDictVersion;
    NSString *_handwriteDictVersion;
    NSString *_yearBlessVersion;
}

+ (id)imeDictInfoToABTestDict:(id)arg1;
+ (id)fromItem:(id)arg1 isNewHot:(_Bool)arg2;
+ (id)fromUpdatedJSON:(id)arg1;
+ (id)fromLocalJSON:(id)arg1;
- (void).cxx_destruct;
@property(copy, nonatomic) NSString *yearBlessVersion; // @synthesize yearBlessVersion=_yearBlessVersion;
@property(copy, nonatomic) NSString *handwriteDictVersion; // @synthesize handwriteDictVersion=_handwriteDictVersion;
@property(copy, nonatomic) NSString *jianpinDictVersion; // @synthesize jianpinDictVersion=_jianpinDictVersion;
@property(copy, nonatomic) NSString *nnlmDictVersion; // @synthesize nnlmDictVersion=_nnlmDictVersion;
@property(copy, nonatomic) NSString *secondDictVersion; // @synthesize secondDictVersion=_secondDictVersion;
@property(copy, nonatomic) NSString *baseDictVersion; // @synthesize baseDictVersion=_baseDictVersion;
@property(copy, nonatomic) NSString *e2eModeVersion; // @synthesize e2eModeVersion=_e2eModeVersion;
@property(copy, nonatomic) NSString *largeDictVersion; // @synthesize largeDictVersion=_largeDictVersion;
@property(copy, nonatomic) NSString *stokeDictVersion; // @synthesize stokeDictVersion=_stokeDictVersion;
@property(copy, nonatomic) NSString *wubiDictVersion; // @synthesize wubiDictVersion=_wubiDictVersion;
@property(copy, nonatomic) NSString *cellDictVersion; // @synthesize cellDictVersion=_cellDictVersion;
@property(copy, nonatomic) NSString *engineVersion; // @synthesize engineVersion=_engineVersion;
@property(retain, nonatomic) NSArray *weights; // @synthesize weights=_weights;
@property(retain, nonatomic) NSArray *tags; // @synthesize tags=_tags;
@property(nonatomic) unsigned long long returnKeys; // @synthesize returnKeys=_returnKeys;
@property(copy, nonatomic) NSArray *bundles; // @synthesize bundles=_bundles;
@property(nonatomic) int specialDictSize; // @synthesize specialDictSize=_specialDictSize;
@property(nonatomic) int specialDictKind; // @synthesize specialDictKind=_specialDictKind;
@property(nonatomic) _Bool canUpdate; // @synthesize canUpdate=_canUpdate;
@property(nonatomic) _Bool isNewHot; // @synthesize isNewHot=_isNewHot;
@property(nonatomic) int dictType; // @synthesize dictType=_dictType;
@property(nonatomic) _Bool inIMEData; // @synthesize inIMEData=_inIMEData;
@property(nonatomic) unsigned long long experiment; // @synthesize experiment=_experiment;
@property(nonatomic) unsigned int timestamp; // @synthesize timestamp=_timestamp;
@property(nonatomic) unsigned int type; // @synthesize type=_type;
@property(copy, nonatomic) NSString *uniqueId; // @synthesize uniqueId=_uniqueId;
@property(copy, nonatomic) NSString *md5; // @synthesize md5=_md5;
@property(nonatomic) unsigned int version; // @synthesize version=_version;
@property(copy, nonatomic) NSString *name; // @synthesize name=_name;
@property(readonly, nonatomic) _Bool dataValid;
@property(readonly, nonatomic) _Bool isWubiDict;
- (id)JSON;
@property(readonly, copy, nonatomic) NSString *rootFolderPath;
@property(readonly, copy, nonatomic) NSString *versionFolderPath;
@property(readonly, copy, nonatomic) NSString *path;
@property(readonly, nonatomic) _Bool isNewYear;
@property(readonly, nonatomic) _Bool isRes;
@property(readonly, nonatomic) _Bool isHandWrite;
@property(readonly, nonatomic) _Bool isJianPin;
@property(readonly, nonatomic) _Bool isNNLM;
@property(readonly, nonatomic) _Bool isSecond;
@property(readonly, nonatomic) _Bool isBase;
@property(readonly, nonatomic) _Bool isE2E;
@property(readonly, nonatomic) _Bool isLarge;
@property(readonly, nonatomic) _Bool isWubi;
@property(readonly, nonatomic) _Bool isStoke;
@property(readonly, nonatomic) _Bool isNormal;
@property(readonly, nonatomic) _Bool isCell;
- (id)description;

@end

