//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "MMService.h"

#import "MMServiceProtocol-Protocol.h"

@class NSString, WBWormhole;

@interface WBDictUpdateManager : MMService <MMServiceProtocol>
{
    _Bool _standAloneModeEnable;
    WBWormhole *_wormhole;
}

- (void).cxx_destruct;
@property(nonatomic) _Bool standAloneModeEnable; // @synthesize standAloneModeEnable=_standAloneModeEnable;
@property(retain, nonatomic) WBWormhole *wormhole; // @synthesize wormhole=_wormhole;
- (void)cancel;
- (void)onGetStopAppUpdateNoti:(id)arg1;
- (void)stopKBUpdate;
- (void)startAppUpdate;
- (void)callAppDictUpdate;
- (void)checkAndCallDictUpdate;
- (void)handlePluginInfoDidUpdate:(id)arg1;
- (void)setUpWormhole;
- (void)handleAppSettingsDidChange;
- (void)addObservers;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

