//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "WBSettingsViewController.h"

@class WBKeyboardPreview, WBModernSlider;

@interface WBDisplayViewController : WBSettingsViewController
{
    WBKeyboardPreview *_keyboardPreview;
    WBModernSlider *_fontSlider;
}

- (void).cxx_destruct;
@property(retain, nonatomic) WBModernSlider *fontSlider; // @synthesize fontSlider=_fontSlider;
@property(retain, nonatomic) WBKeyboardPreview *keyboardPreview; // @synthesize keyboardPreview=_keyboardPreview;
- (void)handleSoundSliderValueChangedEvent:(id)arg1;
- (void)initGroups;
- (void)viewDidLoad;
- (id)title;

@end

