//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "WBPreferences.h"

@interface WBDictConfigUpdatePreferences : WBPreferences
{
}

+ (id)debugInfoForWlanRemainSize;
+ (void)reduceWlanDictDownloadRemainSize:(long long)arg1;
+ (long long)calculateWlanDictDownloadRemainSize:(long long)arg1;
+ (id)generateTodayStr;
+ (id)updatedDictABInfosForDisplay;
+ (id)updatedDictABInfosForReport;
+ (id)downloadSourceHotwordDicts;
+ (id)downloadSourceCommonDicts;
+ (id)updatedDictsAndRes;
+ (id)updatedDicts:(_Bool)arg1 filterIndex:(id)arg2;
+ (id)updatedDicts:(_Bool)arg1;
+ (id)updatedHotwordDicts:(_Bool)arg1 filterIndex:(id)arg2;
+ (id)updatedCommonDicts:(_Bool)arg1 filterIndex:(id)arg2;
+ (_Bool)hasStandAloneDictUpdate;
+ (void)reset;
+ (void)resetWithOutRemoveDict;
+ (void)updateVersionAndSync;
+ (void)updateDictVersion;
+ (_Bool)removeAllDownloadedDicts;
+ (id)nextAvailableAllDicts:(id)arg1;
+ (id)nextAvailableAllRes;
+ (id)nextAvailableAllDicts;
+ (id)nextAvailableAllDictsAndRes;
+ (void)cleanUselessDownloadedDicts:(id)arg1;
+ (void)cleanAllDownloadedDicts;
+ (void)updateForceUpdateDicts:(id)arg1;
+ (void)cleanUselessDownloadedDicts;
+ (void)checkAvailableAndReset;
+ (void)resetInVaildDictFor:(id)arg1 changed:(_Bool *)arg2 reportError:(_Bool *)arg3 logTag:(id)arg4;
+ (id)fileName;
+ (id)folderPath;

@end

