//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Foundation/NSOperation.h>

#import "NSURLSessionDownloadDelegate-Protocol.h"

@class ImeDictItem, NSString, WBDict;
@protocol WBDictUpdateTaskDelegate;

@interface WBDictUpdateTask : NSOperation <NSURLSessionDownloadDelegate>
{
    _Bool _executing;
    _Bool _finished;
    _Bool _isQuickDict;
    _Bool _isWlan;
    _Bool _needDownload;
    WBDict *_dict;
    ImeDictItem *_dictItem;
    double _downloadStartTime;
    double _rate;
    long long _fullBytesDownloaded;
    long long _bytesWritten;
    id <WBDictUpdateTaskDelegate> _delegate;
}

- (void).cxx_destruct;
@property(nonatomic) __weak id <WBDictUpdateTaskDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) _Bool needDownload; // @synthesize needDownload=_needDownload;
@property _Bool isWlan; // @synthesize isWlan=_isWlan;
@property _Bool isQuickDict; // @synthesize isQuickDict=_isQuickDict;
@property long long bytesWritten; // @synthesize bytesWritten=_bytesWritten;
@property long long fullBytesDownloaded; // @synthesize fullBytesDownloaded=_fullBytesDownloaded;
@property double rate; // @synthesize rate=_rate;
@property double downloadStartTime; // @synthesize downloadStartTime=_downloadStartTime;
@property(retain, nonatomic) ImeDictItem *dictItem; // @synthesize dictItem=_dictItem;
@property(retain, nonatomic) WBDict *dict; // @synthesize dict=_dict;
- (void)URLSession:(id)arg1 downloadTask:(id)arg2 didWriteData:(long long)arg3 totalBytesWritten:(long long)arg4 totalBytesExpectedToWrite:(long long)arg5;
- (void)URLSession:(id)arg1 task:(id)arg2 didCompleteWithError:(id)arg3;
- (void)URLSession:(id)arg1 downloadTask:(id)arg2 didFinishDownloadingToURL:(id)arg3;
- (_Bool)isAsynchronous;
- (_Bool)isFinished;
- (void)setFinished:(_Bool)arg1;
- (_Bool)isExecuting;
- (void)setExecuting:(_Bool)arg1;
- (_Bool)handleUnzip:(int)arg1 errorMsg:(id *)arg2 updatedPath:(id *)arg3;
- (_Bool)checkNeedDL:(id)arg1;
- (void)cancel;
- (void)done;
- (void)start;
- (id)initWithDictItem:(id)arg1 isQuickDict:(_Bool)arg2 isNewHot:(_Bool)arg3 isWlan:(_Bool)arg4 delegate:(id)arg5;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

