//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "WBDictUpdateTask.h"

@class ImeDictDownloadItem, NSString, NSURLSession, NSURLSessionDownloadTask;

@interface WBDictPatchUpdateTask : WBDictUpdateTask
{
    int _oldVersion;
    NSString *_basePath;
    ImeDictDownloadItem *_patchItem;
    NSURLSession *_session;
    NSURLSessionDownloadTask *_downloadTask;
}

- (void).cxx_destruct;
- (void)URLSession:(id)arg1 downloadTask:(id)arg2 didWriteData:(long long)arg3 totalBytesWritten:(long long)arg4 totalBytesExpectedToWrite:(long long)arg5;
- (void)URLSession:(id)arg1 task:(id)arg2 didCompleteWithError:(id)arg3;
- (void)URLSession:(id)arg1 downloadTask:(id)arg2 didFinishDownloadingToURL:(id)arg3;
- (void)cancel;
- (void)start;
- (id)initWithDictItem:(id)arg1 isQuickDict:(_Bool)arg2 isNewHot:(_Bool)arg3 isWlan:(_Bool)arg4 oldVersion:(int)arg5 basePath:(id)arg6 resumeData:(id)arg7 delegate:(id)arg8;

@end

