//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@class NSError, NSString, WBDictUpdateTask;

@protocol WBDictUpdateTaskDelegate
- (void)onFailure:(WBDictUpdateTask *)arg1 downloadURL:(NSString *)arg2 because:(NSString *)arg3 fromError:(NSError *)arg4;
- (void)onFailure:(WBDictUpdateTask *)arg1 because:(NSString *)arg2;
- (void)onSuccess:(WBDictUpdateTask *)arg1;

@optional
- (void)onUpdate:(WBDictUpdateTask *)arg1;
@end

