//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "WBDictUpdateTask.h"

@class ImeDictDownloadItem, NSURLSession, NSURLSessionDownloadTask;

@interface WBDictFullUpdateTask : WBDictUpdateTask
{
    NSURLSession *_session;
    NSURLSessionDownloadTask *_downloadTask;
    ImeDictDownloadItem *_fullItem;
}

- (void).cxx_destruct;
@property(retain, nonatomic) ImeDictDownloadItem *fullItem; // @synthesize fullItem=_fullItem;
- (void)URLSession:(id)arg1 downloadTask:(id)arg2 didWriteData:(long long)arg3 totalBytesWritten:(long long)arg4 totalBytesExpectedToWrite:(long long)arg5;
- (void)URLSession:(id)arg1 task:(id)arg2 didCompleteWithError:(id)arg3;
- (void)URLSession:(id)arg1 downloadTask:(id)arg2 didFinishDownloadingToURL:(id)arg3;
- (void)cancel;
- (void)start;
- (id)initWithDictItem:(id)arg1 isQuickDict:(_Bool)arg2 isNewHot:(_Bool)arg3 isWlan:(_Bool)arg4 resumeData:(id)arg5 delegate:(id)arg6;

@end

