//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Foundation/NSOperation.h>

@class NSString, NSURL, NSURLSessionDownloadTask;

@interface WBDownloadImageOperation : NSOperation
{
    _Bool _executing;
    _Bool _finished;
    _Bool _cancelled;
    _Bool _started;
    CDUnknownBlockType _completion;
    NSURL *_url;
    NSString *_destPath;
    NSURLSessionDownloadTask *_downloadTask;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSURLSessionDownloadTask *downloadTask; // @synthesize downloadTask=_downloadTask;
@property(copy, nonatomic) NSString *destPath; // @synthesize destPath=_destPath;
@property(retain, nonatomic) NSURL *url; // @synthesize url=_url;
@property(copy, nonatomic) CDUnknownBlockType completion; // @synthesize completion=_completion;
@property(getter=isStarted) _Bool started; // @synthesize started=_started;
- (void)start;
@property(getter=isCancelled) _Bool cancelled; // @synthesize cancelled=_cancelled;
- (void)_cancelOperation;
- (void)cancel;
- (void)doneWithPath:(id)arg1;
- (_Bool)isAsynchronous;
- (_Bool)isConcurrent;
@property(nonatomic, getter=isExecuting) _Bool executing; // @synthesize executing=_executing;
@property(nonatomic, getter=isFinished) _Bool finished; // @synthesize finished=_finished;
- (id)initWithURL:(id)arg1 destPath:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (id)initWithURLStirng:(id)arg1 destPath:(id)arg2;

@end

