//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "WBSettingsViewController.h"

@class WBSettingsChoicesController;

@interface WBDoublePinyinViewController : WBSettingsViewController
{
    WBSettingsChoicesController *_layoutController;
    WBSettingsChoicesController *_solutionController;
}

- (void).cxx_destruct;
- (void)viewDidLoad;
- (id)title;

@end

