//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "WBViewController.h"

@class DrawPointCanvas, NSHashTable, UIButton;

@interface WBDrawCanvasTestViewController : WBViewController
{
    _Bool _showPath;
    _Bool _shouldSnapshot;
    DrawPointCanvas *_canvas;
    NSHashTable *_historyStrokeViews;
    UIButton *_pathButton;
    UIButton *_snapshotButton;
}

- (void).cxx_destruct;
@property(nonatomic) _Bool shouldSnapshot; // @synthesize shouldSnapshot=_shouldSnapshot;
@property(retain, nonatomic) UIButton *snapshotButton; // @synthesize snapshotButton=_snapshotButton;
@property(retain, nonatomic) UIButton *pathButton; // @synthesize pathButton=_pathButton;
@property(retain, nonatomic) NSHashTable *historyStrokeViews; // @synthesize historyStrokeViews=_historyStrokeViews;
@property(nonatomic) _Bool showPath; // @synthesize showPath=_showPath;
@property(retain, nonatomic) DrawPointCanvas *canvas; // @synthesize canvas=_canvas;
- (void)stopAndRemoveAllHistoryStrokeViews;
- (id)genStrokeViewAndClear:(_Bool)arg1;
- (void)touchesEnded:(id)arg1 withEvent:(id)arg2;
- (void)touchesBegan:(id)arg1 withEvent:(id)arg2;
- (void)onClickSnapShotButton:(id)arg1;
- (void)onClickPathButton:(id)arg1;
- (void)viewDidLayoutSubviews;
- (void)viewDidLoad;

@end

