//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface WBDSBoundInfo : NSObject
{
    unsigned long long _uin;
    NSString *_name;
    long long _platform;
    double _bindTime;
}

+ (id)parsePBInfo:(id)arg1;
+ (id)parseRNDict:(id)arg1;
- (void).cxx_destruct;
@property(nonatomic) double bindTime; // @synthesize bindTime=_bindTime;
@property(nonatomic) long long platform; // @synthesize platform=_platform;
@property(copy, nonatomic) NSString *name; // @synthesize name=_name;
@property(nonatomic) unsigned long long uin; // @synthesize uin=_uin;
- (id)toRNDict;

@end

