//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray;

@interface WBDSGroupInfo : NSObject
{
    long long _groupId;
    NSArray *_boundInfoList;
    long long _funcSwitch;
}

+ (id)parsePBInfo:(id)arg1;
+ (id)parseRNDict:(id)arg1;
- (void).cxx_destruct;
@property(nonatomic) long long funcSwitch; // @synthesize funcSwitch=_funcSwitch;
@property(retain, nonatomic) NSArray *boundInfoList; // @synthesize boundInfoList=_boundInfoList;
@property(nonatomic) long long groupId; // @synthesize groupId=_groupId;
- (_Bool)hasBindPC;
- (id)toRNDict;

@end

