//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class UIImage;

@protocol WBDynamicImageProtocol <NSObject>
@property(readonly, nonatomic) _Bool wb_isDynamicImage;
@property(readonly, nonatomic) UIImage *wb_rawImage;
@end

