//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "WBViewController.h"

@class UITextField;

@interface WBEmojiFinderViewController : WBViewController
{
    UITextField *_textField;
}

- (void).cxx_destruct;
- (void)findEmojis;
- (id)findSubViewOfKind:(id)arg1 inView:(id)arg2;
- (void)viewDidLoad;
- (id)barColor;
- (id)title;

@end

