//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "WBOneViewController.h"

@class NSMutableArray;

@interface WBFAQViewController : WBOneViewController
{
    NSMutableArray *_captainzhuLayoutBlocks;
}

- (void).cxx_destruct;
- (void)viewDidLoad;
- (id)barColor;
- (id)titleColor;
- (void)didMoveToParentViewController:(id)arg1;
- (void)viewDidLayoutSubviews;

@end

