//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "MMService.h"

#import "MMServiceProtocol-Protocol.h"

@class FMDatabase, NSMutableArray, NSString;

@interface WBFeedbackMgr : MMService <MMServiceProtocol>
{
    NSMutableArray *_msgs;
    FMDatabase *_db;
    long long _uiMsgslastTime;
    unsigned long long _pendingInsertCount;
    unsigned long long _uniqid;
    unsigned long long _imageID;
}

- (void).cxx_destruct;
@property(readonly, nonatomic) unsigned long long imageID; // @synthesize imageID=_imageID;
@property(readonly, nonatomic) unsigned long long uniqid; // @synthesize uniqid=_uniqid;
- (id)clientInfo;
- (void)selectMsgs;
- (id)allData;
- (void)setSeq:(unsigned long long)arg1;
- (unsigned long long)seq;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

