//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "WBRCTBaseViewController.h"

@interface WBFeedbackRNViewController : WBRCTBaseViewController
{
}

- (_Bool)canShowGuideForNavigateKeyboardScene;
- (id)init;
- (id)initWithBundleName:(id)arg1 moduleName:(id)arg2 initialProperties:(id)arg3 nativeProperties:(id)arg4;

@end

