//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIControl.h>

@class UILabel, UIView;

@interface WBFeedbackButton : UIControl
{
    UILabel *_feedBackLabel;
    UIView *_border;
    UIView *_redDot;
    UIView *_highlightMask;
    _Bool _notify;
}

- (void).cxx_destruct;
@property(nonatomic) _Bool notify; // @synthesize notify=_notify;
- (void)layoutSubviews;
- (id)init;

@end

