//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface WBFeedbackGenerator : NSObject
{
}

+ (_Bool)isSettingsDidApply;
+ (id)allocWithZone:(struct _NSZone *)arg1;
+ (id)sharedInstance;
+ (void)initialize;
- (void)cleanHapticPlayerData;
- (void)impactFeedback:(unsigned long long)arg1 options:(unsigned long long)arg2;
- (void)playHapticWithLevel:(long long)arg1;
- (void)playClickWithVolume:(unsigned char)arg1 soundType:(unsigned long long)arg2;
- (void)removeSoundCache;
- (void)applySettings;
- (void)appSettingsChanged;
- (id)init;

@end

