//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "WBSettingsViewController.h"

@class NSArray, NSMutableArray, NSObject, NSString, UILabel, UISegmentedControl, UISwitch;
@protocol OS_dispatch_source;

@interface WBFileTestViewController : WBSettingsViewController
{
    NSString *_path;
    UILabel *_label;
    NSMutableArray *_vnodeSwitches;
    NSArray *_vnodeModes;
    UISwitch *_atomicSwitch;
    UISegmentedControl *_dataChooser;
    NSObject<OS_dispatch_source> *_source;
    int _fd;
    NSMutableArray *_captainzhuLayoutBlocks;
}

- (void).cxx_destruct;
- (id)newSwitch;
- (void)listen;
- (void)del;
- (void)writeToFile;
- (void)close;
- (void)write;
- (void)creat;
- (void)setLabel:(id)arg1;
- (void)viewDidLoad;
- (id)title;
- (void)didMoveToParentViewController:(id)arg1;
- (void)viewDidLayoutSubviews;

@end

