//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMutableArray;
@protocol OS_dispatch_source;

@interface WBFileCreationListener : NSObject
{
    NSMutableArray *_nonexistentPaths;
    NSObject<OS_dispatch_source> *_source;
    CDUnknownBlockType _handler;
}

- (void).cxx_destruct;
- (void)listenPathCreate:(id)arg1 callback:(CDUnknownBlockType)arg2;
- (void)dealloc;
- (void)handleOrListen;
- (void)createListenerForPath:(id)arg1 handler:(CDUnknownBlockType)arg2;
- (id)initWith:(id)arg1 handler:(CDUnknownBlockType)arg2;

@end

