//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "WBSettingsViewController.h"

@class NSDateFormatter, NSString;

@interface WBFinderViewController : WBSettingsViewController
{
    NSString *_root;
    _Bool _enableZip;
    NSDateFormatter *_dateFormatter;
}

+ (id)readableSize:(unsigned long long)arg1;
+ (id)root:(id)arg1;
- (void).cxx_destruct;
- (id)descForPath:(id)arg1 isDir:(_Bool)arg2;
- (void)refreshGroups;
- (void)enableZip;
- (void)onClickedZipBtn:(id)arg1;
- (void)viewDidLoad;
- (id)initWithRoot:(id)arg1;

@end

