//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "WBViewController.h"

@class QMUILabel;

@interface WBFontExporterViewController : WBViewController
{
    QMUILabel *_tipsLabel;
}

- (void).cxx_destruct;
@property(readonly, nonatomic) QMUILabel *tipsLabel; // @synthesize tipsLabel=_tipsLabel;
- (void)getSupportedChineseCharactersWithFont:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)exportSupportedChineseCharacters;
- (void)viewDidLayoutSubviews;
- (void)setupNavigationItems;
- (void)viewDidLoad;

@end

