//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <QuartzCore/CAGradientLayer.h>

@class NSArray;

@interface WBGradientLayer : CAGradientLayer
{
    _Bool _transparent;
    NSArray *_segments;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSArray *segments; // @synthesize segments=_segments;
@property(nonatomic) _Bool transparent; // @synthesize transparent=_transparent;
- (void)setSegments:(id)arg1 animated:(_Bool)arg2 animationBlock:(CDUnknownBlockType)arg3 completion:(CDUnknownBlockType)arg4;
- (void)setSegments:(id)arg1 animated:(_Bool)arg2;

@end

