//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <QuartzCore/CAShapeLayer.h>

@interface WBGridBoderFillLayer : CAShapeLayer
{
}

- (void)fillWithArrangeViewContentSize:(struct CGSize)arg1 lastCellFrame:(struct CGRect)arg2 cellSize:(struct CGSize)arg3;
- (id)init;

@end

