//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class UIColor;

@interface WBGradientSegment : NSObject
{
    _Bool _enabled;
    UIColor *_beginColor;
    UIColor *_endColor;
    double _beginAlpha;
    double _endAlpha;
    double _length;
}

- (void).cxx_destruct;
@property(nonatomic) _Bool enabled; // @synthesize enabled=_enabled;
@property(nonatomic) double length; // @synthesize length=_length;
@property(nonatomic) double endAlpha; // @synthesize endAlpha=_endAlpha;
@property(nonatomic) double beginAlpha; // @synthesize beginAlpha=_beginAlpha;
@property(retain, nonatomic) UIColor *endColor; // @synthesize endColor=_endColor;
@property(retain, nonatomic) UIColor *beginColor; // @synthesize beginColor=_beginColor;
- (id)initWithBeginAlpha:(double)arg1 endAlpha:(double)arg2 length:(double)arg3 enabled:(_Bool)arg4;
- (id)initWithBeginColor:(id)arg1 endColor:(id)arg2 length:(double)arg3;
- (id)initWithBeginAlpha:(double)arg1 endAlpha:(double)arg2 length:(double)arg3;
- (id)init;

@end

