//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class CHHapticEngine, CHHapticPattern;

@interface WBHapticEngine : NSObject
{
    float _intensity;
    float _sharpness;
    CHHapticEngine *_engine;
    CHHapticPattern *_pattern;
    _Bool _isRecreating;
    _Bool _creatingEngine;
    _Bool _playImpactAfterCreateEngineFinish;
    double _lastCleanHapticDataTime;
}

+ (void)reportCleanException:(id)arg1;
- (void).cxx_destruct;
- (void)_createEngine;
- (void)createEngineWithCallback:(CDUnknownBlockType)arg1;
- (void)impact;
- (void)cleanHapticPlayerData;
- (void)_playHaptic:(_Bool)arg1;
- (void)recreateEngineWithError:(id)arg1;
- (id)initWithIntensity:(float)arg1 sharpness:(float)arg2;

@end

