//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIView.h>

@interface WBHandWritingSnapShot : UIView
{
    _Bool _animating;
    _Bool _canRevertSpeedUp;
    UIView *_contentView;
}

- (void).cxx_destruct;
@property(nonatomic) _Bool canRevertSpeedUp; // @synthesize canRevertSpeedUp=_canRevertSpeedUp;
@property(nonatomic) _Bool animating; // @synthesize animating=_animating;
@property(readonly, nonatomic) UIView *contentView; // @synthesize contentView=_contentView;
- (void)stopAndRemove;
- (void)revertSpeedUp;
- (void)speedUp:(id)arg1;
- (void)pauseFadeOut;
- (void)fadeOut;
- (id)initWithContentView:(id)arg1;

@end

