//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "WBViewController.h"

#import "WKNavigationDelegate-Protocol.h"

@class NSString, WBFeedbackButton, WBNoNetworkView, WKWebView;

@interface WBHelpWebViewController : WBViewController <WKNavigationDelegate>
{
    WBNoNetworkView *_noNetworkView;
    WKWebView *_webView;
    WBFeedbackButton *_feedbackButton;
    NSString *_URL;
}

+ (id)title:(id)arg1 URL:(id)arg2;
- (void).cxx_destruct;
@property(retain, nonatomic) NSString *URL; // @synthesize URL=_URL;
- (void)feedback;
- (void)updateRedDotStatus:(id)arg1;
- (void)addObservers;
- (void)qmui_themeDidChangeByManager:(id)arg1 identifier:(id)arg2 theme:(id)arg3;
- (void)updateWebViewBackgroundColor;
- (void)webView:(id)arg1 decidePolicyForNavigationAction:(id)arg2 decisionHandler:(CDUnknownBlockType)arg3;
- (void)webView:(id)arg1 didFinishNavigation:(id)arg2;
- (void)showNoNetworkView;
- (void)viewDidLayoutSubviews;
- (void)viewDidLoad;
- (id)barColor;
- (id)titleColor;
- (id)initWithUrlString:(id)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

