//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMutableSet, NSOperationQueue, YYWebImageManager;

@interface WBImageDownloader : NSObject
{
    NSMutableSet *_downloadingUrls;
    NSOperationQueue *_downloadQueue;
    YYWebImageManager *_webImageManager;
}

+ (id)imageNameForUrl:(id)arg1;
+ (void)createDir;
+ (id)dir;
+ (id)imageCacheFolderPath;
+ (id)sharedInstance;
- (void).cxx_destruct;
@property(retain, nonatomic) YYWebImageManager *webImageManager; // @synthesize webImageManager=_webImageManager;
@property(retain, nonatomic) NSOperationQueue *downloadQueue; // @synthesize downloadQueue=_downloadQueue;
@property(retain, nonatomic) NSMutableSet *downloadingUrls; // @synthesize downloadingUrls=_downloadingUrls;
- (void)setCacheObject:(id)arg1 forKey:(id)arg2;
- (id)imageDataForKey:(id)arg1;
- (_Bool)containsImageDataForKey:(id)arg1;
- (void)removeImageExcludeUrls:(id)arg1;
- (void)downloadImageWithUrl:(id)arg1;
- (_Bool)isImageDownloadedWithUrl:(id)arg1;
- (id)cahePathForUrl:(id)arg1;
- (void)loadImage:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (id)init;

@end

