//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray, NSString, WBINISection, WBOrderedDictionary;

@interface WBINIParser : NSObject
{
    WBOrderedDictionary *_sectionsDict;
    WBINISection *_curSection;
    NSString *_iniPath;
    _Bool _parsed;
    NSArray *_allKeys;
}

- (void).cxx_destruct;
@property _Bool parsed; // @synthesize parsed=_parsed;
@property(readonly, nonatomic) WBOrderedDictionary *sectionsDict; // @synthesize sectionsDict=_sectionsDict;
@property(readonly, nonatomic) NSArray *allKeys; // @synthesize allKeys=_allKeys;
- (void)mergeFromSectionsDict:(id)arg1;
- (id)sectionForName:(id)arg1;
@property(readonly, nonatomic) NSArray *allSections;
- (int)parseAssignment:(char *)arg1;
- (int)parseSection:(char *)arg1;
- (int)parseLine:(char *)arg1;
- (int)parse:(const char *)arg1;
- (char *)trim:(char *)arg1;
- (void)rtrim:(char *)arg1;
- (char *)ltrim:(char *)arg1;
- (void)parseAsnyc:(CDUnknownBlockType)arg1;
- (int)parse;
- (id)initWithPath:(id)arg1 parseImmediately:(_Bool)arg2;
- (id)initWithPath:(id)arg1;

@end

