//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class WBPendingInput;

@protocol WBInputStateUpdateProtocol <NSObject>

@optional
- (void)keyboardWillDisappear;
- (void)touchPlayerStateDidChange;
- (void)hasAccessViewStateDidChange;
- (void)shiftStateDidChange;
- (void)hasOverlayLogoContentDidChange;
- (void)usingDebugNetDidChange;
- (void)selectedFontFilterDidChange;
- (void)touchKeyCountDidChange;
- (void)voiceInputControlBarVisibleStateDidChange;
- (void)mainInputSettingDidChange;
- (void)pasteboardStayToolbarRefDidChange;
- (void)presentationTypeDidChange;
- (void)weChatAblityDidFetch;
- (void)isFocusingEmbeddedInputViewDidChange;
- (void)separatedEnabledChanged;
- (void)separatedMidWidthChanged;
- (void)traditionalEnabledDidChange;
- (void)toolbarFuncsDidChange;
- (void)originalTextContentClear;
- (void)innerHandwritingStateDidChange;
- (void)bottomPanelTypeDidChange;
- (void)recommendedSymbolStateDidChange;
- (void)splitEnabledDidChange;
- (void)splitReversedDidChange;
- (void)sessionDidChange;
- (void)currentKeyboardTypeDidChange;
- (void)needsEmoticonKeyDidChange;
- (void)enablePinyinInWubiKeyboardDidChange;
- (void)showingT9AtPendingInputDidChange;
- (void)originTextViewDidTap;
- (void)textViewDidTap;
- (void)pendingInputDidChange:(WBPendingInput *)arg1;
- (void)localCandidateWordsResultDidChange;
- (void)needsSemicolonKeyDidChange;
- (void)panelLangDidChange;
- (void)candidateWordDidSelect;
- (void)cloudCandidateWordsDidChange;
- (void)currentPanelTypeDidChange;
- (void)isEmptyBeforeInputAtLineDidChange;
- (void)responsibleForNewlineDidChange;
- (void)returnActionTypeDidChange;
- (void)hasDocumentTextDidChange;
- (void)syllableDidChange;
- (void)hasPendingInputTextDidChanged;
@end

