//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "WBOrderedDictionary.h"

@class NSString;

@interface WBINISection : WBOrderedDictionary
{
    int _unnamed;
    NSString *_name;
}

- (void).cxx_destruct;
@property(copy, nonatomic) NSString *name; // @synthesize name=_name;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)description;
- (void)insert:(id)arg1 value:(id)arg2;
- (id)initWithName:(id)arg1;

@end

