//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString, WKWebView;

@interface WBJSAPICallback : NSObject
{
    WKWebView *_webView;
    NSString *_callbackId;
}

- (void).cxx_destruct;
@property(copy, nonatomic) NSString *callbackId; // @synthesize callbackId=_callbackId;
@property(nonatomic) __weak WKWebView *webView; // @synthesize webView=_webView;
- (void)handleErrorWithResult:(id)arg1;
- (void)handleSuccessWithResult:(id)arg1;
- (void)handleError;
- (void)handleSuccess;

@end

