//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface WBJSAPIUtil : NSObject
{
}

+ (void)finishCallbackWithSuccessOrNot:(_Bool)arg1 callbackId:(id)arg2 result:(id)arg3 webView:(id)arg4;
+ (_Bool)handleJSAPIName:(id)arg1 params:(id)arg2 callback:(id)arg3;
+ (id)callbackWithId:(id)arg1 webView:(id)arg2;
+ (void)jsApi_request:(id)arg1 callback:(id)arg2;
+ (void)jsApi_openUrl:(id)arg1 callback:(id)arg2;
+ (void)jsApi_reportBusLog:(id)arg1 callback:(id)arg2;
+ (void)jsApi_hideToast:(id)arg1 callback:(id)arg2;
+ (void)jsApi_showToast:(id)arg1 callback:(id)arg2;
+ (void)jsApi_getItem:(id)arg1 callback:(id)arg2;
+ (void)jsApi_setItem:(id)arg1 callback:(id)arg2;
+ (void)jsApi_getAppInfo:(id)arg1 callback:(id)arg2;

@end

