//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray, NSMutableArray, NSNumber, NSSet, NSString, UIColor, UIFont, UIImage, WBINISection;

@interface WBKeyViewItem : NSObject
{
    long long _subTitlePosition;
    long long _floatingStyle;
    NSArray *_floatingBaseList;
    NSSet *_floatingCornerMarks;
    unsigned long long _floatingBaseListDefaultIndex;
    unsigned long long _floatingBaseListInsertedIndex;
    NSNumber *_titleKern;
    long long _panelType;
    NSString *_identifier;
    long long _func;
    long long _styleRule;
    unsigned long long _alphabetIndex;
    double _cornerRadius;
    double _shadowOffset;
    UIColor *_shadowColor;
    unsigned long long _tag;
    NSArray *_normalBgColors;
    NSArray *_tintColors;
    NSArray *_subTintColors;
    NSArray *_highlightedBgColors;
    NSArray *_borderColors;
    NSArray *_shadowColors;
    NSArray *_rects;
    NSArray *_doubleTapInputs;
    NSArray *_upInputs;
    NSArray *_inputs;
    NSArray *_titleFonts;
    NSArray *_upTitleFonts;
    NSArray *_titles;
    WBINISection *_config;
    NSMutableArray *_images;
    NSMutableArray *_highlightedImages;
    NSMutableArray *_highlightedTintColors;
}

+ (id)itemWithConfig:(id)arg1;
- (void).cxx_destruct;
@property(retain, nonatomic) NSMutableArray *highlightedTintColors; // @synthesize highlightedTintColors=_highlightedTintColors;
@property(retain, nonatomic) NSMutableArray *highlightedImages; // @synthesize highlightedImages=_highlightedImages;
@property(retain, nonatomic) NSMutableArray *images; // @synthesize images=_images;
@property(readonly, nonatomic) WBINISection *config; // @synthesize config=_config;
@property(retain, nonatomic) NSArray *titles; // @synthesize titles=_titles;
@property(retain, nonatomic) NSArray *upTitleFonts; // @synthesize upTitleFonts=_upTitleFonts;
@property(retain, nonatomic) NSArray *titleFonts; // @synthesize titleFonts=_titleFonts;
@property(retain, nonatomic) NSArray *inputs; // @synthesize inputs=_inputs;
@property(retain, nonatomic) NSArray *upInputs; // @synthesize upInputs=_upInputs;
@property(retain, nonatomic) NSArray *doubleTapInputs; // @synthesize doubleTapInputs=_doubleTapInputs;
@property(retain, nonatomic) NSArray *rects; // @synthesize rects=_rects;
@property(retain, nonatomic) NSArray *shadowColors; // @synthesize shadowColors=_shadowColors;
@property(retain, nonatomic) NSArray *borderColors; // @synthesize borderColors=_borderColors;
@property(retain, nonatomic) NSArray *highlightedBgColors; // @synthesize highlightedBgColors=_highlightedBgColors;
@property(retain, nonatomic) NSArray *subTintColors; // @synthesize subTintColors=_subTintColors;
@property(retain, nonatomic) NSArray *tintColors; // @synthesize tintColors=_tintColors;
@property(retain, nonatomic) NSArray *normalBgColors; // @synthesize normalBgColors=_normalBgColors;
@property(nonatomic) unsigned long long tag; // @synthesize tag=_tag;
@property(readonly, nonatomic) UIColor *shadowColor; // @synthesize shadowColor=_shadowColor;
@property(readonly, nonatomic) double shadowOffset; // @synthesize shadowOffset=_shadowOffset;
@property(readonly, nonatomic) double cornerRadius; // @synthesize cornerRadius=_cornerRadius;
@property(readonly, nonatomic) unsigned long long alphabetIndex; // @synthesize alphabetIndex=_alphabetIndex;
@property(readonly, nonatomic) long long styleRule; // @synthesize styleRule=_styleRule;
@property(nonatomic) long long func; // @synthesize func=_func;
@property(readonly, nonatomic) NSString *identifier; // @synthesize identifier=_identifier;
@property(readonly, nonatomic) long long panelType; // @synthesize panelType=_panelType;
@property(readonly, nonatomic) NSNumber *titleKern; // @synthesize titleKern=_titleKern;
@property(readonly, nonatomic) unsigned long long floatingBaseListInsertedIndex; // @synthesize floatingBaseListInsertedIndex=_floatingBaseListInsertedIndex;
@property(readonly, nonatomic) unsigned long long floatingBaseListDefaultIndex; // @synthesize floatingBaseListDefaultIndex=_floatingBaseListDefaultIndex;
@property(readonly, nonatomic) NSSet *floatingCornerMarks; // @synthesize floatingCornerMarks=_floatingCornerMarks;
@property(readonly, nonatomic) NSArray *floatingBaseList; // @synthesize floatingBaseList=_floatingBaseList;
@property(readonly, nonatomic) long long floatingStyle; // @synthesize floatingStyle=_floatingStyle;
@property(readonly, nonatomic) long long subTitlePosition; // @synthesize subTitlePosition=_subTitlePosition;
@property(readonly, nonatomic) NSString *upInput;
@property(readonly, nonatomic) NSString *doubleTapInput;
@property(readonly, nonatomic) NSString *input;
@property(readonly, nonatomic) NSString *title;
@property(readonly, nonatomic) UIFont *upTitleFont;
@property(readonly, nonatomic) UIFont *titleFont;
@property(readonly, nonatomic) UIColor *borderColor;
- (id)highlightedImageAtIndex:(long long)arg1;
@property(readonly, nonatomic) UIImage *highlightedImage;
- (id)imageAtIndex:(long long)arg1;
@property(readonly, nonatomic) UIImage *image;
- (id)highlightedTintColorAtIndex:(long long)arg1;
- (_Bool)hasHighlightedTintColor;
@property(readonly, nonatomic) UIColor *highlightedTintColor;
@property(readonly, nonatomic) UIColor *subTintColor;
@property(readonly, nonatomic) UIColor *tintColor;
@property(readonly, nonatomic) UIColor *highlightedBgColor;
@property(readonly, nonatomic) UIColor *normalBgColor;
@property(readonly, nonatomic) struct CGRect rect;
- (void)parseBaseProperties;
- (id)description;
- (id)initWithConfig:(id)arg1 tag:(unsigned long long)arg2 panelType:(long long)arg3;
- (id)copyWithUpdater:(CDUnknownBlockType)arg1;

@end

