//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class WBKeyView;

@protocol WBKeyContentViewProtocol <NSObject>
@property(nonatomic) __weak WBKeyView *keyView;
- (void)elementScaleChanged;
@end

