//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface WBKeyboardInputModeController : NSObject
{
}

+ (id)keyboardBundleID;
+ (id)weTypeKeyboardInputMode;
+ (_Bool)switchToWeTypeInputMode;
+ (_Bool)isWeTypeKeyboardInputMode;
+ (_Bool)isWeTypeKeyboardInputDidAdd;
+ (id)currentInputModeInPreference;
+ (void)setCurrentInputModeInPreference:(id)arg1;
+ (void)setCurrentInputMode:(id)arg1;
+ (id)currentKeyboardInputMode;
+ (id)activeKeyboardInputModes;
+ (id)extensionKeyboardInputModes;
+ (id)sharedController;
+ (void)initialize;

@end

