//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface WBKeyboardRectUtil : NSObject
{
}

+ (double)maxMainAreaHeightForPresentationType:(unsigned long long)arg1 scheme:(unsigned long long)arg2;
+ (double)defaultMainAreaHeightForForPresentationType:(unsigned long long)arg1 scheme:(unsigned long long)arg2;
+ (double)mainAreaHeightForForPresentationType:(unsigned long long)arg1 scheme:(unsigned long long)arg2;
+ (void)setSeparatedMidWidth:(double)arg1;
+ (void)setKeyboardInset:(struct UIEdgeInsets)arg1;
+ (void)setMainAreaHeight:(double)arg1;
+ (_Bool)updatePresentationType:(unsigned long long)arg1 rootPanelViewType:(long long)arg2 topPanelViewType:(long long)arg3 conciseTopBar:(_Bool)arg4;
+ (_Bool)setSplitEnabled:(_Bool)arg1;
+ (_Bool)setSeparateEnabled:(_Bool)arg1;
+ (_Bool)setHandBiasEnabled:(_Bool)arg1;
+ (long long)handBiasEnabled;
+ (unsigned long long)scheme;
+ (_Bool)setScheme:(unsigned long long)arg1;
+ (_Bool)_setSplit:(long long)arg1;
+ (_Bool)_setSeparate:(long long)arg1;
+ (_Bool)_setHandBias:(long long)arg1;
+ (void)saveKeyboardInset:(struct UIEdgeInsets)arg1;
+ (struct WBKeyboardRectInfo)rectInfo;
+ (void)initialize;
- (long long)inputPanelType;

@end

