//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMutableArray;

@interface WBKeyLine : NSObject
{
    NSMutableArray *_rects;
    NSMutableArray *_layoutRects;
    NSMutableArray *_items;
    double _miniHeight;
    double _totalWidth;
    unsigned long long _count;
}

- (void).cxx_destruct;
@property(nonatomic) unsigned long long count; // @synthesize count=_count;
@property(nonatomic) double totalWidth; // @synthesize totalWidth=_totalWidth;
@property(nonatomic) double miniHeight; // @synthesize miniHeight=_miniHeight;
@property(retain, nonatomic) NSMutableArray *items; // @synthesize items=_items;
@property(retain, nonatomic) NSMutableArray *layoutRects; // @synthesize layoutRects=_layoutRects;
@property(retain, nonatomic) NSMutableArray *rects; // @synthesize rects=_rects;
- (id)description;
- (void)pushLayoutRect:(struct CGRect)arg1;
- (void)pushRect:(struct CGRect)arg1 item:(id)arg2;
- (long long)bsearchFirstItemWithArray:(id)arg1 value:(double)arg2;
- (void)mergeWidthReachY:(double)arg1 centerX:(double)arg2 leftPtr:(double *)arg3 rightPtr:(double *)arg4 rawLeftPtr:(double *)arg5 rawRight:(double *)arg6;
- (id)init;

@end

