//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIView.h>

@class WBAppKeyboardView;

@interface WBKeyboardPreview : UIView
{
    WBAppKeyboardView *_keyboardView;
    struct UIEdgeInsets _paddings;
}

- (void).cxx_destruct;
@property(nonatomic) struct UIEdgeInsets paddings; // @synthesize paddings=_paddings;
@property(retain, nonatomic) WBAppKeyboardView *keyboardView; // @synthesize keyboardView=_keyboardView;
- (void)layoutSubviews;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

