//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMutableDictionary, NSString;

@interface WBKV : NSObject
{
    NSString *_mmapID;
    NSString *_filePath;
    NSMutableDictionary *_kv;
    struct _opaque_pthread_rwlock_t _lock;
    _Bool _delaying;
}

+ (void)removeFileWithID:(id)arg1;
+ (id)folderPath;
+ (id)mmkvWithID:(id)arg1;
+ (void)initialize;
- (void).cxx_destruct;
- (void)reload;
- (void)_save;
- (void)sync;
- (void)save;
- (void)clearMemoryCache;
- (void)trim;
- (void)clearAll;
- (id)objectForKey:(id)arg1 withClass:(Class)arg2 tryunarchiveObject:(_Bool)arg3;
- (id)getObjectOfClass:(Class)arg1 forKey:(id)arg2;
- (_Bool)setObject:(id)arg1 forKey:(id)arg2;
- (_Bool)getBoolForKey:(id)arg1;
- (_Bool)setBool:(_Bool)arg1 forKey:(id)arg2;
- (id)numberForKey:(id)arg1;
- (_Bool)setNumber:(id)arg1 forKey:(id)arg2;
- (id)getStringForKey:(id)arg1;
- (_Bool)setString:(id)arg1 forKey:(id)arg2;
- (void)removeValuesForKeys:(id)arg1;
- (void)removeValueForKey:(id)arg1;
- (id)getDataForKey:(id)arg1;
- (_Bool)setData:(id)arg1 forKey:(id)arg2;
- (id)allKeys;
- (_Bool)containsKey:(id)arg1;
- (id)initWithID:(id)arg1;

@end

