//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIControl.h>

@class NSMutableArray, UILabel, UIView;

@interface WBLinkButton : UIControl
{
    UILabel *_label;
    UIView *_underline;
    NSMutableArray *_captainzhuLayoutBlocks;
    CDUnknownBlockType _captainzhuLayoutFitBlock;
    _Bool _underlined;
    double _underlineWidth;
}

+ (id)label:(id)arg1 target:(id)arg2 action:(SEL)arg3 superview:(id)arg4;
- (void).cxx_destruct;
@property(nonatomic) double underlineWidth; // @synthesize underlineWidth=_underlineWidth;
@property(nonatomic) _Bool underlined; // @synthesize underlined=_underlined;
- (void)setHighlighted:(_Bool)arg1;
- (id)initWithLabel:(id)arg1;
- (void)willMoveToSuperview:(id)arg1;
- (void)sizeToFit;
- (void)layoutSubviews;

@end

