//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "WBViewController.h"

@class NSArray, UIButton, UIImageView, UIScrollView, YYLabel;

@interface WBLicenseViewController : WBViewController
{
    NSArray *_laterViewControllers;
    UIImageView *_imageView;
    UIButton *_agreeButton;
    UIButton *_cancelButton;
    UIScrollView *_contentScrollView;
    YYLabel *_contentLabel;
}

- (void).cxx_destruct;
@property(retain, nonatomic) YYLabel *contentLabel; // @synthesize contentLabel=_contentLabel;
@property(retain, nonatomic) UIScrollView *contentScrollView; // @synthesize contentScrollView=_contentScrollView;
@property(retain, nonatomic) UIButton *cancelButton; // @synthesize cancelButton=_cancelButton;
@property(retain, nonatomic) UIButton *agreeButton; // @synthesize agreeButton=_agreeButton;
@property(retain, nonatomic) UIImageView *imageView; // @synthesize imageView=_imageView;
@property(retain, nonatomic) NSArray *laterViewControllers; // @synthesize laterViewControllers=_laterViewControllers;
- (void)handleCancel;
- (void)handleAgree;
- (void)jumpSecret;
- (void)jumpAgreement;
- (void)qmui_themeDidChangeByManager:(id)arg1 identifier:(id)arg2 theme:(id)arg3;
- (void)renderContentLabel;
- (void)viewDidLayoutSubviews;
- (void)viewDidLoad;
- (void)initSubviews;
- (id)barColor;
- (id)titleColor;

@end

