//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "WBRCTBaseViewController.h"

@interface WBMainRNViewController : WBRCTBaseViewController
{
    _Bool _checkShowNotfoundAlertOrTipsWhenVisible;
}

@property(nonatomic) _Bool checkShowNotfoundAlertOrTipsWhenVisible; // @synthesize checkShowNotfoundAlertOrTipsWhenVisible=_checkShowNotfoundAlertOrTipsWhenVisible;
- (void)appearFromPluginSettingWithParams:(id)arg1;
- (void)handleClickRatingEntranceEvent:(id)arg1;
- (void)decreaseRatingEntranceRemainTimes;
- (void)checkRatingEntranceVisibility;
- (void)handleFollowPluginNotFoundGuide:(id)arg1;
- (void)handleClosePluginNotFoundGuide:(id)arg1;
- (void)plusStateDidChange;
- (void)inputModeStateDidChange;
- (void)updateStyleByState;
- (void)hideNotfoundAlertOrTipsIfNeeded;
- (void)_checkCanShowNotfoundAlert:(_Bool *)arg1 canShowTips:(_Bool *)arg2;
- (void)showNotfoundAlertOrTipsIfNeeded;
- (void)handleAppWillEnterForegroundNotification:(id)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (void)handleOnJSEventNotification:(id)arg1;
- (void)addObservers;
- (id)initWithParams:(id)arg1;
- (id)init;

@end

