//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "MXMetricManagerSubscriber-Protocol.h"

@class NSString;

@interface WBMetrics : NSObject <MXMetricManagerSubscriber>
{
}

+ (id)diagnosticZipFilePath;
+ (id)sharedInstance;
- (void)appendDiagnosticFile:(id)arg1 toZipFile:(id)arg2 index:(unsigned long long)arg3;
- (void)createZipFileWithDiagnosticPayloads:(id)arg1;
- (void)uploadDiagnosticZipFile;
- (void)logWithCrashDiagnostic:(id)arg1 timestampBegin:(id)arg2 timestampEnd:(id)arg3;
- (void)logWithHangDiagnostic:(id)arg1 timestampBegin:(id)arg2 timestampEnd:(id)arg3;
- (void)logWithDiskWriteExceptionDiagnostic:(id)arg1 timestampBegin:(id)arg2 timestampEnd:(id)arg3;
- (void)logWithCPUExceptionDiagnostic:(id)arg1 timestampBegin:(id)arg2 timestampEnd:(id)arg3;
- (void)didReceiveDiagnosticPayloads:(id)arg1;
- (void)didReceiveMetricPayloads:(id)arg1;
- (void)pauseReports;
- (void)receiveReports;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

