//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface WBMinimalCandidate : NSObject
{
    _Bool _isWechatEmoji;
    _Bool _isFromCloud;
    _Bool _isAssociating;
    int _calculate_format;
    unsigned int _process_time;
    unsigned int _source;
    unsigned int _originKind;
    unsigned int _mostLikelyType;
    int _input_scene;
    int _pending_len;
    int _hwStrokeNum;
    unsigned int _asso_info_time;
    unsigned int _asso_info_count;
    unsigned int _asso_info_clk_time;
    unsigned int _asso_info_clk_count;
    unsigned int _asso_info_expose_time;
    unsigned int _asso_info_expose_count;
    NSString *_requestId;
    NSString *_requestIdForNoContent;
    NSString *_word;
    NSString *_emitText;
    unsigned long long _flag;
    long long _ime_flag;
    long long _cloudServiceVersion;
    long long _repeatedCout;
    long long _reportCandidateLength;
}

- (void).cxx_destruct;
@property(nonatomic) unsigned int asso_info_expose_count; // @synthesize asso_info_expose_count=_asso_info_expose_count;
@property(nonatomic) unsigned int asso_info_expose_time; // @synthesize asso_info_expose_time=_asso_info_expose_time;
@property(nonatomic) unsigned int asso_info_clk_count; // @synthesize asso_info_clk_count=_asso_info_clk_count;
@property(nonatomic) unsigned int asso_info_clk_time; // @synthesize asso_info_clk_time=_asso_info_clk_time;
@property(nonatomic) unsigned int asso_info_count; // @synthesize asso_info_count=_asso_info_count;
@property(nonatomic) unsigned int asso_info_time; // @synthesize asso_info_time=_asso_info_time;
@property(nonatomic) long long reportCandidateLength; // @synthesize reportCandidateLength=_reportCandidateLength;
@property(nonatomic) int hwStrokeNum; // @synthesize hwStrokeNum=_hwStrokeNum;
@property(nonatomic) long long repeatedCout; // @synthesize repeatedCout=_repeatedCout;
@property(nonatomic) long long cloudServiceVersion; // @synthesize cloudServiceVersion=_cloudServiceVersion;
@property(nonatomic) _Bool isAssociating; // @synthesize isAssociating=_isAssociating;
@property(nonatomic) _Bool isFromCloud; // @synthesize isFromCloud=_isFromCloud;
@property(nonatomic) int pending_len; // @synthesize pending_len=_pending_len;
@property(nonatomic) int input_scene; // @synthesize input_scene=_input_scene;
@property(nonatomic) unsigned int mostLikelyType; // @synthesize mostLikelyType=_mostLikelyType;
@property(nonatomic) unsigned int originKind; // @synthesize originKind=_originKind;
@property(nonatomic) unsigned int source; // @synthesize source=_source;
@property(nonatomic) _Bool isWechatEmoji; // @synthesize isWechatEmoji=_isWechatEmoji;
@property(nonatomic) unsigned int process_time; // @synthesize process_time=_process_time;
@property(nonatomic) int calculate_format; // @synthesize calculate_format=_calculate_format;
@property(nonatomic) long long ime_flag; // @synthesize ime_flag=_ime_flag;
@property(nonatomic) unsigned long long flag; // @synthesize flag=_flag;
@property(copy, nonatomic) NSString *emitText; // @synthesize emitText=_emitText;
@property(copy, nonatomic) NSString *word; // @synthesize word=_word;
@property(copy, nonatomic) NSString *requestIdForNoContent; // @synthesize requestIdForNoContent=_requestIdForNoContent;
@property(copy, nonatomic) NSString *requestId; // @synthesize requestId=_requestId;
- (id)description;

@end

