//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "RAFTKVStorageProtocol-Protocol.h"

@class NSString, WBKV;

@interface WBMMKVImpl : NSObject <RAFTKVStorageProtocol>
{
    WBKV *_mmkv;
}

+ (id)createKVWithName:(id)arg1;
- (void).cxx_destruct;
@property(retain, nonatomic) WBKV *mmkv; // @synthesize mmkv=_mmkv;
- (void)clearMemoryCache;
- (void)trim;
- (void)clearAll;
- (id)objectForKey:(id)arg1 withClass:(Class)arg2;
- (_Bool)setObject:(id)arg1 forKey:(id)arg2;
- (_Bool)boolForKey:(id)arg1;
- (_Bool)setBool:(_Bool)arg1 forKey:(id)arg2;
- (id)numberForKey:(id)arg1;
- (_Bool)setNumber:(id)arg1 forKey:(id)arg2;
- (id)stringForKey:(id)arg1;
- (_Bool)setString:(id)arg1 forKey:(id)arg2;
- (void)removeValuesForKeys:(id)arg1;
- (void)removeValueForKey:(id)arg1;
- (id)dataForKey:(id)arg1;
- (_Bool)setData:(id)arg1 forKey:(id)arg2;
- (id)allKeys;
- (_Bool)containsKey:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

