//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIControl.h>

#import "UIGestureRecognizerDelegate-Protocol.h"

@class NSString, QMUIButton, UIColor, UIFont, UIImage, UIPanGestureRecognizer, UIView;

@interface WBModernSlider : UIControl <UIGestureRecognizerDelegate>
{
    _Bool _continuous;
    _Bool _showDefaultValueView;
    _Bool _isTouchMoved;
    float _value;
    float _defaultValue;
    float _minimumValue;
    float _maximumValue;
    double _step;
    QMUIButton *_thumbView;
    UIView *_leftView;
    UIView *_rightView;
    CDUnknownBlockType _thumbTitleBlock;
    UIColor *_thumbTitleColor;
    UIView *_trackContainerView;
    UIView *_minTrackView;
    UIView *_maxTrackView;
    double _progressBeforeTracking;
    double _lastSendTime;
    UIPanGestureRecognizer *_trickPanGestureRecognizer;
    UIColor *_effectiveTintColor;
    UIView *_defaultValueView;
    struct CGPoint _locationInViewBeforeTracking;
    struct UIEdgeInsets _leftViewEdgeInsets;
    struct UIEdgeInsets _rightViewEdgeInsets;
}

+ (_Bool)wb_isTouch:(id)arg1 insideOfView:(id)arg2 event:(id)arg3;
- (void).cxx_destruct;
@property(retain, nonatomic) UIView *defaultValueView; // @synthesize defaultValueView=_defaultValueView;
@property(nonatomic) _Bool isTouchMoved; // @synthesize isTouchMoved=_isTouchMoved;
@property(retain, nonatomic) UIColor *effectiveTintColor; // @synthesize effectiveTintColor=_effectiveTintColor;
@property(retain, nonatomic) UIPanGestureRecognizer *trickPanGestureRecognizer; // @synthesize trickPanGestureRecognizer=_trickPanGestureRecognizer;
@property(nonatomic) double lastSendTime; // @synthesize lastSendTime=_lastSendTime;
@property(nonatomic) struct CGPoint locationInViewBeforeTracking; // @synthesize locationInViewBeforeTracking=_locationInViewBeforeTracking;
@property(nonatomic) double progressBeforeTracking; // @synthesize progressBeforeTracking=_progressBeforeTracking;
@property(retain, nonatomic) UIView *maxTrackView; // @synthesize maxTrackView=_maxTrackView;
@property(retain, nonatomic) UIView *minTrackView; // @synthesize minTrackView=_minTrackView;
@property(retain, nonatomic) UIView *trackContainerView; // @synthesize trackContainerView=_trackContainerView;
@property(nonatomic) _Bool showDefaultValueView; // @synthesize showDefaultValueView=_showDefaultValueView;
@property(retain, nonatomic) UIColor *thumbTitleColor; // @synthesize thumbTitleColor=_thumbTitleColor;
@property(copy, nonatomic) CDUnknownBlockType thumbTitleBlock; // @synthesize thumbTitleBlock=_thumbTitleBlock;
@property(nonatomic) struct UIEdgeInsets rightViewEdgeInsets; // @synthesize rightViewEdgeInsets=_rightViewEdgeInsets;
@property(nonatomic) struct UIEdgeInsets leftViewEdgeInsets; // @synthesize leftViewEdgeInsets=_leftViewEdgeInsets;
@property(retain, nonatomic) UIView *rightView; // @synthesize rightView=_rightView;
@property(retain, nonatomic) UIView *leftView; // @synthesize leftView=_leftView;
@property(nonatomic) _Bool continuous; // @synthesize continuous=_continuous;
@property(retain, nonatomic) QMUIButton *thumbView; // @synthesize thumbView=_thumbView;
@property(nonatomic) double step; // @synthesize step=_step;
@property(nonatomic) float maximumValue; // @synthesize maximumValue=_maximumValue;
@property(nonatomic) float minimumValue; // @synthesize minimumValue=_minimumValue;
@property(nonatomic) float defaultValue; // @synthesize defaultValue=_defaultValue;
@property(nonatomic) float value; // @synthesize value=_value;
- (void)setTintColor:(id)arg1;
- (double)separatorCenterXWithStepIndex:(long long)arg1 trackRect:(struct CGRect)arg2;
@property(retain, nonatomic) UIFont *thumbTitleFont;
- (void)setEnabled:(_Bool)arg1;
- (void)setBounds:(struct CGRect)arg1;
- (void)setFrame:(struct CGRect)arg1;
- (void)initDefaultValueView;
@property(retain, nonatomic) UIColor *maximumTrackTintColor;
@property(retain, nonatomic) UIColor *minimumTrackTintColor;
@property(readonly, nonatomic) double progress;
@property(readonly, nonatomic) UIImage *currentThumbImage;
- (_Bool)_setValue:(float)arg1 animated:(_Bool)arg2;
- (void)setValue:(float)arg1 animated:(_Bool)arg2;
- (void)updateColorTheme;
- (void)updateEffectiveTintColor;
- (void)updateThumbTitleColor;
- (void)updateCustomViews;
- (void)updateThumbTitle;
- (void)layoutSubviewsWithProgress;
- (id)stepMaskForMinTrackViewWithEdgeCellWidth:(double)arg1 normalCellWidth:(double)arg2 minTrackRect:(struct CGRect)arg3;
- (void)layoutDefaultValueView;
- (void)layoutCustomView;
- (_Bool)updateProgress:(double)arg1;
- (float)valueWithProgress:(double)arg1;
- (float)valueWithRawValue:(float)arg1;
- (struct CGRect)thumbRectForBounds:(struct CGRect)arg1 trackRect:(struct CGRect)arg2 value:(float)arg3;
- (struct CGRect)trackRectForBounds:(struct CGRect)arg1;
- (void)didMoveToWindow;
- (double)closeToDefaultRate;
- (void)touchesEnded:(id)arg1 withEvent:(id)arg2;
- (void)touchesMoved:(id)arg1 withEvent:(id)arg2;
- (void)endTrackingWithTouch:(id)arg1 withEvent:(id)arg2;
- (_Bool)continueTrackingWithTouch:(id)arg1 withEvent:(id)arg2;
- (_Bool)beginTrackingWithTouch:(id)arg1 withEvent:(id)arg2;
- (void)layoutSubviews;
- (void)didInitialize;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

