//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "WBDictUpdater.h"

@interface WBNewHotDictUpdater : WBDictUpdater
{
}

+ (id)fetchDictSizeSuccessNotification;
+ (id)repeatedNotification;
+ (id)failureNotification;
+ (id)successNotification;
+ (_Bool)isNewHot;
+ (id)parseResp:(id)arg1 toDictItems:(id *)arg2 abinfos:(id *)arg3 interval:(unsigned int *)arg4 content:(id *)arg5;
+ (unsigned int)subCmdForQuickDict;
+ (unsigned int)subCmd;
+ (id)newRequestWithExpectedDeviceType:(int)arg1 option:(unsigned long long)arg2 engineVersion:(id)arg3 cellDictVersion:(int)arg4 stokeDictVersion:(int)arg5 wubiDictVersion:(int)arg6 largeDictVersion:(int)arg7 e2eModeVersion:(int)arg8 baseVersion:(int)arg9 secondVersion:(int)arg10 nnlmVersion:(int)arg11 jianpinVersion:(int)arg12 handwriteVersion:(int)arg13 newYearCardVersion:(int)arg14 extraInfo:(id)arg15 clientDicts:(id)arg16;
+ (id)logPrefix;
- (void)syncWlanDLUsage:(long long)arg1;
- (void)syncUpdatedData:(id)arg1;
- (void)syncUpdateTime;
- (id)forceUpdateDicts;
- (id)sourceDicts:(unsigned long long)arg1;
- (unsigned long long)downloadOption;
- (id)checkCanUpdate:(id)arg1 dictSizeToDLMapByType:(id)arg2 forceUpdateDicts:(id)arg3 needUpdateWlanDLData:(_Bool *)arg4 networkStatus:(long long)arg5;
- (id)createDownloadUnderlyingQueue;

@end

