//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "MMService.h"

#import "MMServiceProtocol-Protocol.h"

@class MMTimer, NSString;

@interface WBNewHotDictUpdateTimer : MMService <MMServiceProtocol>
{
    MMTimer *_timer;
}

- (void).cxx_destruct;
- (void)fire;
- (_Bool)isUpdating;
- (void)update;
- (void)cancel;
- (void)start;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

