//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "WBViewController.h"

@class NSMutableArray, WBLinkButton;

@interface WBNewWelcomeViewController : WBViewController
{
    WBLinkButton *_link;
    _Bool _showLink;
    NSMutableArray *_captainzhuLayoutBlocks;
}

+ (void)addObserver:(id)arg1 selector:(SEL)arg2;
- (void).cxx_destruct;
- (void)inputModeStateDidChange;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewWillEnterForeground;
- (void)help;
- (void)open;
- (void)viewDidLoad;
- (id)barColor;
- (id)titleColor;
- (void)didMoveToParentViewController:(id)arg1;
- (void)viewDidLayoutSubviews;

@end

