//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "WBKeyView.h"

@interface WBNewlineKeyView : WBKeyView
{
}

- (id)inputForNormalState;
- (id)mainTextForCurrentState;
- (void)responsibleForNewlineDidChange;
- (void)didAttachHosting;

@end

