//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface WBNoRetainTimerTarget : NSObject
{
    SEL _targetAction;
    id _target;
}

- (void).cxx_destruct;
@property(nonatomic) __weak id target; // @synthesize target=_target;
@property(nonatomic) SEL targetAction; // @synthesize targetAction=_targetAction;
- (void)onNoRetainTimer:(id)arg1;
- (id)initWithTarget:(id)arg1 withAction:(SEL)arg2;

@end

