//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIViewController.h>

@class NSMutableArray, UIView;

@interface WBNotFoundViewController : UIViewController
{
    _Bool _shown;
    UIView *_infoView;
    NSMutableArray *_captainzhuLayoutBlocks;
    CDUnknownBlockType _callback;
}

+ (void)showWith:(id)arg1 callback:(CDUnknownBlockType)arg2;
- (void).cxx_destruct;
@property(copy, nonatomic) CDUnknownBlockType callback; // @synthesize callback=_callback;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)show;
- (void)confirm;
- (void)dismiss;
- (void)viewDidLoad;
- (void)didMoveToParentViewController:(id)arg1;
- (void)viewDidLayoutSubviews;

@end

