//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIView.h>

#import "UITextViewDelegate-Protocol.h"

@class NSString, UIImageView, UILabel, WBTextView;

@interface WBNoNetworkView : UIView <UITextViewDelegate>
{
    UIImageView *_imageView;
    WBTextView *_textView;
    UILabel *_titltLabel;
}

- (void).cxx_destruct;
@property(retain, nonatomic) UILabel *titltLabel; // @synthesize titltLabel=_titltLabel;
@property(retain, nonatomic) WBTextView *textView; // @synthesize textView=_textView;
@property(retain, nonatomic) UIImageView *imageView; // @synthesize imageView=_imageView;
- (_Bool)textView:(id)arg1 shouldInteractWithURL:(id)arg2 inRange:(struct _NSRange)arg3 interaction:(long long)arg4;
- (void)layoutSubviews;
- (void)initUI;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

