//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "MMService.h"

#import "MMServiceProtocol-Protocol.h"

@class NSMutableDictionary, NSObject, NSString;
@protocol OS_dispatch_semaphore;

@interface WBNotificationCenter : MMService <MMServiceProtocol>
{
    NSString *_signalRoot;
    NSString *_historyRoot;
    NSMutableDictionary *_sources;
    NSMutableDictionary *_fileCreationListeners;
    NSObject<OS_dispatch_semaphore> *_fileCreationListenersLock;
    NSObject<OS_dispatch_semaphore> *_sourcesLock;
}

- (void).cxx_destruct;
- (void)clearClass:(Class)arg1;
- (void)stopListenClass:(Class)arg1;
- (void)stopListen:(id)arg1;
- (void)handleClass:(Class)arg1 ifNeededWith:(CDUnknownBlockType)arg2;
- (void)listenClass:(Class)arg1 with:(CDUnknownBlockType)arg2;
- (void)handle:(id)arg1 ifNeededWith:(CDUnknownBlockType)arg2;
- (void)listen:(id)arg1 with:(CDUnknownBlockType)arg2;
- (void)stoplistenFile:(id)arg1;
- (void)listenFile:(id)arg1 with:(CDUnknownBlockType)arg2;
- (void)sendObject:(id)arg1;
- (void)send:(id)arg1;
- (id)objectOf:(Class)arg1;
- (id)historyFileOfClass:(Class)arg1;
- (id)signalFileOfClass:(Class)arg1;
- (id)historyFileOf:(id)arg1;
- (id)signalFileOf:(id)arg1;
- (void)setModTimeOfFile:(id)arg1 to:(double)arg2;
- (double)modTimeOfFile:(id)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

