//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "WBViewController.h"

@class NSMutableArray, UIView;

@interface WBOneViewController : WBViewController
{
    NSMutableArray *_captainzhuLayoutBlocks;
    UIView *_oneView;
    double _padding;
    double _maxWidth;
    UIView *_footer;
}

- (void).cxx_destruct;
@property(retain, nonatomic) UIView *footer; // @synthesize footer=_footer;
@property(nonatomic) double maxWidth; // @synthesize maxWidth=_maxWidth;
@property(nonatomic) double padding; // @synthesize padding=_padding;
@property(retain, nonatomic) UIView *oneView; // @synthesize oneView=_oneView;
- (void)viewDidLoad;
- (void)didMoveToParentViewController:(id)arg1;
- (void)viewDidLayoutSubviews;

@end

