//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray, NSMutableArray, NSMutableOrderedSet;

@interface WBOrderedDictionary : NSObject
{
    NSMutableOrderedSet *_mutableAllKeys;
    NSMutableArray *_mutableAllValues;
}

+ (id)dictionary;
- (void).cxx_destruct;
@property(retain, nonatomic) NSMutableArray *mutableAllValues; // @synthesize mutableAllValues=_mutableAllValues;
@property(retain, nonatomic) NSMutableOrderedSet *mutableAllKeys; // @synthesize mutableAllKeys=_mutableAllKeys;
- (unsigned long long)countByEnumeratingWithState:(CDStruct_70511ce9 *)arg1 objects:(id *)arg2 count:(unsigned long long)arg3;
- (void)inheritFromDictionary:(id)arg1 conflictResolver:(CDUnknownBlockType)arg2;
- (void)inheritFromDictionary:(id)arg1;
- (void)addEntriesFromDictionary:(id)arg1;
- (void)enumerateKeysAndObjectsUsingBlock:(CDUnknownBlockType)arg1;
- (void)removeObjectForKey:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)mutableCopyWithZone:(struct _NSZone *)arg1;
- (id)description;
- (id)objectAtIndexedSubscript:(unsigned long long)arg1;
- (id)objectAtIndex:(long long)arg1;
- (void)setObject:(id)arg1 forKeyedSubscript:(id)arg2;
- (id)objectForKeyedSubscript:(id)arg1;
- (id)objectForKey:(id)arg1;
- (void)removeObject:(id)arg1 atIndex:(long long)arg2;
- (void)removeObject:(id)arg1 forKey:(id)arg2;
- (void)insertObjects:(id)arg1 forKeys:(id)arg2 atIndex:(long long)arg3;
- (void)insertObject:(id)arg1 forKey:(id)arg2 atIndex:(long long)arg3;
- (void)addObjects:(id)arg1 forKeys:(id)arg2;
- (void)addObject:(id)arg1 forKey:(id)arg2;
- (void)removeAllObjects;
- (void)setObject:(id)arg1 forKey:(id)arg2;
@property(readonly, copy, nonatomic) NSArray *allValues;
@property(readonly, copy, nonatomic) NSArray *allKeys;
@property(readonly) unsigned long long count;
- (id)init;
- (id)initWithKeysAndObjects:(id)arg1;

@end

