//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class UITouch, WBKeyView;

@protocol WBPanelProxy <NSObject>
@property(readonly, nonatomic) long long panelType;
@property(readonly, nonatomic) _Bool isWubiPanel;
@property(readonly, nonatomic) _Bool isShuangPinPanel;
@property(readonly, nonatomic) _Bool canResponseSyllables;

@optional
@property(readonly, nonatomic) double firstUpFloatingKeyWidth;
@property(readonly, nonatomic) unsigned long long letterTextShiftRule;
@property(readonly, nonatomic) unsigned long long shiftState;
@property(readonly, nonatomic) _Bool isUppercase;
- (void)recognizeLongPressWithTouch:(UITouch *)arg1 keyView:(WBKeyView *)arg2;
- (void)processTouchEnd:(UITouch *)arg1 keyView:(WBKeyView *)arg2 interrupterKeyView:(WBKeyView *)arg3;
- (void)processTouchCancel:(UITouch *)arg1 keyView:(WBKeyView *)arg2;
- (void)processTouchBegan:(UITouch *)arg1 keyView:(WBKeyView *)arg2;
@end

