//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSSet, UITouch, WBKeyView, WBPanelLayout;

@protocol WBPanelLayoutDelegate <NSObject>
- (NSSet *)placeholderTagSet;
- (NSSet *)uninstallKeyTagSet;
- (long long)optionsForLayout:(WBPanelLayout *)arg1;
- (void)layoutDidUpdate:(WBPanelLayout *)arg1;
- (void)subviewsDidCreate:(WBPanelLayout *)arg1;
- (struct CGRect)rectForLayout:(WBPanelLayout *)arg1;
- (struct CGPoint)layout:(WBPanelLayout *)arg1 locationForTouch:(UITouch *)arg2;
- (void)setNeedsLayout:(WBPanelLayout *)arg1;
- (void)layout:(WBPanelLayout *)arg1 addKeyView:(WBKeyView *)arg2;
@end

