//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface WBPath : NSObject
{
}

+ (id)userMD5;
+ (id)wbGroup;
+ (id)wbUserGroup;
+ (id)oldUserGroup;
+ (id)oldGroup;
+ (id)userDocumentsOld;
+ (id)userDocuments;
+ (id)librarys;
+ (id)documents;
+ (id)temp;
+ (id)imeData;
+ (id)pluginBundleDy;
+ (id)pluginBundle;
+ (id)mainAppBundle;
+ (id)businessOld;
+ (id)business;

@end

