//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString, WBINIParser, WBOrderedDictionary;

@interface WBPanelConfig : NSObject
{
    NSString *_identifer;
    CDUnknownBlockType _styleInjecter;
    WBINIParser *_iniParser;
    NSString *_iniPatch;
    WBOrderedDictionary *_configSections;
}

- (void).cxx_destruct;
@property(retain, nonatomic) WBOrderedDictionary *configSections; // @synthesize configSections=_configSections;
@property(copy, nonatomic) NSString *iniPatch; // @synthesize iniPatch=_iniPatch;
@property(retain, nonatomic) WBINIParser *iniParser; // @synthesize iniParser=_iniParser;
@property(copy, nonatomic) CDUnknownBlockType styleInjecter; // @synthesize styleInjecter=_styleInjecter;
@property(copy, nonatomic) NSString *identifer; // @synthesize identifer=_identifer;
@property(readonly, nonatomic) _Bool isParsed;
- (id)keyItemConfigByINISection:(id)arg1 styleInjecter:(CDUnknownBlockType)arg2;
- (void)keyItemWithPanelConfigBlock:(CDUnknownBlockType)arg1 keyConfigBlock:(CDUnknownBlockType)arg2;
- (id)sectionForKey:(id)arg1;
- (void)parse;
- (id)initWithFilePath:(id)arg1;

@end

