//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray, NSMutableArray, NSMutableDictionary, NSSet, UIView, WBHotArea, WBKeyView, WBPanelConfig;
@protocol WBKeyViewHostingProtocol, WBPanelLayoutDelegate;

@interface WBPanelLayout : NSObject
{
    NSMutableDictionary *_keyViewsMap;
    NSMutableDictionary *_keyTagMap;
    NSMutableDictionary *_unInitializeKeyTagMap;
    NSMutableArray *_placeholderItem;
    NSSet *_uninstallTags;
    NSMutableArray *_keyViews;
    NSMutableArray *_pairedViews;
    WBPanelConfig *_config;
    struct CGSize _previousLayoutSize;
    long long _layoutOptions;
    struct CGPoint _cachedHitTestPoint;
    WBKeyView *_cachedHitTestTargetView;
    WBHotArea *_cachedHotArea;
    _Bool _subviewCreated;
    struct CGSize _layoutBaseSize;
    double _normX;
    double _normY;
    struct UIEdgeInsets _keyHintEdgeInsets;
    _Bool _needsLayoutKeyViews;
    NSMutableArray *_layoutedLines;
    UIView *_debugRectView;
    _Bool _isSeparated;
    _Bool _refreshLayout;
    _Bool _hasPendingInput;
    _Bool _canResponseSyllables;
    _Bool _parsWillFinish;
    _Bool _isT26;
    _Bool _isT9;
    _Bool _isHandWrite;
    _Bool _isInputPanelType;
    id <WBPanelLayoutDelegate> _layoutDelegate;
    long long _panelType;
    id <WBKeyViewHostingProtocol> _hosting;
    CDUnknownBlockType _parseFinishBlock;
    struct UIEdgeInsets _keyTouchOutsideEdge;
}

- (void).cxx_destruct;
@property(readonly, nonatomic) _Bool isInputPanelType; // @synthesize isInputPanelType=_isInputPanelType;
@property(readonly, nonatomic) _Bool isHandWrite; // @synthesize isHandWrite=_isHandWrite;
@property(readonly, nonatomic) _Bool isT9; // @synthesize isT9=_isT9;
@property(readonly, nonatomic) _Bool isT26; // @synthesize isT26=_isT26;
@property _Bool parsWillFinish; // @synthesize parsWillFinish=_parsWillFinish;
@property(copy) CDUnknownBlockType parseFinishBlock; // @synthesize parseFinishBlock=_parseFinishBlock;
@property(nonatomic) __weak id <WBKeyViewHostingProtocol> hosting; // @synthesize hosting=_hosting;
@property(nonatomic) struct UIEdgeInsets keyTouchOutsideEdge; // @synthesize keyTouchOutsideEdge=_keyTouchOutsideEdge;
@property(nonatomic) _Bool canResponseSyllables; // @synthesize canResponseSyllables=_canResponseSyllables;
@property(readonly, nonatomic) long long panelType; // @synthesize panelType=_panelType;
@property(readonly, nonatomic) __weak id <WBPanelLayoutDelegate> layoutDelegate; // @synthesize layoutDelegate=_layoutDelegate;
@property(readonly, nonatomic) NSArray *keyViews;
- (void)invalidateHitTestCache;
- (id)viewForTouch:(id)arg1 event:(id)arg2;
- (id)viewForPoint:(struct CGPoint)arg1 event:(id)arg2;
- (void)hasPendingInputTextDidChanged;
- (id)keyForPoint:(struct CGPoint)arg1 inKeys:(id)arg2 withProbs:(const float *)arg3 andDeltas:(const struct _wxime_user_coordinate_dict_item *)arg4;
- (void)prepareForLayoutDelegate:(id)arg1;
- (id)viewForKey:(id)arg1;
- (void)layoutKeyViews;
- (void)updateKeyViews;
- (void)refreshLayout;
- (void)getMainInputKeyRectsUsingBlock:(CDUnknownBlockType)arg1;
- (void)layoutKeyViewsBySpecifiedSpacing;
- (void)updatePairedKeys;
- (void)layoutOptionsDidChange;
- (void)removeAllPairedKeyViews;
- (void)removePairedKeyViewForKeyView:(id)arg1;
- (void)addPairedKeyViewForKeyView:(id)arg1;
- (void)layoutKeyViewsBySeparated;
- (double)splitPanelWithForContainerSize:(struct CGSize)arg1 paddingPtr:(struct UIEdgeInsets *)arg2 spacingPtr:(struct CGPoint *)arg3;
- (void)layoutKeyViewsByScaleWay;
- (void)parserAndAddSubviewsIfNeeded;
- (void)ensureSubviewCreated;
- (void)addSubviewsToContainerIfNeeded;
- (void)setNeedsLayoutKeyViews;
- (void)uninstallKeyViewWithFunc:(long long)arg1;
- (void)installKeyViewWithFunc:(long long)arg1;
- (void)reloadUninstalledFuncsKeys;
- (void)parsePanelAttributes:(id)arg1;
- (id)layoutedKeys;
- (id)layoutedKeysOrderByLine;
- (id)viewsForLine:(id)arg1;
- (id)keyForIdentifier:(id)arg1;
- (id)keyForTag:(unsigned long long)arg1;
- (id)keysForTag:(unsigned long long)arg1;
- (id)createKeyViewWithConfig:(id)arg1 tag:(unsigned long long)arg2;
- (id)initWithConfig:(id)arg1 type:(long long)arg2;
- (id)init;

@end

