//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface WBPluginManager : NSObject
{
    _Bool _inputModeObserverInitialized;
    _Bool _hasFullAccessStateExplicit;
    _Bool _needsReloadCurrentInputMode;
    long long _currentKeyboardType;
    _Bool _hasShownOnOtherApp;
    _Bool _applicationDidBecomeActivating;
    _Bool _kbInfoSynced;
    _Bool _hasFullAccess;
    _Bool _plusEnabled;
    _Bool _standaloneModeEnabled;
    unsigned long long _inputModeState;
    long long _clipboardStatus;
}

+ (void)initialize;
+ (void)load;
+ (id)allocWithZone:(struct _NSZone *)arg1;
+ (id)manager;
@property(readonly, nonatomic) _Bool standaloneModeEnabled; // @synthesize standaloneModeEnabled=_standaloneModeEnabled;
@property(readonly, nonatomic) _Bool plusEnabled; // @synthesize plusEnabled=_plusEnabled;
@property(readonly, nonatomic) long long clipboardStatus; // @synthesize clipboardStatus=_clipboardStatus;
@property(readonly, nonatomic) _Bool hasFullAccess; // @synthesize hasFullAccess=_hasFullAccess;
@property(readonly, nonatomic) _Bool kbInfoSynced; // @synthesize kbInfoSynced=_kbInfoSynced;
- (_Bool)canDownloadDict;
- (void)showKeyboardWithArguments:(id)arg1 hidesTextField:(_Bool)arg2 forceNewActivity:(_Bool)arg3 callback:(CDUnknownBlockType)arg4;
- (void)deleteKeyboardCustomSymbol;
- (void)showKeyboardCustomToolbarWithCallback:(CDUnknownBlockType)arg1;
- (void)setShowKeyboardCustomSymbol;
- (void)showKeyboardRectSettingWithCallback:(CDUnknownBlockType)arg1;
- (void)showKeyboardInnerHWWithCallback:(CDUnknownBlockType)arg1;
- (void)handleEnablePlusAction:(long long)arg1 callback:(CDUnknownBlockType)arg2;
- (void)updateClipboardStatus:(long long)arg1;
- (void)notifyAuthChange;
- (void)updateHasFullAccess:(_Bool)arg1;
- (void)handleCurrentInputModeDidChangeNotification:(id)arg1;
- (void)applicationDidBecomeActive:(id)arg1;
- (void)updateInputModeState:(unsigned long long)arg1;
- (unsigned long long)currentInputModeState;
- (void)checkFullAccessIfNeeded:(id)arg1;
- (void)applyPluginInfoSync;
- (void)cancelRemoteKeyboardWindowHiddenTask;
@property(readonly, nonatomic) NSString *currentKeyboardName;
@property(readonly, nonatomic) _Bool hasShownOnOtherApp;
@property(readonly, nonatomic) long long currentKeyboardType;
- (_Bool)pluginDidBecomeCurrentInputMode;
- (void)reloadCurrentInputModeIfNeeded;
@property(readonly, nonatomic) NSString *pluginDisplayName;
- (_Bool)pluginDidAddToInputModesList;
- (_Bool)handleOpenURL:(id)arg1;
- (void)updateStandaloneModeEnabledState;
- (void)updatePlusEnabledState;
- (_Bool)getStandaloneModeEnabled;
- (_Bool)getPlusEnabledState;
- (void)handleAppSettingUpdated:(id)arg1;
@property(readonly, nonatomic) unsigned long long inputModeState; // @synthesize inputModeState=_inputModeState;
- (void)setupInputModeObserver;
- (void)handleWillResignActiveNotification:(id)arg1;
- (id)init;

@end

