//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface WBPlayerHelper : NSObject
{
}

+ (id)scrollViewsInView:(id)arg1;
+ (id)findFirstScrollViewInViewRecursively:(id)arg1;
+ (id)scrollViewsInViewController:(id)arg1;
+ (id)firstScrollViewsInViewController:(id)arg1;

@end

