//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "WBSettingBitSwitchBaseController.h"

@interface WBPluginSettingBitSwitchController : WBSettingBitSwitchBaseController
{
    int _bit;
}

+ (id)withBit:(int)arg1 on:(CDUnknownBlockType)arg2 off:(CDUnknownBlockType)arg3;
+ (id)withBit:(int)arg1;
- (_Bool)currentBoolValue;
- (void)onValueChanged;
- (id)initWithBit:(int)arg1 on:(CDUnknownBlockType)arg2 off:(CDUnknownBlockType)arg3;

@end

