//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "WBViewController.h"

#import "QMUIModalPresentationContentViewControllerProtocol-Protocol.h"
#import "QMUIModalPresentationViewControllerDelegate-Protocol.h"
#import "UIGestureRecognizerDelegate-Protocol.h"
#import "UIScrollViewDelegate-Protocol.h"
#import "WHPlayerPanelControllerDelegate-Protocol.h"

@class NSDictionary, NSString, QMUIModalPresentationViewController, UIColor, UIImageView, UIPanGestureRecognizer, UIScreenEdgePanGestureRecognizer, UIScrollView, UIView;

@interface WBPlayerPanelController : WBViewController <QMUIModalPresentationViewControllerDelegate, QMUIModalPresentationContentViewControllerProtocol, UIGestureRecognizerDelegate, UIScrollViewDelegate, WHPlayerPanelControllerDelegate>
{
    _Bool _needGesture;
    _Bool _needSceenGesture;
    _Bool _backgroundEffect;
    _Bool _showGrabber;
    _Bool _enableDimmingViewTap;
    _Bool _keyboadrDelegateEnabled;
    _Bool _isInDismiss;
    _Bool _enableSpringAnimation;
    _Bool _preferredStatusBarHidden;
    _Bool _gestureBeginFromScrollView;
    _Bool _ignoreQMUIHideAnimation;
    unsigned long long _showStyle;
    NSDictionary *_initialParams;
    UIColor *_grabColor;
    UIColor *_backgroundColor;
    CDUnknownBlockType _willHideBlock;
    CDUnknownBlockType _didHideBlock;
    CDUnknownBlockType _didHideByDimmingViewBlock;
    CDUnknownBlockType _layoutBlock;
    QMUIModalPresentationViewController *_modalVC;
    UIPanGestureRecognizer *_gesture;
    UIView *_backgroundView;
    UIView *_headerView;
    UIView *_contentView;
    UIImageView *_grabber;
    UIScrollView *_firstScrollView;
    UIScreenEdgePanGestureRecognizer *_edgePanGesture;
}

+ (void)hideAllVisiblePanel;
+ (void)initialize;
- (void).cxx_destruct;
@property(nonatomic) _Bool ignoreQMUIHideAnimation; // @synthesize ignoreQMUIHideAnimation=_ignoreQMUIHideAnimation;
@property(retain, nonatomic) UIScreenEdgePanGestureRecognizer *edgePanGesture; // @synthesize edgePanGesture=_edgePanGesture;
@property(nonatomic) _Bool gestureBeginFromScrollView; // @synthesize gestureBeginFromScrollView=_gestureBeginFromScrollView;
@property(nonatomic) __weak UIScrollView *firstScrollView; // @synthesize firstScrollView=_firstScrollView;
@property(retain, nonatomic) UIImageView *grabber; // @synthesize grabber=_grabber;
@property(retain, nonatomic) UIView *contentView; // @synthesize contentView=_contentView;
@property(retain, nonatomic) UIView *headerView; // @synthesize headerView=_headerView;
@property(retain, nonatomic) UIView *backgroundView; // @synthesize backgroundView=_backgroundView;
@property(retain, nonatomic) UIPanGestureRecognizer *gesture; // @synthesize gesture=_gesture;
@property(retain, nonatomic) QMUIModalPresentationViewController *modalVC; // @synthesize modalVC=_modalVC;
@property(nonatomic) _Bool preferredStatusBarHidden; // @synthesize preferredStatusBarHidden=_preferredStatusBarHidden;
@property(copy, nonatomic) CDUnknownBlockType layoutBlock; // @synthesize layoutBlock=_layoutBlock;
@property(copy, nonatomic) CDUnknownBlockType didHideByDimmingViewBlock; // @synthesize didHideByDimmingViewBlock=_didHideByDimmingViewBlock;
@property(copy, nonatomic) CDUnknownBlockType didHideBlock; // @synthesize didHideBlock=_didHideBlock;
@property(copy, nonatomic) CDUnknownBlockType willHideBlock; // @synthesize willHideBlock=_willHideBlock;
@property(nonatomic) _Bool enableSpringAnimation; // @synthesize enableSpringAnimation=_enableSpringAnimation;
@property(nonatomic) _Bool isInDismiss; // @synthesize isInDismiss=_isInDismiss;
@property(nonatomic) _Bool keyboadrDelegateEnabled; // @synthesize keyboadrDelegateEnabled=_keyboadrDelegateEnabled;
@property(nonatomic) _Bool enableDimmingViewTap; // @synthesize enableDimmingViewTap=_enableDimmingViewTap;
@property(nonatomic) _Bool showGrabber; // @synthesize showGrabber=_showGrabber;
@property(nonatomic) _Bool backgroundEffect; // @synthesize backgroundEffect=_backgroundEffect;
@property(retain, nonatomic) UIColor *backgroundColor; // @synthesize backgroundColor=_backgroundColor;
@property(retain, nonatomic) UIColor *grabColor; // @synthesize grabColor=_grabColor;
@property(nonatomic) _Bool needSceenGesture; // @synthesize needSceenGesture=_needSceenGesture;
@property(nonatomic) _Bool needGesture; // @synthesize needGesture=_needGesture;
@property(copy, nonatomic) NSDictionary *initialParams; // @synthesize initialParams=_initialParams;
@property(nonatomic) unsigned long long showStyle; // @synthesize showStyle=_showStyle;
- (_Bool)disableGlobalEntrance;
- (void)handleDimmingViewTapGestureRecognizer:(id)arg1;
- (struct CGRect)whPanelContentViewFrame:(struct CGRect)arg1;
- (id)whPanelContentView;
- (struct CGRect)whPanelHeaderViewFrame:(struct CGRect)arg1;
- (id)whPanelHeaderView;
- (void)layoutWithContainerBounds:(struct CGRect)arg1 keyboardHeight:(double)arg2 contentViewDefaultFrame:(struct CGRect)arg3;
- (void)scrollViewDidScroll:(id)arg1;
- (void)didChangeGestureState:(long long)arg1;
- (void)doAppearAnimation;
- (void)handleGesture:(id)arg1;
- (void)handleEdgePanGesture:(id)arg1;
- (_Bool)gestureRecognizer:(id)arg1 shouldRecognizeSimultaneouslyWithGestureRecognizer:(id)arg2;
- (_Bool)gestureRecognizerShouldBegin:(id)arg1;
- (struct CGSize)preferredContentSizeInModalPresentationViewController:(id)arg1 keyboardHeight:(double)arg2 limitSize:(struct CGSize)arg3;
- (double)expandBottomHeight;
- (void)didHideModalPresentationViewController:(id)arg1;
- (_Bool)ignoreCheckTabBar;
- (void)hideWithAnimated:(_Bool)arg1 completion:(CDUnknownBlockType)arg2;
- (void)showWithAnimated:(_Bool)arg1 completion:(CDUnknownBlockType)arg2;
- (void)traitCollectionDidChange:(id)arg1;
- (void)show;
- (void)recognizeFirstScrollView;
- (void)viewDidLayoutSubviews;
- (void)windowDidTransitionToSize:(struct CGSize)arg1;
- (_Bool)shouldRecognizeOtherScrollView;
- (_Bool)shouldUseEffectView;
- (double)maxContentWidth;
- (double)bgViewCornerRadius;
- (void)initSubviews;
- (void)updateLayout;
- (_Bool)prefersStatusBarHidden;
- (void)checkIfShouldShowGlobalEntranceInViewController:(id)arg1;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)didInitialize;
- (void)initContentViewSubviews;
- (void)initHeaderViewSubviews;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

