//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "WBViewController.h"

#import "UITextFieldDelegate-Protocol.h"

@class NSMutableArray, NSString, UIImageView, UILabel, UITextField, UIView, UIVisualEffectView, WBPlaygroundSwitchGuideView, WBUIKeyboardManager, YYAnimatedImageView;

@interface WBPlaygroundViewController : WBViewController <UITextFieldDelegate>
{
    UIView *_textFieldWrapper;
    UITextField *_textField;
    UIView *_guideView;
    double _guideBottomMargin;
    UIView *_bubbleView;
    double _bubbleLeft;
    UIView *_arrowView;
    double _arrowCenterX;
    _Bool _showed;
    _Bool _step3;
    UILabel *_title2;
    YYAnimatedImageView *_image2;
    UILabel *_title3;
    UIImageView *_image3;
    UIVisualEffectView *_blurView;
    NSMutableArray *_captainzhuLayoutBlocks;
    _Bool _showStep2;
    _Bool _updateTextViewActiveTime;
    _Bool _fromActiveDetection;
    _Bool _hidesTextField;
    _Bool _isFloatingKeyboard;
    _Bool _pluginNotActiveAtFirst;
    _Bool _forceShowSwitchGuide;
    CDUnknownBlockType _callback;
    WBUIKeyboardManager *_uikeyboardManager;
    WBPlaygroundSwitchGuideView *_switchGuideView;
}

+ (id)findActionInMenu:(id)arg1 identifier:(id)arg2;
+ (void)showSoftwareKeyboard;
+ (void)playWith:(id)arg1 hidesTextField:(_Bool)arg2 fromActiveDetection:(_Bool)arg3 forceShowSwitchGuide:(_Bool)arg4 updateTextViewActiveTime:(_Bool)arg5 callback:(CDUnknownBlockType)arg6;
+ (void)playWith:(id)arg1 callback:(CDUnknownBlockType)arg2;
- (void).cxx_destruct;
@property(nonatomic) _Bool forceShowSwitchGuide; // @synthesize forceShowSwitchGuide=_forceShowSwitchGuide;
@property(retain, nonatomic) WBPlaygroundSwitchGuideView *switchGuideView; // @synthesize switchGuideView=_switchGuideView;
@property(retain, nonatomic) WBUIKeyboardManager *uikeyboardManager; // @synthesize uikeyboardManager=_uikeyboardManager;
@property(nonatomic) _Bool pluginNotActiveAtFirst; // @synthesize pluginNotActiveAtFirst=_pluginNotActiveAtFirst;
@property(nonatomic) _Bool isFloatingKeyboard; // @synthesize isFloatingKeyboard=_isFloatingKeyboard;
@property(copy, nonatomic) CDUnknownBlockType callback; // @synthesize callback=_callback;
@property(nonatomic) _Bool hidesTextField; // @synthesize hidesTextField=_hidesTextField;
@property(nonatomic) _Bool fromActiveDetection; // @synthesize fromActiveDetection=_fromActiveDetection;
@property(nonatomic) _Bool updateTextViewActiveTime; // @synthesize updateTextViewActiveTime=_updateTextViewActiveTime;
@property(nonatomic) _Bool showStep2; // @synthesize showStep2=_showStep2;
- (void)keyboardDidHide:(id)arg1;
- (void)handleKeyboardWillHide:(id)arg1;
- (void)appDidEnterBackground:(id)arg1;
- (void)keyboardWillShowOrHide:(id)arg1;
- (void)dismiss;
- (void)dismissWithAnimated:(_Bool)arg1 completion:(CDUnknownBlockType)arg2;
- (_Bool)textFieldShouldReturn:(id)arg1;
- (void)report:(id)arg1;
- (void)inputModeStateDidChange;
- (void)showViewOnKeyboard;
- (id)findSubViewOfKind:(id)arg1 inView:(id)arg2;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (void)presentWith:(id)arg1;
- (id)initWithHidesTextField:(_Bool)arg1 fromActiveDetection:(_Bool)arg2 forceShowSwitchGuide:(_Bool)arg3 updateTextViewActiveTime:(_Bool)arg4 callback:(CDUnknownBlockType)arg5;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (void)didMoveToParentViewController:(id)arg1;
- (void)viewDidLayoutSubviews;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

