//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray, NSMutableArray, NSMutableDictionary;

@interface WBPluginSettingSyncManager : NSObject
{
    char *_bits;
    NSMutableArray *_toolbarFuncs;
    NSArray *_secKeyboards;
    _Bool _transacting;
    NSMutableDictionary *_tempAppOperations;
}

+ (id)allocWithZone:(struct _NSZone *)arg1;
+ (id)sharedInstance;
- (void).cxx_destruct;
@property(retain, nonatomic) NSArray *secKeyboards;
- (void)setToolbarFunc:(unsigned long long)arg1 enabled:(_Bool)arg2;
- (void)showKeyboardCustomToolbar;
- (_Bool)canSetToolbarFunc:(unsigned long long)arg1 enabled:(_Bool)arg2;
- (_Bool)isToolbarFuncEnabled:(unsigned long long)arg1;
- (_Bool)boolForKey:(int)arg1;
- (void)_updateSyncKeyAndSave;
- (void)updateSyncKeyAndSave;
- (void)activeTempAppOperations;
- (void)setBool:(_Bool)arg1 forKey:(int)arg2;
- (void)commit;
- (void)beginTransaction;
- (void)saveBits;
- (_Bool)handlePluginOpenURLParameters:(id)arg1;
- (_Bool)reload;
- (id)init;

@end

