//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIControl.h>

@class NSMutableArray, NSString, UIImageView, UILabel, UIView;

@interface WBPlayButton : UIControl
{
    UIImageView *_icon;
    UILabel *_label;
    UIView *_highlightMask;
    NSMutableArray *_captainzhuLayoutBlocks;
    CDUnknownBlockType _captainzhuLayoutFitBlock;
    NSString *_title;
}

- (void).cxx_destruct;
@property(copy, nonatomic) NSString *title; // @synthesize title=_title;
- (void)setIconWithName:(id)arg1;
- (void)setContainerBackgroundColor:(id)arg1;
- (void)setTitleColor:(id)arg1;
- (void)setTitleFont:(id)arg1;
- (id)init;
- (void)willMoveToSuperview:(id)arg1;
- (void)sizeToFit;
- (void)layoutSubviews;

@end

