//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "WBSettingBitSwitchBaseController.h"

@interface WBPluginSettingToolbarFuncSwitchController : WBSettingBitSwitchBaseController
{
    unsigned long long _func;
}

+ (id)withFunc:(unsigned long long)arg1 on:(CDUnknownBlockType)arg2 off:(CDUnknownBlockType)arg3;
+ (id)withFunc:(unsigned long long)arg1;
- (_Bool)currentBoolValue;
- (void)onValueChanged;
- (id)initWithFunc:(unsigned long long)arg1 on:(CDUnknownBlockType)arg2 off:(CDUnknownBlockType)arg3;

@end

