//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "WBCodingObject.h"

@class NSArray;

@interface WBPluginSettingsObject : WBCodingObject
{
    char *_toolbarFuncs;
    char *_secKeyboards;
    NSArray *_toolbarFuncs_object;
    NSArray *_secKeyboards_object;
    unsigned char _operationsSyncKey;
    char *_bits;
    char *_bitVersions;
}

+ (void)setDefaultValueBlock:(CDUnknownBlockType)arg1;
+ (CDUnknownBlockType)defaultValueBlock;
+ (char *)bitsFromString:(id)arg1;
+ (id)stringFromBits:(char *)arg1;
+ (id)diffBits:(char *)arg1 otherBits:(char *)arg2;
+ (void)setBool:(_Bool)arg1 forKey:(int)arg2 fromBit:(char *)arg3;
+ (_Bool)boolForKey:(int)arg1 fromBit:(char *)arg2;
+ (id)descriptionForBit:(char *)arg1;
+ (id)defaultValuesMapper;
+ (void)setDefaultValueForBoolItemBlock:(CDUnknownBlockType)arg1;
+ (CDUnknownBlockType)defaultValueForBoolItemBlock;
+ (unsigned long long)properties:(const struct WBCodingProperty **)arg1;
- (void).cxx_destruct;
@property(nonatomic) unsigned char operationsSyncKey; // @synthesize operationsSyncKey=_operationsSyncKey;
@property(nonatomic) char *bitVersions; // @synthesize bitVersions=_bitVersions;
@property(nonatomic) char *bits; // @synthesize bits=_bits;
- (id)defaultValueForKey:(id)arg1;
@property(retain, nonatomic) NSArray *secKeyboards;
@property(retain, nonatomic) NSArray *toolbarFuncs;
- (id)bitsToString;
- (void)setBool:(_Bool)arg1 forKey:(int)arg2;
- (_Bool)boolForKey:(int)arg1;
- (id)diffBits:(char *)arg1;
- (void)copyBit:(char *)arg1;
- (id)description;
- (_Bool)writeToFile:(id)arg1 atomically:(_Bool)arg2;
- (void)checkBitsVerionUpdate;
- (id)initWithContentsOfFile:(id)arg1 dataUpdated:(_Bool *)arg2;

@end

