//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSDictionary, NSMutableDictionary, NSString, WBFileCreationListener;
@protocol OS_dispatch_source;

@interface WBPreferences : NSObject
{
    NSMutableDictionary *_dit;
    struct _opaque_pthread_rwlock_t _lock;
    NSString *_filePath;
    NSString *_folderPath;
    _Bool _delaying;
    NSMutableDictionary *_containers;
    NSDictionary *_defaultValuesMapper;
    _Bool _needsReloadOnFileCreation;
    NSObject<OS_dispatch_source> *_fileSource;
    WBFileCreationListener *_folderListener;
    _Bool _reloadFromDiskAutomatically;
    _Bool _useNSEncoding;
}

+ (id)defaultValuesMapper;
+ (id)objectForKey:(id)arg1;
+ (void)setObject:(id)arg1 forKey:(id)arg2;
+ (void)addPreferenceDidReloadFromFileObserver:(id)arg1;
+ (void)addPreferenceChangeObserver:(id)arg1 forKeySelector:(SEL)arg2;
+ (id)folderPath;
+ (id)fileName;
+ (void)save;
+ (void)reset;
+ (void)reload;
+ (void)sync;
+ (void)initialize;
+ (_Bool)reloadFromDiskAutomatically;
+ (id)classesForUnarchivedObject;
- (void).cxx_destruct;
- (void)onFileChange;
- (void)cancelListenForFileChange;
- (_Bool)listenForFileChange;
- (void)_addPreferenceChangeObserver:(id)arg1 keySelector:(SEL)arg2;
- (id)fullFilePath;
@property(nonatomic) _Bool _BOOL;
@property(nonatomic) unsigned long long _NSUInteger;
@property(nonatomic) long long _NSInteger;
@property(nonatomic) double _CGFloat;
@property(retain, nonatomic) NSObject *_NSObject;
- (void)save;
- (void)_save;
- (void)_reload;
- (id)init;
- (id)description;

@end

