//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "WBOneViewController.h"

@class NSArray, NSMutableArray;

@interface WBPrivacyViewController : WBOneViewController
{
    NSArray *_options;
    NSMutableArray *_captainzhuLayoutBlocks;
}

- (void).cxx_destruct;
- (void)check:(unsigned long long)arg1;
- (void)optionChanged:(unsigned long long)arg1;
- (void)viewDidLoad;
- (id)barColor;
- (id)titleColor;
- (void)didMoveToParentViewController:(id)arg1;
- (void)viewDidLayoutSubviews;

@end

