//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface WBQueueStore : NSObject
{
}

+ (id)cacheSyncQueue;
+ (id)defaultQueue;
+ (id)userInteractiveQueue;

@end

