//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIView.h>

@class NSArray, UIButton, UILabel;

@interface WBRatingEntranceView : UIView
{
    CDUnknownBlockType _didTapButtonBlock;
    UILabel *_label;
    UIButton *_button;
    NSArray *_starViews;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSArray *starViews; // @synthesize starViews=_starViews;
@property(retain, nonatomic) UIButton *button; // @synthesize button=_button;
@property(retain, nonatomic) UILabel *label; // @synthesize label=_label;
@property(copy, nonatomic) CDUnknownBlockType didTapButtonBlock; // @synthesize didTapButtonBlock=_didTapButtonBlock;
- (void)layoutSubviews;
- (void)handleTapButton:(id)arg1;
- (void)initSubviews;
- (id)init;

@end

