//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class FMDatabase, NSOperationQueue;

@interface WBRCTFeedbackManager : NSObject
{
    FMDatabase *_db;
    double _uploadLogsTimestamp;
    NSOperationQueue *_uploadLogsQueue;
}

+ (void)createPaths;
+ (id)messageDBPath;
+ (id)feedbackDir;
+ (id)sharedInstance;
- (void).cxx_destruct;
@property(retain, nonatomic) NSOperationQueue *uploadLogsQueue; // @synthesize uploadLogsQueue=_uploadLogsQueue;
@property(nonatomic) double uploadLogsTimestamp; // @synthesize uploadLogsTimestamp=_uploadLogsTimestamp;
@property(retain, nonatomic) FMDatabase *db; // @synthesize db=_db;
- (void)initUploadLogsQueue;
- (void)notifyPluginToUploadLogs;
- (void)uploadProcessExitLogsIfNeeded;
- (void)markNeedUploadProcessExitLogs;
- (void)uploadLogsIfNeeded;
- (void)removeAllData;
- (id)readMessgeWithUniqId:(long long)arg1;
- (void)updateOrInsertMessage:(id)arg1 uniqId:(long long)arg2;
- (void)saveMessages:(id)arg1;
- (void)createDB;
- (id)init;

@end

