//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMutableDictionary;
@protocol OS_dispatch_queue;

@interface WBRCTAssetPickerFileHelper : NSObject
{
    NSMutableDictionary *_items;
    NSObject<OS_dispatch_queue> *_queue;
}

+ (id)sharedInstance;
- (void).cxx_destruct;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *queue; // @synthesize queue=_queue;
@property(retain, nonatomic) NSMutableDictionary *items; // @synthesize items=_items;
- (void)removeUnusedFile;
- (void)removeOldDirIfNeeded;
- (void)updateState:(id)arg1 forKey:(id)arg2;
- (void)addItem:(id)arg1 forKey:(id)arg2;
- (void)_writeToFile;
- (void)writeToFile;
- (void)readFromFile;
- (id)filePath;
- (id)init;

@end

