//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIView.h>

@class NSDictionary, NSString, QMUIEmptyView, WBRCTRootView;
@protocol WBRCTRootViewWrapperDelegate;

@interface WBRCTRootViewWrapper : UIView
{
    WBRCTRootView *_rootView;
    long long _cannotReloadIfUsing;
    id <WBRCTRootViewWrapperDelegate> _delegate;
    NSString *_bundleLoaderKey;
    NSString *_bundleName;
    NSString *_moduleName;
    NSString *_forceReloadScene;
    NSDictionary *_initialProperties;
    long long _rnAppId;
    QMUIEmptyView *_emptyView;
    double _beginLoadTimestamp;
}

- (void).cxx_destruct;
@property(nonatomic) double beginLoadTimestamp; // @synthesize beginLoadTimestamp=_beginLoadTimestamp;
@property(retain, nonatomic) QMUIEmptyView *emptyView; // @synthesize emptyView=_emptyView;
@property(nonatomic) long long rnAppId; // @synthesize rnAppId=_rnAppId;
@property(retain, nonatomic) NSDictionary *initialProperties; // @synthesize initialProperties=_initialProperties;
@property(copy, nonatomic) NSString *forceReloadScene; // @synthesize forceReloadScene=_forceReloadScene;
@property(copy, nonatomic) NSString *moduleName; // @synthesize moduleName=_moduleName;
@property(copy, nonatomic) NSString *bundleName; // @synthesize bundleName=_bundleName;
@property(copy, nonatomic) NSString *bundleLoaderKey; // @synthesize bundleLoaderKey=_bundleLoaderKey;
@property(nonatomic) __weak id <WBRCTRootViewWrapperDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) long long cannotReloadIfUsing; // @synthesize cannotReloadIfUsing=_cannotReloadIfUsing;
@property(retain, nonatomic) WBRCTRootView *rootView; // @synthesize rootView=_rootView;
- (id)curBundleLoader;
- (void)_addObservers;
- (void)_removeLiveReloadObservers;
- (void)_addLiveReloadObservers;
- (void)layoutEmptyView;
- (void)showEmptyViewWithLoadingView;
- (void)_rctRetryForError;
- (void)_rctDidEncounterFatalError;
- (void)hideEmptyView;
- (void)showEmptyView;
- (void)initEmptyViewIfNeeded;
- (void)_removeRootView;
- (void)_reloadBundleForPatchWithVersion:(id)arg1;
- (void)_rctWillReload;
- (void)layoutSubviews;
- (void)_initRootView;
- (void)_trySyncPatchConfigAndBundle;
- (void)_trySyncPatchWithBundleName;
- (_Bool)decideForceLoadDesignatedBundle:(id)arg1 nativeProperties:(id)arg2;
- (id)initWithBridge:(id)arg1 moduleName:(id)arg2 bundleName:(id)arg3 bundleLoaderKey:(id)arg4 initialProperties:(id)arg5 nativeProperties:(id)arg6;

@end

