//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "RCTRootView.h"

@class NSString;

@interface WBRCTRootView : RCTRootView
{
    long long _rnAppId;
    long long _cannotReloadIfUsing;
    NSString *_bundleLoaderKey;
    struct CGSize _rctSize;
}

+ (long long)genRNAppId;
- (void).cxx_destruct;
@property(copy, nonatomic) NSString *bundleLoaderKey; // @synthesize bundleLoaderKey=_bundleLoaderKey;
@property(nonatomic) struct CGSize rctSize; // @synthesize rctSize=_rctSize;
@property(nonatomic) long long cannotReloadIfUsing; // @synthesize cannotReloadIfUsing=_cannotReloadIfUsing;
@property(nonatomic) long long rnAppId; // @synthesize rnAppId=_rnAppId;
- (void)javaScriptDidLoad:(id)arg1;
- (void)dealloc;
- (id)curBundleLoader;
- (id)initWithBridge:(id)arg1 moduleName:(id)arg2 initialProperties:(id)arg3;
- (id)initWithBridge:(id)arg1 moduleName:(id)arg2 bundleLoaderKey:(id)arg3 initialProperties:(id)arg4;

@end

