//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSDictionary, NSMutableDictionary, NSString, RACSubject;

@interface WBRCTBundleManager : NSObject
{
    NSString *_sandboxRootDir;
    RACSubject *_syncItemsSubject;
    NSMutableDictionary *_configForAllVid;
    NSDictionary *_rnBundleInfo;
    NSMutableDictionary *_bundleName2Assets;
    NSMutableDictionary *_assetsSubPaths2FullPath;
}

+ (void)reportRNPatchWithAction:(id)arg1 status:(long long)arg2 bundleName:(id)arg3 bundleVersion:(long long)arg4 moduleName:(id)arg5;
+ (id)bundleFileNameInDirectory:(id)arg1;
+ (_Bool)isDevMode;
+ (id)sharedInstance;
+ (id)dictionaryWithBundleItems:(id)arg1;
- (void).cxx_destruct;
@property(retain, nonatomic) NSMutableDictionary *assetsSubPaths2FullPath; // @synthesize assetsSubPaths2FullPath=_assetsSubPaths2FullPath;
@property(retain, nonatomic) NSMutableDictionary *bundleName2Assets; // @synthesize bundleName2Assets=_bundleName2Assets;
@property(retain, nonatomic) NSDictionary *rnBundleInfo; // @synthesize rnBundleInfo=_rnBundleInfo;
@property(retain, nonatomic) NSMutableDictionary *configForAllVid; // @synthesize configForAllVid=_configForAllVid;
@property(readonly, nonatomic) RACSubject *syncItemsSubject; // @synthesize syncItemsSubject=_syncItemsSubject;
@property(readonly, copy, nonatomic) NSString *sandboxRootDir; // @synthesize sandboxRootDir=_sandboxRootDir;
- (id)allCGIRelatedDirName;
- (id)allPatchBundles;
- (id)availableBundlesInfos;
- (_Bool)isIgnoreFilename:(id)arg1;
- (id)cgiRelatedBundlePathWithModuleName:(id)arg1;
- (id)_moduleBundlePathWithName:(id)arg1 patchVersion:(id)arg2;
- (id)configVersionWithBundleName:(id)arg1;
- (id)qualifiedVersionsWithBundleName:(id)arg1;
- (id)patchVersionForBundleName:(id)arg1;
- (id)moduleBundlePathWithName:(id)arg1;
- (id)platformBundlePath;
- (id)bundleInfoWithName:(id)arg1 isCGIRelated:(_Bool)arg2;
- (id)assetPatchFullPathWithSubPath:(id)arg1;
- (void)updateAssetsSubPaths;
- (void)willLoadBundleWithName:(id)arg1 patchVersion:(long long)arg2 bundlePath:(id)arg3;
- (void)prepareForAllFiles;
- (id)_dirWithBusinessGroup:(id)arg1;
- (id)cgiRelatedDir;
- (id)patchDir;
- (id)buildinDir;
- (id)longAppVersion;
- (id)buildinBunldesAndAssets;
- (id)allBuildinBundleNames;
- (id)allBuildinBusinessBundleNames;
- (void)saveCurrentConfig:(id)arg1;
- (id)currentConfig;
- (id)discoverListModuleName;
- (id)_discoverListIgnoreBundleName;
- (id)discoverListBundleName;
- (id)fixedLottieFileUri:(id)arg1;
- (id)init;
- (id)moveUnzipResultToDestWithUnzipPath:(id)arg1 withItem:(id)arg2;
- (id)unzipWithZipPath:(id)arg1 withItem:(id)arg2;
- (_Bool)checkMD5WithFilePath:(id)arg1 md5sum:(id)arg2;
- (id)downloadBundleWithItem:(id)arg1;
- (void)downloadItemFailed:(id)arg1;
- (void)didSuccessDownloadItem:(id)arg1;
- (void)didPatchAlreadyExist:(id)arg1;
- (id)startSyncItem:(id)arg1;
- (void)syncPatchBundleItemWithBundleName:(id)arg1;
- (void)didFailSyncConfig;
- (void)didSuccessSyncConfig:(id)arg1;
- (void)sync;

@end

