//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "RCTBridgeDelegate-Protocol.h"

@class NSMutableArray, NSMutableDictionary, NSMutableSet, NSString, RACDisposable, RACSubject, RCTBridge, WBRCTBundle;

@interface WBRCTBundleLoader : NSObject <RCTBridgeDelegate>
{
    _Bool _envSetted;
    _Bool _needReload;
    _Bool _reloading;
    RCTBridge *_bridge;
    NSMutableArray *_bundles;
    WBRCTBundle *_loadingBundle;
    RACSubject *_subject;
    RACDisposable *_disposable;
    WBRCTBundle *_platformBundle;
    NSMutableSet *_bundleLoadedFlags;
    NSMutableDictionary *_activeModules;
    NSMutableDictionary *_bundleZipsMD5;
    NSMutableDictionary *_bundlesMD5;
    NSMutableDictionary *_forceUpdateBundles;
    NSMutableDictionary *_rollbackBundles;
    NSMutableArray *_execSourceInfo;
    NSMutableSet *_cannotReloadIfUsingObjects;
    unsigned long long _bundleIndex;
}

+ (id)sharedInstance;
- (void).cxx_destruct;
@property(nonatomic) _Bool reloading; // @synthesize reloading=_reloading;
@property(nonatomic) unsigned long long bundleIndex; // @synthesize bundleIndex=_bundleIndex;
@property(nonatomic) _Bool needReload; // @synthesize needReload=_needReload;
@property(retain, nonatomic) NSMutableSet *cannotReloadIfUsingObjects; // @synthesize cannotReloadIfUsingObjects=_cannotReloadIfUsingObjects;
@property(retain, nonatomic) NSMutableArray *execSourceInfo; // @synthesize execSourceInfo=_execSourceInfo;
@property(retain, nonatomic) NSMutableDictionary *rollbackBundles; // @synthesize rollbackBundles=_rollbackBundles;
@property(retain, nonatomic) NSMutableDictionary *forceUpdateBundles; // @synthesize forceUpdateBundles=_forceUpdateBundles;
@property(retain, nonatomic) NSMutableDictionary *bundlesMD5; // @synthesize bundlesMD5=_bundlesMD5;
@property(retain, nonatomic) NSMutableDictionary *bundleZipsMD5; // @synthesize bundleZipsMD5=_bundleZipsMD5;
@property(nonatomic) _Bool envSetted; // @synthesize envSetted=_envSetted;
@property(retain, nonatomic) NSMutableDictionary *activeModules; // @synthesize activeModules=_activeModules;
@property(retain, nonatomic) NSMutableSet *bundleLoadedFlags; // @synthesize bundleLoadedFlags=_bundleLoadedFlags;
@property(retain, nonatomic) WBRCTBundle *platformBundle; // @synthesize platformBundle=_platformBundle;
@property(retain, nonatomic) RACDisposable *disposable; // @synthesize disposable=_disposable;
@property(retain, nonatomic) RACSubject *subject; // @synthesize subject=_subject;
@property(retain, nonatomic) WBRCTBundle *loadingBundle; // @synthesize loadingBundle=_loadingBundle;
@property(readonly, nonatomic) NSMutableArray *bundles; // @synthesize bundles=_bundles;
@property(retain, nonatomic) RCTBridge *bridge; // @synthesize bridge=_bridge;
- (void)resetReloading;
- (void)handleJSDidReloadNotification:(id)arg1;
- (void)handleJSWillReloadNotification:(id)arg1;
- (void)handleJSDidFailToLoadNotification:(id)arg1;
- (void)handleJSDidLoadNotification:(id)arg1;
- (_Bool)isCurrentPatchVersionFreshed:(id)arg1;
- (_Bool)checkBlacklistHasActive:(id)arg1;
- (void)refreshBundleItemToCurrentPatchVersion;
- (void)checkBundleVersionShouldReload;
- (void)addObservers;
- (_Bool)bridge:(id)arg1 didNotFindModule:(id)arg2;
- (id)sourceURLForBridge:(id)arg1;
- (id)shouldForceUpdateBundleWithBundleName:(id)arg1;
- (void)setRollbackVersions:(id)arg1 forBundleName:(id)arg2;
- (void)setBundleToForceUpdate:(id)arg1 forcedPatchVersion:(id)arg2;
- (void)setModuleToUnactive:(id)arg1;
- (void)setModuleToActive:(id)arg1;
- (id)allExecSourceInfo;
- (void)clearExecSourceInfo;
- (void)appendExecSourceWithBundle:(id)arg1 md5:(id)arg2;
- (id)bundleMD5WithName:(id)arg1;
- (void)markBundleMD5:(id)arg1 bundleName:(id)arg2;
- (id)bundleZipMD5WithName:(id)arg1;
- (void)markBundleZipMD5:(id)arg1 bundleName:(id)arg2;
- (id)bundleWithName:(id)arg1;
- (_Bool)isBundleLoaded:(id)arg1 andBundleMD5NotSame:(id)arg2;
- (_Bool)isBundleLoaded:(id)arg1;
- (void)subscribeBundle:(id)arg1 subscriber:(id)arg2;
- (id)loadBundleSignal:(id)arg1;
- (void)unloadBundle:(id)arg1;
- (void)loadBundle:(id)arg1;
- (void)didReceiveReloadCommand;
- (void)removeCannotReloadObject:(id)arg1;
- (void)addCannotReloadObject:(id)arg1;
- (void)reloadIfBundleChanged:(id)arg1;
- (void)reloadIfNeeded;
- (void)reload;
- (void)invalidateSubject;
- (void)initSubjectIfNeeded;
- (void)invalidateBridge;
- (void)initBridgeIfNeeded;
- (void)invalidate;
- (void)setup;
- (void)setupRNCommonFunction;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

