//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface WBRCTBusinessLoader : NSObject
{
}

+ (id)unzipBusinessBundle:(id)arg1 name:(id)arg2;
+ (_Bool)isUnzipBundleDirValid:(id)arg1;
+ (id)parseDownloadBundleFromBase64:(id)arg1 bundleName:(id)arg2;
+ (_Bool)isBundleLoaded:(id)arg1;
+ (void)loadCGIRelatedBundleWithModuleName:(id)arg1;
+ (id)bundleWithName:(id)arg1;
+ (void)loadBundleWithName:(id)arg1;
+ (void)loadBundles;

@end

