//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class WBRCTRootViewWrapper;

@protocol WBRCTRootViewWrapperDelegate <NSObject>
- (void)rootViewWrapperDidCreateRootView:(WBRCTRootViewWrapper *)arg1;
@end

