//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray, NSString;

@interface WBRCTBundleManagerItem : NSObject
{
    NSString *_bundleName;
    NSString *_bundleUrl;
    NSString *_bundleVersion;
    NSString *_md5sum;
    NSString *_forcedPatchVersion;
    NSArray *_rollbackVersions;
    id _beginDownloadTimeToken;
}

- (void).cxx_destruct;
@property(retain, nonatomic) id beginDownloadTimeToken; // @synthesize beginDownloadTimeToken=_beginDownloadTimeToken;
@property(retain, nonatomic) NSArray *rollbackVersions; // @synthesize rollbackVersions=_rollbackVersions;
@property(copy, nonatomic) NSString *forcedPatchVersion; // @synthesize forcedPatchVersion=_forcedPatchVersion;
@property(copy, nonatomic) NSString *md5sum; // @synthesize md5sum=_md5sum;
@property(copy, nonatomic) NSString *bundleVersion; // @synthesize bundleVersion=_bundleVersion;
@property(copy, nonatomic) NSString *bundleUrl; // @synthesize bundleUrl=_bundleUrl;
@property(copy, nonatomic) NSString *bundleName; // @synthesize bundleName=_bundleName;
- (id)versionPath;
- (id)initWithDictionary:(id)arg1;

@end

