//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "WBViewController.h"

#import "WBRCTRootViewWrapperDelegate-Protocol.h"

@class NSDictionary, NSMutableDictionary, NSString, RCTScrollView, UIColor, UIImage, UIView, WBRCTRootViewWrapper;

@interface WBRCTBaseViewController : WBViewController <WBRCTRootViewWrapperDelegate>
{
    _Bool _canPostGlobalExposedNotification;
    _Bool _underneathNavigationBar;
    _Bool _usesStatusBarLightStyle;
    _Bool _hideStatusBar;
    _Bool _hideNavigationBar;
    _Bool _rct_shadow;
    _Bool _isPreparingSharing;
    _Bool _poppingToNavigationBarExistingViewController;
    _Bool _hasMount;
    _Bool _shouldDetectMuteStatus;
    NSString *_bundleName;
    NSString *_moduleName;
    WBRCTRootViewWrapper *_rctRootView;
    NSDictionary *_initialProperties;
    UIImage *_navigationBackgroundImage;
    UIImage *_navigationBackgroundImageLight;
    UIImage *_navigationBackgroundImageDark;
    UIView *_navigationTitleView;
    double _navigationTitleViewPositionLeft;
    NSString *_navigationTitle;
    UIColor *_navigationBarBackgroundColor;
    UIColor *_navigationBarBackgroundColorLight;
    UIColor *_navigationBarBackgroundColorDark;
    RCTScrollView *_scrollView1;
    RCTScrollView *_scrollView2;
    RCTScrollView *_targetScrollView;
    double _notEqualStartTime;
    long long _notEqualCount;
    long long _checkDeadLoopCount;
    NSDictionary *_initialNativeProperties;
    NSMutableDictionary *_nativeProps;
    id _beginLoadTimeToken;
    long long _hasExposedWhenMount;
    long long _muteStatus;
    long long _mutedCallbackCount;
}

- (void).cxx_destruct;
@property(nonatomic) long long mutedCallbackCount; // @synthesize mutedCallbackCount=_mutedCallbackCount;
@property(nonatomic) _Bool shouldDetectMuteStatus; // @synthesize shouldDetectMuteStatus=_shouldDetectMuteStatus;
@property(nonatomic) long long muteStatus; // @synthesize muteStatus=_muteStatus;
@property(nonatomic) long long hasExposedWhenMount; // @synthesize hasExposedWhenMount=_hasExposedWhenMount;
@property(nonatomic) _Bool hasMount; // @synthesize hasMount=_hasMount;
@property(retain, nonatomic) id beginLoadTimeToken; // @synthesize beginLoadTimeToken=_beginLoadTimeToken;
@property(nonatomic) _Bool poppingToNavigationBarExistingViewController; // @synthesize poppingToNavigationBarExistingViewController=_poppingToNavigationBarExistingViewController;
@property(retain, nonatomic) NSMutableDictionary *nativeProps; // @synthesize nativeProps=_nativeProps;
@property(nonatomic) _Bool isPreparingSharing; // @synthesize isPreparingSharing=_isPreparingSharing;
@property(retain, nonatomic) NSDictionary *initialNativeProperties; // @synthesize initialNativeProperties=_initialNativeProperties;
@property(nonatomic) long long checkDeadLoopCount; // @synthesize checkDeadLoopCount=_checkDeadLoopCount;
@property(nonatomic) long long notEqualCount; // @synthesize notEqualCount=_notEqualCount;
@property(nonatomic) double notEqualStartTime; // @synthesize notEqualStartTime=_notEqualStartTime;
@property(nonatomic) __weak RCTScrollView *targetScrollView; // @synthesize targetScrollView=_targetScrollView;
@property(nonatomic) __weak RCTScrollView *scrollView2; // @synthesize scrollView2=_scrollView2;
@property(nonatomic) __weak RCTScrollView *scrollView1; // @synthesize scrollView1=_scrollView1;
@property(nonatomic) _Bool rct_shadow; // @synthesize rct_shadow=_rct_shadow;
@property(nonatomic) _Bool hideNavigationBar; // @synthesize hideNavigationBar=_hideNavigationBar;
@property(retain, nonatomic) UIColor *navigationBarBackgroundColorDark; // @synthesize navigationBarBackgroundColorDark=_navigationBarBackgroundColorDark;
@property(retain, nonatomic) UIColor *navigationBarBackgroundColorLight; // @synthesize navigationBarBackgroundColorLight=_navigationBarBackgroundColorLight;
@property(retain, nonatomic) UIColor *navigationBarBackgroundColor; // @synthesize navigationBarBackgroundColor=_navigationBarBackgroundColor;
@property(nonatomic) _Bool hideStatusBar; // @synthesize hideStatusBar=_hideStatusBar;
@property(nonatomic) _Bool usesStatusBarLightStyle; // @synthesize usesStatusBarLightStyle=_usesStatusBarLightStyle;
@property(copy, nonatomic) NSString *navigationTitle; // @synthesize navigationTitle=_navigationTitle;
@property(nonatomic) double navigationTitleViewPositionLeft; // @synthesize navigationTitleViewPositionLeft=_navigationTitleViewPositionLeft;
@property(retain, nonatomic) UIView *navigationTitleView; // @synthesize navigationTitleView=_navigationTitleView;
@property(retain, nonatomic) UIImage *navigationBackgroundImageDark; // @synthesize navigationBackgroundImageDark=_navigationBackgroundImageDark;
@property(retain, nonatomic) UIImage *navigationBackgroundImageLight; // @synthesize navigationBackgroundImageLight=_navigationBackgroundImageLight;
@property(retain, nonatomic) UIImage *navigationBackgroundImage; // @synthesize navigationBackgroundImage=_navigationBackgroundImage;
@property(nonatomic) _Bool underneathNavigationBar; // @synthesize underneathNavigationBar=_underneathNavigationBar;
@property(nonatomic) _Bool canPostGlobalExposedNotification; // @synthesize canPostGlobalExposedNotification=_canPostGlobalExposedNotification;
@property(retain, nonatomic) NSDictionary *initialProperties; // @synthesize initialProperties=_initialProperties;
@property(retain, nonatomic) WBRCTRootViewWrapper *rctRootView; // @synthesize rctRootView=_rctRootView;
@property(copy, nonatomic) NSString *moduleName; // @synthesize moduleName=_moduleName;
@property(copy, nonatomic) NSString *bundleName; // @synthesize bundleName=_bundleName;
- (void)soundDidPlayWithDuration:(double)arg1;
- (void)detectMuteStatus;
- (void)stopMonitorMuteStatus;
- (void)startMonitorMuteStatus;
- (_Bool)canShowGuideForNavigateKeyboardScene;
- (id)colorWithColorString:(id)arg1;
- (_Bool)stringRepresentsEmpty:(id)arg1;
- (_Bool)stringRepresentsTransparent:(id)arg1;
- (void)rootViewWrapperDidCreateRootView:(id)arg1;
- (void)rootViewDidChangeIntrinsicSize:(id)arg1;
- (void)postNotificationName:(id)arg1 params:(id)arg2;
- (void)_handleExchangeEvent;
- (void)showRewardAd;
- (void)willPopInNavigationControllerWithAnimated:(_Bool)arg1;
- (void)previewSharingForTopListWithCategoryId:(id)arg1;
- (void)showRCTNoteConfigControlWithParams:(id)arg1;
- (void)showMoreOperationWithParams:(id)arg1;
- (void)handleRankShareAction;
- (void)setupNavigationItems;
- (void)windowDidTransitionToSize:(struct CGSize)arg1;
- (void)tryPostDimensionNotification;
- (double)insetBottomWithTabBar;
- (_Bool)shouldHideTabBar;
- (_Bool)prefersStatusBarHidden;
- (_Bool)preferredNavigationBarHidden;
- (id)qmui_navigationBarBarTintColor;
- (id)qmui_navigationBarShadowImage;
- (_Bool)forceEnableInteractivePopGestureRecognizer;
- (void)postGlobalExposedNotification:(_Bool)arg1;
- (void)handleDidMountEvent:(id)arg1;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)_rctRetryForError;
- (void)_rctDidEncounterFatalError;
- (void)_rctWillReload;
- (void)addRCTRootSubview;
- (void)afterInitRootView;
- (void)_rctInitRootView;
- (void)applyNewNativeProps:(id)arg1;
- (void)handleInvalidateBridgeNotification:(id)arg1;
- (void)exitCurrentView:(_Bool)arg1;
- (void)handlePerformNativeActionsNotification:(id)arg1;
- (void)handleSetNativePropsNotification:(id)arg1;
- (long long)rnAppId;
- (void)handleRNSetNavigationPropsNotification:(id)arg1;
- (void)handleRNSetNavigationTitleNotification:(id)arg1;
- (void)handleOnJSEventNotification:(id)arg1;
- (void)_rctAddObservers;
- (void)rctInit;
- (void)viewDidLayoutSubviews;
- (void)removeMarkRecover;
- (void)markRecover;
- (void)viewDidLoad;
- (void)setUpBackgroundColorIfNeeded;
- (void)setUpUIInitialProperties;
- (id)curBundleLoader;
- (void)dealloc;
- (id)initWithBundleName:(id)arg1 moduleName:(id)arg2 initialProperties:(id)arg3 nativeProperties:(id)arg4;
- (id)initWithBundleName:(id)arg1 moduleName:(id)arg2 initialProperties:(id)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

