//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "RCTBridgeModule-Protocol.h"

@class NSString, RCTBridge, RCTBundleManager, RCTCallableJSModules, RCTModuleRegistry, RCTViewRegistry;
@protocol OS_dispatch_queue;

@interface WBRCTNavigator : NSObject <RCTBridgeModule>
{
}

+ (const struct RCTMethodInfo *)__rct_export__66378;
+ (const struct RCTMethodInfo *)__rct_export__21377;
+ (const struct RCTMethodInfo *)__rct_export__16376;
+ (void)load;
+ (id)moduleName;
- (void)navigateToURL:(id)arg1;
- (void)_navigateWithName:(id)arg1 model:(id)arg2 info:(id)arg3;
- (void)navigateWithInfo:(id)arg1 model:(id)arg2 info:(id)arg3;
- (void)navigate:(id)arg1 model:(id)arg2;

// Remaining properties
@property(readonly, nonatomic) __weak RCTBridge *bridge;
@property(nonatomic) __weak RCTBundleManager *bundleManager;
@property(nonatomic) __weak RCTCallableJSModules *callableJSModules;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly, nonatomic) NSObject<OS_dispatch_queue> *methodQueue;
@property(nonatomic) __weak RCTModuleRegistry *moduleRegistry;
@property(readonly) Class superclass;
@property(nonatomic) __weak RCTViewRegistry *viewRegistry_DEPRECATED;

@end

