//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "RCTEventEmitter.h"

#import "RCTBridgeModule-Protocol.h"
#import "WBPreferencesFileObserving-Protocol.h"
#import "WBPreferencesObserving-Protocol.h"

@class NSObject, NSString, RCTBridge, RCTBundleManager, RCTCallableJSModules, RCTModuleRegistry, RCTViewRegistry, WBRCTAssetPicker;
@protocol OS_dispatch_queue;

@interface WBRCTManager : RCTEventEmitter <WBPreferencesObserving, WBPreferencesFileObserving, RCTBridgeModule>
{
    _Bool _canShowPluginNotFoundAlert;
    _Bool _canShowPluginNotFoundTips;
    _Bool _canShowRatingEntranceView;
    _Bool _isRecording;
    WBRCTAssetPicker *_assetPicker;
}

+ (id)assetCacheNameForUrl:(id)arg1;
+ (id)assetCacheDir;
+ (void)downloadForPreviewWithUrl:(id)arg1 successBlock:(CDUnknownBlockType)arg2 failBlock:(CDUnknownBlockType)arg3;
+ (void)downloadWithUrl:(id)arg1 successBlock:(CDUnknownBlockType)arg2 failBlock:(CDUnknownBlockType)arg3;
+ (id)keyboardsSettingInfo;
+ (id)mainSettingInfo;
+ (unsigned long long)voiceInputTypetoNative:(long long)arg1;
+ (long long)voiceInputTypetoRN:(unsigned long long)arg1;
+ (id)initialPropertiesWithNavigateParams:(id)arg1;
+ (void)navigateToRCTScene:(id)arg1;
+ (id)controllerForNavigateToRCTScene:(id)arg1;
+ (void)navigateKeyboardScene:(id)arg1;
+ (_Bool)isKeyboardShown:(_Bool)arg1;
+ (_Bool)canShowGuideForNavigateKeyboardScene;
+ (id)appInfoWithChatClientInfo:(_Bool)arg1;
+ (const struct RCTMethodInfo *)__rct_export__2521;
+ (const struct RCTMethodInfo *)__rct_export__2300;
+ (id)moduleInstance;
+ (void)load;
+ (id)moduleName;
- (void).cxx_destruct;
@property(retain, nonatomic) WBRCTAssetPicker *assetPicker; // @synthesize assetPicker=_assetPicker;
@property(nonatomic) _Bool isRecording; // @synthesize isRecording=_isRecording;
@property(nonatomic) _Bool canShowRatingEntranceView; // @synthesize canShowRatingEntranceView=_canShowRatingEntranceView;
@property(nonatomic) _Bool canShowPluginNotFoundTips; // @synthesize canShowPluginNotFoundTips=_canShowPluginNotFoundTips;
@property(nonatomic) _Bool canShowPluginNotFoundAlert; // @synthesize canShowPluginNotFoundAlert=_canShowPluginNotFoundAlert;
- (void)resolveAssetSource:(id)arg1 resolver:(CDUnknownBlockType)arg2 rejecter:(CDUnknownBlockType)arg3;
- (void)hideStatusBar:(id)arg1 resolver:(CDUnknownBlockType)arg2 rejecter:(CDUnknownBlockType)arg3;
- (void)setGroupInfo:(id)arg1 resolver:(CDUnknownBlockType)arg2 rejecter:(CDUnknownBlockType)arg3;
- (void)getGroupInfo:(id)arg1 resolver:(CDUnknownBlockType)arg2 rejecter:(CDUnknownBlockType)arg3;
- (void)uploadLogs:(id)arg1;
- (void)uploadAsset:(id)arg1 resolver:(CDUnknownBlockType)arg2 rejecter:(CDUnknownBlockType)arg3;
- (void)preview:(id)arg1;
- (void)loadAsset:(id)arg1 resolver:(CDUnknownBlockType)arg2 rejecter:(CDUnknownBlockType)arg3;
- (void)pickImageWithResolver:(CDUnknownBlockType)arg1 rejecter:(CDUnknownBlockType)arg2;
- (void)selectAssets:(id)arg1 resolver:(CDUnknownBlockType)arg2 rejecter:(CDUnknownBlockType)arg3;
- (void)saveChatMessage:(id)arg1 resolver:(CDUnknownBlockType)arg2 rejecter:(CDUnknownBlockType)arg3;
- (void)getChatMessage:(id)arg1 resolver:(CDUnknownBlockType)arg2 rejecter:(CDUnknownBlockType)arg3;
- (void)getChatList:(id)arg1 resolver:(CDUnknownBlockType)arg2 rejecter:(CDUnknownBlockType)arg3;
- (void)getAiChatCopywriterInfo:(id)arg1 resolver:(CDUnknownBlockType)arg2 rejecter:(CDUnknownBlockType)arg3;
- (void)getNetworkInfo:(id)arg1 resolver:(CDUnknownBlockType)arg2 rejecter:(CDUnknownBlockType)arg3;
- (void)saveImage:(id)arg1 resolver:(CDUnknownBlockType)arg2 rejecter:(CDUnknownBlockType)arg3;
- (void)openClipboardSetting:(id)arg1;
- (void)openFullAccessSetting:(id)arg1;
- (void)clearPasteBoard:(id)arg1 resolver:(CDUnknownBlockType)arg2 rejecter:(CDUnknownBlockType)arg3;
- (void)showBottomSheet:(id)arg1;
- (void)informKeyboardProcessEvent:(id)arg1;
- (void)getKeyboardsSettingInfo:(id)arg1 resolver:(CDUnknownBlockType)arg2 rejecter:(CDUnknownBlockType)arg3;
- (void)setKeyboardsSettingInfo:(id)arg1 resolver:(CDUnknownBlockType)arg2 rejecter:(CDUnknownBlockType)arg3;
- (void)setMainSettingInfo:(id)arg1 resolver:(CDUnknownBlockType)arg2 rejecter:(CDUnknownBlockType)arg3;
- (void)_getMainSettingInfoOnMainThread:(id)arg1 resolver:(CDUnknownBlockType)arg2 rejecter:(CDUnknownBlockType)arg3;
- (void)getMainSettingInfo:(id)arg1 resolver:(CDUnknownBlockType)arg2 rejecter:(CDUnknownBlockType)arg3;
- (void)getItem:(id)arg1 resolver:(CDUnknownBlockType)arg2 rejecter:(CDUnknownBlockType)arg3;
- (void)setItem:(id)arg1 resolver:(CDUnknownBlockType)arg2 rejecter:(CDUnknownBlockType)arg3;
- (void)setNavigationProps:(id)arg1;
- (void)onJSEvent:(id)arg1;
- (void)showTips:(id)arg1;
- (void)navigateBack:(id)arg1;
- (void)navigateScene:(id)arg1;
- (void)canSwitchInCurrentKeyboard:(id)arg1 resolver:(CDUnknownBlockType)arg2 rejecter:(CDUnknownBlockType)arg3;
- (void)navigateKeyboardScene:(id)arg1;
- (void)sound:(id)arg1;
- (void)shake:(id)arg1;
- (void)busReport:(id)arg1;
- (void)request:(id)arg1 resolver:(CDUnknownBlockType)arg2 rejecter:(CDUnknownBlockType)arg3;
- (void)getSafeAreaInset:(id)arg1 resolver:(CDUnknownBlockType)arg2 rejecter:(CDUnknownBlockType)arg3;
- (void)getAppInfo:(id)arg1 resolver:(CDUnknownBlockType)arg2 rejecter:(CDUnknownBlockType)arg3;
- (void)callJSMethodWithSubevent:(id)arg1 params:(id)arg2;
- (void)callNativeMethodWithCallback:(id)arg1 params:(id)arg2 resolver:(CDUnknownBlockType)arg3 rejecter:(CDUnknownBlockType)arg4;
- (void)callNativeMethodNoCallback:(id)arg1 params:(id)arg2;
- (void)handleDidBecomeActiveNotification:(id)arg1;
- (void)handleWillResignActiveNotification:(id)arg1;
- (void)handleDidEnterBackgroundNotification:(id)arg1;
- (void)handleExposedPageWithParams:(id)arg1;
- (void)stopObserving;
- (void)handleAppSettingUpdated:(id)arg1;
- (void)startObserving;
- (id)supportedEvents;

// Remaining properties
@property(readonly, nonatomic) __weak RCTBridge *bridge;
@property(nonatomic) __weak RCTBundleManager *bundleManager;
@property(nonatomic) __weak RCTCallableJSModules *callableJSModules;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly, nonatomic) NSObject<OS_dispatch_queue> *methodQueue;
@property(nonatomic) __weak RCTModuleRegistry *moduleRegistry;
@property(readonly) Class superclass;
@property(nonatomic) __weak RCTViewRegistry *viewRegistry_DEPRECATED;

@end

