//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "PHPickerViewControllerDelegate-Protocol.h"
#import "UIImagePickerControllerDelegate-Protocol.h"
#import "UINavigationControllerDelegate-Protocol.h"

@class NSString;

@interface WBRCTAssetPicker : NSObject <PHPickerViewControllerDelegate, UIImagePickerControllerDelegate, UINavigationControllerDelegate>
{
    long long _selectionLimit;
    CDUnknownBlockType _didSelectAssets;
}

- (void).cxx_destruct;
@property(copy, nonatomic) CDUnknownBlockType didSelectAssets; // @synthesize didSelectAssets=_didSelectAssets;
@property(nonatomic) long long selectionLimit; // @synthesize selectionLimit=_selectionLimit;
- (void)imagePickerController:(id)arg1 didFinishPickingMediaWithInfo:(id)arg2;
- (void)processPickedVideoInfo:(id)arg1 completionBlock:(CDUnknownBlockType)arg2;
- (void)processPickedImageInfo:(id)arg1 completionBlock:(CDUnknownBlockType)arg2;
- (void)picker:(id)arg1 didFinishPicking:(id)arg2;
- (void)showUploadVideoInvalidTips:(id)arg1;
- (void)compressVideoWithURL:(id)arg1 isTmpFile:(_Bool)arg2 completionBlock:(CDUnknownBlockType)arg3;
- (id)videoSizeWithURL:(id)arg1;
- (void)processPickedResults:(id)arg1 completionBlock:(CDUnknownBlockType)arg2;
- (id)cacheAssetWithPath:(id)arg1 type:(id)arg2;
- (void)show;
- (id)randomPathWithOriginName:(id)arg1 type:(id)arg2;
- (id)cachePathWithType:(id)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

