//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString, NSURL, RACDisposable;

@interface WBRCTBundle : NSObject
{
    _Bool _isCGIRelatedBundle;
    NSString *_bundleName;
    NSURL *_bundleURL;
    NSString *_bundleZipMD5;
    long long _patchVersion;
    RACDisposable *_didLoadDisposable;
    RACDisposable *_bundleDidFailToLoadDisposable;
    id _beginDownloadTimeToken;
}

- (void).cxx_destruct;
@property(retain, nonatomic) id beginDownloadTimeToken; // @synthesize beginDownloadTimeToken=_beginDownloadTimeToken;
@property(nonatomic) __weak RACDisposable *bundleDidFailToLoadDisposable; // @synthesize bundleDidFailToLoadDisposable=_bundleDidFailToLoadDisposable;
@property(nonatomic) __weak RACDisposable *didLoadDisposable; // @synthesize didLoadDisposable=_didLoadDisposable;
@property(nonatomic) _Bool isCGIRelatedBundle; // @synthesize isCGIRelatedBundle=_isCGIRelatedBundle;
@property(nonatomic) long long patchVersion; // @synthesize patchVersion=_patchVersion;
@property(retain, nonatomic) NSString *bundleZipMD5; // @synthesize bundleZipMD5=_bundleZipMD5;
@property(retain, nonatomic) NSURL *bundleURL; // @synthesize bundleURL=_bundleURL;
@property(retain, nonatomic) NSString *bundleName; // @synthesize bundleName=_bundleName;
- (id)description;
- (_Bool)isEqual:(id)arg1;
- (void)bundleDidFailToLoad:(id)arg1;
- (void)bundleDidLoad;
- (void)retryLoadForError;

@end

