//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "MMService.h"

#import "MMServiceProtocol-Protocol.h"

@class NSString;

@interface WBRedDotMgr : MMService <MMServiceProtocol>
{
}

- (void)addHasNewStatusChangeObserver:(id)arg1 selector:(SEL)arg2;
@property(readonly, nonatomic) _Bool hasRedDot;
- (void)checkRedDot;
- (void)addObservers;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

