//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIView.h>

#import "RCTInvalidating-Protocol.h"

@class NSArray, NSNumber, NSString, RCTBridge, RCTTouchHandler, WBReactModalHostViewController;
@protocol WHReactModalHostViewInteractor;

@interface WBReactModalHostView : UIView <RCTInvalidating>
{
    _Bool _animateHide;
    _Bool _canSwipeBack;
    _Bool _mask;
    _Bool _hideStatusBar;
    _Bool _isPresented;
    _Bool _enableAnimation;
    NSString *_animationType;
    CDUnknownBlockType _willClose;
    CDUnknownBlockType _onRequestClose;
    CDUnknownBlockType _onShow;
    CDUnknownBlockType _didShow;
    NSNumber *_inputAction;
    id <WHReactModalHostViewInteractor> _delegate;
    NSArray *_supportedOrientations;
    CDUnknownBlockType _onOrientationChange;
    RCTBridge *_bridge;
    WBReactModalHostViewController *_hostViewController;
    RCTTouchHandler *_touchHandler;
    UIView *_reactSubview;
    long long _lastKnownOrientation;
}

- (void).cxx_destruct;
@property(nonatomic) _Bool enableAnimation; // @synthesize enableAnimation=_enableAnimation;
@property(nonatomic) long long lastKnownOrientation; // @synthesize lastKnownOrientation=_lastKnownOrientation;
@property(retain, nonatomic) UIView *reactSubview; // @synthesize reactSubview=_reactSubview;
@property(retain, nonatomic) RCTTouchHandler *touchHandler; // @synthesize touchHandler=_touchHandler;
@property(retain, nonatomic) WBReactModalHostViewController *hostViewController; // @synthesize hostViewController=_hostViewController;
@property(nonatomic) _Bool isPresented; // @synthesize isPresented=_isPresented;
@property(nonatomic) __weak RCTBridge *bridge; // @synthesize bridge=_bridge;
@property(copy, nonatomic) CDUnknownBlockType onOrientationChange; // @synthesize onOrientationChange=_onOrientationChange;
@property(copy, nonatomic) NSArray *supportedOrientations; // @synthesize supportedOrientations=_supportedOrientations;
@property(nonatomic) __weak id <WHReactModalHostViewInteractor> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) _Bool hideStatusBar; // @synthesize hideStatusBar=_hideStatusBar;
@property(retain, nonatomic) NSNumber *inputAction; // @synthesize inputAction=_inputAction;
@property(nonatomic) _Bool mask; // @synthesize mask=_mask;
@property(nonatomic) _Bool canSwipeBack; // @synthesize canSwipeBack=_canSwipeBack;
@property(nonatomic) _Bool animateHide; // @synthesize animateHide=_animateHide;
@property(copy, nonatomic) CDUnknownBlockType didShow; // @synthesize didShow=_didShow;
@property(copy, nonatomic) CDUnknownBlockType onShow; // @synthesize onShow=_onShow;
@property(copy, nonatomic) CDUnknownBlockType onRequestClose; // @synthesize onRequestClose=_onRequestClose;
@property(copy, nonatomic) CDUnknownBlockType willClose; // @synthesize willClose=_willClose;
@property(copy, nonatomic) NSString *animationType; // @synthesize animationType=_animationType;
- (void)dismissHostViewController;
- (void)showHostViewController;
- (unsigned long long)supportedOrientationsMask;
- (void)invalidate;
- (void)didMoveToSuperview;
- (void)didMoveToWindow;
- (void)didUpdateReactSubviews;
- (void)removeReactSubview:(id)arg1;
- (void)insertReactSubview:(id)arg1 atIndex:(long long)arg2;
- (void)notifyForOrientationChange;
- (void)notifyForBoundsChange:(struct CGRect)arg1;
- (void)notifyForContentBoundsChange:(struct CGRect)arg1;
- (id)initWithBridge:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

