//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@protocol WBBusinessRequestProtocol;

@interface WBReportSampleRatioMgr : NSObject
{
    id <WBBusinessRequestProtocol> _requestHandler;
    double _lastFetchedTimeInterval;
}

+ (id)sharedInstance;
- (void).cxx_destruct;
@property(nonatomic) double lastFetchedTimeInterval; // @synthesize lastFetchedTimeInterval=_lastFetchedTimeInterval;
@property(nonatomic) __weak id <WBBusinessRequestProtocol> requestHandler; // @synthesize requestHandler=_requestHandler;
- (int)sampleRatioForReportID:(id)arg1;
- (void)processFetchedData:(id)arg1;
- (void)fetchRatio;
- (id)init;

@end

