//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "WBPlayerPanelController.h"

@class NSString, UIView;

@interface WBReactModalHostViewController : WBPlayerPanelController
{
    struct CGRect _lastViewFrame;
    long long _preferredStatusBarStyle;
    CDUnknownBlockType _contentFrameDidChangeBlock;
    CDUnknownBlockType _boundsDidChangeBlock;
    unsigned long long _supportedInterfaceOrientations;
    NSString *_animationType;
    UIView *_hostContentView;
    struct CGRect _contentFrame;
    struct CGRect _lastContentViewFrame;
}

- (void).cxx_destruct;
@property(nonatomic) struct CGRect lastContentViewFrame; // @synthesize lastContentViewFrame=_lastContentViewFrame;
@property(nonatomic) struct CGRect lastViewFrame; // @synthesize lastViewFrame=_lastViewFrame;
@property(retain, nonatomic) UIView *hostContentView; // @synthesize hostContentView=_hostContentView;
@property(nonatomic) struct CGRect contentFrame; // @synthesize contentFrame=_contentFrame;
@property(copy, nonatomic) NSString *animationType; // @synthesize animationType=_animationType;
@property(nonatomic) unsigned long long supportedInterfaceOrientations; // @synthesize supportedInterfaceOrientations=_supportedInterfaceOrientations;
@property(copy, nonatomic) CDUnknownBlockType boundsDidChangeBlock; // @synthesize boundsDidChangeBlock=_boundsDidChangeBlock;
@property(copy, nonatomic) CDUnknownBlockType contentFrameDidChangeBlock; // @synthesize contentFrameDidChangeBlock=_contentFrameDidChangeBlock;
- (struct CGRect)whPanelContentViewFrame:(struct CGRect)arg1;
- (id)whPanelContentView;
- (double)expandBottomHeight;
- (long long)preferredStatusBarStyle;
- (void)viewDidLayoutSubviews;
- (void)viewDidLoad;
- (id)init;

@end

