//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "RCTViewManager.h"

#import "WHReactModalHostViewInteractor-Protocol.h"

@class NSPointerArray, NSString;

@interface WBReactModalHostViewManager : RCTViewManager <WHReactModalHostViewInteractor>
{
    NSPointerArray *_hostViews;
}

+ (id)propConfig_hideStatusBar;
+ (id)propConfig_inputAction;
+ (id)propConfig_mask;
+ (id)propConfig_canSwipeBack;
+ (id)propConfig_animateHide;
+ (id)propConfig_didShow;
+ (id)propConfig_onShow;
+ (id)propConfig_onRequestClose;
+ (id)propConfig_willClose;
+ (id)propConfig_animationType;
+ (void)load;
+ (id)moduleName;
- (void).cxx_destruct;
@property(retain, nonatomic) NSPointerArray *hostViews; // @synthesize hostViews=_hostViews;
- (void)dismissHostView:(id)arg1 withViewController:(id)arg2 animated:(_Bool)arg3;
- (void)presentHostView:(id)arg1 withViewController:(id)arg2 animated:(_Bool)arg3;
- (void)invalidate;
- (id)view;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

