//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "WBKeyView.h"

#import "WBInputStateUpdateProtocol-Protocol.h"

@class NSString;

@interface WBReturnKeyView : WBKeyView <WBInputStateUpdateProtocol>
{
    NSString *_title;
    _Bool _brightStyle;
}

- (void).cxx_destruct;
- (id)highlightedTintColorForCurrentState;
- (id)normalTintColorForCurrentState;
- (id)borderColorForCurrentState;
- (id)highlightedBgForCurrentState;
- (id)normalBgColorForCurrentState;
- (id)mainTextForCurrentState;
- (void)updateReturnStyle;
- (void)returnActionTypeDidChange;
- (void)didAttachHosting;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

