//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "WBDictFullUpdateTask.h"

@interface WBResDictFullUpdateTask : WBDictFullUpdateTask
{
}

- (void)URLSession:(id)arg1 downloadTask:(id)arg2 didFinishDownloadingToURL:(id)arg3;
- (_Bool)handleUnzipForFull:(int)arg1 extraInfo:(id)arg2 errorMsg:(id *)arg3 updatedPath:(id *)arg4 unzipped:(_Bool *)arg5;
- (_Bool)checkNeedDL:(id)arg1;

@end

