//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "WBPreferencesFileObserving-Protocol.h"

@class NSDictionary, NSString;
@protocol OS_dispatch_queue;

@interface WBRfixManager : NSObject <WBPreferencesFileObserving>
{
    _Bool _needKillMe;
    _Bool _patchApplied;
    _Bool _standaloneEnabled;
    NSString *_uin;
    NSString *_rfixVersion;
    NSObject<OS_dispatch_queue> *_operationQueue;
    long long _initOption;
    NSDictionary *_downloadResourceInfo;
    NSDictionary *_patchWillStopInfo;
    double _lastRequestTime;
    double _nextRequestTime;
    double _lastSideRequestTime;
    double _nextSideRequestTime;
}

+ (id)sharedInstance;
- (void).cxx_destruct;
@property(nonatomic) double nextSideRequestTime; // @synthesize nextSideRequestTime=_nextSideRequestTime;
@property(nonatomic) double lastSideRequestTime; // @synthesize lastSideRequestTime=_lastSideRequestTime;
@property(nonatomic) double nextRequestTime; // @synthesize nextRequestTime=_nextRequestTime;
@property(nonatomic) double lastRequestTime; // @synthesize lastRequestTime=_lastRequestTime;
@property(retain, nonatomic) NSDictionary *patchWillStopInfo; // @synthesize patchWillStopInfo=_patchWillStopInfo;
@property(retain, nonatomic) NSDictionary *downloadResourceInfo; // @synthesize downloadResourceInfo=_downloadResourceInfo;
@property(nonatomic) _Bool standaloneEnabled; // @synthesize standaloneEnabled=_standaloneEnabled;
@property(nonatomic) _Bool patchApplied; // @synthesize patchApplied=_patchApplied;
@property(nonatomic) _Bool needKillMe; // @synthesize needKillMe=_needKillMe;
@property(nonatomic) long long initOption; // @synthesize initOption=_initOption;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *operationQueue; // @synthesize operationQueue=_operationQueue;
@property(copy, nonatomic) NSString *rfixVersion; // @synthesize rfixVersion=_rfixVersion;
@property(copy, nonatomic) NSString *uin; // @synthesize uin=_uin;
- (void)onPatchWillStopNotification:(id)arg1;
- (void)onDownloadNotification:(id)arg1;
- (void)onApplyNotification:(id)arg1;
- (id)appGroupFolderRootPath;
- (id)localFolderRootPath;
- (id)debugInfoForSideRequest;
- (id)debugInfo;
- (id)debugInfoForResourceDict:(id)arg1;
- (void)onAppSettingsChanged;
- (void)preferencesDidReloadFromFile:(Class)arg1;
- (_Bool)needKillMeForPatchWillStop:(id)arg1 featureNeedKillMe:(_Bool)arg2;
- (_Bool)needKillMeForDownload:(id)arg1 featureNeedKillMe:(_Bool)arg2;
- (_Bool)checkUpdateNeedKillMeForPatchWillStop;
- (_Bool)checkUpdateNeedKillMeForDownload;
- (void)checkUpdateNeedKillMe;
- (double)feauteUpdateIntervalForCurrenrProcess;
- (double)feauteUpdateIntervalForPlugin;
- (double)feauteUpdateIntervalForMainApp;
- (_Bool)featureNeedKillMe;
- (_Bool)featureShouldinitializeForMainApp;
- (_Bool)featureShouldinitializeForPlugin;
- (void)sideRequest;
- (void)refresh;
- (void)updateUin:(id)arg1;
- (long long)loadLocalPatch:(id)arg1;
- (void)setUpBuglyHotFixVersion;
- (void)setUp:(long long)arg1;
- (_Bool)sideRequestEnabled:(long long)arg1;
- (_Bool)currentProcessPatchEnabled:(long long)arg1;
- (_Bool)alreadyInitialized:(long long)arg1;
- (void)checkSetUpAndUpdateNeedKillMe;
- (void)checkSetUp;
- (void)updateRfixNetworkEnable;
- (void)performActionInQueue:(CDUnknownBlockType)arg1;
- (id)appKey:(id)arg1;
- (id)appId:(id)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

