//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "RAFTLogProtocol-Protocol.h"

@class NSString;

@interface WBRifxLoggerImpl : NSObject <RAFTLogProtocol>
{
}

- (void)flushLog;
- (void)setLogLevel:(long long)arg1;
- (void)log:(long long)arg1 tags:(id)arg2 file:(const char *)arg3 func:(const char *)arg4 line:(int)arg5 msg:(id)arg6;
- (void)log:(long long)arg1 tag:(id)arg2 file:(const char *)arg3 func:(const char *)arg4 line:(int)arg5 msg:(id)arg6;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

