//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "WBKeyView.h"

#import "WBInputStateUpdateProtocol-Protocol.h"

@class NSString;
@protocol WBKeyViewHostingProtocol, WBPanelProxy;

@interface WBRuleKeyView : WBKeyView <WBInputStateUpdateProtocol>
{
    id <WBKeyViewHostingProtocol> _hosting;
    id <WBPanelProxy> _panel;
    long long _styleRule;
    unsigned long long _keyStyleIndex;
    unsigned long long _letterTextShiftRule;
}

- (void).cxx_destruct;
@property(nonatomic) unsigned long long letterTextShiftRule; // @synthesize letterTextShiftRule=_letterTextShiftRule;
@property(nonatomic) unsigned long long keyStyleIndex; // @synthesize keyStyleIndex=_keyStyleIndex;
@property(nonatomic) long long styleRule; // @synthesize styleRule=_styleRule;
- (void)updateAppSettings;
- (void)updateKeyAppearance;
- (_Bool)shouldPerformLongPressLaunch;
- (void)decideKeyStyleIndex;
- (void)decideAndUpdateKeyStyle;
- (id)normalBgColorForCurrentState;
- (id)inputForNormalState;
- (id)highlightedBgForCurrentState;
- (id)highlightedImageForCurrentState;
- (id)normalImageImageForCurrentState;
- (id)mainTextFontForCurrentState;
- (id)upTextForCurrentState;
- (id)mainTextForCurrentState;
- (void)onVoiceInputControlStatusDidChange:(_Bool)arg1 finishedWordCnt:(long long)arg2;
- (void)hasAccessViewStateDidChange;
- (void)shiftStateDidChange;
- (void)panelLangDidChange;
- (void)enablePinyinInWubiKeyboardDidChange;
- (void)needsSemicolonKeyDidChange;
- (void)hasPendingInputTextDidChanged;
- (void)showingT9AtPendingInputDidChange;
- (void)registerPanelLangChangeEventIfNeeded;
- (void)registerVoiceInputEventIfNeeded;
- (void)registerWubiShiftEventIfNeeded;
- (void)registerShuangPinEventIfNeeded;
- (void)subviewsWillLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

