//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface WBSchemeManager : NSObject
{
}

+ (void)processAIChatWeb:(id)arg1;
+ (void)processStandaloneMode:(id)arg1;
+ (void)processShowFeedbackEggsModal:(id)arg1;
+ (void)processVoiceShowIconSetting:(id)arg1;
+ (void)processVoicePunctuationSetting:(id)arg1;
+ (void)processMainSetting:(id)arg1;
+ (void)processNavigateKeyboardScene:(id)arg1;
+ (void)processExperienceKeyboard:(id)arg1;
+ (void)processNetworkSetting:(id)arg1;
+ (void)processWeb:(id)arg1;
+ (void)processFeedback:(id)arg1;
+ (void)processRating:(id)arg1;
+ (void)showVC:(id)arg1 params:(id)arg2 insertVCs:(id)arg3;
+ (void)processDebug:(id)arg1;
+ (void)processAbout:(id)arg1;
+ (void)processHelpAndFeedback:(id)arg1;
+ (void)processPermissionAndPrivacySetting:(id)arg1;
+ (void)processPlusSetting:(id)arg1;
+ (void)processT9CustomSymbolSetting:(id)arg1;
+ (void)processSlideInputSetting:(id)arg1;
+ (void)processKeyboardAppearanceSetting:(id)arg1;
+ (void)processDisplaySetting:(id)arg1;
+ (void)processVibrateVolumeSetting:(id)arg1;
+ (void)processVoiceInputSetting:(id)arg1;
+ (void)processRCTView:(id)arg1;
+ (void)_handleSingleScheme:(id)arg1 insertVCs:(id)arg2;
+ (void)handleScheme:(id)arg1;

@end

