//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "WBSettingsViewController.h"

@class WBSettingsChoicesController;

@interface WBSettingWubiPlanViewController : WBSettingsViewController
{
    WBSettingsChoicesController *_planChoices;
}

- (void).cxx_destruct;
@property(retain, nonatomic) WBSettingsChoicesController *planChoices; // @synthesize planChoices=_planChoices;
- (void)selectDownloadedPlan:(unsigned long long)arg1;
- (void)viewDidLoad;
- (void)dealloc;
- (id)title;

@end

