//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "WBSettingsElement.h"

@class WBSettingBitSwitchController;

@interface WBSettingsElementWithSwitchController : WBSettingsElement
{
    WBSettingBitSwitchController *_switchController;
}

- (void).cxx_destruct;
@property(retain, nonatomic) WBSettingBitSwitchController *switchController; // @synthesize switchController=_switchController;
- (void)reloadData;

@end

