//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIView.h>

@class NSArray, NSMutableArray, UILabel;

@interface WBSettingsGroup : UIView
{
    NSArray *_elements;
    NSMutableArray *_tops;
    UIView *_customView;
    double _topOffset;
    UILabel *_label;
    CDUnknownBlockType _innerSizeChangeBlock;
}

+ (id)custom:(id)arg1;
+ (id)name:(id)arg1 elements:(id)arg2;
+ (id)elements:(id)arg1;
- (void).cxx_destruct;
@property(copy, nonatomic) CDUnknownBlockType innerSizeChangeBlock; // @synthesize innerSizeChangeBlock=_innerSizeChangeBlock;
@property(retain, nonatomic) UILabel *label; // @synthesize label=_label;
@property(nonatomic) double topOffset; // @synthesize topOffset=_topOffset;
- (void)setUserInteractionEnabled:(_Bool)arg1;
- (void)didHide;
- (void)hide;
- (void)willHide;
- (void)show;
- (void)willShow;
- (id)elements;
- (void)removeElementAtIndex:(long long)arg1;
- (void)appendElement:(id)arg1;
- (void)reloadData;
- (id)initWithCustomView:(id)arg1;
- (id)initWithElements:(id)arg1;

@end

