//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "WBKeyView.h"

@class UIImage;

@interface WBSecKeyboardKeyView : WBKeyView
{
    UIImage *_cachedNormalImageImage;
}

- (void).cxx_destruct;
- (id)normalImageImageForCurrentState;
- (id)combineImages;
- (void)panelLangDidChange;
- (void)subviewsWillLoad;
- (void)mainInputSettingDidChange;
- (void)didAttachHosting;

@end

