//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray, NSMutableDictionary, WBSettingsChoice;

@interface WBSettingsChoicesController : NSObject
{
    WBSettingsChoice *_chosen;
    NSMutableDictionary *_choices;
    CDUnknownBlockType _onChoose;
    CDUnknownBlockType _shouldChoose;
    NSArray *_elements;
}

+ (id)choices:(id)arg1 onChoose:(CDUnknownBlockType)arg2 shouldChoose:(CDUnknownBlockType)arg3;
+ (id)choices:(id)arg1 onChoose:(CDUnknownBlockType)arg2;
- (void).cxx_destruct;
@property(readonly, nonatomic) NSArray *elements; // @synthesize elements=_elements;
- (void)hideAllHint;
- (void)updateHint:(id)arg1 tag:(long long)arg2;
- (void)chooseTag:(long long)arg1;
- (id)initWithChoices:(id)arg1 onChoose:(CDUnknownBlockType)arg2 shouldChoose:(CDUnknownBlockType)arg3;

@end

