//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString, UIButton, UILabel, UIView;

@interface WBSettingsChoice : NSObject
{
    NSString *_title;
    NSString *_aDescription;
    long long _tag;
    UIButton *_checkMark;
    UILabel *_hintLabel;
    UIView *_rightContainerView;
}

+ (id)title:(id)arg1 description:(id)arg2 tag:(long long)arg3;
- (void).cxx_destruct;
@property(retain, nonatomic) UIView *rightContainerView; // @synthesize rightContainerView=_rightContainerView;
@property(retain, nonatomic) UILabel *hintLabel; // @synthesize hintLabel=_hintLabel;
@property(retain, nonatomic) UIButton *checkMark; // @synthesize checkMark=_checkMark;
@property(nonatomic) long long tag; // @synthesize tag=_tag;
@property(copy, nonatomic) NSString *aDescription; // @synthesize aDescription=_aDescription;
@property(copy, nonatomic) NSString *title; // @synthesize title=_title;
- (void)updateContainerViewFrame;
- (void)setMarkChecked:(_Bool)arg1;
- (void)setHitText:(id)arg1;
- (id)initWithTitle:(id)arg1 description:(id)arg2 tag:(long long)arg3;

@end

