//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIControl.h>

@class NSString, UIColor, UIFont, UIImage, UIImageView, UILabel, UIView;

@interface WBSettingItemView : UIControl
{
    UIImageView *_arrowImageView;
    CDUnknownBlockType _config;
    UIImage *_image;
    NSString *_title;
    UIColor *_titleColor;
    UIFont *_titleFont;
    double _titleLineheight;
    NSString *_subtitle;
    UIColor *_subtitleColor;
    UIFont *_subtitleFont;
    double _subtitleLineheight;
    double _spacingBetweenImageAndTitle;
    UIView *_accessoryView;
    UIView *_contentView;
    UIImageView *_imageView;
    UILabel *_titleLabel;
    UILabel *_subtitleLabel;
}

+ (id)itemWithConfig:(CDUnknownBlockType)arg1;
- (void).cxx_destruct;
@property(retain, nonatomic) UILabel *subtitleLabel; // @synthesize subtitleLabel=_subtitleLabel;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(retain, nonatomic) UIImageView *imageView; // @synthesize imageView=_imageView;
@property(retain, nonatomic) UIView *contentView; // @synthesize contentView=_contentView;
@property(retain, nonatomic) UIView *accessoryView; // @synthesize accessoryView=_accessoryView;
@property(nonatomic) double spacingBetweenImageAndTitle; // @synthesize spacingBetweenImageAndTitle=_spacingBetweenImageAndTitle;
@property(nonatomic) double subtitleLineheight; // @synthesize subtitleLineheight=_subtitleLineheight;
@property(retain, nonatomic) UIFont *subtitleFont; // @synthesize subtitleFont=_subtitleFont;
@property(retain, nonatomic) UIColor *subtitleColor; // @synthesize subtitleColor=_subtitleColor;
@property(copy, nonatomic) NSString *subtitle; // @synthesize subtitle=_subtitle;
@property(nonatomic) double titleLineheight; // @synthesize titleLineheight=_titleLineheight;
@property(retain, nonatomic) UIFont *titleFont; // @synthesize titleFont=_titleFont;
@property(retain, nonatomic) UIColor *titleColor; // @synthesize titleColor=_titleColor;
@property(copy, nonatomic) NSString *title; // @synthesize title=_title;
@property(retain, nonatomic) UIImage *image; // @synthesize image=_image;
@property(copy, nonatomic) CDUnknownBlockType config; // @synthesize config=_config;
- (void)setEnabled:(_Bool)arg1;
- (void)reload;
- (void)setHighlighted:(_Bool)arg1;
- (void)layoutSubviews;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)dealloc;

@end

