//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class UISwitch;

@interface WBSettingBitSwitchBaseController : NSObject
{
    UISwitch *_s;
    CDUnknownBlockType _on;
    CDUnknownBlockType _off;
}

- (void).cxx_destruct;
@property(copy, nonatomic) CDUnknownBlockType off; // @synthesize off=_off;
@property(copy, nonatomic) CDUnknownBlockType on; // @synthesize on=_on;
@property(readonly, nonatomic) UISwitch *s; // @synthesize s=_s;
- (void)reloadData;
- (_Bool)currentBoolValue;
- (void)toggle;
- (void)onValueChanged;
- (id)init;

@end

