//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIControl.h>

@class NSMutableArray, UILabel, UIView;

@interface WBSettingsElement : UIControl
{
    UILabel *_titleLabel;
    UILabel *_descLabel;
    UIView *_rightView;
    UIView *_bottomView;
    UILabel *_hintLabel;
    UIView *_highlightMask;
    CDUnknownBlockType _hint;
    CDUnknownBlockType _onClick;
    NSMutableArray *_captainzhuLayoutBlocks;
    CDUnknownBlockType _captainzhuLayoutFitBlock;
}

+ (id)title:(id)arg1 description:(id)arg2 rightView:(id)arg3 onClick:(CDUnknownBlockType)arg4;
+ (id)title:(id)arg1 rightView:(id)arg2 onClick:(CDUnknownBlockType)arg3;
+ (id)title:(id)arg1 description:(id)arg2 hint:(CDUnknownBlockType)arg3 onClick:(CDUnknownBlockType)arg4;
+ (id)title:(id)arg1 description:(id)arg2 onClick:(CDUnknownBlockType)arg3;
+ (id)title:(id)arg1 hint:(CDUnknownBlockType)arg2 onClick:(CDUnknownBlockType)arg3;
+ (id)title:(id)arg1 onClick:(CDUnknownBlockType)arg2;
+ (id)title:(id)arg1 description:(id)arg2 control:(id)arg3;
+ (id)title:(id)arg1 description:(id)arg2 bit:(int)arg3 on:(CDUnknownBlockType)arg4 off:(CDUnknownBlockType)arg5;
+ (id)title:(id)arg1 control:(id)arg2;
+ (id)title:(id)arg1 bit:(int)arg2 on:(CDUnknownBlockType)arg3 off:(CDUnknownBlockType)arg4;
+ (id)title:(id)arg1 bit:(int)arg2;
+ (void)setCompact:(_Bool)arg1;
- (void).cxx_destruct;
- (void)reloadData;
- (void)setUserInteractionEnabled:(_Bool)arg1;
- (void)onSettingsChanged;
- (void)update:(id)arg1;
- (void)setHighlighted:(_Bool)arg1;
- (void)doClick;
- (void)addBottom;
- (void)addTop;
- (id)initWithTitle:(id)arg1 description:(id)arg2 hint:(CDUnknownBlockType)arg3 rightView:(id)arg4 onClick:(CDUnknownBlockType)arg5;
- (void)willMoveToSuperview:(id)arg1;
- (void)sizeToFit;
- (void)layoutSubviews;

@end

