//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "WBOneViewController.h"

@class NSArray, UIView;

@interface WBSettingsViewController : WBOneViewController
{
    struct unordered_set<unsigned long, std::hash<unsigned long>, std::equal_to<unsigned long>, std::allocator<unsigned long>> _hiddenGroupIndices;
    _Bool _loaded;
    UIView *_header;
    NSArray *_groups;
}

- (id).cxx_construct;
- (void).cxx_destruct;
@property(retain, nonatomic) NSArray *groups; // @synthesize groups=_groups;
@property(retain, nonatomic) UIView *header; // @synthesize header=_header;
- (_Bool)groupIsShown:(unsigned long long)arg1;
- (void)hideGroupWithoutAnimationFrom:(unsigned long long)arg1 to:(unsigned long long)arg2;
- (void)hideGroupWithAnimationFrom:(unsigned long long)arg1 to:(unsigned long long)arg2;
- (void)hideGroupFrom:(unsigned long long)arg1 to:(unsigned long long)arg2 animated:(_Bool)arg3;
- (void)showGroupWithoutAnimationFrom:(unsigned long long)arg1 to:(unsigned long long)arg2;
- (void)showGroupWithAnimationFrom:(unsigned long long)arg1 to:(unsigned long long)arg2;
- (void)showGroupFrom:(unsigned long long)arg1 to:(unsigned long long)arg2 animated:(_Bool)arg3;
- (void)loadGroups;
- (void)reloadGroups;
- (void)viewDidLoad;
- (id)init;

@end

