//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface WBShareUtils : NSObject
{
}

+ (id)JSONObjectWithString:(id)arg1;
+ (void)moveAndMapDataFileWithTempURL:(id)arg1 fileSizeLimit:(long long)arg2 completion:(CDUnknownBlockType)arg3;
+ (id)openFilePaths;
+ (id)printStorageSizeWithPath:(id)arg1 totalSize:(unsigned long long *)arg2;
+ (id)visitDir:(id)arg1 level:(long long)arg2 maxLevel:(long long)arg3 count:(long long *)arg4 maxCount:(long long)arg5 totalSize:(unsigned long long *)arg6 minSize:(long long)arg7;
+ (id)formatFileSize:(unsigned long long)arg1;
+ (id)parametersFromURL:(id)arg1;
+ (_Bool)isCurrentSystemLowerThanVersion:(id)arg1;
+ (_Bool)isCurrentSystemAtLeastVersion:(id)arg1;
+ (long long)compareSystemVersion:(id)arg1 toVersion:(id)arg2;

@end

