//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "WBSettingsViewController.h"

@class WBSettingsChoicesController;

@interface WBSlideUpSettingsViewController : WBSettingsViewController
{
    WBSettingsChoicesController *_layoutController;
}

- (void).cxx_destruct;
- (void)viewDidLoad;
- (unsigned long long)currentSlideUpScheme;
- (id)title;

@end

