//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIView.h>

#import "UITextViewDelegate-Protocol.h"

@class NSString, UIButton, WBLabel, WBTextView;

@interface WBStandaloneModeNoNetWorkView : UIView <UITextViewDelegate>
{
    WBLabel *_mainTitleLabel;
    UIButton *_knownBtn;
    WBTextView *_networkAlertTextView;
}

- (void).cxx_destruct;
@property(retain, nonatomic) WBTextView *networkAlertTextView; // @synthesize networkAlertTextView=_networkAlertTextView;
@property(retain, nonatomic) UIButton *knownBtn; // @synthesize knownBtn=_knownBtn;
@property(retain, nonatomic) WBLabel *mainTitleLabel; // @synthesize mainTitleLabel=_mainTitleLabel;
- (_Bool)textView:(id)arg1 shouldInteractWithURL:(id)arg2 inRange:(struct _NSRange)arg3 interaction:(long long)arg4;
- (double)expandBottomHeight;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;
- (void)layoutSubviews;
- (void)initUI;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

