//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "WBPlayerPanelController.h"

@class WBStandaloneModeNoNetWorkView, WBStandaloneModeTipView;

@interface WBStandaloneModeTipViewController : WBPlayerPanelController
{
    CDUnknownBlockType _cancelAction;
    CDUnknownBlockType _confirmAction;
    WBStandaloneModeTipView *_tipView;
    WBStandaloneModeNoNetWorkView *_noNetworkView;
}

- (void).cxx_destruct;
@property(retain, nonatomic) WBStandaloneModeNoNetWorkView *noNetworkView; // @synthesize noNetworkView=_noNetworkView;
@property(retain, nonatomic) WBStandaloneModeTipView *tipView; // @synthesize tipView=_tipView;
@property(copy, nonatomic) CDUnknownBlockType confirmAction; // @synthesize confirmAction=_confirmAction;
@property(copy, nonatomic) CDUnknownBlockType cancelAction; // @synthesize cancelAction=_cancelAction;
- (double)maxContentWidth;
- (double)bgViewCornerRadius;
- (struct CGRect)whPanelContentViewFrame:(struct CGRect)arg1;
- (id)whPanelContentView;
- (void)didTapConfromAction:(id)arg1;
- (void)didTapCancelAction:(id)arg1;
- (void)viewDidLayoutSubviews;
- (void)dealloc;
- (void)viewDidLoad;
- (id)initWithNoNetWork;
- (id)initWithTitle:(id)arg1 subTitle:(id)arg2 cancelTitle:(id)arg3 confirmTitle:(id)arg4;

@end

