//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIView.h>

@class WBLabel;

@interface WBStandaloneModeDownloadingButton : UIView
{
    WBLabel *_mainLabel;
    WBLabel *_mainLabelForProcess;
    UIView *_processView;
    double _process;
    UIView *_bgView;
}

- (void).cxx_destruct;
@property(retain, nonatomic) UIView *bgView; // @synthesize bgView=_bgView;
@property(nonatomic) double process; // @synthesize process=_process;
@property(retain, nonatomic) UIView *processView; // @synthesize processView=_processView;
@property(retain, nonatomic) WBLabel *mainLabelForProcess; // @synthesize mainLabelForProcess=_mainLabelForProcess;
@property(retain, nonatomic) WBLabel *mainLabel; // @synthesize mainLabel=_mainLabel;
- (void)configWithMainTitle:(id)arg1 process:(double)arg2;
- (void)layoutSubviews;
- (id)initWithFrame:(struct CGRect)arg1;

@end

