//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIView.h>

@class UIImageView, WBLabel;

@interface WBStandaloneModeInfoCell : UIView
{
    WBLabel *_mainLabel;
    UIImageView *_iconImageView;
}

- (void).cxx_destruct;
@property(retain, nonatomic) UIImageView *iconImageView; // @synthesize iconImageView=_iconImageView;
@property(retain, nonatomic) WBLabel *mainLabel; // @synthesize mainLabel=_mainLabel;
- (void)configWithImage:(id)arg1 mainTitle:(id)arg2;
- (void)layoutSubviews;
- (id)initWithFrame:(struct CGRect)arg1;

@end

