//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIView.h>

@class WBLabel;

@interface WBStandaloneModePrepareButton : UIView
{
    WBLabel *_mainLabel;
    WBLabel *_subTitleLabel;
}

- (void).cxx_destruct;
@property(retain, nonatomic) WBLabel *subTitleLabel; // @synthesize subTitleLabel=_subTitleLabel;
@property(retain, nonatomic) WBLabel *mainLabel; // @synthesize mainLabel=_mainLabel;
- (void)configWithMainTitle:(id)arg1 subTitle:(id)arg2;
- (void)layoutSubviews;
- (id)initWithFrame:(struct CGRect)arg1;

@end

