//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "WBViewController.h"

@class CADisplayLink, NSArray, NSDictionary, UIButton, UIScrollView, UIView, WBStandaloneModeDoneButton, WBStandaloneModeDownloadingButton, WBStandaloneModeExitButton, WBStandaloneModeModel, WBStandaloneModePrepareButton, YYAnimatedImageView;

@interface WBStandaloneModeViewController : WBViewController
{
    NSDictionary *_rnParams;
    WBStandaloneModeModel *_dataMode;
    UIScrollView *_scrollView;
    YYAnimatedImageView *_mainImageView;
    UIView *_infoView;
    NSArray *_infoCells;
    UIView *_buttonView;
    WBStandaloneModePrepareButton *_prepareButton;
    WBStandaloneModeDownloadingButton *_downloadingButton;
    WBStandaloneModeDoneButton *_doneButton;
    UIButton *_actionButton;
    CADisplayLink *_updateLink;
    WBStandaloneModeExitButton *_exitButton;
}

- (void).cxx_destruct;
@property(retain, nonatomic) WBStandaloneModeExitButton *exitButton; // @synthesize exitButton=_exitButton;
@property(retain, nonatomic) CADisplayLink *updateLink; // @synthesize updateLink=_updateLink;
@property(retain, nonatomic) UIButton *actionButton; // @synthesize actionButton=_actionButton;
@property(retain, nonatomic) WBStandaloneModeDoneButton *doneButton; // @synthesize doneButton=_doneButton;
@property(retain, nonatomic) WBStandaloneModeDownloadingButton *downloadingButton; // @synthesize downloadingButton=_downloadingButton;
@property(retain, nonatomic) WBStandaloneModePrepareButton *prepareButton; // @synthesize prepareButton=_prepareButton;
@property(retain, nonatomic) UIView *buttonView; // @synthesize buttonView=_buttonView;
@property(retain, nonatomic) NSArray *infoCells; // @synthesize infoCells=_infoCells;
@property(retain, nonatomic) UIView *infoView; // @synthesize infoView=_infoView;
@property(retain, nonatomic) YYAnimatedImageView *mainImageView; // @synthesize mainImageView=_mainImageView;
@property(retain, nonatomic) UIScrollView *scrollView; // @synthesize scrollView=_scrollView;
@property(retain, nonatomic) WBStandaloneModeModel *dataMode; // @synthesize dataMode=_dataMode;
@property(retain, nonatomic) NSDictionary *rnParams; // @synthesize rnParams=_rnParams;
- (void)onDownloadFailed;
- (void)onDownloadSuccess;
- (void)onGetDownloadDictSize;
- (id)displayDictSize;
- (void)refreshCloseButton:(id)arg1;
- (void)refreshUpdatingButton:(id)arg1;
- (void)refreshInfoView:(id)arg1;
- (void)refreshUI:(id)arg1;
- (void)updateStatusToDownloading;
- (void)updateAndUpgradeDict;
- (void)updateAndDownloadDict;
- (void)downloadDicts;
- (void)openDirectly;
- (void)showNoNetwork;
- (void)didTapOpen;
- (void)didTapUpdate;
- (void)handleDisplayLink;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)clickStandAloneModeAction:(id)arg1;
- (void)clickExitStandaloneModeAction:(id)arg1;
- (void)viewDidLayoutSubviews;
- (void)initUI;
- (void)dealloc;
- (void)addObservers;
- (void)initData;
- (void)viewDidLoad;
- (id)initWithParams:(id)arg1;

@end

