//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface WBStandaloneModeModel : NSObject
{
    _Bool _dataInited;
    _Bool _autoDownload;
    _Bool _enabled;
    _Bool _hasUpdate;
    _Bool _needToOpen;
    _Bool _needToUpgrade;
    _Bool _updating;
    _Bool _dictInfoFetched;
    _Bool _currentDownloadFailed;
    _Bool _currentDownloadSuccess;
    _Bool _isTip;
    _Bool _isDownload;
    long long _downloadSource;
    unsigned long long _updateSource;
    double _updatingProcess;
    unsigned long long _dictSize;
}

@property(nonatomic) _Bool isDownload; // @synthesize isDownload=_isDownload;
@property(nonatomic) _Bool isTip; // @synthesize isTip=_isTip;
@property(nonatomic) unsigned long long dictSize; // @synthesize dictSize=_dictSize;
@property(nonatomic) double updatingProcess; // @synthesize updatingProcess=_updatingProcess;
@property(nonatomic) unsigned long long updateSource; // @synthesize updateSource=_updateSource;
@property(nonatomic) long long downloadSource; // @synthesize downloadSource=_downloadSource;
@property(nonatomic) _Bool currentDownloadSuccess; // @synthesize currentDownloadSuccess=_currentDownloadSuccess;
@property(nonatomic) _Bool currentDownloadFailed; // @synthesize currentDownloadFailed=_currentDownloadFailed;
@property(nonatomic) _Bool dictInfoFetched; // @synthesize dictInfoFetched=_dictInfoFetched;
@property(nonatomic) _Bool updating; // @synthesize updating=_updating;
@property(nonatomic) _Bool needToUpgrade; // @synthesize needToUpgrade=_needToUpgrade;
@property(nonatomic) _Bool needToOpen; // @synthesize needToOpen=_needToOpen;
@property(nonatomic) _Bool hasUpdate; // @synthesize hasUpdate=_hasUpdate;
@property(nonatomic) _Bool enabled; // @synthesize enabled=_enabled;
@property(nonatomic) _Bool autoDownload; // @synthesize autoDownload=_autoDownload;
@property(nonatomic) _Bool dataInited; // @synthesize dataInited=_dataInited;
- (id)description;

@end

