//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "WBPreferences.h"

@interface WBStandAloneAppPreference : WBPreferences
{
}

+ (_Bool)reloadFromDiskAutomatically;
+ (id)fileName;
+ (id)folderPath;
+ (void)checkAndSetRedDotInfo:(id)arg1;
- (void)_save;

@end

