//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface WBStandaloneModeReporter : NSObject
{
}

+ (id)reportForStandAloneUpdate:(unsigned long long)arg1;
+ (void)reportScene:(int)arg1 source:(int)arg2 action:(int)arg3 actionText:(id)arg4;

@end

