//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIView.h>

@class UIButton, WBLabel;

@interface WBStandaloneModeTipView : UIView
{
    WBLabel *_mainTitleLabel;
    WBLabel *_subTitleLabel;
    UIButton *_cancelBtn;
    UIButton *_downloadBtn;
}

- (void).cxx_destruct;
@property(retain, nonatomic) UIButton *downloadBtn; // @synthesize downloadBtn=_downloadBtn;
@property(retain, nonatomic) UIButton *cancelBtn; // @synthesize cancelBtn=_cancelBtn;
@property(retain, nonatomic) WBLabel *subTitleLabel; // @synthesize subTitleLabel=_subTitleLabel;
@property(retain, nonatomic) WBLabel *mainTitleLabel; // @synthesize mainTitleLabel=_mainTitleLabel;
- (double)expandBottomHeight;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;
- (void)layoutSubviews;
- (void)configWithMainTitle:(id)arg1 subTitle:(id)arg2 cancelTitle:(id)arg3 confirmTitle:(id)arg4;
- (id)initWithFrame:(struct CGRect)arg1;

@end

