//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class MMTimer;

@interface WBSwipeEdgeDetector : NSObject
{
    CDUnknownBlockType _actionBlock;
    double _lastTriggerTime;
    MMTimer *_deleteTimer;
    double _lastMoveX;
    double _lastMaxWidth;
}

- (void).cxx_destruct;
@property(nonatomic) double lastMaxWidth; // @synthesize lastMaxWidth=_lastMaxWidth;
@property(nonatomic) double lastMoveX; // @synthesize lastMoveX=_lastMoveX;
@property(retain, nonatomic) MMTimer *deleteTimer; // @synthesize deleteTimer=_deleteTimer;
@property(nonatomic) double lastTriggerTime; // @synthesize lastTriggerTime=_lastTriggerTime;
@property(copy, nonatomic) CDUnknownBlockType actionBlock; // @synthesize actionBlock=_actionBlock;
- (void)updateMoveX:(double)arg1 maxWidth:(double)arg2;
@property(readonly, nonatomic) double currentMoveTime;
- (void)handleTimer;
- (void)stopDetect;
- (void)startDetect:(double)arg1;

@end

