//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIView.h>

@class UILabel, UISwitch;

@interface WBSwitchItemView : UIView
{
    UILabel *_titleLabel;
    UISwitch *_switchButton;
    CDUnknownBlockType _switchGetter;
    CDUnknownBlockType _switchSetter;
}

- (void).cxx_destruct;
@property(copy, nonatomic) CDUnknownBlockType switchSetter; // @synthesize switchSetter=_switchSetter;
@property(copy, nonatomic) CDUnknownBlockType switchGetter; // @synthesize switchGetter=_switchGetter;
@property(retain, nonatomic) UISwitch *switchButton; // @synthesize switchButton=_switchButton;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;
- (void)layoutSubviews;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)onValueChanged;
- (void)reload;
- (void)didMoveToWindow;
- (id)initWithTitle:(id)arg1 swicthGetter:(CDUnknownBlockType)arg2 switchSetter:(CDUnknownBlockType)arg3;

@end

