//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "WBTextItemCell.h"

@class Protocol, UIColor, UIImageView;

@interface WBSymbolCell : WBTextItemCell
{
    _Bool _usingWBSymbolListItemProtocol;
    UIImageView *_iconImageView;
    double _elementScale;
    struct CGSize _iconImageOriginalSize;
    CDUnknownBlockType _updateItemBlock;
    unsigned long long _borderPosition;
    Protocol *_protocol;
    UIColor *_selectedBackgroundColor;
}

- (void).cxx_destruct;
@property(retain, nonatomic) UIColor *selectedBackgroundColor; // @synthesize selectedBackgroundColor=_selectedBackgroundColor;
@property(retain, nonatomic) Protocol *protocol; // @synthesize protocol=_protocol;
@property(nonatomic) unsigned long long borderPosition; // @synthesize borderPosition=_borderPosition;
@property(copy, nonatomic) CDUnknownBlockType updateItemBlock; // @synthesize updateItemBlock=_updateItemBlock;
- (void)layoutSubviews;
- (void)updateBackgroundColor;
- (void)setSelected:(_Bool)arg1;
- (void)setHighlighted:(_Bool)arg1;
- (void)initIconImageView;
- (void)setArrangeItem:(id)arg1 atIndex:(unsigned long long)arg2 layout:(id)arg3;
- (void)updateFont:(id)arg1 scale:(double)arg2;
- (id)initWithFrame:(struct CGRect)arg1;

@end

