//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIView.h>

#import "WBArrangeCellUpdateDelegate-Protocol.h"
#import "WBInputStateUpdateProtocol-Protocol.h"
#import "WBKeyContentViewProtocol-Protocol.h"

@class NSArray, NSString, UIColor, UIFont, WBArrangeView, WBKeyView;
@protocol WBKeyViewHostingProtocol;

@interface WBSymbolListView : UIView <WBArrangeCellUpdateDelegate, WBKeyContentViewProtocol, WBInputStateUpdateProtocol>
{
    id <WBKeyViewHostingProtocol> _hosting;
    _Bool _supportsSelectedStyle;
    _Bool _lockContentOffset;
    _Bool _needsUpdateFont;
    UIFont *_itemFont;
    WBKeyView *_keyView;
    WBArrangeView *_arrangeView;
    UIColor *_selectedBackgroundColor;
    unsigned long long _selectedIndex;
}

- (void).cxx_destruct;
@property(nonatomic) _Bool needsUpdateFont; // @synthesize needsUpdateFont=_needsUpdateFont;
@property(nonatomic) _Bool lockContentOffset; // @synthesize lockContentOffset=_lockContentOffset;
@property(nonatomic) _Bool supportsSelectedStyle; // @synthesize supportsSelectedStyle=_supportsSelectedStyle;
@property(nonatomic) unsigned long long selectedIndex; // @synthesize selectedIndex=_selectedIndex;
@property(retain, nonatomic) UIColor *selectedBackgroundColor; // @synthesize selectedBackgroundColor=_selectedBackgroundColor;
@property(retain, nonatomic) WBArrangeView *arrangeView; // @synthesize arrangeView=_arrangeView;
@property(nonatomic) __weak WBKeyView *keyView; // @synthesize keyView=_keyView;
@property(retain, nonatomic) UIFont *itemFont; // @synthesize itemFont=_itemFont;
@property(readonly, nonatomic) unsigned long long itemsAndSelectedHash;
- (void)clearSection;
- (void)scrollsToTop;
@property(retain, nonatomic) NSArray *items;
- (void)arrangeViewWillResetContentOffset:(id)arg1 targetContentOffset:(inout struct CGPoint *)arg2 layout:(id)arg3;
- (void)arrangeView:(id)arg1 didUpdateLayout:(id)arg2;
- (void)arrangeView:(id)arg1 didSelectCell:(id)arg2 atIndex:(unsigned long long)arg3;
- (unsigned long long)arrangeView:(id)arg1 willSelectCell:(id)arg2 atIIndex:(unsigned long long)arg3;
- (void)arrangeView:(id)arg1 touchBeginAtCell:(id)arg2 atIIndex:(unsigned long long)arg3;
- (void)arrangeView:(id)arg1 didSetArrangeItem:(id)arg2 forCell:(id)arg3 atIndex:(unsigned long long)arg4;
- (void)arrangeView:(id)arg1 didCreateCell:(id)arg2 atIIndex:(unsigned long long)arg3;
- (void)updateFontForCell:(id)arg1;
- (void)updateSelectedItemWithPendingInput:(id)arg1;
- (void)setNeedsUpdateSelectedItem;
- (void)pendingInputDidChange:(id)arg1;
- (void)didAttachHosting;
- (void)layoutSubviews;
- (void)elementScaleChanged;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

