//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "WBCommonPanelView.h"

#import "WBInputStateUpdateProtocol-Protocol.h"

@class NSString;
@protocol WBKeyViewHostingProtocol;

@interface WBT26Panel : WBCommonPanelView <WBInputStateUpdateProtocol>
{
    id <WBKeyViewHostingProtocol> _hosting;
    _Bool _isHodingShiftKey;
    _Bool _didProcessShiftKey;
    unsigned long long _shiftState;
    unsigned long long _letterTextShiftRule;
    unsigned long long _shiftStateBeforeHolding;
}

- (void).cxx_destruct;
@property(nonatomic) _Bool didProcessShiftKey; // @synthesize didProcessShiftKey=_didProcessShiftKey;
@property(nonatomic) unsigned long long shiftStateBeforeHolding; // @synthesize shiftStateBeforeHolding=_shiftStateBeforeHolding;
@property(nonatomic) _Bool isHodingShiftKey; // @synthesize isHodingShiftKey=_isHodingShiftKey;
@property(nonatomic) unsigned long long shiftState; // @synthesize shiftState=_shiftState;
@property(readonly, nonatomic) unsigned long long letterTextShiftRule; // @synthesize letterTextShiftRule=_letterTextShiftRule;
- (_Bool)isUppercase;
- (void)updateShiftState;
- (void)textViewDidTap;
- (void)bottomPanelTypeDidChange;
- (void)documentContextBeforeInputDidChange:(long long)arg1;
- (void)currentKeyboardTypeDidChange;
- (void)willAppear:(_Bool)arg1;
- (void)endUpperCaseOnceIfNeeded;
- (void)pendingInputDidChange:(id)arg1;
- (void)didAttachHosting;
- (void)handleInputKeyTouchEnd:(id)arg1 hasProcessedInput:(_Bool)arg2;
- (void)processShiftNextStateIfNeeded;
- (void)endHoldingShiftKey:(_Bool)arg1;
- (void)beginHoldingShiftKey;
- (void)handleShiftKeyViewEvent:(id)arg1 options:(unsigned long long)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

