//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "WBCommonPanelView.h"

#import "WBInputStateUpdateProtocol-Protocol.h"

@class NSString, WBSymbolListView;

@interface WBT9Panel : WBCommonPanelView <WBInputStateUpdateProtocol>
{
    _Bool _updateSymbolListUpdated;
    WBSymbolListView *_symbolListView;
}

- (void).cxx_destruct;
- (double)firstUpFloatingKeyWidth;
- (void)updateSymbolList;
- (void)keyViewsDidLoad:(id)arg1;
- (void)syllableDidChange;
- (void)willAppear:(_Bool)arg1;
- (void)splitEnabledDidChange;
- (void)didAttachHosting;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

