//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "WBSymbolListItemProtocol-Protocol.h"

@class NSString;

@interface WBT9SymbolItem : NSObject <WBSymbolListItemProtocol>
{
    NSString *_text;
}

+ (id)itemWithText:(id)arg1;
- (void).cxx_destruct;
@property(readonly, nonatomic) NSString *text; // @synthesize text=_text;
- (id)syllable;
- (_Bool)supportsSelectedStyle;
- (double)itemWidth;
- (_Bool)asyncCompute;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

