//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIControl.h>

@interface WBTapView : UIControl
{
    CDUnknownBlockType _handler;
}

+ (id)with:(CDUnknownBlockType)arg1 superview:(id)arg2;
- (void).cxx_destruct;
- (void)onTap;
- (id)initWith:(CDUnknownBlockType)arg1;

@end

