//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "PBCoding-Protocol.h"

@class NSString;

@interface WBTestNotification : NSObject <PBCoding>
{
    int integer;
    NSString *string;
}

+ (void)initialize;
+ (void)PBArrayAdd_integer;
+ (void)PBArrayAdd_string;
- (void).cxx_destruct;
@property(nonatomic) int integer; // @synthesize integer;
@property(copy, nonatomic) NSString *string; // @synthesize string;
- (id)getPBPropertyTable;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

