//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class WBTextAttachment;

@protocol WBTextAttachmentDelegate <NSObject>
- (void)attachment:(WBTextAttachment *)arg1 drawInRect:(struct CGRect)arg2;
@end

