//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UITextField.h>

#import "UITextFieldDelegate-Protocol.h"

@class NSString;

@interface WBTextField : UITextField <UITextFieldDelegate>
{
    CDUnknownBlockType _onReturn;
    struct UIEdgeInsets _contentInset;
}

- (void).cxx_destruct;
@property(copy, nonatomic) CDUnknownBlockType onReturn; // @synthesize onReturn=_onReturn;
@property(nonatomic) struct UIEdgeInsets contentInset; // @synthesize contentInset=_contentInset;
- (struct CGRect)editingRectForBounds:(struct CGRect)arg1;
- (struct CGRect)textRectForBounds:(struct CGRect)arg1;
- (_Bool)textFieldShouldReturn:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

