//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/NSTextAttachment.h>

@class _WBTextAttachmentImage;
@protocol KBIMECandidateAttachedDataProtocol, WBTextAttachmentDelegate;

@interface WBTextAttachment : NSTextAttachment
{
    id <KBIMECandidateAttachedDataProtocol> _attachedData;
    id <WBTextAttachmentDelegate> _delegate;
    _WBTextAttachmentImage *_attachmentImage;
}

- (void).cxx_destruct;
@property(retain, nonatomic) _WBTextAttachmentImage *attachmentImage; // @synthesize attachmentImage=_attachmentImage;
@property(nonatomic) __weak id <WBTextAttachmentDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) id <KBIMECandidateAttachedDataProtocol> attachedData; // @synthesize attachedData=_attachedData;
- (id)initWithData:(id)arg1 ofType:(id)arg2;

@end

