//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSAttributedString, NSDictionary;

@interface WBTextLayout : NSObject
{
    NSAttributedString *_firstLineAttributedString;
    double _limitedWidth;
    double _attachmentWidth;
    NSAttributedString *_attributedString;
    NSDictionary *_attributes;
    struct CGSize _boundingSize;
}

+ (id)layoutWithAttributedString:(id)arg1 attributes:(id)arg2 limitedWidth:(double)arg3 attachmentWidth:(double)arg4;
- (void).cxx_destruct;
@property(readonly, nonatomic) NSDictionary *attributes; // @synthesize attributes=_attributes;
@property(readonly, nonatomic) NSAttributedString *attributedString; // @synthesize attributedString=_attributedString;
@property(readonly, nonatomic) NSAttributedString *displayAttributedString;
@property(readonly, nonatomic) struct CGSize boundingSize; // @synthesize boundingSize=_boundingSize;
- (id)init;

@end

