//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UILabel.h>

#import "WBTextAttachmentDelegate-Protocol.h"

@class NSString, WBTextAttachment, YYAnimatedImageView;

@interface WBTextItemLabel : UILabel <WBTextAttachmentDelegate>
{
    YYAnimatedImageView *_iconImageView;
    WBTextAttachment *_textAttachment;
}

- (void).cxx_destruct;
@property(retain, nonatomic) WBTextAttachment *textAttachment; // @synthesize textAttachment=_textAttachment;
@property(retain, nonatomic) YYAnimatedImageView *iconImageView; // @synthesize iconImageView=_iconImageView;
- (void)attachment:(id)arg1 drawInRect:(struct CGRect)arg2;
- (void)updateTextAttachment:(id)arg1;
- (void)updateIconImageWithAttributedText:(id)arg1;
- (void)drawTextInRect:(struct CGRect)arg1;
- (void)setAttributedText:(id)arg1;
- (void)initIconImageIfNeeded;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

