//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UITextView.h>

@interface WBTextView : UITextView
{
    _Bool _selectForLinkOnly;
}

@property(nonatomic) _Bool selectForLinkOnly; // @synthesize selectForLinkOnly=_selectForLinkOnly;
- (_Bool)pointInside:(struct CGPoint)arg1 withEvent:(id)arg2;

@end

