//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "WBArrangeCell.h"

@class CALayer, NSAttributedString, UIColor, WBLabel, WBTextItemLabel;

@interface WBTextItemCell : WBArrangeCell
{
    NSAttributedString *_attributedText;
    _Bool _didLastedOnce;
    _Bool _applyHighlightedBgOnfocus;
    _Bool _focusedStyle;
    WBTextItemLabel *_textLabel;
    WBLabel *_debugLabel;
    double _highlightedBgCornerRadius;
    UIColor *_highlightedBgColor;
    UIColor *_textColor;
    UIColor *_focusedTextColor;
    CALayer *_backgroundLayer;
}

- (void).cxx_destruct;
@property(retain, nonatomic) CALayer *backgroundLayer; // @synthesize backgroundLayer=_backgroundLayer;
@property(nonatomic) _Bool focusedStyle; // @synthesize focusedStyle=_focusedStyle;
@property(retain, nonatomic) UIColor *focusedTextColor; // @synthesize focusedTextColor=_focusedTextColor;
@property(retain, nonatomic) UIColor *textColor; // @synthesize textColor=_textColor;
@property(retain, nonatomic) UIColor *highlightedBgColor; // @synthesize highlightedBgColor=_highlightedBgColor;
@property(nonatomic) double highlightedBgCornerRadius; // @synthesize highlightedBgCornerRadius=_highlightedBgCornerRadius;
@property(nonatomic) _Bool applyHighlightedBgOnfocus; // @synthesize applyHighlightedBgOnfocus=_applyHighlightedBgOnfocus;
@property(retain, nonatomic) WBLabel *debugLabel; // @synthesize debugLabel=_debugLabel;
- (void)cleanUp;
- (void)layoutSubviews;
- (id)wordEmojiCanBoldRangesWithCandidateWord:(id)arg1 text:(id)arg2;
- (void)applyLabelAttributedText;
- (void)setAttributedText:(id)arg1 focusedStyle:(_Bool)arg2;
- (void)updateHighlightedBg;
- (void)setHighlighted:(_Bool)arg1;
- (void)initBackgroundLayerIfNeeded;
@property(readonly, nonatomic) WBTextItemLabel *textLabel; // @synthesize textLabel=_textLabel;
- (id)initWithFrame:(struct CGRect)arg1;

@end

