//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIViewController.h>

@interface WBTestVoiceInputViewController : UIViewController
{
}

- (void)stopRecordAction:(id)arg1;
- (void)startRecordAction:(id)arg1;
- (id)stopLabel;
- (void)testFunc2;
- (void)testFunc;
- (id)startLabel;
- (void)viewDidLoad;

@end

