//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface WBTestOperation : NSObject
{
    unsigned long long _cmd;
    id _data;
}

+ (id)operationWithCmd:(unsigned long long)arg1 data:(id)arg2;
- (void).cxx_destruct;
@property(retain, nonatomic) id data; // @synthesize data=_data;
@property(nonatomic) unsigned long long cmd; // @synthesize cmd=_cmd;

@end

