//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIImage.h>

#import "NSCopying-Protocol.h"
#import "WBDynamicImageProtocol-Protocol.h"

@class NSObject, NSRecursiveLock, NSString, WBThemeImageCache;
@protocol NSCopying;

@interface WBThemeImage : UIImage <WBDynamicImageProtocol, NSCopying>
{
    NSObject<NSCopying> *_managerName;
    CDUnknownBlockType _themeProvider;
    WBThemeImageCache *_cachedRawImages;
    NSRecursiveLock *_lock;
}

+ (void)initialize;
- (void).cxx_destruct;
@property(retain, nonatomic) NSRecursiveLock *lock; // @synthesize lock=_lock;
@property(retain, nonatomic) WBThemeImageCache *cachedRawImages; // @synthesize cachedRawImages=_cachedRawImages;
@property(copy, nonatomic) CDUnknownBlockType themeProvider; // @synthesize themeProvider=_themeProvider;
@property(copy, nonatomic) NSObject<NSCopying> *managerName; // @synthesize managerName=_managerName;
@property(readonly, nonatomic) _Bool wb_isDynamicImage;
@property(readonly, nonatomic) UIImage *wb_rawImage;
- (id)imageWithTintColor:(id)arg1 renderingMode:(long long)arg2;
- (id)imageWithTintColor:(id)arg1;
- (id)imageByApplyingSymbolConfiguration:(id)arg1;
- (id)symbolConfiguration;
- (id)imageWithConfiguration:(id)arg1;
- (id)configuration;
- (id)imageWithoutBaseline;
- (id)imageWithBaselineOffsetFromBottom:(double)arg1;
- (_Bool)hasBaseline;
- (double)baselineOffsetFromBottom;
- (_Bool)isSymbolImage;
- (id)imageWithHorizontallyFlippedOrientation;
- (_Bool)flipsForRightToLeftLayoutDirection;
- (id)imageFlippedForRightToLeftLayoutDirection;
- (id)imageAsset;
- (id)traitCollection;
- (id)imageRendererFormat;
- (long long)renderingMode;
- (id)imageWithRenderingMode:(long long)arg1;
- (id)imageWithAlignmentRectInsets:(struct UIEdgeInsets)arg1;
- (long long)resizingMode;
- (struct UIEdgeInsets)capInsets;
- (id)resizableImageWithCapInsets:(struct UIEdgeInsets)arg1 resizingMode:(long long)arg2;
- (id)resizableImageWithCapInsets:(struct UIEdgeInsets)arg1;
- (void)drawAsPatternInRect:(struct CGRect)arg1;
- (void)drawInRect:(struct CGRect)arg1 blendMode:(int)arg2 alpha:(double)arg3;
- (void)drawInRect:(struct CGRect)arg1;
- (void)drawAtPoint:(struct CGPoint)arg1 blendMode:(int)arg2 alpha:(double)arg3;
- (void)drawAtPoint:(struct CGPoint)arg1;
- (struct UIEdgeInsets)alignmentRectInsets;
- (double)duration;
- (id)images;
- (double)scale;
- (long long)imageOrientation;
- (id)CIImage;
- (struct CGImage *)CGImage;
- (struct CGSize)size;
- (_Bool)isEqual:(id)arg1;
@property(readonly) unsigned long long hash;
- (_Bool)conformsToProtocol:(id)arg1;
- (_Bool)isMemberOfClass:(Class)arg1;
- (_Bool)isKindOfClass:(Class)arg1;
- (_Bool)respondsToSelector:(SEL)arg1;
- (id)init;
@property(readonly, copy) NSString *description;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)forwardingTargetForSelector:(SEL)arg1;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) Class superclass;

@end

