//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "WBViewController.h"

@class NSMutableArray, UIView;

@interface WBThreeViewController : WBViewController
{
    NSMutableArray *_captainzhuLayoutBlocks;
    UIView *_topView;
    UIView *_middleView;
    double _middleMinHeight;
    UIView *_bottomView;
    double _bottomMinPadding;
    double _bottomMaxPadding;
    double _horizontalPadding;
    double _maxWidth;
}

- (void).cxx_destruct;
@property(nonatomic) double maxWidth; // @synthesize maxWidth=_maxWidth;
@property(nonatomic) double horizontalPadding; // @synthesize horizontalPadding=_horizontalPadding;
@property(nonatomic) double bottomMaxPadding; // @synthesize bottomMaxPadding=_bottomMaxPadding;
@property(nonatomic) double bottomMinPadding; // @synthesize bottomMinPadding=_bottomMinPadding;
@property(retain, nonatomic) UIView *bottomView; // @synthesize bottomView=_bottomView;
@property(nonatomic) double middleMinHeight; // @synthesize middleMinHeight=_middleMinHeight;
@property(retain, nonatomic) UIView *middleView; // @synthesize middleView=_middleView;
@property(retain, nonatomic) UIView *topView; // @synthesize topView=_topView;
- (void)viewDidLoad;
- (void)didMoveToParentViewController:(id)arg1;
- (void)viewDidLayoutSubviews;

@end

