//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "WBBaseView.h"

@interface WBTransitionView : WBBaseView
{
    _Bool _automaticallyManagesState;
    unsigned long long _state;
}

@property(readonly, nonatomic) unsigned long long state; // @synthesize state=_state;
@property(nonatomic) _Bool automaticallyManagesState; // @synthesize automaticallyManagesState=_automaticallyManagesState;
- (void)transitState:(unsigned long long)arg1 animated:(_Bool)arg2;
- (void)setHidden:(_Bool)arg1;
- (void)didRemoveFromWindow;
- (void)didAddToWindow;
- (void)didDisappear:(_Bool)arg1;
- (void)willDisappear:(_Bool)arg1;
- (void)didAppear:(_Bool)arg1;
- (void)willAppear:(_Bool)arg1;
- (void)didLoad;
- (void)didInitialize;
- (void)layoutSubviews;
- (void)didMoveToWindow;
- (void)willMoveToWindow:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

