//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "NSFastEnumeration-Protocol.h"

@class NSArray;

@interface WBTuple : NSObject <NSFastEnumeration>
{
    NSArray *_backingArray;
}

+ (id)tupleWithObjects:(id)arg1;
- (void).cxx_destruct;
@property(readonly, nonatomic) NSArray *backingArray; // @synthesize backingArray=_backingArray;
@property(readonly, nonatomic) id last;
@property(readonly, nonatomic) id fifth;
@property(readonly, nonatomic) id fourth;
@property(readonly, nonatomic) id third;
@property(readonly, nonatomic) id second;
@property(readonly, nonatomic) id first;
@property(readonly, nonatomic) unsigned long long count;
- (id)allObjects;
- (id)objectAtIndex:(unsigned long long)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (unsigned long long)countByEnumeratingWithState:(CDStruct_70511ce9 *)arg1 objects:(id *)arg2 count:(unsigned long long)arg3;
- (unsigned long long)hash;
- (_Bool)isEqual:(id)arg1;
- (id)description;
- (id)initWithBackingArray:(id)arg1;
- (id)init;

@end

