//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class WBFileCreationListener;

@interface WBUinGenerator : NSObject
{
    WBFileCreationListener *_uinFileCreationListener;
}

+ (id)generateDeviceCode;
+ (id)generateUinToken;
+ (id)deviceCodeFilePath;
+ (id)uinFilePath;
+ (id)uinTokenFilePath;
+ (id)uinParentFolder;
+ (id)sharedInstance;
- (void).cxx_destruct;
@property(retain, nonatomic) WBFileCreationListener *uinFileCreationListener; // @synthesize uinFileCreationListener=_uinFileCreationListener;
- (void)listenForUinFileGenerated:(CDUnknownBlockType)arg1;
- (void)saveUin:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (id)getDeviceCode;
- (id)getUin;
- (void)generateDeviceCode:(CDUnknownBlockType)arg1;
- (void)generateUinToken:(CDUnknownBlockType)arg1;
- (void)checkAndCreateParentDirectory;

@end

