//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "WBViewController.h"

@interface WBUIDevViewController : WBViewController
{
}

- (void)handleSlider:(id)arg1;
- (void)testModernSlider;
- (void)viewDidLoad;

@end

