//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface WBUIHelper : NSObject
{
}

+ (id)compressImage:(id)arg1 toByte:(unsigned long long)arg2;
+ (id)resizedImageWithData:(id)arg1 withSize:(struct CGSize)arg2;
+ (void)saveImageDataToAlbum:(id)arg1 completeBlock:(CDUnknownBlockType)arg2;
+ (void)addPopEffectAnimationForView:(id)arg1;
+ (void)addBlinkAnimationForView:(id)arg1 backgroundColor:(id)arg2 cornerRadius:(double)arg3 repeatCount:(unsigned long long)arg4;
+ (void)resetContentOffsetForScrollView:(id)arg1 currentPage:(long long)arg2;
+ (void)animateWithAnimated:(_Bool)arg1 duration:(double)arg2 delay:(double)arg3 usingSpringWithDamping:(double)arg4 initialSpringVelocity:(double)arg5 options:(unsigned long long)arg6 animations:(CDUnknownBlockType)arg7 completion:(CDUnknownBlockType)arg8;
+ (void)animateWithAnimated:(_Bool)arg1 duration:(double)arg2 animations:(CDUnknownBlockType)arg3;
+ (void)animateWithAnimated:(_Bool)arg1 duration:(double)arg2 animations:(CDUnknownBlockType)arg3 completion:(CDUnknownBlockType)arg4;
+ (void)animateWithAnimated:(_Bool)arg1 duration:(double)arg2 delay:(double)arg3 options:(unsigned long long)arg4 animations:(CDUnknownBlockType)arg5 completion:(CDUnknownBlockType)arg6;
+ (struct CGSize)systemMainScreenSize;
+ (id)deviceMachine;
+ (id)getSubView:(id)arg1 array:(id)arg2 level:(long long)arg3;
+ (id)imageWithContentSize:(struct CGSize)arg1 cornerRadius:(double)arg2 borderWidth:(double)arg3 borderColor:(id)arg4 shadowColor:(id)arg5 shadowHeight:(double)arg6 cacheable:(_Bool)arg7;
+ (void)removeImageCache;
+ (_Bool)isIPad;
+ (id)wb_panelGradientBGColors;
+ (struct CGSize)stackSizeWithBaseHeight:(double)arg1 columnCount:(unsigned long long)arg2 itemSpacing:(double)arg3;
+ (void)_wb_executeTimerBlock:(id)arg1;
+ (id)scheduledTimerWithTimeInterval:(double)arg1 block:(CDUnknownBlockType)arg2 repeats:(_Bool)arg3;
+ (void)impactFeedbackRigid;
+ (void)impactFeedback;
+ (id)attributesWithFont:(id)arg1 textColor:(id)arg2 lineHeight:(double)arg3 lineBreakMode:(long long)arg4 textAlignment:(long long)arg5;
+ (id)attributesWithFont:(id)arg1 lineBreakMode:(long long)arg2 textAlignment:(long long)arg3 attachmentSize:(double)arg4;
+ (id)attributesWithFont:(id)arg1 lineBreakMode:(long long)arg2 textAlignment:(long long)arg3;
+ (id)attributesWithFont:(id)arg1 textColor:(id)arg2;
+ (struct CGPoint)spacingForPanelType:(long long)arg1 layoutSize:(struct CGSize)arg2;
+ (struct UIEdgeInsets)paddingForPanelType:(long long)arg1 layoutSize:(struct CGSize)arg2;
+ (double)calculateCostBlock:(CDUnknownBlockType)arg1;
+ (_Bool)executeBlock:(CDUnknownBlockType)arg1 oncePerIdentifier:(id)arg2;
+ (void)showFormatInfo:(id)arg1 action:(CDUnknownBlockType)arg2;
+ (void)showAlertWithTitle:(id)arg1 subTitle:(id)arg2 cancelButtonTitle:(id)arg3 actionButtonTitle:(id)arg4 cancelAction:(CDUnknownBlockType)arg5 comfirmAction:(CDUnknownBlockType)arg6;
+ (void)showAlert:(id)arg1 action:(CDUnknownBlockType)arg2;
+ (void)showAlert:(id)arg1;
+ (void)showViewOnTop:(id)arg1;
+ (_Bool)isLaunching;
+ (double)pixelOne;
+ (_Bool)hasNotch;
+ (unsigned long long)currentPresentationType;
+ (struct CGSize)deviceSize;
+ (struct CGSize)windowSize;
+ (struct CGSize)mainScreenSize;
+ (void)addPresentationTypeChangeObserver:(id)arg1 selector:(SEL)arg2;
+ (void)updateScreenSize:(struct CGSize)arg1 viewSize:(struct CGSize)arg2;
+ (void)updateWindowSize:(struct CGSize)arg1;

@end

