//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface WBUIKeyboardManager : NSObject
{
    CDUnknownBlockType _containerViewBlock;
    CDUnknownBlockType _keyboardWillHideBlock;
    CDUnknownBlockType _keyboardWillShowBlock;
}

- (void).cxx_destruct;
@property(copy, nonatomic) CDUnknownBlockType keyboardWillShowBlock; // @synthesize keyboardWillShowBlock=_keyboardWillShowBlock;
@property(copy, nonatomic) CDUnknownBlockType keyboardWillHideBlock; // @synthesize keyboardWillHideBlock=_keyboardWillHideBlock;
@property(copy, nonatomic) CDUnknownBlockType containerViewBlock; // @synthesize containerViewBlock=_containerViewBlock;
- (void)keyboardWillChangeFrameNotification:(id)arg1;
- (void)addKeyboardNotification;
- (id)init;

@end

