//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "QMUICommonViewController.h"

#import "WBVCGuideForNavigateKeyboardScene-Protocol.h"

@class NSString, UIColor;

@interface WBViewController : QMUICommonViewController <WBVCGuideForNavigateKeyboardScene>
{
    _Bool _hasCallViewDidEnterForeground;
    UIColor *_titleColor;
    UIColor *_barColor;
}

- (void).cxx_destruct;
@property(retain, nonatomic) UIColor *barColor; // @synthesize barColor=_barColor;
@property(retain, nonatomic) UIColor *titleColor; // @synthesize titleColor=_titleColor;
- (_Bool)canShowGuideForNavigateKeyboardScene;
- (void)motionBegan:(long long)arg1 withEvent:(id)arg2;
- (void)setupNavigationItems;
- (void)viewDidEnterForeground;
- (void)viewWillEnterForeground;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)pluginInfoDidChange;
- (void)plusStateDidChange;
- (void)inputModeStateDidChange;
- (void)pluginSettingsDidChange;
- (void)viewDidLoad;
- (_Bool)shouldCustomizeNavigationBarTransitionIfHideable;
- (id)qmui_navigationBarBackgroundImage;
- (id)qmui_navigationBarTintColor;
- (id)qmui_titleViewTintColor;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

