//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@protocol WBKeyViewHostingProtocol, WBPanelProxy;

@interface WBViewContext : NSObject
{
    id <WBKeyViewHostingProtocol> _hosting;
    id <WBPanelProxy> _panelProxy;
}

+ (id)contextWithhosting:(id)arg1 panelProxy:(id)arg2;
- (void).cxx_destruct;
@property(readonly, nonatomic) __weak id <WBPanelProxy> panelProxy; // @synthesize panelProxy=_panelProxy;
@property(readonly, nonatomic) __weak id <WBKeyViewHostingProtocol> hosting; // @synthesize hosting=_hosting;

@end

