//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface WBVoiceInputEVADArchiver : NSObject
{
}

+ (void)savePcmData:(id)arg1 index:(long long)arg2 status:(int)arg3;
+ (void)cleanAllData;

@end

