//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSDate, NSMutableData, NSString;
@protocol WBVoiceInputEVADProcessorDelegate;

@interface WBVoiceInputEVADProcessor : NSObject
{
    unsigned long long _pcmCount;
    NSDate *m_dtLastChangeToSilence;
    struct AudioCoder *m_silkEncoder;
    NSMutableData *m_pcmDataBuffer;
    int m_pcmDataCount;
    _Bool _firstStartDetect;
    int _currentState;
    int _previousState;
    id <WBVoiceInputEVADProcessorDelegate> _delegate;
    NSString *_m_iOSPath;
    NSString *_m_iOSVADDir;
    void *_handle;
    unsigned long long _vad_block_size;
}

- (void).cxx_destruct;
@property(nonatomic) unsigned long long vad_block_size; // @synthesize vad_block_size=_vad_block_size;
@property(nonatomic) void *handle; // @synthesize handle=_handle;
@property(nonatomic) int previousState; // @synthesize previousState=_previousState;
@property(nonatomic) int currentState; // @synthesize currentState=_currentState;
@property(retain, nonatomic) NSString *m_iOSVADDir; // @synthesize m_iOSVADDir=_m_iOSVADDir;
@property(retain, nonatomic) NSString *m_iOSPath; // @synthesize m_iOSPath=_m_iOSPath;
@property(nonatomic) _Bool firstStartDetect; // @synthesize firstStartDetect=_firstStartDetect;
@property(nonatomic) __weak id <WBVoiceInputEVADProcessorDelegate> delegate; // @synthesize delegate=_delegate;
- (id)voiceData:(const char *)arg1 length:(unsigned int)arg2;
- (void)releaseProcessor;
- (void)processSpxVoiceData:(id)arg1 queueItem:(id)arg2;
- (void)reInitSilkEncoder;
- (_Bool)initSilkEncoder;
- (void)resetPCMBuffer;
- (_Bool)setupProcessor;
- (void)dealloc;
- (id)init;

@end

