//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface WBVoiceInputSetUpResultItem : NSObject
{
    _Bool _otherAudioPlaying;
    _Bool _usingBlueTooth;
    _Bool _success;
}

@property(nonatomic) _Bool success; // @synthesize success=_success;
@property(nonatomic) _Bool usingBlueTooth; // @synthesize usingBlueTooth=_usingBlueTooth;
@property(nonatomic) _Bool otherAudioPlaying; // @synthesize otherAudioPlaying=_otherAudioPlaying;

@end

