//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class WBNoRetainTimer, WBVoiceInputRecordState;

@interface WBVoiceInputAudioRecorder : NSObject
{
    _Bool _m_hasPrepare;
    WBNoRetainTimer *_m_meterTimer;
    WBVoiceInputRecordState *_m_bufferState;
}

+ (void)sprintRetCode:(int)arg1;
- (void).cxx_destruct;
@property(nonatomic) _Bool m_hasPrepare; // @synthesize m_hasPrepare=_m_hasPrepare;
@property(retain, nonatomic) WBVoiceInputRecordState *m_bufferState; // @synthesize m_bufferState=_m_bufferState;
@property(retain, nonatomic) WBNoRetainTimer *m_meterTimer; // @synthesize m_meterTimer=_m_meterTimer;
- (void)printRetCode:(int)arg1;
- (void)stop;
- (_Bool)record;
- (_Bool)audioQueueStop;
- (_Bool)audioQueueStart;
- (_Bool)prepareRecord;
- (_Bool)updateBuffer;
- (void)clearBuffer;
- (_Bool)updateQueue;
- (void)clearQueue;
- (_Bool)updateDataFormat;
- (long long)RecordingTime;
- (id)getState;
- (void)onMeterChange;
- (id)init;
- (void)dealloc;

@end

