//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "WBPreferences.h"

@interface WBVoiceinputPreferences : WBPreferences
{
}

+ (void)resetAllData;
+ (void)resetAutoCommaSetting;
+ (id)descStr;
+ (void)checkVoiceInputSend:(id)arg1 suffixPunctuationType:(long long)arg2;
+ (void)checkNormalSendWord:(id)arg1;
+ (void)initPunctuationTypeFromOldPunctuationType:(unsigned long long)arg1;
+ (id)defaultValuesMapper;
+ (_Bool)reloadFromDiskAutomatically;
+ (id)fileName;
+ (id)folderPath;

@end

