//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "NSCoding-Protocol.h"

@class NSString;

@interface WBVoiceInputStopRecordRequest : NSObject <NSCoding>
{
    _Bool _force;
    unsigned int _inputId;
    unsigned int _reason;
    unsigned int _source;
    NSString *_targetBundleId;
}

- (void).cxx_destruct;
@property(copy, nonatomic) NSString *targetBundleId; // @synthesize targetBundleId=_targetBundleId;
@property(nonatomic) _Bool force; // @synthesize force=_force;
@property(nonatomic) unsigned int source; // @synthesize source=_source;
@property(nonatomic) unsigned int reason; // @synthesize reason=_reason;
@property(nonatomic) unsigned int inputId; // @synthesize inputId=_inputId;
- (id)description;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;

@end

