//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class WBVoiceInputQueueItem;

@protocol WBVoiceInputEVADProcessorDelegate <NSObject>

@optional
- (_Bool)shouldAcceptFirstSlice;
- (void)onVADDetectSilentTooLong;
- (void)onVADDetectSpeakingToLongRestart;
- (void)onVADDetectSpeakingToLongEnd:(WBVoiceInputQueueItem *)arg1;
- (void)onVADFilterdSpeakingVoice:(WBVoiceInputQueueItem *)arg1;
- (void)onVADDetectSpeakingToSlience:(long long)arg1 data:(WBVoiceInputQueueItem *)arg2;
- (void)onVADDetectSlienceToSpeaking:(long long)arg1 data:(WBVoiceInputQueueItem *)arg2;
- (void)onVADDetectFirstStart:(WBVoiceInputQueueItem *)arg1;
@end

