//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "MMService.h"

#import "MMServiceProtocol-Protocol.h"
#import "WBVoiceInputEVADProcessorDelegate-Protocol.h"
#import "WBVoiceInputRecordBufferDelegate-Protocol.h"

@class NSMutableDictionary, NSString, NSTimer, WBVoiceInputAudioRecorder, WBVoiceInputEVADProcessor, WBWormhole;

@interface WBVoiceInputManager : MMService <WBVoiceInputRecordBufferDelegate, WBVoiceInputEVADProcessorDelegate, MMServiceProtocol>
{
    unsigned int m_uiVoiceOffset;
    unsigned int m_currentInputId;
    _Bool m_recordStart;
    int m_fileRandomStartIndex;
    int m_voiceDataFileOffset;
    int m_voiceDataFileHandle;
    int m_voiceDataFileIndex;
    NSString *m_sessionId;
    NSString *m_currentVoiceId;
    WBVoiceInputEVADProcessor *m_evad;
    WBWormhole *m_wormhole;
    WBVoiceInputAudioRecorder *m_recorder;
    NSMutableDictionary *m_sequenceMap;
    NSString *m_currentBundleId;
    NSTimer *otherAudioPlayingCheckTimer;
    CDUnknownBlockType _preRecordActionBlock;
    CDUnknownBlockType _postRecordActionBlock;
}

- (void).cxx_destruct;
@property(copy, nonatomic) CDUnknownBlockType postRecordActionBlock; // @synthesize postRecordActionBlock=_postRecordActionBlock;
@property(copy, nonatomic) CDUnknownBlockType preRecordActionBlock; // @synthesize preRecordActionBlock=_preRecordActionBlock;
- (void)onServiceClearData;
- (_Bool)onServiceMemoryWarning;
- (void)onServiceTerminate;
- (void)onServiceEnterForeground;
- (void)onServiceEnterBackground;
- (void)onServiceReloadData;
- (void)onServiceInit;
- (void)handleInterruption:(id)arg1;
- (void)onVADDetectSpeakingToLongEnd:(id)arg1;
- (void)onVADDetectSpeakingToLongRestart;
- (void)onVADDetectSilentTooLong;
- (void)onVADFilterdSpeakingVoice:(id)arg1;
- (void)onVADDetectSpeakingToSlience:(long long)arg1 data:(id)arg2;
- (void)onVADDetectSlienceToSpeaking:(long long)arg1 data:(id)arg2;
- (_Bool)shouldAcceptFirstSlice;
- (void)onVADDetectFirstStart:(id)arg1;
- (unsigned int)genSquenceByVoiceId:(id)arg1;
- (double)playPerTime;
- (void)outputPeakPower:(float)arg1;
- (double)simpleRateForBuffer;
- (unsigned int)framesPerPacket;
- (unsigned int)channlesPerFrame;
- (unsigned int)bitsPerChannel;
- (void)onAudioBufferRecordEnd;
- (void)outputPcmBuffer:(void *)arg1 bufferSize:(unsigned int)arg2;
- (void)writeVoiceData:(id)arg1;
- (_Bool)writeDataToFile:(int)arg1 writeData:(id)arg2;
- (void)releaseEvodProcessor;
- (_Bool)setUpEvodProcessor;
- (void)closeDataTransformFile;
- (_Bool)setUpDataTransformFile;
- (_Bool)isRecording;
- (_Bool)isCurrentUsingBlueTooth;
- (_Bool)stopTransfer;
- (unsigned int)beginTransfer;
- (void)stopTimer;
- (_Bool)stopRecord;
- (void)stopRecordWithOtherAudioPlaying;
- (void)stopRecordWithAutoClose;
- (void)stopRecordWithTimeout;
- (void)setRecorderStarted:(_Bool)arg1;
- (void)doStartRecordWithCompletion:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)requestRecordAuthorization:(CDUnknownBlockType)arg1 failedBlock:(CDUnknownBlockType)arg2;
- (void)releaseRecorder;
- (id)setUpRecorder:(_Bool)arg1 allowBlueTooth:(_Bool)arg2;
- (void)startRecordAndBeginTransferWithCompletion:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)resetAutoCloseTime:(_Bool)arg1 time:(double)arg2;
- (void)resetCheckOtherAudioPlaying:(_Bool)arg1;
- (void)closeOtherAudioPlayingCheckTimer;
- (void)resetStopRecordCountDown:(_Bool)arg1;
- (void)sendBeginRecordFailResponseSignal:(unsigned int)arg1;
- (void)sendBeginRecordSuccessResponseSignal:(_Bool)arg1 usingBlueTooth:(_Bool)arg2 otherAudioPlaying:(_Bool)arg3;
- (void)sendRecordHeatBeatResponseSignal;
- (_Bool)openVoiceDataFile;
- (_Bool)checkShouldHandleSignalBundleId:(id)arg1;
- (void)onReceiveStopTransferSignal:(id)arg1;
- (void)onReceiveStartTransferSignal:(id)arg1;
- (void)onReceiveStopRecordSignal:(id)arg1;
- (void)onReceiveBeginRecordSignal;
- (void)onReceivePingSignal;
- (void)setUp;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

