//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "NSCoding-Protocol.h"

@interface WBVoiceInputFileInfo : NSObject <NSCoding>
{
    int _offset;
    int _index;
}

@property(nonatomic) int index; // @synthesize index=_index;
@property(nonatomic) int offset; // @synthesize offset=_offset;
- (id)description;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;

@end

