//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "WBViewController.h"

@class UIImageView, UILabel, UIView;

@interface WBVoiceInputCoverViewController_iOS17 : WBViewController
{
    UIImageView *_successLogo;
    UIImageView *_voiceinputLogo;
    UIImageView *_topIcon;
    UILabel *_mainTitleLabel;
    UILabel *_subTitleLabel;
    UILabel *_topLabelLeft;
    UILabel *_topLabelRight;
    UIView *_guideView;
    UIView *_arrowView;
    UIView *_bubbleView;
}

- (void).cxx_destruct;
@property(retain, nonatomic) UIView *bubbleView; // @synthesize bubbleView=_bubbleView;
@property(retain, nonatomic) UIView *arrowView; // @synthesize arrowView=_arrowView;
@property(retain, nonatomic) UIView *guideView; // @synthesize guideView=_guideView;
@property(retain, nonatomic) UILabel *topLabelRight; // @synthesize topLabelRight=_topLabelRight;
@property(retain, nonatomic) UILabel *topLabelLeft; // @synthesize topLabelLeft=_topLabelLeft;
@property(retain, nonatomic) UILabel *subTitleLabel; // @synthesize subTitleLabel=_subTitleLabel;
@property(retain, nonatomic) UILabel *mainTitleLabel; // @synthesize mainTitleLabel=_mainTitleLabel;
@property(retain, nonatomic) UIImageView *topIcon; // @synthesize topIcon=_topIcon;
@property(retain, nonatomic) UIImageView *voiceinputLogo; // @synthesize voiceinputLogo=_voiceinputLogo;
@property(retain, nonatomic) UIImageView *successLogo; // @synthesize successLogo=_successLogo;
- (void)didActiveAudioSession:(id)arg1;
- (_Bool)preferredNavigationBarHidden;
- (void)viewDidLayoutSubviews;
- (void)updateStatusToSuccess;
- (void)updateStatusToInit;
- (void)viewDidLoad;

@end

