//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "WBViewController.h"

@class UIImageView, UILabel;

@interface WBVoiceInputCoverViewController : WBViewController
{
    UIImageView *_iconImageView;
    UILabel *_titleLabel;
}

- (void).cxx_destruct;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(retain, nonatomic) UIImageView *iconImageView; // @synthesize iconImageView=_iconImageView;
- (void)viewDidLayoutSubviews;
- (_Bool)preferredNavigationBarHidden;
- (void)viewDidLoad;

@end

