//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMutableArray;
@protocol OS_dispatch_queue;

@interface WBVoiceInputRealtimeAnalyser : NSObject
{
    struct OpaqueFFTSetup *_fftSetup;
    float *_inputBuffer;
    float *_hannwindow;
    float *_amplitudes;
    float *_realData;
    float *_imagData;
    struct DSPSplitComplex _frame;
    float *_loudnessWeights;
    float *_spectrum;
    _Bool _bDenyWriteData;
    _Bool _shouldDoFFTAnalysis;
    unsigned int _sampleRate;
    unsigned int _bandsCount;
    unsigned int _fftSize;
    unsigned int _log2FFTSize;
    unsigned int _writeIndex;
    unsigned int _writeLength;
    unsigned int _amplitudeLevel;
    float _minFrequency;
    float _maxFrequency;
    NSMutableArray *_arrFrequencyBands;
    NSObject<OS_dispatch_queue> *_processQueue;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *processQueue; // @synthesize processQueue=_processQueue;
@property(retain, nonatomic) NSMutableArray *arrFrequencyBands; // @synthesize arrFrequencyBands=_arrFrequencyBands;
@property(nonatomic) float maxFrequency; // @synthesize maxFrequency=_maxFrequency;
@property(nonatomic) float minFrequency; // @synthesize minFrequency=_minFrequency;
@property(nonatomic) _Bool shouldDoFFTAnalysis; // @synthesize shouldDoFFTAnalysis=_shouldDoFFTAnalysis;
@property(nonatomic) unsigned int amplitudeLevel; // @synthesize amplitudeLevel=_amplitudeLevel;
@property unsigned int writeLength; // @synthesize writeLength=_writeLength;
@property unsigned int writeIndex; // @synthesize writeIndex=_writeIndex;
@property _Bool bDenyWriteData; // @synthesize bDenyWriteData=_bDenyWriteData;
@property(nonatomic) unsigned int log2FFTSize; // @synthesize log2FFTSize=_log2FFTSize;
@property(nonatomic) unsigned int fftSize; // @synthesize fftSize=_fftSize;
@property(readonly, nonatomic) unsigned int bandsCount; // @synthesize bandsCount=_bandsCount;
@property(nonatomic) unsigned int sampleRate; // @synthesize sampleRate=_sampleRate;
- (void)smoothHorizontalSpectrum:(float *)arg1 length:(int)arg2;
- (void)smoothVerticalSpectrum:(float *)arg1 length:(int)arg2;
- (void)processAmplitudes;
- (_Bool)doFFTAnalysisIfNecessary;
- (void)getFloatFrequencWithBands:(unsigned int)arg1 completion:(CDUnknownBlockType)arg2;
- (void)writeInput:(float *)arg1 audioFrameCount:(unsigned int)arg2;
- (void)cleanCacheData;
- (void)onRecievePcmData:(id)arg1 frameCount:(unsigned int)arg2;
- (void)updateFrequencyBandsCount:(unsigned int)arg1;
- (void)updateSampleRate:(unsigned int)arg1;
- (void)initWeightings;
- (void)dealloc;
- (id)initWithFFTSize:(unsigned int)arg1 sampleRate:(unsigned int)arg2;
- (id)init;

@end

