//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSData, NSString;

@interface WBVoiceInputQueueItem : NSObject
{
    unsigned int _endFlag;
    unsigned int _sequence;
    NSString *_voiceId;
    NSData *_voiceData;
    double _creationTime;
    double _transformStartTime;
    double _transformEndTime;
}

+ (id)decode:(id)arg1;
+ (id)dataFromString:(id)arg1;
- (void).cxx_destruct;
@property(nonatomic) double transformEndTime; // @synthesize transformEndTime=_transformEndTime;
@property(nonatomic) double transformStartTime; // @synthesize transformStartTime=_transformStartTime;
@property(nonatomic) double creationTime; // @synthesize creationTime=_creationTime;
@property(copy, nonatomic) NSData *voiceData; // @synthesize voiceData=_voiceData;
@property(copy, nonatomic) NSString *voiceId; // @synthesize voiceId=_voiceId;
@property(nonatomic) unsigned int sequence; // @synthesize sequence=_sequence;
@property(nonatomic) unsigned int endFlag; // @synthesize endFlag=_endFlag;
- (id)encode;
- (id)description;
- (id)init;

@end

