//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "NSCoding-Protocol.h"

@class NSString;

@interface WBVoiceInputUpdateAutoCloseTimeRequest : NSObject <NSCoding>
{
    double _autoCloseTime;
    NSString *_targetBundleId;
}

- (void).cxx_destruct;
@property(copy, nonatomic) NSString *targetBundleId; // @synthesize targetBundleId=_targetBundleId;
@property(nonatomic) double autoCloseTime; // @synthesize autoCloseTime=_autoCloseTime;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;

@end

