//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "NSCoding-Protocol.h"

@class NSString;

@interface WBVoiceInputStopTransferResponse : NSObject <NSCoding>
{
    unsigned int _errorCode;
    unsigned int _inputId;
    NSString *_targetBundleId;
}

- (void).cxx_destruct;
@property(copy, nonatomic) NSString *targetBundleId; // @synthesize targetBundleId=_targetBundleId;
@property(nonatomic) unsigned int inputId; // @synthesize inputId=_inputId;
@property(nonatomic) unsigned int errorCode; // @synthesize errorCode=_errorCode;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;

@end

