//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "NSCoding-Protocol.h"

@class NSString, WBVoiceInputFileInfo;

@interface WBVoiceInputStartRecordResponse : NSObject <NSCoding>
{
    _Bool _usingBlueTooth;
    _Bool _queryBlueTooth;
    _Bool _otherAudioPlaying;
    unsigned int _errorCode;
    unsigned int _inputId;
    NSString *_targetBundleId;
    WBVoiceInputFileInfo *_fileInfo;
}

- (void).cxx_destruct;
@property(retain, nonatomic) WBVoiceInputFileInfo *fileInfo; // @synthesize fileInfo=_fileInfo;
@property(copy, nonatomic) NSString *targetBundleId; // @synthesize targetBundleId=_targetBundleId;
@property(nonatomic) _Bool otherAudioPlaying; // @synthesize otherAudioPlaying=_otherAudioPlaying;
@property(nonatomic) _Bool queryBlueTooth; // @synthesize queryBlueTooth=_queryBlueTooth;
@property(nonatomic) _Bool usingBlueTooth; // @synthesize usingBlueTooth=_usingBlueTooth;
@property(nonatomic) unsigned int inputId; // @synthesize inputId=_inputId;
@property(nonatomic) unsigned int errorCode; // @synthesize errorCode=_errorCode;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;

@end

