//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "WBSettingsViewController.h"

@class UILabel, WBSettingsChoicesController;

@interface WBVoiceInputIconDisplayTimeSettingsViewController : WBSettingsViewController
{
    WBSettingsChoicesController *_layoutController;
    UILabel *_noticeLabel;
}

+ (void)logChoseFixTimeAfterUse:(long long)arg1;
- (void).cxx_destruct;
- (void)viewDidLayoutSubviews;
- (void)updateNoticeLabel:(unsigned long long)arg1;
- (void)viewDidLoad;
- (void)updateChooseTag;
- (void)pluginSettingsDidChange;
- (id)title;

@end

