//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface WBVoiceInputUtil : NSObject
{
}

+ (unsigned int)genCurrentTime;
+ (unsigned long long)genCurrentTimeInMsFrom1970;
+ (id)genSessionId;
+ (id)genVoiceId:(id)arg1;

@end

