//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface WBVoiceInputAudioBandsInfo : NSObject
{
    int _startIndex;
    int _endIndex;
}

+ (id)createWith:(float)arg1 upperFrequency:(float)arg2 bandWidth:(float)arg3;
@property(nonatomic) int endIndex; // @synthesize endIndex=_endIndex;
@property(nonatomic) int startIndex; // @synthesize startIndex=_startIndex;
- (float)getMaxAmplitude:(float *)arg1 length:(int)arg2;

@end

