//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface WBVoiceInputAudioEncoder : NSObject
{
}

+ (id)encodePcmBuffer:(id)arg1 Encoder:(struct AudioCoder *)arg2 SampleRate:(double)arg3 NoiseSupression:(_Bool)arg4;

@end

