//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface WBVoiceInputTransformFileUtil : NSObject
{
}

+ (id)fileGroupRootFolderPath;
+ (id)voiceDataFileGroupPath;
+ (id)spectrumFileGroupPath;
+ (_Bool)CreatePath:(id)arg1;
+ (_Bool)removeFile:(id)arg1;
+ (_Bool)fileExist:(id)arg1;
+ (void)createParentDirIfNeed:(id)arg1;

@end

