//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "WBSettingsViewController.h"

#import "WBPreferencesObserving-Protocol.h"

@class NSArray, NSString, UILabel, WBAppButton, WBSettingsElement;

@interface WBVoiceInputSettingsViewController : WBSettingsViewController <WBPreferencesObserving>
{
    UILabel *_openLabel;
    WBAppButton *_openPlusButton;
    NSArray *_commonGroups;
    WBSettingsElement *_settingsElement;
    NSArray *_valueList;
    NSArray *_nameList;
    UILabel *_noticeLabel;
}

- (void).cxx_destruct;
@property(retain, nonatomic) UILabel *noticeLabel; // @synthesize noticeLabel=_noticeLabel;
@property(retain, nonatomic) NSArray *nameList; // @synthesize nameList=_nameList;
@property(retain, nonatomic) NSArray *valueList; // @synthesize valueList=_valueList;
@property(retain, nonatomic) WBSettingsElement *settingsElement; // @synthesize settingsElement=_settingsElement;
@property(retain, nonatomic) NSArray *commonGroups; // @synthesize commonGroups=_commonGroups;
@property(nonatomic) __weak WBAppButton *openPlusButton; // @synthesize openPlusButton=_openPlusButton;
@property(nonatomic) __weak UILabel *openLabel; // @synthesize openLabel=_openLabel;
- (void)openPlusAction:(id)arg1;
- (void)viewDidLayoutSubviews;
- (void)updateShowingGroups;
- (void)initGroups;
- (void)preferences:(Class)arg1 didChangeValueForKeySelector:(SEL)arg2;
- (void)plusStateDidChange;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (id)title;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

