//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "WBViewController.h"

#import "WKNavigationDelegate-Protocol.h"

@class NSString, WBNoNetworkView, WKWebView;

@interface WBWebViewController : WBViewController <WKNavigationDelegate>
{
    _Bool _needCustomHeader;
    _Bool _needHandleAppUpgradeUrl;
    WKWebView *_webView;
    WBNoNetworkView *_noNetworkView;
    NSString *_urlString;
}

- (void).cxx_destruct;
@property(copy, nonatomic) NSString *urlString; // @synthesize urlString=_urlString;
@property(retain, nonatomic) WBNoNetworkView *noNetworkView; // @synthesize noNetworkView=_noNetworkView;
@property(retain, nonatomic) WKWebView *webView; // @synthesize webView=_webView;
@property(nonatomic) _Bool needHandleAppUpgradeUrl; // @synthesize needHandleAppUpgradeUrl=_needHandleAppUpgradeUrl;
@property(nonatomic) _Bool needCustomHeader; // @synthesize needCustomHeader=_needCustomHeader;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)qmui_themeDidChangeByManager:(id)arg1 identifier:(id)arg2 theme:(id)arg3;
- (void)updateWebViewBackgroundColor;
- (_Bool)decideForAppUpgradeWithURL:(id)arg1;
- (void)webView:(id)arg1 decidePolicyForNavigationAction:(id)arg2 decisionHandler:(CDUnknownBlockType)arg3;
- (void)webView:(id)arg1 didFinishNavigation:(id)arg2;
- (void)removeNoNetworkView;
- (void)showNoNetworkView;
- (void)viewDidLayoutSubviews;
- (void)reload;
- (void)viewDidLoad;
- (id)barColor;
- (id)titleColor;
- (id)initWithUrlString:(id)arg1 title:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

