//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <WebKit/WKWebView.h>

@interface WBWebView : WKWebView
{
    CDUnknownBlockType _canBecomeFirstResponderBlock;
}

+ (void)initialize;
- (void).cxx_destruct;
@property(copy, nonatomic) CDUnknownBlockType canBecomeFirstResponderBlock; // @synthesize canBecomeFirstResponderBlock=_canBecomeFirstResponderBlock;
- (void)evaluateJavaScriptWithoutLog:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;
- (void)evaluateJavaScript:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;
- (_Bool)becomeFirstResponder;
- (id)initWithFrame:(struct CGRect)arg1 configuration:(id)arg2;

@end

