//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class MMWormhole;

@interface WBWormhole : NSObject
{
    MMWormhole *_wormHole;
    long long _type;
}

+ (id)defaultInstance;
- (void).cxx_destruct;
@property(nonatomic) long long type; // @synthesize type=_type;
@property(retain, nonatomic) MMWormhole *wormHole; // @synthesize wormHole=_wormHole;
- (void)clearMessageContentsForIdentifier:(id)arg1;
- (void)sendSignal:(id)arg1 signal:(id)arg2 completeBlock:(CDUnknownBlockType)arg3;
- (void)stopListenForSignal:(id)arg1;
- (void)listenForSignal:(id)arg1 handler:(CDUnknownBlockType)arg2;
- (void)sendSignal:(id)arg1 completeBlock:(CDUnknownBlockType)arg2;
- (void)sendMessage:(id)arg1 signal:(id)arg2 completeBlock:(CDUnknownBlockType)arg3;
- (void)sendMessage:(id)arg1 signal:(id)arg2;
- (id)initWithType:(long long)arg1;

@end

