//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface WBXImageContext : NSObject
{
    _Bool _mmap;
    void *_imageSourceDataBuffer;
    unsigned long long _imageSourceDataBufferSize;
    NSString *_imageSourceDataMmapFilePath;
    unsigned long long _imageType;
}

+ (id)contextWithData:(id)arg1;
+ (id)contextWithContentsOfFile:(id)arg1;
- (void).cxx_destruct;
@property(readonly, nonatomic) unsigned long long imageType; // @synthesize imageType=_imageType;
- (void)dealloc;
- (id)initWithData:(id)arg1;
- (id)initWithContentsOfFile:(id)arg1;

@end

