//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface WBZipArchiver : NSObject
{
}

+ (_Bool)createZipFileAtPath:(id)arg1 withFileInfos:(id)arg2;
+ (id)zipArchiveWithDestPath:(id)arg1 fileInfos:(id)arg2;
+ (id)zipArchiveWithDocPathArr:(id)arg1 containSuffixArray:(id)arg2;
+ (id)zipArchiveWithDocPathArr:(id)arg1;
+ (id)zipArchiveWithFilePath:(id)arg1 fileName:(id)arg2;
+ (_Bool)containSuffixArray:(id)arg1 filePath:(id)arg2;

@end

