BUNDLE_NAME = WKSPreferences
WKSPreferences_BUNDLE_EXTENSION = bundle
WKSPreferences_ARCHS = arm64
WKSPreferences_FILES = WKSRootListController.m
WKSPreferences_FRAMEWORKS = UIKit
WKSPreferences_PRIVATE_FRAMEWORKS = Preferences
WKSPreferences_INSTALL_PATH = /Library/PreferenceBundles
WKSPreferences_CFLAGS = -fobjc-arc

include $(THEOS)/makefiles/common.mk
include $(THEOS_MAKE_PATH)/bundle.mk
